uxlfoundation/oneDNN

- include/oneapi/dnnl/dnnl_types.h
- src/common/c_types_map.hpp
- src/common/matmul.cpp
- src/common/matmul_pd.hpp
- src/common/memory_tracking.hpp
- src/common/opdesc.hpp
- src/common/primitive_hashing.cpp
- src/common/type_helpers.hpp
- src/cpu/cpu_inner_product_list.cpp
- src/cpu/x64/jit_brgemm_post_ops.cpp
- src/cpu/x64/jit_brgemm_post_ops.hpp
- src/cpu/x64/matmul/brgemm_matmul.cpp
- src/cpu/x64/matmul/brgemm_matmul.hpp
- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
- src/cpu/x64/matmul/brgemm_matmul_utils.hpp
- src/cpu/x64/matmul_inner_product.cpp
- src/cpu/x64/matmul_inner_product.hpp
This PR introduces matmul-based IP implementation for training.
* When IP is created for `forward_training` plain layouts are always used to be consistent with the corresponding tensors used for  `backward_data` and `backward_weights` 
* To support bias gradients for `backward_weights` case the matmul primitive has been extended with an internal feature that enables matmul to reduce matrix A. The reduction is fused.
* Verbose was not extended to cover the new internal feature intentionally because having it in verbose doesn't provide any information that would be helpful, information about bias for IP is already enough.
* This matmul-based implementation for training is meant to be a full replacement for the existing brgemm-based one however, the latter one will stay available through the …
> Introduce matmul-based IP for training

- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
- src/cpu/x64/matmul/brgemm_matmul_utils.hpp
- tests/benchdnn/inputs/matmul/harness_matmul_regression_f32
This PR fixes [MFDNN-12799](https://jira.devtools.intel.com/browse/MFDNN-12799).
> x64: brgemm matmul utils: fix LDA initialization

- src/common/verbose.cpp
- src/common/verbose.hpp
Align dnnl_set_verbose(int level) and DNNL_VERBOSE=level handling of verbose_t::warn.
> common: align verbose level interface

- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
- tests/benchdnn/inputs/matmul/harness_matmul_regression_f32
- tests/benchdnn/inputs/matmul/harness_matmul_regression_int8
Fixes # (MFDNN-12707, MFDNN-12625)
When one tag can be treated as plain or adbc, some offsets should be updated.
WIP: checking if additional test cases are needed
> cpu: x64: matmul: fixes correctness issue about tags

- src/gpu/intel/ocl/reusable_softmax.cpp
> [rls-v3.7] softmax wg reduce range workaround

- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
- src/cpu/x64/matmul/brgemm_matmul_utils.hpp
- tests/benchdnn/inputs/matmul/harness_matmul_regression_f32
Backporting bug fixing [MFDNN-12799](https://jira.devtools.intel.com/browse/MFDNN-12799)
into `rls-v3.7`.
The same changes as in https://github.com/oneapi-src/oneDNN/pull/2452
> x64: matmul: fix LDA init via strides

- src/graph/backend/dnnl/kernels/large_partition.cpp
fix bug that can't enable block format in large partition kernel.
root cause: setting wei for matmul before constant propagation, wei is not constant which makes block layout disabled.
fix: constant propagation before layout propagation.
original log:
onednn_verbose,v1,primitive,exec,cpu,matmul,brg_matmul:undef,src:bf16::blocked:ab::f0 wei:bf16::blocked:ba::f0 dst:bf16::blocked:ab::f0,attr-scratchpad:user,,4x4096:4096x11008,
after fix:
onednn_verbose,v1,primitive,exec,cpu,matmul,brg_matmul:undef,src:bf16::blocked:ab::f0 wei:bf16:a:blocked:BA16a64b2a::f0 dst:bf16::blocked:ab::f0,attr-scratchpad:user,,4x4096:4096x11008,
> src: graph: backend: dnnl: enable block format in large partition kernel

- src/common/reduction_pd.hpp
- src/gpu/intel/ocl/reduction/atomic_reduction.cpp
- src/gpu/intel/ocl/reduction/combined_reduction.cl
- src/gpu/intel/ocl/reduction/combined_reduction.cpp
Fixes [MFDNN-13039](https://jira.devtools.intel.com/browse/MFDNN-13039). Reduction gtests were enabled on the GPU in #2243, which revealed floating point exceptions when dividing by zero:
```
$ ctest -R test_reduction_gpu
Test project oneDNN/build
Start 209: test_reduction_gpu
1/1 Test #209: test_reduction_gpu ...............***Exception: Numerical  0.31 sec
0% tests passed, 1 tests failed out of 1
Total Test time (real) =   0.32 sec
209 - test_reduction_gpu (NUMERICAL)
```
These errors are fixed by adding appropriate short-circuit checks to skip most logic (and execution) when a zero-dim is present.
> xe: reduction: fixup exceptions on zero dims

- src/graph/backend/dnnl/fusion_info.cpp
- src/graph/backend/graph_compiler/core/src/runtime/microkernel/cpu/brgemm_onednn.cpp
- src/graph/utils/pm/nested_matcher.cpp
- src/graph/utils/pm/pass_manager.cpp
- tests/benchdnn/graph/custom_driver.hpp
1. Backports coverity fixes from #2449
2. Backports a minor fix for graph compiler build from #2424
> [rls-v3.7] graph: backport coverity fixes

- src/graph/backend/dnnl/kernels/sdp_decomp_config.cpp
Recently we supported a SDPA with compressed K using per_channel quantization [case](https://github.com/oneapi-src/oneDNN/blob/22037c494cd3b0b8d118a48b10e84aa8cb99d5f3/tests/benchdnn/inputs/graph/complex_fusion/harness_mha_all#L50), which will run into the decomposed sdpa primitive kernel unexpectedly with `THREADPOOL` cpu runtime( as it passes the [check](https://github.com/oneapi-src/oneDNN/blob/22037c494cd3b0b8d118a48b10e84aa8cb99d5f3/src/graph/backend/dnnl/kernels/sdp_decomp_config.cpp#L87)). 
As we do not aim to support dynamic quantized cases in decomposed sdpa kernel, the PR enhanced the restriction to avoid such case.
> graph: backend: dnnl: not use decomp sdpa kernel for dynamic quantized cases

- tests/benchdnn/graph/deserialize.cpp
- tests/benchdnn/graph/deserialize.hpp
- tests/benchdnn/graph/flex_rewrite.cpp
- tests/benchdnn/graph/flex_rewrite.hpp
- tests/benchdnn/graph/input_displacer.cpp
- tests/benchdnn/graph/setting_handler.cpp
- tests/benchdnn/inputs/graph/complex_fusion/harness_mha_all
The PR enhances input displacement and rewrite functionality in benchdnn graph for the following aspects:
1. Support mb rewrite on SRC1 of `MatMul` and scale and zp of `DynamicDequantize` to support SDPA patterns rewriting.
2. Support shape rewrite for linked attributes and shapes, such as `group_shape` and scale/zp input of `DynamicDequantize`. If user provides  shapes for one of the attributes or input shapes, benchdnn graph will update the other accordingly after performing some checks.
3. Fix the data type setting for input displacement in case the primitive cannot be created, which solved two specific cases: f8_e4m3 cases as primitive creating might fail as f8_e4m3:f8_e4m3:f8_e5m2 is not supported, and bf16:int4:bf16 matmul cases where f32:int4:bf16 matmul is not supported.
For …
> benchdnn: graph: enhance input displace and shape rewrite for linked attribute and shapes

- src/graph/backend/dnnl/kernels/large_partition.cpp
porting #2450 
fix bug that can't enable block format in large partition kernel.
root cause: setting wei for matmul before constant propagation, wei is not constant which makes block layout disabled.
fix: constant propagation before layout propagation.
original log:
onednn_verbose,v1,primitive,exec,cpu,matmul,brg_matmul:undef,src:bf16::blocked:ab::f0 wei:bf16::blocked:ba::f0 dst:bf16::blocked:ab::f0,attr-scratchpad:user,,4x4096:4096x11008,
after fix:
onednn_verbose,v1,primitive,exec,cpu,matmul,brg_matmul:undef,src:bf16::blocked:ab::f0 wei:bf16:a:blocked:BA16a64b2a::f0 dst:bf16::blocked:ab::f0,attr-scratchpad:user,,4x4096:4096x11008,
> [rls-v3.7]src: graph: backend: dnnl: enable block format in large partition kernel

- src/graph/backend/dnnl/kernels/sdp_decomp_config.cpp
Backport the enhancement of restriction to not use decomposed sdpa for dynamic quantized cases.
Backports #2458
> [rls-v3.7]graph: backend: dnnl: not use decomp sdpa kernel for dynamic quantized cases

- src/gpu/intel/ocl/ocl_math_utils.h
Fixes the following error observed on XeLP systems.
```
./benchdnn --matmul --engine=gpu --dt=f8_e5m2:s4:f8_e5m2 --stag=abc --attr-scales=src:common:2+wei:per_ocic:f8_e4m3:32x1 --attr-zero-points=wei:per_ocic
:s4:32x1 --attr-fpmath=bf16:true 7x6x32:7x32x64
onednn_verbose,v1,info,oneDNN v3.8.0 (commit 0eb6cd6d9e934905c6caa2db8cbe131da7af2231)
onednn_verbose,v1,info,cpu,runtime:OpenMP,nthr:24
onednn_verbose,v1,info,cpu,isa:Intel AVX2 with Intel DL Boost
onednn_verbose,v1,info,gpu,runtime:OpenCL
onednn_verbose,v1,info,gpu,engine,opencl device count:2
onednn_verbose,v1,info,gpu,engine,0,name:Intel(R) UHD Graphics 770 [0x4680],driver_version:22.49.25018,binary_kernels:enabled
onednn_verbose,v1,info,gpu,engine,1,name:Intel(R) UHD Graphics 770 …
```
> xe: ocl: add missing type enablement

- src/cpu/x64/jit_brgemm_conv.cpp
- src/cpu/x64/jit_brgemm_conv.hpp
- src/cpu/x64/jit_brgemm_conv_utils.cpp
- src/cpu/x64/jit_brgemm_conv_utils.hpp
> [backport][rls-v3.7] brgconv: fix long pd time for problems with dilation (fixed MFDNN-12916)

- src/graph/backend/dnnl/kernels/sdp_decomp_config.cpp
- src/graph/backend/dnnl/kernels/sdp_primitive_config.cpp
> graph: backend: dnnl: fix check for sdpa

- src/gpu/intel/ocl/ocl_utils.cpp
Handles the header layout for DPC++ 2025.1.0, where OpenCL headers and the `sycl` subdirectory are located in the same place, so `__has_include(<sycl/sycl.hpp>)` is true even for OpenCL builds.
Fixes [MFDNN-13073](https://jira.devtools.intel.com/browse/MFDNN-13073).
> xe: ocl: strengthen sycl header guard

- src/gpu/intel/ocl/ocl_utils.cpp
> [rls-v3.7] xe: ocl: strengthen sycl header guard

- src/gpu/intel/ocl/ocl_utils.cpp
> [rls-v3.6] xe: ocl: strengthen sycl header guard

- include/oneapi/dnnl/dnnl.hpp
- include/oneapi/dnnl/dnnl_types.h
- src/common/c_types_map.hpp
- src/common/dnnl_debug_autogenerated.cpp
- src/common/memory_desc_wrapper.cpp
- src/common/tag_traits.hpp
- src/cpu/rnn/ref_rnn.cpp
- src/cpu/rnn/rnn_reorders.hpp
- src/cpu/rnn/rnn_utils.cpp
- src/cpu/x64/brgemm/brgemm_utils.cpp
- src/cpu/x64/brgemm/jit_brgemm_kernel.cpp
- src/cpu/x64/matmul/brgemm_matmul_copy_utils.cpp
- src/cpu/x64/rnn/rnn_brgemm_utils.cpp
- tests/benchdnn/rnn/rnn.cpp
> Enable brgemm-based RNN for int8 on avx2 and avx512 without VNNI

- src/cpu/x64/injectors/jit_uni_eltwise_injector.cpp
If `aux_gprs_count` returns 0, then expression `aux_gprs_count(alg_, is_fwd_, alpha_) - 1` will underflow because of unsigned type. Fixing it by casting to `int`.
> [Coverity] x64: injectors: eltwise: fix potential int underflow

- .github/automation/build_acl.sh
- .github/automation/ci-aarch64.json
- .github/workflows/aarch64-acl.yml
- .github/workflows/ci-aarch64.yml
- .github/workflows/nightly-aarch64.yml
When using github actions caches with the matrix strategy, the `cache-hit` variable is shared amongst all the strategies, potentially causing a race condition when run in parallel. This work creates just the caches sequentially, avoiding this problem
> Build acl cache sequentially

- tests/benchdnn/dnnl_common.cpp
- tests/benchdnn/dnnl_common.hpp
- tests/benchdnn/doc/knobs_common.md
This PR disables the `check-ref-impl` benchdnn flag when used on nvidia, amd or generic vendors. The nvidia and amd vendors use reference implementations to fill gaps in feature support and therefore this change will remove some false positives when testing.
> gpu: nvidia: amd: generic: ignore check-ref-impl

- src/gpu/intel/compute/device_info.cpp
> [rls-v3.7] xe: correct allowable sg sizes

- tests/benchdnn/dnn_types.cpp
- tests/benchdnn/dnn_types.hpp
- tests/benchdnn/softmax/softmax.cpp
Way of checking softmax type of comparison did take into account acc_mode (by mistake).
This PR adds an argument to skip acc_mode (as it shouldn't be considered as an attribute) and updates softmax comparison to become p2p back again for logsoftmax.
> benchdnn: softmax: update setup_cmp

- src/gpu/intel/jit/gemm/xe_hp_systolic_gemm.cpp
This reverts commit d22e43f9635af48c235fa778223f1e01b5c67a80 and splits the runtime dimension checks to avoid undefined behavior.
Fixes [MFDNN-13082](https://jira.devtools.intel.com/browse/MFDNN-13082).
> xe: jit: gemm: rearrange runtime dim checks

- src/gpu/intel/jit/gemm/xe_hp_systolic_gemm.cpp
Backport of #2492.
This reverts commit 419038ad48522fb7cd68a338c7375dea00eb271c and splits the runtime dimension checks to avoid undefined behavior.
> [rls-v3.7] xe: jit: gemm: rearrange runtime dim checks

- src/cpu/x64/matmul/brgemm_matmul_reorders.cpp
Fixes MFDNN-13029
Dispatch small shapes to jit reorder for performance purpose.
> cpu: x64: disable small shapes for brgemm matmul reorder

- src/gpu/intel/jit/gemm/xe_hp_systolic_gemm.cpp
address MFDNN-13086.
ZP args need to be swapped in the` jit:gemm::xe_hp` implementation.
> xe: jit: gemm: swap zp args in xe_hp impl

- src/gpu/intel/ocl/convolution_inner_product.cpp
- src/gpu/intel/ocl/convolution_inner_product.hpp
- src/gpu/intel/ocl/gemm/gemm_with_post_ops.cl
- src/gpu/intel/ocl/gemm/gemm_with_post_ops.cpp
- src/gpu/intel/ocl/ocl_conversion.h
- src/gpu/intel/ocl/ocl_custom_types.h
- src/gpu/intel/ocl/ocl_io.h
- src/gpu/intel/ocl/ocl_math_utils.h
- src/gpu/intel/primitive_conf.cpp
- src/gpu/intel/primitive_conf.hpp
This PR updates gemm_with_post_ops implementation with a new way of loading scales as they are going to be affected after refactor. The main issue is that `data_type::undef` becomes a valid data type for scales, meaning, they were not specified, which would trigger a bunch of issues in the existing implementation.
This PR guards from that situation.
Thanks to @rjoursler for a patch to deal with undefined data types.
> gpu: quantization refactoring prerequisites

- src/cpu/x64/matmul/brgemm_matmul.cpp
- tests/benchdnn/inputs/matmul/harness_matmul_regression_bf16
bugfix for issue:
https://jira.devtools.intel.com/browse/MFDNN-13037
> x64 : matmul : b padding calculation

- src/gpu/intel/jit/gemm/jit_gemm_pd.cpp
Revert invalid condition allowing conversion of src scales to post ops. 
Fixes # https://jira.devtools.intel.com/browse/MFDNN-13045
> [GPU] Gemm: remove invalid src post-ops condition

- src/common/verbose.cpp
- src/gpu/intel/jit/gemm/generator/microkernel_provider.cpp
- src/gpu/intel/jit/gemm/generator/pieces/k_loop.cxx
- src/gpu/intel/jit/gemm/generator/pieces/state.hpp
- src/gpu/intel/ocl/micro_sdpa.cl
- src/gpu/intel/ocl/micro_sdpa.cpp
- tests/benchdnn/inputs/graph/complex_fusion/harness_mha_all
This PR addresses several out of bound access errors related to second token shapes(Q = 1 K/V = SEQ_LEN+1). 
Additionally this PR fixes issues related to compilation errors when using common zero points masks are used without scales when quantizing.
> xe: sdpa: fix several errors related to out of bound accesses in sdpa

- src/cpu/x64/utils/jit_io_helper.cpp
- tests/benchdnn/inputs/reorder/harness_reorder_regression
This is a short fix for [MFDNN-12635](https://jira.devtools.intel.com/browse/MFDNN-12635).
Function `jit_io_helper_t<Vmm>::store_bf16` doesn't support `Xmm`, that's why it crashed when using `bf16` with blocked format with channels blocked by 4.
I changed a way it works to use `jit_io_helper_t<Vmm>::store_byte_by_byte` function instead. 
Though, I have other idea that maybe using `store_bf16` could work if we introduced another `Opmask` to filter out the lower half of `Xmm`. It would require some changes to `jit_io_helper_t` class, so I prefer to not submit it now as a bugfix, but after some time (as it requires some analysis), that's why I left a `TODO` comment.
Also I'm adding reorder regression input to benchdnn, as it was likely not covered on CPU side.
> x64: utils: jit_io_helper: fix xf16 store from Xmm (fixes MFDNN-12635)

- src/cpu/aarch64/brgemm/brgemm.cpp
- src/cpu/aarch64/brgemm/brgemm.hpp
- src/cpu/aarch64/jit_brgemm_1x1_conv.cpp
- src/cpu/aarch64/jit_brgemm_conv.cpp
- src/cpu/aarch64/matmul/brgemm_matmul.cpp
- src/cpu/x64/brgemm/brgemm.cpp
- src/cpu/x64/brgemm/brgemm.hpp
- src/cpu/x64/brgemm/brgemm_types.hpp
- src/cpu/x64/brgemm/brgemm_utils.cpp
- src/cpu/x64/brgemm/brgemm_utils.hpp
- src/cpu/x64/brgemm/capi/brgemm_api.cpp
- src/cpu/x64/brgemm/jit_brgemm_kernel.cpp
- src/cpu/x64/jit_brdgmm_dw_conv.cpp
- src/cpu/x64/jit_brgemm_1x1_conv.cpp
- src/cpu/x64/jit_brgemm_conv.cpp
- src/cpu/x64/jit_brgemm_conv_bwd_strided.cpp
- src/cpu/x64/jit_brgemm_conv_bwd_w.cpp
- src/cpu/x64/jit_brgemm_conv_utils.cpp
- src/cpu/x64/jit_brgemm_conv_utils.hpp
- src/cpu/x64/jit_brgemm_inner_product.cpp
- src/cpu/x64/jit_brgemm_inner_product.hpp
- src/cpu/x64/jit_brgemm_inner_product_utils.cpp
- src/cpu/x64/jit_primitive_conf.hpp
- src/cpu/x64/matmul/brgemm_matmul.cpp
- src/cpu/x64/rnn/rnn_brgemm_utils.cpp
- tests/benchdnn/brgemm/brgemm.cpp
- tests/gtests/internals/test_brgemm.cpp
This request contains a few general brgemm code changes and some performance updates for avx2:
- brgemm: introduce brgemm_desc_finalize function  :  this function must be called after all the parameters of the brgemm descriptor are set.  As result brgemm blocking is called only once having all needed information
- brgemm conv: update to reduce the number of generated kernels: small update for brgemm non-amx convolutions 
- brgemm: update non-amx blocking: more careful distribution of available vmm registers. It's especially important for avx2.  It also determine which order of data loading in microkernel to choose - n_bcast_1_load or 1_bcast_n_load .
- brgemm kernel: update gemm microkernel: just update the kernel code
- brgemm kernel: reduce number of vpad variants: it reduces the size …
> x64: updates for brgemm kernel and avx2 brgemm convolutions

- .github/workflows/nightly-aarch64.yml
The aarch64 nightly ci is failing due to a recent change in https://github.com/oneapi-src/oneDNN/pull/2388 where the ACL caching mechanism was changed. This updates the nightly pipeline to use the new caching system
> ci: fix aarch64 nightly failures

- src/gpu/nvidia/cudnn_eltwise_impl.hpp
This patch fix dimension conversion from `int64_t` to `int`. Currently the conversion is performed without checking if the provided value respect `int` value limit, with this patch every dimension is checked to respect it and return `unimplemented` in case of error.
To check the error run test with a very big dimension as input e.g.:
`./tests/benchdnn/benchdnn --mode-modifier=P --eltwise --engine=gpu --allow-enum-tags-only=false --dir=BWD_D --dt=bf16 --alg=relu --alpha=0 --beta=0 4294967297_n"large_dim1"`
> gpu: nvidia: fix relu type cast for dimension

- .github/automation/commit-msg-check.py
- third_party/ngen/ngen.hpp
- third_party/ngen/ngen_core.hpp
Check that `movi` src is indirect as required.
> third_party: ngen: add movi src check

- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
- src/cpu/x64/matmul/brgemm_matmul_utils.hpp
- tests/benchdnn/inputs/matmul/harness_matmul_regression_f32
Backport of #2452
Asked by TF team to support the upgrade of oneDNN.
> [backport][rls-v3.6] x64: matmul: fix LDA init via strides

- tests/benchdnn/rnn/rnn.cpp
- tests/benchdnn/rnn/rnn.hpp
Implements MFDNN-13023.
This PR improves diagnostics for unimplemented cases when domain specific tags are used. The idea is to normalize input tags prior to validating them to avoid skipping unimplemented cases that are supposed to implemented. This will help us to catch accidently disabled implementations or reduced coverage (e.g. MFDNN-12818).
For example:
```bash
--rnn --cfg=u8u8u8u8 --tag=tnc:any:tnc --alg=VANILLA_GRU --activation=UNDEF l1t1mb3sic16slc16dhc16dic16n"uniform"
--rnn --cfg=u8u8u8u8 --tag=tnc:any:tnc --alg=VANILLA_GRU --activation=UNDEF l1t1mb3sic16slc16dhc16dic16n"uniform"
```
> Improve diagnostics for unimplemented RNN cases

- src/gpu/amd/miopen_batch_normalization_executor.hpp
When compiling oneDNN with C++20, the current bnorm operator causes errors due to the lambda capturing `this`.
In C++20 implicit capture of this is an error, while in C++17 explicit capture will flag as a warning.
PR adds use of the already existing compiler workaround for the lambda capture WA_THIS_COPY_CAPTURE
- [ x ] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [ x ] Have you formatted the code using clang-format?
> gpu:amd: Update bnorm lambda capture

- src/cpu/aarch64/jit_uni_reorder.cpp
- src/cpu/reorder/cpu_reorder_regular_f16.cpp
This PR adds support for fp16 JIT reorder for data type `f16->f32`. Partially solves [issue](https://github.com/oneapi-src/oneDNN/issues/2185).
Bellow small test case logs are added to demonstrate performance numbers before and after.
`ONEDNN_VERBOSE=all ./benchdnn --reorder --sdt=f16 --ddt=f32 --mode=p 1x4096x4096`
**(new) jit:uni**: `total perf: min(ms):0.328857 avg(ms):0.348092`
**(old) simple:any**: `total perf: min(ms):65.8274 avg(ms):67.0692`
> src: cpu: aarch64: Enable fp16 data type in JIT Reorder kernel

- src/cpu/x64/brgemm/jit_brdgmm_kernel.cpp
- src/cpu/x64/brgemm/jit_brgemm_kernel.cpp
- src/cpu/x64/jit_brgemm_conv_comp_pad_kernel.cpp
- src/cpu/x64/jit_generator.hpp
- src/cpu/x64/jit_uni_batch_normalization.cpp
- src/cpu/x64/jit_uni_deconv_zp_pad_str_kernel.cpp
- src/cpu/x64/jit_uni_tbb_batch_normalization.cpp
- src/cpu/x64/matmul/brgemm_matmul_copy_utils.cpp
- src/cpu/x64/utils/jit_io_helper.cpp
Introducing `get_encoding()` to get rid of repetitive conditionals in usage of `vcvtneps2bf16`.
> x64: jit_generator: replace encoding conditionals with get_encoding()

- src/gpu/intel/jit/gemm/xe_hp_systolic_gemm.cpp
closes MFDNN-13103
fixup #2507.  swapping of args already happens if using `DNNL_ARG_A/B` for gemm, but xe_hp implementation was using the outdated `SRC/WEI` args.
> [GPU] fixup gemm args 

- examples/tutorials/matmul/cpu_matmul_quantization.cpp
- src/common/ittnotify.cpp
- src/common/sdpa_utils.hpp
- tests/gtests/dnnl_test_common.hpp
- tests/gtests/test_sum.cpp
True backport of #2364, the previous one landed into main.
Also a backport of #2508.
> [backport][rls-v3.7] Arch: coverity fixes (fixed MFDNN-12954)

- src/cpu/rnn/rnn_utils.hpp
- src/cpu/x64/rnn/brgemm_cell_common_bwd.cpp
- src/cpu/x64/rnn/brgemm_cell_common_fwd.cpp
This PR fixes a bug in GRU brgemm implementation causing a segfault due to out of bounds access. The bug was uncovered after enabling the implementation for AVX2. Apparently, running tests under SDE creates certain conditions that increase chances of running into the issue, supposedly because the chances of triggering a segfault under SDE is higher and the number of threads is limited because of threadpool. The bug is not specific to AVX2.
Additionally, this PR adds a check for the number of available threads at execution time.
7b7b478ee9e109ad2b1b5f27ec278fddbf9efc42: Fixes offset calculation for `addr_batch_global_`, which is scratchpad memory. 
b83a9b4f6782fee581c641a8406a90e349a2118e: Adds a check for the number of available threads at execution time to avoid using more threads than …
> Fix GRU brgemm implementation

- src/cpu/x64/jit_brgemm_conv_utils.cpp
Partially fixed MFDNN-12557
When the shapes has big ow but small ic/oc, it may require small calculation work in pre-calculated compensation. So it's better to calculate the pre-calculate compensation instead of calculating the compensation in brgemm kernel. 
Summarized performance data on SRF and CLX:
Raw data:
[brg_zp_avx2_vnni_2.xlsx](https://github.com/user-attachments/files/18596637/brg_zp_avx2_vnni_2.xlsx)
[brg_zp_avx512_core_vnni.xlsx](https://github.com/user-attachments/files/18596639/brg_zp_avx512_core_vnni.xlsx)
> cpu: x64: brgemm: update conditions for zp with big ow

- third_party/ngen/ngen.hpp
- third_party/ngen/ngen_auto_swsb.hpp
- third_party/ngen/ngen_core.hpp
Closes MFDNN-12992. Introduces a workaround for a PVC HW bug related to SWSB dependencies on send instruction src operands in the presence of heavy double precision usage. This is not an expected use case for oneDNN, but could theoretically occur if another f64-heavy kernel is running in parallel.
The workaround is carefully written to minimize performance impacts, but if performance impacts are still too high, we can enable the WA on an as-needs basis.
As requested in CMPLRLLVM-65139/MKLD-18120, the WA may be controlled by the environment variable `ONEAPI_PVCSendWARWA`.
> ngen: workaround for PVC SWSB HW bug

- tests/benchdnn/inputs/matmul/harness_matmul_regression_bf16
Incorrect descriptor name causes the parsing step to fail.
> benchdnn: inputs: matmul: fix descriptor name

- src/cpu/x64/brgemm/brgemm_utils.cpp
- src/cpu/x64/brgemm/jit_brgemm_kernel.cpp
Updating brgemm kernel and `calculate_max_bcast_block` function and brgemm kernel for better utilization of Vmm registers for avx2* and avx512*.
This should improve brgemm performance for cases with register-consuming post-operations for example. 
Running convolution on 6 MTL performance cores as `benchdnn  -conv --mode=P --dir=FWD_B --dt=u8:s8:u8  --stag=acdb --wtag=any --dtag=acdb --attr-post-ops=eltwise_gelu_erf:0.271:0.314:1.234 --attr-zero-points=src0:common:1 mb1_ic16oc96_ih256oh256kh1sh1dh0ph0_iw256ow256kw1sw1dw0pw0` we can see that brgemm microkernel decomposition is  changed from "1 bcast x 4 load" for current main to "2 bcast x 4 load" for this update. Performance improvement is ~13%
> x64: brgemm kernel: update Vmm usage

- MAINTAINERS.md
I am proposing @Ryo-not-rio for nomination as code owner of the AArch64 component. As a member of our core team contributors, he has demonstrated his expertise through a [history of significant changes](https://github.com/oneapi-src/oneDNN/pulls?q=is%3Apr+author%3Aryo-not-rio).
> governance: add @Ryo-not-rio as codeowner for AArch64

- src/cpu/x64/matmul_inner_product.hpp
We don't support Inner Product for training on AVX2, the only exception is an f32 data type configuration.
> cpu: x64: disable MM IP for unsupported ISAs

- src/cpu/x64/rnn/brgemm_cell_common_fwd.cpp
Backport of #2552. Only a fix for out of bounds access is backported.
> cpu: x64: rnn: multiplier is not required for gru

- tests/benchdnn/dnnl_common.cpp
Partial fix for MFDNN-13045
In addition, memory estimation of iGPU memory within benchnn is currently incorrect, as the device memory needs to be added to the system memory. As identifying when this extra memory is a tricky problem, this PR just requires the device memory requirements fit within the available CPU memory.
In addition, there is a memory miss estimation coming from blocked memory formats used in the reference primitive. In the worst case, the padding in the blocked formats could increase memory utilization of a buffer by 16x. This issue is expected to be addressed in a future PR by @dzarukin.
> benchdnn, ngen, xe: fix memory use miss-estimation triggering out-of-memory issues

- doc/primitives/convolution.md
- examples/primitives/pooling.cpp
The formula for dilated convolution and dilated pooling in oneDNN differs from that used in PyTorch and some other applications. This difference has led to confusion and several related questions in oneDNN, including #2355, #1652, and #438. This PR clarifies the differences in the documentation and updates the code example comments accordingly.
Fixes #2355
> doc: conv: add note for the dilation computation formula

- src/gpu/intel/jit/conv/config.cpp
This resolves [MFDNN-13021](https://jira.devtools.intel.com/browse/MFDNN-13021) on Xe3-LPG.
> src: gpu: intel: jit: conv: fix reorder zp precomp page faults on xe3

- src/gpu/intel/jit/conv/config.cpp
This resolves [MFDNN-13021](https://jira.devtools.intel.com/browse/MFDNN-13021) on Xe3-LPG.
Backport of #2559.
> (v3.7 backport) src: gpu: intel: jit: conv: fix reorder zp precomp page faults on xe3

- src/cpu/x64/jit_brgemm_post_ops.cpp
- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
- src/cpu/x64/matmul/brgemm_matmul_utils.hpp
- tests/benchdnn/inputs/matmul/harness_matmul_regression_bf16
- tests/benchdnn/inputs/matmul/harness_matmul_regression_float16
- tests/benchdnn/inputs/matmul/harness_matmul_regression_int8
Fixes MFDNN-13124.
When M == 1 MatMul always considers A to be non-transposed even if A md was created using "ba" tag so the condition for `treat_transposed_A_as_plain` was incorrect.
> Fix a condition for when A can be treated as plain (non-transposed)

- tests/benchdnn/benchdnn.cpp
- tests/benchdnn/common.cpp
- tests/benchdnn/common.hpp
- tests/benchdnn/doc/knob_summary.md
- tests/benchdnn/doc/knobs_common.md
- tests/benchdnn/utils/parser.cpp
This is the feature preview:
```
(100k rows of cases, the screen buffer has likely overflowed)
run: --brgemm --dt=f8_e5m2:f8_e4m3:f8_e5m2 --beta=1 --bs=16 --brgemm-attr=use_uker:0+use_interleave_stores:1 64x192:192x64_n"int8:no_tail:47"
56447:SKIPPED (Case not supported) __REPRO: --brgemm --dt=f8_e5m2:f8_e4m3:f8_e5m2 --beta=1 --bs=16 --brgemm-attr=use_uker:0+use_interleave_stores:1 64x192:192x64_n"int8:no_tail:47"
===========================================================
= Failed cases summary (--summary=no-failures to disable) =
===========================================================
0:FAILED __REPRO: --brgemm 1x16:16x16_n"f32:no_tail:0"
1542:FAILED __REPRO: --brgemm --bs=16 13x16:16x16_n"f32:no_tail:16"
3084:FAILED __REPRO: --brgemm --beta=1 16x16:16x16_n"f32:no_tail:32" …
```
> benchdnn: introduce --summary knob for better usability

- third_party/ngen/ngen_auto_swsb.hpp
`getenv` usage in #2472 is producing build errors on Windows. Removing the environment variable control for now; will reintroduce later.
> ngen: remove ONEAPI_PVCSendWARWA environment variable control

- src/cpu/x64/matmul/brgemm_matmul.cpp
- tests/benchdnn/inputs/matmul/harness_matmul_regression_bf16
back port of bugfix for issue:
https://jira.devtools.intel.com/browse/MFDNN-13037
original pull request:
https://github.com/oneapi-src/oneDNN/pull/2491
> x64: matmul: bugfix copy B padding calculation

- src/cpu/x64/brgemm/brgemm_utils.cpp
This is a backport of #2584  to fix [MFDNN-13143](https://jira.devtools.intel.com/browse/MFDNN-13143)
> x64: brgemm: update blocking for big virtual padding

- src/cpu/x64/jit_brgemm_conv_bwd_strided.cpp
Backport of https://github.com/oneapi-src/oneDNN/pull/2523.
> x64: conv: addressing coverity issues (backport into rls-v3.7)

- src/cpu/x64/jit_brgemm_conv_bwd_strided.cpp
This PR fixes coverity issues with `Severity == Major` in Convolution primitive, in particular:
`brg_idx` could be equal `-1`, which causes issues in `call_brgemm(..., brg_idx, ...)`. 
Solution: add  an assertion in `call_brgemm()`.
The same as in `6980313`, but for tail computations.
PS. Other coverity hits in convolution will be marked as false positive.
> x64: conv: addressing coverity issues

- src/cpu/x64/jit_uni_pool_kernel.hpp
Update the solution for Coverity. 
When indices is not required(max pooling during forward training or backward), `ind_dt` is initialized as data_type::undef and it will hit the assertion.
> cpu: x64: pooling: fix assertion for ind_dt

- cmake/host_compiler.cmake
Option `-fsycl-unnamed-lambda` is enabled by default in SYCL compiler, but not compatible with `-fsycl-host-compiler` option. While icpx driver adds `-fno-sycl-unnamed-lambda` implicitly to avoid build issues clang++ does not do that.
Closes #2035
> build: added -fno-sycl-unnamed-lambda for builds with host compiler

- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
Fixes MFDNN-13095
When `is_wei_batch_layout_trivial == true`, [B_batch_offset ](https://github.com/intel-innersource/libraries.performance.math.onednn/blob/main/src/cpu/x64/matmul/brgemm_matmul.cpp#L1495) may not be divided by 2 and then cause correctness issue.
> cpu: x64: matmul: correct batch layout support for int4 wei

- src/cpu/cpu_engine.cpp
- src/cpu/sycl/engine.hpp
SYCL CPU engine is inherited from classic CPU engine that overrides an interface for creating a memory storage therefore SYCL CPU engine must also override it.
This bug was introduced during the recent architecture refactoring (8187bb585b2e242fba778266cb8d2c396fe669d1) and caused SYCL CPU engine to allocate classic CPU memory storage. ~~It means that we haven't been testing usm/buffer for SYCL CPU since the bug was introduced. Also, it means that set_data_handle()/get_data_handle() and their counterparts for SYCL buffers might not work correctly (could manifest as weird issues in validation)~~.
**Update:** Only the `memory_t` objects created inside the library are affected.
I also, added additional checks to reduce the chance of introducing such a bug in the future.
> Fix memory storage allocation for SYCL CPU

- src/cpu/rnn/ref_rnn.cpp
- src/cpu/rnn/rnn_utils.hpp
Fixes MFDNN-13148 and MFDNN-12386.
Regular, raw CPU pointers can only be used with memory_t objects created for the classic CPU engine. Use service engine to create such objects.
> Enable matmul-based RNN implementation back for SYCL CPU

- .github/automation/common_aarch64.sh
- .github/workflows/aarch64-acl.yml
- .github/workflows/ci-aarch64.yml
GitHub-hosted Cobalt-100 runners are now [available](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/).
It comes with the caveat of the restrictions of the free GitHub-hosted runners (size, limited runners), however, let's put this in and observe the impact it has on CI. But the advantage is that this architecture is different from the Arm-Hosted Graviton-based runners.
> github: workflows: Add GitHub hosted Cobalt-100 runners

- src/cpu/reorder/simple_sparse_reorder.hpp
Fixes MFDNN-13062.
Incorrect condition `if (output_d.nelems(true)) return 0;` was introduced in b20dcfcd409 resulting in returning an incorrect scratchpad size an consequently the crash.
This PR removes the condition and improves verbose diagnostics. 
The piece of code below is removed because `nelems()` can return a value that is < 0 only if md contains runtime dimensions, and that check was moved to `is_applicable()`.
```cpp
const memory_desc_wrapper dst_d(dst_md());
if (dst_d.nelems(true) < 0) return status::unimplemented
```
> Fix crash in sparse reorder

- src/common/memory_tracking.hpp
- src/gpu/generic/sycl/ref_matmul.hpp
- src/gpu/nvidia/cudnn_matmul.cpp
- src/gpu/nvidia/cudnn_matmul_executor.hpp
- src/gpu/nvidia/cudnn_matmul_lt.hpp
- src/gpu/nvidia/cudnn_matmul_lt_impl.hpp
Currently tests that use the cublasLt implementation of matmul with src, weight or dst scaling fail. This PR fixes several issues:
- For dst scaling, the binary operation was created with the incorrect datatype for the scales tensor. Additionally, the memory descriptor for the scales tensor was not initialised correctly and was triggering an assertion due to inner_idxs not being initialised to sensible values. Additionally, a `shared_ptr` containing the binary_pd was freed incorrectly at the end of the `create_scaling_format_desc` function, resulting in a segmentation fault.
- src & weight scaling currently cannot be supported with this implementation. The current approach was to use the binary primitive to scale the src/weights before performing matmul. However, since the cublasLt …
> gpu: nvidia: matmul: fix issues with scaling

- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
Fixes MFDNN-13075.
This PR adds checks for large (> INT32_MAX) strides to brgemm-based matmul primitive so that such cases can be properly handled by returning an "unimplemented".
Adding support for large strides will require extending brgemm and copy routines which doesn't seem to be a good investment at this point because the shapes are not used in real world workloads for CPU.
> Handle large strides in matmul properly

- src/gpu/intel/ocl/gemm/ref_gemm.cl
- src/gpu/intel/ocl/gemm/ref_gemm.hpp
- src/gpu/intel/ocl/gen9_eltwise.cpp
- src/gpu/intel/ocl/ocl_eltwise.h
- src/gpu/intel/ocl/ocl_post_ops.h
- src/gpu/intel/ocl/ref_eltwise.cpp
- src/gpu/intel/ocl/ref_prelu.cpp
- src/gpu/intel/primitive_conf.cpp
Remove dead code emitted by OpenCL Post Ops, this just triggers needless complexity.
Removes many post-op macros which are unused anywhere.
Removes the WITH_ELTWISE define. All primitives support post-ops, thereby always enabling this define, except eltwise kernels which just need the support anyway.
> xe: ocl: remove dead code

- src/cpu/reorder/simple_reorder.hpp
- src/cpu/reorder/simple_sparse_reorder.hpp
- src/cpu/x64/jit_uni_binary_kernel.cpp
Partially fixes MFDNN-12964
1. Check `g0`, `g1` before division
2. `nelems` can be negative, cast it into `size_t` may cause potential issue.
> cpu: fixes coverity issues

- src/gpu/intel/ocl/micro_sdpa.cl
- src/gpu/intel/ocl/tile_ops.h
This PR fixes an issue with SDPA with bf16 data types with explicit masks. This issue was caused because of a copy operation from the native type(bf16) to the internal type of the kernel(float). With float16 there are implicit conversation in OpenCL but the internal data type uses ushort to represent bf16 so the conversion was incorrectly representing those values.
> xe: sdpa: Fix bug with conversion of mask from bf16 to float

- src/gpu/intel/ocl/micro_sdpa.cl
- src/gpu/intel/ocl/tile_ops.h
This PR fixes an issue with SDPA with bf16 data types with explicit masks. This issue was caused because of a copy operation from the native type(bf16) to the internal type of the kernel(float). With float16 there are implicit conversation in OpenCL but the internal data type uses ushort to represent bf16 so the conversion was incorrectly representing those values.
> [backport rls-v3.7] Fix bug with conversion of mask from bf16 to float

- src/gpu/intel/jit/gemm/CMakeLists.txt
- src/gpu/intel/jit/gemm/gen_gemm_kernel.cpp
- src/gpu/intel/jit/gemm/gen_gemm_kernel_db.cpp
- src/gpu/intel/jit/gemm/gen_gemm_kernel_db.hpp
GCC can take upwards of 10 minutes to compile the gemm catalog. This patch moves kcatalog generation to its own compilation unit to limit recompilations.
> xe: jit: gemm: move catalog generation to its own compilation unit

- src/gpu/intel/jit/gemm/generator/pieces/common.cxx
Fixes an out of registers failure on XeLP systems for the following workload:
```
benchdnn --matmul --engine=gpu --dt=bf16:s4:bf16 --wtag=acb --attr-scales=wei:per_ocic:bf16:32x1 --attr-zero-points=wei:per_ocic:s4:32x1 --attr-fpmath=bf16:true 3x96x96:3x96x64
```
On this workload, a duplicated scalar is the only subregister allocation present in r1. Removing this duplication thereby frees a register and avoids kernel generation failure.
Fixes [MFDNN-13167](https://jira.devtools.intel.com/browse/MFDNN-13167).
> xe: jit: gemm: remove unnecessary register duplication

- src/cpu/x64/jit_avx2_conv_kernel_f32.cpp
- src/cpu/x64/jit_avx512_common_conv_kernel.cpp
- src/cpu/x64/jit_avx512_core_bf16_conv_kernel.cpp
- src/cpu/x64/jit_brgemm_conv_bwd_w.cpp
- src/cpu/x64/jit_brgemm_conv_utils.cpp
Fix for [MFDNN-13089](https://jira.devtools.intel.com/browse/MFDNN-13089). Also fixing overflows catched by `-ftrapv` in GCC. The final cause was in jit code where the big number was propagated, but jit functions are `void` and we can't return any status from there, so I decided to disable `src/diff_dst size > INT_MAX`.
> x64: conv: avoid overflows and add limit for huge spatial sizes (MFDNN-13089)

- src/cpu/reorder/simple_reorder.hpp
- src/cpu/reorder/simple_sparse_reorder.hpp
- src/cpu/x64/jit_uni_binary_kernel.cpp
> Backport: cpu: fixes coverity issues

- src/cpu/x64/jit_avx2_conv_kernel_f32.cpp
- src/cpu/x64/jit_avx512_common_conv_kernel.cpp
- src/cpu/x64/jit_avx512_core_bf16_conv_kernel.cpp
- src/cpu/x64/jit_brgemm_conv_bwd_w.cpp
- src/cpu/x64/jit_brgemm_conv_utils.cpp
backport of #2627
```
(base) gta@DUT7314PVC:~/tczeszun$ LD_LIBRARY_PATH=. DNNL_VERBOSE=2 ./benchdnn  --conv --engine=gpu --dir=BWD_W --dt=bf16:bf16:bf16 --stag=axb --wtag=xba --dtag=axb --impl=jit -v5 mb1ic32iw134217732oc1ow134217730kw3pw0
create: --conv --engine=gpu --dir=BWD_W --dt=bf16:bf16:bf16 --stag=axb --wtag=xba --dtag=axb --impl=jit mb1ic32iw134217732oc1ow134217730kw3pw0
onednn_verbose,v1,info,oneDNN v3.7.0 (commit 10df79807cf134982920bbbdb02a0dab666d4ed3)
onednn_verbose,v1,info,cpu,runtime:OpenMP,nthr:208
onednn_verbose,v1,info,cpu,isa:Intel AVX-512 with float16, Intel DL Boost and bfloat16 support
onednn_verbose,v1,info,gpu,runtime:OpenCL
onednn_verbose,v1,info,gpu,engine,opencl device count:2
onednn_verbose,v1,info,gpu,engine,0,name:Intel(R) Data Center GPU Max …
```
> x64: conv: avoid overflows and add limit for huge spatial sizes (backport)

- tests/gtests/dnnl_test_common_ocl.hpp
MFDNN-13110
Symbol was moved from .hpp to .cpp and became hidden. Copy-paste the body to remove the dependency.
> gtests: fix linking for test_api_ocl with mem_debug (fixes MFDNN-13110)

- src/cpu/x64/amx_tile_configure.cpp
MFDNN-13157
It used to check 16 bits instead of all 64 expected.
> cpu: x64: tile_config: fix lazy config to check full mask (fixes MFDNN-13157)

- src/cpu/x64/brgemm/jit_brgemm_kernel.cpp
Backport of #2642.
Validation:
* [CI test set, all CPU archs](https://ecmd.jf.intel.com/commander/link/jobDetails/jobs/efe71b18-adef-f15a-a5e3-a4bf010d0e2d?linkPageType=jobDetails&objectLocator=/jobs/efe71b18-adef-f15a-a5e3-a4bf010d0e2d&stepFilter=all&s=Jobs)
* [Nightly test set, all CPU archs](https://ecmd.jf.intel.com/commander/link/jobDetails/jobs/efe71b03-d098-f138-a652-a4bf010d0e2d?linkPageType=jobDetails&objectLocator=/jobs/efe71b03-d098-f138-a652-a4bf010d0e2d&stepFilter=all&s=Jobs)
* [Nightly test set, all GPU archs](https://ecmd.jf.intel.com/commander/link/jobDetails/jobs/efe719d3-f916-f106-ac66-a4bf010d0e2d?linkPageType=jobDetails&objectLocator=/jobs/efe719d3-f916-f106-ac66-a4bf010d0e2d&linkPageType=jobDetails&objectLocator=/jobs/efe719d3-f916-f106-ac66-a4bf010d0e2d&stepFilter=err …
> Fix condition for identifying the need to process K tail

- MAINTAINERS.md
Nominating @Rbiessy, @AD2605, and @s-Nick as code owners for `gpu-generic` component. @Rbiessy, @AD2605, and @s-Nick are Codeplay Software employees assigned to work on oneDNN and established contributors to UXL Foundation's [oneMath](https://github.com/uxlfoundation/oneMath) project with focus on cross-platform GPU support. Specific contributions:
* @Rbiessy: [oneDNN](https://github.com/oneapi-src/oneDNN/pulls?q=is%3Apr+involves%3Arbiessy), [oneMath](https://github.com/uxlfoundation/oneMath/pulls?q=is%3Apr+author%3Arbiessy)
* @AD2605: [oneDNN](https://github.com/oneapi-src/oneDNN/pulls?q=is%3Apr+author%3AAD2605), [oneMath](https://github.com/uxlfoundation/oneMath/pulls?q=is%3Apr+author%3AAD2605)
* @s-Nick: [oneDNN](https://github.com/oneapi-src/oneDNN/pulls?q=is%3Apr+involves%3As-Nick), …
> New code owners for gpu-generic component

- src/cpu/x64/brgemm/jit_brgemm_kernel.cpp
This is backport of #2651:
This is extended fix for MFDNN-13170.
This PR fixes the condition of last bd block and as result the identifying the need to process K tail.
> x64: brgemm kernel: fix condition for k tail processing

- src/gpu/intel/jit/ir/post_ops.cpp
MFDNN-13188
Addresses the part about assert. The error sneaked in during the scales PR refactor rebase on top of fresh changes.
> gpu: intel: jit: ir: post_ops: restore original assert (fixes MFDNN-13188)

- src/graph/backend/dnnl/kernels/sdp_primitive.cpp
- src/graph/backend/dnnl/scratchpad.hpp
-  Fix the sanitizer issues: `applying non-zero offset 150994944 to null pointer`
-  Remove the unused code.
> graph: backend: dnnl: fix the null pointer issue and remove unused code

- RELEASE_NOTES.md
This PR includes a release notes draft based on the information from the PRs for the contributors to review. Your additions and corrections are highly appreciated.
> oneDNN v3.7 release notes

- tests/benchdnn/conv/ref_conv.cpp
- tests/benchdnn/deconv/ref_deconv.cpp
`ceilf()` does not preserve accuracy for values > 2^24.
> benchdnn: conv: replace ceilf() by div_up()

- src/cpu/x64/jit_avx512_core_amx_conv_kernel.cpp
- src/cpu/x64/jit_brgemm_conv_utils.cpp
Fixes [MFDNN-13192](https://jira.devtools.intel.com/browse/MFDNN-13192).
> x64: conv: add limitation for huge shape sizes (fixes MFDNN-13192)

- third_party/ngen/ngen_auto_swsb.hpp
Followup to #2577, reinstating the environment variable for Linux only (since it is not needed on Windows) and updating to the final name.
> ngen: reinstate ONEAPI_PVC_SEND_WAR_WA environment variable

- src/gpu/intel/jit/ir/eltwise.hpp
- src/gpu/intel/jit/v2/conv/kernel_desc.cpp
- src/gpu/intel/jit/v2/conv/kernel_desc.hpp
- src/gpu/intel/jit/v2/conv/model.cpp
- src/gpu/intel/jit/v2/conv/plan_registry_data.cpp
Jira: https://jira.devtools.intel.com/browse/MFDNN-13005
Reusing XeHPC kernels for Xe2/Xe3.
> xe: conv_v2: add Xe2/Xe3 support

- tests/gtests/test_iface_sparse.cpp
Fixes MFDNN-13144.
With `-DDNNL_ENABLE_MEM_DEBUG=ON`, [test_iface_sparse](https://github.com/oneapi-src/oneDNN/blob/main/tests/gtests/test_iface_sparse.cpp) crashes due to a mismatch between failed `malloc` counts during memory object instantiation. The PR adds a fix for the expected failure.
> gtests: fix test_iface_sparse fails for mem_debug (fixes MFDNN-13144)

- src/graph/backend/dnnl/dnnl_op_def.hpp
- src/graph/backend/dnnl/kernels/sdp_primitive_config.cpp
- src/graph/backend/dnnl/passes/constant_propagation.cpp
- src/graph/backend/dnnl/passes/lower.cpp
- tests/benchdnn/graph/custom_driver.cpp
- tests/benchdnn/inputs/graph/complex_fusion/harness_mha_all
- tests/benchdnn/inputs/graph/op/harness_bf16_all
- tests/benchdnn/inputs/graph/op/harness_f16_all
- tests/benchdnn/inputs/graph/op/harness_f32_all
This PR includes 3 minor fixes for SDPA with explicit or implicit mask:
[x] enhance check of axis in implicit causal mask to include negative axis (-1 & -2).
[x] support 1D / 2D mask for explicit causal mask (MFDNN-13164).
[x] add a internal attribute for internal op dnnl_gen_index for constant propagation (SET_ATTR_IS_CONSTANT)
> graph, benchdnn: several minor fixes for SDPA with mask

- cmake/FindMIOpen.cmake
- cmake/FindrocBLAS.cmake
- src/gpu/amd/README.md
- src/gpu/amd/miopen_gemm_inner_product_impl.hpp
- src/gpu/amd/sycl_hip_utils.hpp
This PR enables compilation of oneDNN with rocm6.1 by updating the cmake configuration to find rocblas and miopen. Additionally, the `int8x4` datatype was removed in miopen version 3, so this PR adds a check for the miopen version and disables support for the `int8x4` datatype.
> gpu: amd: add support for rocm6.1

- src/gpu/intel/jit/v2/conv/gen_convolution.cpp
Backport of https://github.com/oneapi-src/oneDNN/pull/2670.
> xe: conv_v2: fix large buffer check

- src/gpu/intel/jit/gemm/gen_gemm_kernel.cpp
Addresses MFDNN-13083 -- regressions on XeHPG for certain sizes of copy-based systolic GEMMs due to d06bde39 improperly moving from boustrophedon to scanline walk order.
The copy-based systolic GEMMs use special hard-coded inner loops and implicitly use 256-GRF mode. When deciding whether we can get by with scanline walk order, we need to know the GRF mode in order to check how many thread groups can run concurrently on the GPU. The GRF mode will be adjusted by `GEMMStrategy::preflight` but this has not been called yet, so this PR manually adjusts GRF mode in the strategy.
> xehpg: jit: gemm: fix walk order calculations for copy-based gemm

- examples/ukernels/cpu_brgemm.cpp
- include/oneapi/dnnl/dnnl_ukernel.h
- include/oneapi/dnnl/dnnl_ukernel.hpp
- src/cpu/x64/brgemm/brgemm_types.hpp
- src/cpu/x64/brgemm/brgemm_utils.hpp
- src/cpu/x64/brgemm/capi/brgemm_api.cpp
- src/cpu/x64/brgemm/capi/brgemm_api.hpp
- tests/benchdnn/brgemm/brgemm.cpp
Certain user applications can't create brgemm objects at creation stage because of lacking certain information, like strides.
But current API mandates a brgemm object to query an information about packing the tensor B.
Thus, such users get into a trap when they are forced to move ukernel creation to their execution stage, but the decision about tensor B and its packing must have been done at creation stage which makes API unusable.
To address this kind of situation, this PR makes the function that is responsible for packing requirement `static`, or independent from the object, which would let query that information based on data types (which are available) and make specific choices ahead of time.
> api: ukernel: make get_B_pack_type static for better usability

- src/gpu/intel/ocl/generic_reorder.hpp
- tests/benchdnn/inputs/concat/test_concat_large_gpu
The new large buffer concat tests trigger an attempt to use an unsupported fp64 extension on DG2. This PR adds the missing checks for the extension required by the kernel. 
An invalid configuration in the new concat tests is also addressed.
Fixes [MFDNN-13206](https://jira.devtools.intel.com/browse/MFDNN-13206).
> additional fp64 checks for generic reorder

- src/graph/backend/dnnl/dnnl_op_def.hpp
- src/graph/backend/dnnl/kernels/sdp_primitive_config.cpp
- src/graph/backend/dnnl/passes/constant_propagation.cpp
- src/graph/backend/dnnl/passes/lower.cpp
- tests/benchdnn/graph/custom_driver.cpp
- tests/benchdnn/inputs/graph/complex_fusion/harness_mha_all
- tests/benchdnn/inputs/graph/op/harness_bf16_all
- tests/benchdnn/inputs/graph/op/harness_f16_all
- tests/benchdnn/inputs/graph/op/harness_f32_all
backport https://github.com/oneapi-src/oneDNN/pull/2660 to rls-v3.7
This PR includes 3 minor fixes for SDPA with explicit or implicit mask:
[x] enhance check of axis in implicit causal mask to include negative axis (-1 & -2).
[x] support 1D / 2D mask for explicit causal mask (MFDNN-13164).
[x] add a internal attribute for internal op dnnl_gen_index for constant propagation (SET_ATTR_IS_CONSTANT)
> [v3.7 backport] graph, benchdnn: several minor fixes for SDPA with mask

- examples/ukernels/cpu_brgemm.cpp
- src/cpu/x64/brgemm/capi/brgemm_api.cpp
- tests/benchdnn/utils/compare.cpp
get_B_pack_type is not working for int8 on AVX and older.
Windows has slightly higher precision issue with logsoftmax than Linux.
All failures popped-up in Nightly.
> Fixups for recent changes.

- .github/automation/aarch64/skipped-tests.sh
- .github/automation/aarch64/test.sh
This will help developers use the same skip-list when verifying their changes locally.
> ci: split aarch64 skipped tests into their own file

- .github/workflows/ci-aarch64.yml
preventing performance tests being run on cobalt in order to not block the ci runners
> ci: aarch64: don't run performance tests on cobalt

- src/cpu/aarch64/matmul/acl_matmul.cpp
- src/cpu/aarch64/matmul/acl_matmul.hpp
- src/cpu/aarch64/matmul/acl_matmul_utils.cpp
- src/cpu/aarch64/matmul/acl_matmul_utils.hpp
Provide scratchpad memory for fixed format kernels that need a workspace. The previous assumption that fixed format kernels will never need auxiliary memory was inaccurate.
> cpu: aarch64: use scratchpad for fixed-format gemms that need it

- CMakeLists.txt
- cmake/FindcublasLt.cmake
- cmake/SYCL.cmake
- src/CMakeLists.txt
- src/graph/backend/dnnl/kernels/sdp_primitive.cpp
1. Relax the gpu vendor limitation for nv gpu. amd gpu is still disabled as I don't have any machine to test it.
2. Fix a minor issue in finding and linking cublasLt.
3. Limit the ukernel based sdpa on intel gpu.
TODO:
- Still see failing cases due to some primitive fusions are not supported on nv gpu. We will need to define fusion patterns for different vendors in a follow-up PR.
With this PR, a matmul test on nv gpu as follows:
```
$ ONEDNN_VERBOSE=1 ./tests/benchdnn/benchdnn --graph --engine=gpu --case=op/f32/matmul_2d_4d.json
onednn_verbose,v1,info,oneDNN v3.8.0 (commit 6c99c4e24a4f915aa71b5a7325eb494d758a7e25)
onednn_verbose,v1,info,cpu,runtime:DPC++,nthr:48
onednn_verbose,v1,info,cpu,isa:Intel AVX-512 with Intel DL Boost
onednn_verbose,v1,info,gpu,runtime:DPC++ …
```
> graph: enable build for nvidia gpu

- .github/automation/build_linters.sh
- .github/workflows/pr-linter.yml
This PR is to provide fails in clang-tidy job in case of warnings occurrences, also speeded up a job.
> ci: linters: clang-tidy job improvements

- .github/automation/aarch64/build.sh
- .github/automation/aarch64/build_acl.sh
- .github/automation/aarch64/ci.json
- .github/automation/aarch64/common.sh
- .github/automation/aarch64/get_acl.sh
- .github/automation/aarch64/skipped-tests.sh
- .github/automation/aarch64/test.sh
- .github/automation/performance/bench_performance.sh
- .github/automation/performance/benchdnn_comparison.py
- .github/automation/performance/inputs/conv
- .github/automation/performance/inputs/matmul
- .github/workflows/aarch64-acl.yml
- .github/workflows/ci-aarch64.yml
- .github/workflows/nightly-aarch64.yml
Backport to https://github.com/oneapi-src/oneDNN/pull/2713 for v3.7
Edit: This was more tedious than I thought. We have changed the CI so much since 3.6 that it was easier to backport the whole AArch64 CI folder to maintain consistency, otherwise there were errors that would take time to debug, and would be pointless to debug anyways.
For convenience, I will backport the CI in one commit (a 1:1 copy of CI in main), and then upgrade ACL in the other.
I ran a nightly just to be sure: https://github.com/oneapi-src/oneDNN/actions/runs/13381628230
> github: workflows: Update ACL in CI

- .github/automation/aarch64/skipped-tests.sh
- src/cpu/aarch64/brgemm/brgemm.cpp
This fixes #2572.
Patches aarch64 brgemm dispatching without scales involved.
@Ryo-not-rio, you probably may use this commit for your performance regression tracking. It's a dispatching issue, performance should increase significantly (or should have caught a major regression).
> fixup: src: introduce quant_entry_t and refactor arg_scales_t to rely on it

- src/cpu/x64/jit_brgemm_inner_product.hpp
- src/cpu/x64/jit_brgemm_post_ops.cpp
- src/cpu/x64/matmul_inner_product.hpp
The lack of the check for data type of bias caused the reduction kernel to generate illegal instruction. Only "all f32" configuration is supported for avx2.
Another fix is to skip brgemm-based IP on avx2 for non-f32 configurations.
> cpu: x64: fix condition for detecting f32 conf

- src/common/memory_storage.hpp
- src/gpu/generic/sycl/README.md
- src/gpu/generic/sycl/rnn/cell_common.cpp
- src/gpu/generic/sycl/rnn/ref_rnn.cpp
- src/gpu/generic/sycl/rnn/ref_rnn.hpp
- src/gpu/generic/sycl/rnn/rnn_kernels.hpp
- src/gpu/generic/sycl/rnn/rnn_utils.cpp
- src/gpu/generic/sycl/rnn/rnn_utils.hpp
- src/gpu/generic/sycl/sycl_post_ops.hpp
- src/gpu/generic/sycl/sycl_primitive_conf.hpp
- src/gpu/gpu_rnn_list.cpp
- src/gpu/nvidia/cudnn_convolution.cpp
- src/xpu/sycl/buffer_memory_storage.cpp
- src/xpu/sycl/buffer_memory_storage.hpp
- src/xpu/sycl/memory_storage_helper.hpp
- src/xpu/sycl/types.hpp
- src/xpu/sycl/usm_memory_storage.hpp
- tests/gtests/test_rnn_forward.cpp
Adding implementation for generic RNN Vanilla forward left-to-right. 
(Note: This PR is to serve as the first part of adding a generic RNN implementation which would support additional functionality with following PRs)
> generic: sycl: Vanilla RNN FWD l2r

- doc/programming_model/data_types.md
- examples/example_utils.hpp
- examples/primitives/convolution.cpp
- include/oneapi/dnnl/dnnl_threadpool_iface.hpp
- include/oneapi/dnnl/dnnl_ukernel.h
- src/common/binary.cpp
- src/common/convolution.cpp
- src/common/deconvolution.cpp
- src/common/eltwise.cpp
- src/common/group_normalization.cpp
- src/common/inner_product.cpp
- src/common/layer_normalization.cpp
- src/common/matmul.cpp
- src/common/memory_desc.cpp
- src/common/pooling.cpp
- src/common/primitive_attr.cpp
- src/common/primitive_attr.hpp
- src/common/reduction.cpp
- src/common/resampling.cpp
- src/common/softmax.cpp
- src/common/verbose_msg.hpp
- src/cpu/x64/jit_brgemm_post_ops.cpp
- tests/benchdnn/dnn_types.cpp
- tests/benchdnn/dnn_types.hpp
- tests/benchdnn/utils/parser.cpp
- tests/gtests/dnnl_test_common.hpp
- tests/gtests/test_resampling.cpp
Binary post-op check + improved verbose message for a single function is coming from MFDNN-13225.
Parser for engine improvement is coming from MFDNN-13218.
Doc and header fixes are coming from Nightly.
Clang-tidy fixes for CPU file.
> Portion of various fixes and minor improvements

- src/cpu/gemm_convolution.hpp
- src/cpu/gemm_inner_product.hpp
- src/cpu/gemm_x8s8s32x_convolution_utils.hpp
- src/cpu/matmul/gemm_bf16_matmul.hpp
- src/cpu/matmul/gemm_f32_matmul.hpp
- src/cpu/nchw_pooling.hpp
- src/cpu/ncsp_batch_normalization.hpp
- src/cpu/nhwc_pooling.hpp
- src/cpu/nspc_batch_normalization.hpp
- src/cpu/ref_batch_normalization.hpp
- src/cpu/ref_deconvolution.hpp
- src/cpu/ref_eltwise.hpp
- src/cpu/ref_lrn.hpp
- src/cpu/simple_concat.hpp
- src/cpu/simple_resampling.cpp
- src/cpu/simple_sum.hpp
Partially addresses [MFDNN-13014](https://jira.devtools.intel.com/browse/MFDNN-13014) and failures observed in the clang-tidy CI step.
> cpu: address some clang-tidy complaints

- .github/workflows/clang-tidy.yml
- src/graph/backend/dnnl/kernels/sdp_decomp_config.cpp
- src/graph/backend/dnnl/op_executable.cpp
- src/graph/backend/dnnl/passes/transform.cpp
- src/graph/interface/graph.cpp
- src/graph/interface/graph.hpp
- src/graph/interface/op_schema.cpp
- src/graph/utils/pm/pbuilder.cpp
- src/graph/utils/utils.hpp
Addresses two missed hits from #2517/[MFDNN-13013](https://jira.devtools.intel.com/browse/MFDNN-13013) and some others from the clang-tidy CI step.
> graph: address some *more* clang-tidy complaints

- src/gpu/generic/sycl/matmul_kernels.hpp
The signature of dropout function doesn't respect arguments type it receives. Due to implicit casting, it doesn't appear as an issue but adding dropout to matmul would make it fails.
This patch fixes the issue.
To reproduce, run the following command on main:
`./tests/benchdnn/benchdnn --mode-modifier=P --matmul --engine=gpu  --dt=bf16:bf16:bf16 --stag=ab --dtag=ab --attr-dropout=0.5:12345678 100x1:1x1 `
> gpu: generic: Fix dropout tests

- src/gpu/intel/ocl/ocl_gpu_kernel.cpp
- src/gpu/intel/ocl/ocl_stream.cpp
- src/xpu/ocl/context.hpp
- src/xpu/ocl/engine_factory.hpp
- src/xpu/ocl/engine_impl.hpp
- src/xpu/ocl/usm_memory_storage.hpp
- src/xpu/ocl/verbose.hpp
- src/xpu/sycl/context.hpp
Partially addresses [MFDNN-13015](https://jira.devtools.intel.com/browse/MFDNN-13015). Also removes some Intel-specific `#include`s from `src/xpu/ocl/usm_memory_storage.hpp`.
> xpu: address some clang-tidy complaints

- src/gpu/intel/ocl/bnorm/ref_batch_normalization.cpp
- src/gpu/intel/ocl/bnorm/ref_bnorm.cl
- src/gpu/intel/ocl/bnorm/reusable_bnorm.cl
- src/gpu/intel/ocl/bnorm/reusable_bnorm.cpp
- src/gpu/intel/ocl/gemm/gemm_with_post_ops.cl
- src/gpu/intel/ocl/ocl_io.h
- src/gpu/intel/ocl/ref_eltwise.cl
- src/gpu/intel/ocl/ref_eltwise.cpp
- src/gpu/intel/ocl/ref_lrn.cl
- src/gpu/intel/ocl/ref_lrn.hpp
- src/gpu/intel/ocl/reusable_lnorm.cl
Adds a new load function overload to remove the need for variable pre-declaration before loading. In addition, refactors a few reference kernels (ref_bnorm, ref_eltwise, ref_lrn) to use ocl_io.h to demonstrate the utility.
> xe: ocl: add inline load

- tests/gtests/graph/unit/backend/dnnl/test_large_partition.cpp
A gtest issue was found during the daily test with constant tensor cache enabled through env var.
Constant tensor cache enable and disable API need to be called before partition compilation or it will take no effect and introduce unexpected results.
Before change:
```
export ONEDNN_GRAPH_CONSTANT_TENSOR_CACHE_CAPACITY="cpu:10240;gpu:20480"
./tests/gtests/graph/unit/test_graph_unit --gtest_filter=test_large_partition_execute.F32Resnet50Stage2Block
Note: Google Test filter = test_large_partition_execute.F32Resnet50Stage2Block:-*_GPU*
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from test_large_partition_execute
[ RUN      ] test_large_partition_execute.F32Resnet50Stage2Block
index = 0, a = 1.13047e+07, b = 1.24032e+07, diff …
```
> gtests: graph: unit: fix constant cache hit and miss test

- src/gpu/nvidia/README.md
- src/gpu/nvidia/cudnn_conv_inner_product.hpp
- src/gpu/nvidia/cudnn_conv_inner_product_impl.hpp
- src/gpu/nvidia/cudnn_gemm_inner_product.hpp
- src/gpu/nvidia/cudnn_gemm_inner_product_impl.hpp
- src/gpu/nvidia/cudnn_inner_product.cpp
- src/gpu/nvidia/cudnn_inner_product_impl.hpp
- tests/benchdnn/ip/ip.cpp
Currently the inner product error threshold in benchdnn is set to 0. In some cases for large shapes on nvidia backend there are some precision issues (e.g. the cases reported in MFDNN-12610). This PR adjusts the error threshold so that such cases are not reported as failures.
Fixes MFDNN-12610.
> gpu: nvidia: ip: respect acc_mode for sum post-op

- doc/build/build.md
@vpirogov 
As discussed previously, it seems the system will be unresponsive if the number of jobs is not specified for the make -j command present in the build from source guide. Creating a PR to address this. 
Please review when you have a moment.
> doc:specifying number of jobs for make j command

- src/gpu/generic/sycl/matmul_kernels.hpp
Backport from https://github.com/oneapi-src/oneDNN/pull/2677 to fix matmul postop.  
Done in https://github.com/oneapi-src/oneDNN/pull/2677.
> [backport] gpu: generic: Fix dropout tests

- src/cpu/aarch64/acl_reorder.hpp
Some reorder cases calling ACL reorder kernels are currently giving incorrect results as the kernels do not support them. This commit adds a guard so those cases do not call ACL reorders.
Reproducers:
```
./benchdnn --reorder --stag=ba --dtag=BA8b4a 512x512
./benchdnn --reorder --stag=ba --dtag=BA4b4a 512x512
./benchdnn --reorder --stag=ab --dtag=Ab4a --ddt=bf16 512x512
```
> src: cpu: aarch64: reorder: Fix f32 acl reorders

- tests/benchdnn/inputs/rnn/shapes_small
When t > 1 the results can become numerically unstable causing some cases to fail. The refactoring of the input files in 10d64ff23e9ebdafa8277db54c3413e3549f3073 introduced some problematic shapes that should be either run with --skip-nonlinear=true or excluded/adjusted. This commit adjusts the shapes as it looks like a more reasonable solution.
> benchdnn: inputs: rnn: fix shapes leading to unstable results

- src/cpu/x64/jit_avx512_core_bf16_convolution.cpp
Addressing major Coverity issues `OVERFLOW_BEFORE_WIDEN` that recently appeared.
> x64: conv: fix potential int overflow

- src/cpu/cpu_convolution_list.cpp
- src/cpu/ref_convolution.hpp
- src/cpu/ref_deconvolution.hpp
- src/cpu/x64/brgemm/brgemm_utils.cpp
- src/cpu/x64/brgemm/jit_brdgmm_kernel.cpp
- src/cpu/x64/jit_brdgmm_dw_conv.cpp
- src/cpu/x64/jit_brgemm_conv_bwd_strided.cpp
- src/cpu/x64/jit_brgemm_conv_bwd_utils.cpp
- src/cpu/x64/jit_brgemm_conv_utils.cpp
- src/cpu/x64/jit_primitive_conf.hpp
- tests/benchdnn/inputs/conv/test_conv_bfloat16_nxc
- tests/benchdnn/inputs/conv/test_conv_ci
- tests/benchdnn/inputs/conv/test_conv_float16_nxc
- tests/benchdnn/inputs/deconv/test_deconv_bfloat16_nxc
- tests/benchdnn/inputs/deconv/test_deconv_ci
- tests/benchdnn/inputs/deconv/test_deconv_float16_nxc
Fixes MFDNN-12960
This patch enables fp32 conv with bf16/f16 weights support(including fwd/bwd conv and deconv) on avx2 and avx512. 
Note: We do not expect that f32 with xf16 weights has better performance than fp32.
[brgconv_f32_xf16_perf_v2.xlsx](https://github.com/user-attachments/files/18855501/brgconv_f32_xf16_perf_v2.xlsx)
> cpu: x64: conv: enable f32 with xf16 weights decompression support

- src/common/verbose.cpp
- src/gpu/intel/ocl/engine.cpp
Fixes MFDNN-13224.
Querying for verbose mode using `dnnl::impl::get_verbose()` has the unintentional side effect of printing verbose headers upon a match even when no logging is implied. The PR adds an option to disable printing of verbose headers for such cases (An example being the verbose checks made to determine if OpenCL C warnings should be printed or not when building the program from source).
> common: verbose: update logic for printing verbose headers (fixes MFDNN-13224)

- tests/gtests/internals/test_sdpa.cpp
Fixes a build error in test_sdpa.cpp when building to target the CUDA and HIP devices using the SYCL runtime. This is because the test_internals tests do not accept the engine type as an input argument to the executable and therefore the get_test_engine_type functions are not defined. 
Fixes [MFDNN-13273](https://jira.devtools.intel.com/browse/MFDNN-13273)
> sdpa: tests: fix build error because of SKIP_IF_(CUDA,HIP) macros

- src/cpu/aarch64/jit_uni_reorder.cpp
- src/cpu/reorder/cpu_reorder_regular_f32_f16.cpp
This PR adds support for fp16 JIT reorder for data type f32->f16. Partially solves [issue](https://github.com/oneapi-src/oneDNN/issues/2185)
Below are small test case logs that demonstrate performance numbers before and after.
`./tests/benchdnn/benchdnn --reorder --sdt=f32 --ddt=f16 --mode=p 1x4096x4096`
**(new) jit:uni**: `total perf: min(ms):0.125977 avg(ms):0.136528`
**(old) simple:any**: `total perf: min(ms):10.1409 avg(ms):10.168`
> src:cpu:aarch64: Enable JIT fp32 -> fp16 reorder

- src/cpu/x64/jit_uni_pool_kernel.cpp
- src/cpu/x64/jit_uni_pool_kernel.hpp
Opening one more time this PR. The previous one was [here](https://github.com/oneapi-src/oneDNN/pull/2678).
It is similar use case as https://github.com/oneapi-src/oneDNN/pull/2627. The problem is with huge input sizes, so I decided disable src_size <= INT_MAX for jit:avx512_core implementation.
> x64: pool: Accuracy issue in benchnn pooling test

- src/graph/backend/dnnl/kernels/sdp_decomp_config.cpp
- src/graph/backend/dnnl/kernels/sdp_decomp_config.hpp
- tests/benchdnn/inputs/graph/complex_fusion/harness_mha_all
MFDNN-13232
Add test cases where the head size of QK is different from the head size of V.
The decomposition kernel on CPU is fixed to support the cases.
> benchdnn: inputs: graph: sdpa: add tests for d_qk != d_v

- include/oneapi/dnnl/dnnl_graph.hpp
- tests/benchdnn/graph/allocator.hpp
- tests/benchdnn/graph/bench_graph.cpp
- tests/benchdnn/graph/deserialize.cpp
- tests/benchdnn/graph/deserialize.hpp
- tests/benchdnn/graph/flex_rewrite.cpp
- tests/benchdnn/graph/flex_rewrite.hpp
- tests/benchdnn/graph/graph.cpp
- tests/benchdnn/graph/graph.hpp
- tests/benchdnn/graph/graph_memory.hpp
- tests/benchdnn/graph/input_displacer.cpp
- tests/benchdnn/graph/input_displacer.hpp
- tests/benchdnn/graph/memory_pool.hpp
- tests/benchdnn/graph/parser.cpp
- tests/benchdnn/graph/ref_partition.cpp
- tests/benchdnn/graph/ref_partition.hpp
- tests/benchdnn/graph/ref_primitive.cpp
- tests/benchdnn/graph/ref_primitive.hpp
- tests/benchdnn/graph/setting_handler.cpp
- tests/benchdnn/graph/setting_handler.hpp
- tests/benchdnn/graph/utils.hpp
MFDNN-13013: fix clang-tidy warning in headers.
Corresponding violations are explained by the commit messages.
> {include, benchdnn}: graph: fix clang-tidy warnings in headers

- src/common/memory.cpp
- src/common/memory_desc_wrapper.hpp
- src/gpu/intel/compute/kernel_ctx.cpp
- src/gpu/intel/compute/kernel_ctx.hpp
- src/gpu/intel/ocl/gen9_pooling.cpp
- src/gpu/intel/primitive_conf.cpp
When offset0 is set, the maximum offset addressed by an OpenCL kernel is `offset0 + buffer_size`. If this value exceeds a 4GB offset, stateless addressing must be used, which requires setting the ` -cl-intel-greater-than-4GB-buffer-required` flag. This PR adds the missing checks against offset0. This required modifying `memory_desc_wrapper::size()` to return an appropriate size when `offset0` is set. 
Fixes [MFDNN-13205](https://jira.devtools.intel.com/browse/MFDNN-13205).
> common, xe: fix missing -cl-intel-greater-than-4GB-buffer-required OpenCL flag

- src/cpu/x64/jit_brgemm_conv_utils.cpp
Fixes MFDNN-12557
Missing initialized some variables in `estimate_brgemm_ur() `(like zp_type_a, max_vpad) may cause some shapes fall into `exec_base` instead of `exec_vpad`.
The perf data was collect on ADL with 6 core per sockets.
[brg_zp_avx2_vnni.xlsx](https://github.com/user-attachments/files/19017009/brg_zp_avx2_vnni.xlsx)
> cpu: x64: conv: update estimate_brgemm_ur for better blocking

- src/common/memory.cpp
- src/common/memory_desc_wrapper.hpp
- src/gpu/intel/compute/kernel_ctx.cpp
- src/gpu/intel/compute/kernel_ctx.hpp
- src/gpu/intel/ocl/gen9_pooling.cpp
- src/gpu/intel/primitive_conf.cpp
> [rls-v3.8-pc] common, xe: fix missing -cl-intel-greater-than-4GB-buffer-required OpenCL flag 

- src/cpu/x64/jit_uni_binary_kernel.cpp
>cl --version
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30158 for x64
This version of compiler for C++17 (C++11 is fine) will generate wrong code for non-ternary algorithms due to the branch in the constructor. It inverts objects that must be created and must not:
```
io_=0000028F599311D8
io_.at(conf_.src0_type)=0000000000000000
io_.at(conf_.src1_type)=0000000000000000
io_.at(conf_.src2_type)=0000028F59929C00
io_.at(conf_.dst_type)=0000000000000000
```
The solution is to pass src2_type unconditionally, access to such io_injector must be regulated by checking for is_ternary().
> cpu: x64: jit_binary_kernel: pass src2_dt unconditionally

- CMakeLists.txt
This is a patch release containing the following changes to v3.7:
* Fixed correctness issue in `int8` matmul primitive with `int4` weights on on Intel Arc graphics (b16184d155b578036c94e44fbc960e25b3c522f7)
* Fixed matmul performance regression on Intel Arc graphics (41e406bfb448a0600a50ef213c5237d4a3ce3155)
* Fixed potential integer overflow in `bf16` convolution for processors with Intel AVX-512 instruction set support (f882861fe0d0f2ed61b42377408ad62e5a665bc2)
* Fixed functional issue in matmul with dropout attribute on generic GPUs (83033303c072c3b18e070d1abfedfd1f50248eac)
* Fixed functional issues in matmul with scales on NVIDIA GPUs (e8d8594956a626be1debf359618024d1cb7c702a)
* Fixed integer overflows for large shapes in convolution for x64 processors …
> oneDNN v3.7.1 patch release

- src/cpu/aarch64/acl_inner_product.hpp
- src/cpu/cpu_inner_product_list.cpp
Enable ACL inner product for forward bf16. This change depends on updates in the next ACL release. With those, this has shown 170x and 160x performance improvements in torchbench for BERT_pytorch and alexnet respectively when run in bf16 compile mode.
Commands used for benchmarks:
`TORCHINDUCTOR_FREEZING=1 python3 run_benchmark.py cpu --model BERT_pytorch --torchdynamo inductor --test eval --nwarmup 5 --niter 15 --precision bf16`
`TORCHINDUCTOR_FREEZING=1 python3 run_benchmark.py cpu --model alexnet --torchdynamo inductor --test eval --nwarmup 5 --niter 15 --precision bf16`
> cpu: aarch64: ip: Allow bf16 for ACL inner product

- third_party/ngen/ngen_asm.hpp
Fix missing copyright in `ngen_asm.hpp`
> Fix ngen_asm copyright

- src/gpu/intel/jit/codegen/kernel.hpp
- src/gpu/intel/jit/ir/config.hpp
- src/gpu/intel/jit/ir/ir.hpp
- src/gpu/intel/jit/ir/ir_builder.cpp
- src/gpu/intel/jit/ir/ir_builder.hpp
- src/gpu/intel/jit/ir/tensor.hpp
- src/gpu/intel/jit/pooling/config.hpp
- src/gpu/intel/jit/reorder/ir_builder.cpp
- src/gpu/intel/jit/v2/conv/builder.cpp
- src/gpu/intel/jit/v2/conv/gen_convolution.cpp
- src/gpu/intel/jit/v2/conv/kernel_desc.cpp
- src/gpu/intel/jit/v2/conv/kernel_desc.hpp
This should resolve MFDNN-13019 by eliminating thread-local `expr_t`-s which could accidentally spill into other threads.
> src: gpu: intel: jit: eliminate thread_local expr_t for tgs

- src/gpu/generic/sycl/README.md
- src/gpu/generic/sycl/group_normalization_kernel.hpp
- src/gpu/generic/sycl/ref_group_normalization.cpp
- src/gpu/generic/sycl/ref_group_normalization.hpp
- src/gpu/generic/sycl/sycl_primitive_conf.hpp
- src/gpu/gpu_group_normalization_list.cpp
- tests/gtests/test_group_normalization.cpp
Adds the implementation of group normalization for the SYCL backend.
> genenric:sycl: Group Norm Forward

- src/common/memory_tracking.hpp
- src/gpu/generic/sycl/README.md
- src/gpu/generic/sycl/ref_inner_product.cpp
- src/gpu/generic/sycl/ref_inner_product.hpp
- src/gpu/gpu_inner_product_list.cpp
- tests/gtests/test_inner_product_backward_data.cpp
- tests/gtests/test_inner_product_backward_weights.cpp
- tests/gtests/test_inner_product_forward.cpp
Adds the backward_data and the backward_weight of the inner product for the generic backend and supports all possible layouts of inputs / outputs. To enable the same, this PR also enables the forward pass supporting different possible layouts of inputs / outputs, which was previously missing.
> generic:sycl: Inner Product Backward

- src/cpu/x64/brgemm/brgemm_types.hpp
- src/cpu/x64/brgemm/brgemm_utils.cpp
- src/cpu/x64/brgemm/jit_brgemm_amx_uker.cpp
- src/cpu/x64/brgemm/jit_brgemm_kernel.cpp
- src/cpu/x64/jit_brgemm_conv.cpp
- src/cpu/x64/jit_brgemm_conv_utils.cpp
- src/cpu/x64/jit_brgemm_conv_utils.hpp
- src/cpu/x64/jit_primitive_conf.hpp
This is backport of https://github.com/oneapi-src/oneDNN/pull/2420 to rls-v3.7 + update of calculate_max_bcast_block function in brgemm_utils to improve performance for some cases with post-ops (see #2540 ).
> [backport] x64: updates for brgemm kernel and avx2 brgemm convolutions

- src/gpu/intel/microkernels/shim.cpp
Fixes a variable aliasing bug in the microkernel service library when multiple microkernels are used.
The vISA shim that transfers control to the microkernel has several series of variables (`COPY*`, `CLOBBER*`) that are tied to physical GRFs. They are necessarily global scope vISA variables, which meant that variables from different microkernel invocations could alias and as a result vISA could copy input/output arguments to the wrong registers or the calling kernel's variables could be trashed. It's quite surprising this wasn't found earlier. Likely it's the cause of some failing SDPA configs -- FYI @umar456.
This PR annotates the variable names with their physical locations so that any aliasing that does occur will not be a problem.
> xe: microkernels: disambiguate vISA variables from separate invocations

- src/common/convolution.cpp
- src/gpu/intel/jit/conv/config.cpp
PR updates convolution to report grouped scales as unimplemented as there is no support for them in the library or benchdnn.
> xe, common: conv: exclude grouped scales from check as not supported

- src/gpu/intel/ocl/graph/gen_index.cl
- src/graph/backend/dnnl/kernels/gen_index.cpp
- src/graph/backend/dnnl/kernels/gen_index.hpp
- src/graph/backend/dnnl/op_executable.hpp
- src/graph/backend/dnnl/patterns/single_op_pattern.cpp
- tests/benchdnn/graph/graph.cpp
The GenIndex op is used to construct SDPA with an implicit causal mask. Since no primitive supports this op, we implement a reference kernel with OCL in Graph.
> graph: backend: enable genindex ref implementation for gpu

- MAINTAINERS.md
I would like to nominate Hamza @theComputeKid for the maintainer role of `cpu-arch64` component. Hamza is dedicated technical lead for oneDNN team at Arm responsible for product quality and performance, interfacing with Pytorch and Tensorflow upstream, and integration with ACL. Major contributions to oneDNN include:
* Migration of ACL-based implementations to stateless ACL operators to address.
* Enabling oneDNN validation on AArch64 including CI and nightly testing.
> governance: add @theComputeKid as maintainer for cpu-aarch64

- src/gpu/intel/jit/codegen/reorder.hpp
- src/gpu/intel/jit/conv/gen_convolution.cpp
- src/gpu/intel/jit/ir/primitive_plan.cpp
- src/gpu/intel/jit/reorder/config.cpp
- src/gpu/intel/jit/reorder/config.hpp
- src/gpu/intel/jit/reorder/gen_reorder.cpp
- src/gpu/intel/jit/reorder/ir_builder.cpp
- src/gpu/intel/jit/reorder/ir_builder.hpp
- src/gpu/intel/jit/reorder/normalization.cpp
- src/gpu/intel/jit/reorder/normalization.hpp
- src/gpu/intel/jit/reorder/reorder_kernel.hpp
- src/gpu/intel/jit/reorder/tiler.cpp
- src/gpu/intel/jit/reorder/tiler.hpp
Refactors the jit reorder interface so that the work tile (iter * loop) is known at config time. It is prework for [MFDNN-12529](https://jira.devtools.intel.com/browse/MFDNN-12529) to adhere to tile size restrictions at primitive creation time.
> xe: jit: refactor reorder interface

- third_party/ngen/ngen_asm.hpp
Taking over #2809 so that we can get it merged ASAP due to the release schedule.
The only effective change here is to fix the commit message formatting.
> ngen: fix a build issue when DNNL_DEV_MODE is OFF

- src/gpu/intel/jit/conv/config.cpp
- src/gpu/intel/jit/conv/ir_builder.cpp
- src/gpu/intel/jit/conv/lookup_table_data.cpp
- src/gpu/intel/jit/conv/plan.cpp
- src/gpu/intel/jit/conv/plan.hpp
- src/gpu/intel/jit/conv/problem.cpp
- src/gpu/intel/jit/conv/tiler.cpp
Jira: [MFDNN-13199](https://jira.devtools.intel.com/browse/MFDNN-13199)
List of changes:
- Adjusted heuristics to enable `mad` (instead of `dpas`) and M/N transposition
- Both optimizations are to reduce padding (and related redundant work) in case of small channels
- This is like 10th or so version of the heuristics - unfortunately still seeing a few regressions in P3 KPIs. There are much more improvements so it does not look too bad
- Removed suboptimal lookup table entries
- Refactored and simplified accumulator type and transposed blocking logic
- We still incorrectly use f16 accumulator with f16 data type in some cases. I tried to fix it but it causes quite a few model-level slowdowns so let's keep it this way for now. In the future we need to add FP math mode based dispatching …
> [GPU] Convolution: improve small IC/OC performance

- src/gpu/intel/jit/gemm/gen_gemm.hpp
Backport of a single commit from #2746
> [backport][rls-v3.8-pc] fixup: src: move zero_points to quant_entry_t abstraction

- src/gpu/generic/sycl/ref_group_normalization.cpp
#2746 got merged after #2733 , which did not reflect the changes for the scale/zero-point refactor.
This PR fixes the build issue of main when GPU_VENDOR is set to GENERIC
> ref: sycl: fix group norm build after quant refactor part 3

- src/gpu/generic/sycl/README.md
- src/gpu/generic/sycl/group_normalization_kernel.hpp
- src/gpu/generic/sycl/ref_group_normalization.cpp
- src/gpu/generic/sycl/ref_group_normalization.hpp
- src/gpu/generic/sycl/sycl_primitive_conf.hpp
- src/gpu/gpu_group_normalization_list.cpp
- tests/gtests/test_group_normalization.cpp
Add the implementation of group normalization's  backward pass for the reference sycl backend
> ref:sycl: group norm backward

- tests/gtests/internals/test_sdpa.cpp
Fixes a build error in test_sdpa.cpp when building to target the CUDA and HIP devices using the SYCL runtime. This is because the test_internals tests do not accept the engine type as an input argument to the executable and therefore the get_test_engine_type functions are not defined.
Fixes [MFDNN-13273](https://jira.devtools.intel.com/browse/MFDNN-13273)
> [rls-v3.8pc] sdpa: tests: fix build error because of SKIP_IF_(CUDA,HIP) macros

- .github/CODEOWNERS
Removed inner source groups from CODEOWNERS because they are not required anymore after migration
> Removed inner source groups from CODEOWNERS

- src/CMakeLists.txt
Cmake: explicitly set compile PDB names for object libraries, because the behavior is different between MSVC and Ninja generators:
- MSVC uses target name as default name for compile PDB
- Ninja uses vc<vs version>.pdb
When you want to re-distribute such PDB files and move all files into a single folder, in later cases all files will override each other.
> build: explicitly set compile PDB names

- src/common/dnnl_thread.hpp
`#pragma omp simd` on Windows debug builds in some corner cases creates incorrect code that leads to wrong results. We are disabling it using `/Qopenmp-simd-` compilation flag, but it seems to not be enough.
> common: disabling #pragma omp simd on windows debug builds

- tests/benchdnn/inputs/conv/test_conv_large_gpu
While testing large buffer concat and matmul, it was found that very simple tests like the current suite do not get sufficient coverage. This patch modifies the test set to significantly improve coverage in a time efficient manner. Interestingly on XeHPC, this doesn't appear to have uncovered any new edge cases like I saw in our other primitives.
> benchdnn: inputs: conv: revamp large buffer gpu tests

- src/gpu/intel/jit/gemm/generator/pieces/matrix_multiply.cxx
Backport of #2852 to `rls-v3.8-pc`.
> xe: jit: gemm: fix dynamic quantization scale tensor indexing

- src/common/batch_normalization_pd.hpp
- src/common/convolution_pd.hpp
- src/common/deconvolution_pd.hpp
- src/common/eltwise_pd.hpp
- src/common/group_normalization_pd.hpp
- src/common/inner_product_pd.hpp
- src/common/layer_normalization_pd.hpp
- src/common/lrn_pd.hpp
- src/common/matmul_pd.hpp
- src/common/pooling_pd.hpp
- src/common/primitive_desc.hpp
- src/common/rnn_pd.hpp
- src/common/sdpa_pd.hpp
- src/common/softmax_pd.hpp
- src/cpu/ref_fused_convolution.hpp
- src/cpu/x64/injectors/jit_uni_binary_injector.cpp
- src/cpu/x64/injectors/jit_uni_eltwise_injector.cpp
- src/cpu/x64/injectors/jit_uni_postops_injector.cpp
- src/cpu/x64/jit_avx2_1x1_convolution.hpp
- src/cpu/x64/jit_avx512_common_1x1_convolution.hpp
- src/cpu/x64/jit_avx512_core_bf16_1x1_convolution.hpp
- src/cpu/x64/jit_avx512_core_x8s8s32x_1x1_convolution.hpp
- src/cpu/x64/jit_sse41_1x1_convolution.hpp
- src/cpu/x64/jit_uni_x8s8s32x_1x1_convolution.hpp
- tests/benchdnn/dnn_types.cpp
- tests/benchdnn/utils/parser.cpp
- tests/benchdnn/utils/parser.hpp
PR includes:
* Better handling of dangling symbols on the benchdnn input line.
* `arg_usage` function improvements not to fallback on known arguments but decide on the spot if it's needed or not.
* Verbose diagnostics improvements for post-ops injector and underlying calls.
Last two items are asked by @EgorDuplensky from OV team.
> Minor improvements for arg_usage and post-ops verbose

- src/cpu/x64/jit_avx2_1x1_conv_kernel_f32.cpp
- src/cpu/x64/jit_avx2_conv_kernel_f32.cpp
- src/cpu/x64/jit_avx512_common_1x1_conv_kernel.cpp
- src/cpu/x64/jit_avx512_common_conv_kernel.cpp
- src/cpu/x64/jit_avx512_core_amx_1x1_conv_kernel.cpp
- src/cpu/x64/jit_avx512_core_amx_conv_kernel.cpp
- src/cpu/x64/jit_avx512_core_bf16_1x1_conv_kernel.cpp
- src/cpu/x64/jit_avx512_core_bf16_conv_kernel.cpp
- src/cpu/x64/jit_avx512_core_x8s8s32x_1x1_conv_kernel.cpp
- src/cpu/x64/jit_avx512_core_x8s8s32x_conv_kernel.cpp
- src/cpu/x64/jit_brdgmm_dw_conv.cpp
- src/cpu/x64/jit_brgemm_conv_bwd_utils.cpp
- src/cpu/x64/jit_brgemm_conv_utils.cpp
- src/cpu/x64/jit_primitive_conf.hpp
- src/cpu/x64/jit_sse41_1x1_conv_kernel_f32.cpp
- src/cpu/x64/jit_sse41_conv_kernel_f32.cpp
- src/cpu/x64/jit_uni_dw_conv_kernel_utils.cpp
- src/cpu/x64/jit_uni_x8s8s32x_1x1_conv_kernel.cpp
- src/cpu/x64/jit_uni_x8s8s32x_conv_kernel.cpp
> [Backport]: cpu: conv: disable huge shapes to avoid potential overflows

- src/common/primitive_attr.cpp
- tests/gtests/dnnl_test_common.hpp
Immediate work around to MFDNN-13325
> common: attr: switch off consistency check for now

- src/gpu/intel/jit/codegen/kernel.hpp
- src/gpu/intel/jit/codegen/ngen_helpers.hpp
- src/gpu/intel/jit/codegen/register_allocator.hpp
- src/gpu/intel/jit/codegen/register_scope.hpp
- src/gpu/intel/jit/emulated_generator.hpp
- src/gpu/intel/jit/gemm/generator/microkernel_provider.cpp
- src/gpu/intel/jit/gemm/include/internal/ngen_includes.hpp
- src/gpu/intel/jit/generator.hpp
- src/gpu/intel/jit/pooling/gen_pooling.cpp
- src/gpu/intel/jit/reduction_generator.hpp
- src/gpu/intel/jit/reduction_injector.cpp
- src/gpu/intel/jit/reduction_injector.hpp
- src/gpu/intel/sycl/l0/utils.cpp
For third party builds, the relative directory will resolve to the wrong path.
Implementation of proposal in #2853 for merging.
> xe: remove ngen relative directories

- src/common/memory_tracking.hpp
- src/cpu/x64/jit_primitive_conf.hpp
- src/cpu/x64/jit_uni_pool_kernel.cpp
- src/cpu/x64/jit_uni_pool_kernel.hpp
- src/cpu/x64/jit_uni_pooling.cpp
- src/cpu/x64/jit_uni_pooling.hpp
- src/cpu/x64/utils/jit_io_helper.cpp
- tests/benchdnn/inputs/pool/test_pool_bfloat16
- tests/benchdnn/pool/pool.cpp
[MFDNN-11050](https://jira.devtools.intel.com/browse/MFDNN-11050) bf16 backward max pooling returns incorrect results
[MFDNN-11396](https://jira.devtools.intel.com/browse/MFDNN-11396) BF16 pooling_backward performance regression on SPR
As a result of a refactoring,  [MFDNN-12863](https://jira.devtools.intel.com/browse/MFDNN-12863) (JIT max pool implementation works incorrectly for small data types and large kernels) was also fixed.
Also, as it was recommended during the review, io injector is used to load/store tensor data.
It was found earlier ([MFDNN-11050](https://jira.devtools.intel.com/browse/MFDNN-11050)) that bf16 backward max pooling returns incorrect results. An initial fix of an accuracy led to significant performance regression …
> Fix accuracy of max-pooling backpropagation for bfloat16 data

- .github/workflows/clang-tidy.yml
clang-tidy runs are currently broken if the head ref comes from a fork (see, e.g., https://github.com/oneapi-src/oneDNN/actions/runs/13798408419/job/38595447059?pr=2850, #2850).
This PR changes the repository to match that of the PR head repo.
> ci: clang-tidy: run on PRs from forks

- src/gpu/intel/compute/kernel_ctx.hpp
- src/gpu/intel/ocl/device_info.cpp
- src/gpu/intel/ocl/ocl_eltwise.h
When cl_khr_f64 is unsupported, the compiler warns about double literals.
> xe: ocl: prevent double->float literal conversion in post ops

- rfcs/20230818-Dropout/README.md
This is proposal to support dropout operation in oneDNN via primitive attribute
[Link ](https://github.com/itaraban/oneDNN/blob/itaraban/rfcs/dropout/rfcs/20230818-Dropout/README.md)to rendered document
[Link](https://github.com/itaraban/oneDNN/tree/itaraban/dropout-impl) to PoC
Performance data for [DGL](https://github.com/dmlc/dgl) (with PyTorch backend) GNN training benchmarks using Icelake server machine:
| benchmark    | dataset       | default     | with oneDNN dropout | difference |
|--------------|---------------|-------------|---------------------|------------|
| bench_gat    |  cora         | 0.012357805 | 0.009989643         | 124%       |
|              | pubmed        | 0.029577794 | 0.021833464         | 135%       |
| bench_sage   | cora          | 0.007244702 | 0.00432033 …
> rfc: dropout primitive attribute

- rfcs/20240311-verbose-logging-support/README.md
[Link](https://github.com/oneapi-src/oneDNN/tree/amanerik/rfcs/verbose-logging-support/rfcs/20240311-verbose-logging-support) to rendered document.
> rfcs: proposal for a verbose logging mechanism

- rfcs/20240531-coo-sparse-encoding/README.md
Proposal on extending sparsity support to include Coordinate sparse encoding (COO) format.
[Link](https://github.com/oneapi-src/oneDNN/blob/amanerik/rfcs/coo-sparse-encoding/rfcs/20240531-coo-sparse-encoding/README.md) to rendered document.
> rfcs: add proposal on coo sparse encoding

- src/cpu/reorder/cpu_reorder_comp_s8_s8.cpp
- src/cpu/scale_utils.cpp
- src/cpu/x64/jit_avx512_core_x8s8s32x_conv_kernel.cpp
- src/cpu/x64/jit_uni_reorder_direct_copy.cpp
- tests/benchdnn/common.cpp
- tests/benchdnn/dnnl_memory.cpp
- tests/benchdnn/dnnl_memory.hpp
- tests/benchdnn/doc/knobs_common.md
- tests/benchdnn/inputs/reorder/harness_reorder_large
- tests/benchdnn/inputs/reorder/test_reorder_all
- tests/benchdnn/inputs/reorder/test_reorder_gpu
- tests/benchdnn/matmul/matmul.cpp
- tests/benchdnn/reorder/reorder_aux.cpp
- tests/benchdnn/utils/cold_cache.cpp
- tests/benchdnn/utils/compare.cpp
- tests/benchdnn/utils/parser.cpp
* Remove mask retrieval for the lowest precompute_scales calls as it's already determined based on the number of scales needed for weights.
* Restored the memory usage for scratchpad size after the refactor for a single implementation.
* Adjusted softmax threshold a little more to fit Windows threadpool output values.
* Added support for mode-modifier=M for sparse functionality. Metadata can't be generated with random values - it leads to an access a random memory location which is prohibited. Fill metadata as for correctness mode, rest buffer are kept with random values.
> Bunch of functional fixes (fixes MFDNN-13193, fixes MFDNN-13282, fixes MFDNN-13236)

- src/graph/backend/dnnl/op_executable.hpp
- src/graph/backend/dnnl/patterns/single_op_pattern.cpp
- tests/benchdnn/graph/graph.cpp
1. Fix the GenIndex sycl cpu dispatch issue. It should be dispatched to CPU implementation.
2. GreaterEqual w/ s32 dtype is not currently supported by GPU. Add the checking in the pattern definition and benchdnn.
> graph: backend: dnnl: fix genindex and causal mask issue

- tests/gtests/internals/test_sdpa.cpp
Fixes a bug in the internal SDPA tests because the lambda was going out of scope before the function finished. This was only appearing on Windows when running the 2nd token shapes using the SYCL backend. Adding synchronization fixes this issue.
Fixes: MFDNN-13266
> xe: sdpa: Fix failure in test on Windows with SYCL runtime

- src/graph/backend/dnnl/kernels/mqa_decomp.cpp
- src/graph/backend/dnnl/kernels/mqa_decomp_config.hpp
- src/graph/backend/dnnl/kernels/sdp_primitive.cpp
- src/graph/backend/dnnl/passes/transform.cpp
1. Fix the pass `fuse_src_transpose_to_matmul`, it is aimed to optimize pattern like "softmax+transpose+reshape/reorder+matmul". But the order in the `in_md.permute_axes` needs to be converted. 
2. `fuse_src_transpose_to_matmul` is not used in `mqa_decomp` and `sdp_primitive` kernels. So removed.
3. Fix the kernel the dst pointer issue in the `mqa_decomp` kernel.
> graph: backend: dnnl: fix some issue about fuse_src_tranpose to_matmul and mqa decompose kernel

- src/gpu/intel/jit/gemm/generator/pieces/layout_utils.cpp
Fixes MFDNN-13350. There was a corner case where a particular XeHPG strategy was asking to use variable send descriptors for k remainder handling, but they weren't necessary. This case wasn't being handled correctly (it used indirect descriptors but didn't initialize them), leading to hangs.
> xe: jit: gemm: fix corner cases in descriptor-based remainders

- src/graph/interface/backend.hpp
- src/graph/interface/graph.cpp
- src/graph/interface/graph.hpp
- src/graph/interface/graph_attr.hpp
- src/graph/utils/json.hpp
- tests/gtests/graph/unit/backend/dnnl/test_compiled_partition.cpp
- tests/gtests/graph/unit/backend/dnnl/test_layout_propagator_cpu.cpp
- tests/gtests/graph/unit/backend/dnnl/test_partition_cpu.cpp
- tests/gtests/graph/unit/backend/dnnl/test_subgraph_pass.cpp
- tests/gtests/graph/unit/interface/test_graph_cpu.cpp
1. JSON file serialization: removed the trailing whitespaces which may cause unintended edits when a JSON file is opened and closed with an editor (eg. vscode) configured with removing trailing whitespaces. Also added a newline at the end of the JSON file.
2. Moved the graph::serialize() method to cpp file so changing it or the JSON utility will not cause the whole graph component recompile (due to graph.hpp is almost included everywhere).
3. Backend interface: removed two lock guards which seem unnecessary.
4. fpmath_t: make the constructor explicit so we don't confuse it with fpmath_mode_t. At some places, we passed fpmath_mode_t to functions which requires fpmath_t as an argument.
> graph: interface: several fixes and code improves

- src/graph/backend/dnnl/fusion_info.hpp
- src/graph/backend/dnnl/op_executable.hpp
- src/graph/backend/dnnl/passes/lower.cpp
- src/graph/backend/dnnl/passes/transform.cpp
- src/graph/backend/dnnl/patterns/data_type_check_pass.hpp
- src/graph/backend/dnnl/patterns/pattern_matcher_pass.hpp
- src/graph/backend/fake/transformation_pass.hpp
- src/graph/interface/constant_tensor_cache.cpp
- src/graph/interface/graph.hpp
- src/graph/interface/op.hpp
- src/graph/interface/op_def_constraint.cpp
- src/graph/interface/op_schema.hpp
- src/graph/interface/partition_impl.hpp
- src/graph/utils/json.hpp
- src/graph/utils/pm/dag_check_pass.hpp
- src/graph/utils/pm/nested_matcher.cpp
- src/graph/utils/pm/op_depth_check_pass.hpp
- src/graph/utils/pm/pass_base.cpp
- src/graph/utils/pm/pass_base.hpp
- src/graph/utils/pm/pass_manager.cpp
- src/graph/utils/pm/pass_manager.hpp
- tests/gtests/graph/unit/utils/test_pattern_matcher_cpu.cpp
More fixes for clang-tidy warnings in headers.
> {src, gtests}: graph: fix clang-tidy warnings

- src/common/float4.cpp
- src/gpu/intel/jit/gemm/generator/pieces/copy_plan.cpp
- src/gpu/intel/ocl/ocl_math_utils.h
For very large float values, subtracting from values in fp4 range will alias to the same value. For f4_e3m0, for example:
```c
fabsf(0.25 - 2.41592e+09) = 0x4f100000
fabsf(0.5  - 2.41592e+09) = 0x4f100000
fabsf(1    - 2.41592e+09) = 0x4f100000
fabsf(2    - 2.41592e+09) = 0x4f100000
fabsf(4    - 2.41592e+09) = 0x4f100000
fabsf(8    - 2.41592e+09) = 0x4f100000
fabsf(16   - 2.41592e+09) = 0x4f100000
```
Because the differences are the same, the logic to choose the nearest fp4 value thinks the floating point value is halfway between 0.25 and 0.5, then between 0.5 and 1, ..., ultimately choosing 8 (!) because it is the "nearest even".
This change clamps values to within fp4 range to mitigate aliasing. It also maintains signs for inf/nan values, so -inf/-nan -> -16 in f4_e3m0.
+ @mgouicem …
> common, xe: fix fp4 aliasing issues

- tests/benchdnn/dnnl_common.cpp
Adds a new benchdnn_combined_limit for the combined device and CPU memory limit. A new combined capacity factor was introduced, as the capacity factor appears unnecessarily strict from what has been observed in practice. We likely could increase the current capacity factor, but that is avoided in this patch to limit the scope of this change.
Fixes [MFDNN-13353](https://jira.devtools.intel.com/browse/MFDNN-13353).
> benchdnn: fix out-of-memory encountered on iGPU systems

- tests/benchdnn/bnorm/bnorm_aux.cpp
- tests/benchdnn/conv/conv_aux.cpp
- tests/benchdnn/deconv/deconv_aux.cpp
- tests/benchdnn/gnorm/gnorm_aux.cpp
- tests/benchdnn/ip/ip_aux.cpp
- tests/benchdnn/lrn/lrn_aux.cpp
- tests/benchdnn/pool/pool_aux.cpp
- tests/benchdnn/resampling/resampling_aux.cpp
- tests/benchdnn/rnn/rnn_aux.cpp
This is a minimal fix of parsing a problem description in benchdnn's arguments. The issue was found during analysis of [MFDNN-13286](https://jira.devtools.intel.com/browse/MFDNN-13286) on **Windows**.
> benchdnn: fix large problem description parsing

- src/cpu/nchw_pooling.cpp
- src/cpu/nchw_pooling.hpp
- src/cpu/nhwc_pooling.cpp
- src/cpu/nhwc_pooling.hpp
This PR fixes crashes of simple_nchw and simple_nhwc in some cases that were found in [MFDNN-13286](https://jira.devtools.intel.com/browse/MFDNN-13286).
It also reduces memory allocation in simple_nchw in case of back propagation for non-f32 data types: simple_nchw requested scratchpad memory for every available thread even if the number of work items was smaller (e.g. it requested more than 4TB for mb1ic1iw4294967311ow858993461kw7sw5pw0 according to logs in MFDNN-13286; the size depends on the number of available threads). This helps in some cases (particularly, in the cases from MFDNN-13286).
> cpu: pooling: fix crashes of large tensor processing

- src/common/verbose.cpp
- src/gpu/intel/ocl/engine.cpp
Backport of PR https://github.com/uxlfoundation/oneDNN/pull/2725.
> [backport][rls-v3.8-pc] common: verbose: update logic for printing verbose headers

- CMakeLists.txt
This is a patch release containing the following changes to v3.7.1:
* Fixed hang in matmul with odd shapes on Intel Arc GPUs (46e7499d8576ac036346f23c9f6d746823dd56b0)
* Fixed out-of-registers error in matmul on Intel Arc GPUs (599c8390610bbd9e8c8afdfeba582726ad3af0e1)
* Fixed incorrect results in SDPA pattern on Intel GPUs (6343c73143a6185d440bbd61e4089ed07196e9ec)
* Fixed integer overflow in convolution with large shapes on x64 CPUs (c541100d5b7678cf042c698aca5cddcbac1426a2)
* Fixed acccess violation issue in experimental Graph Compiler (8b0e6265648a95f3fdb8f3e734b8eb3075538de2)
* Fixed access violation in pooling on Intel GPUs (cd2cd5d654078608b9f0de3a1a847708dc3d8e15)
* Improved performance of int8 matmul with int4 weights on Intel GPUs (d6c98ec835f449c71fe359f9da68cf48ed68fad1)
> oneDNN v3.7.2 patch release

- src/cpu/aarch64/matmul/acl_lowp_matmul.cpp
- src/cpu/aarch64/matmul/acl_lowp_matmul.hpp
- src/cpu/aarch64/matmul/acl_lowp_matmul_sq.cpp
- src/cpu/aarch64/matmul/acl_lowp_matmul_sq.hpp
This PR introduces 3D and 4D support for acl_lowp_matmul_t and acl_lowp_sq_matmul_t in ACL. Solves [issue](https://github.com/oneapi-src/oneDNN/issues/2696).
Below are small test case logs that demonstrate performance numbers before and after.
* 3D lowp:
``OMP_NUM_THREADS=16 ./tests/benchdnn/benchdnn --mode=pc --matmul --dt=s8:s8:f32 4x1024x1024:1x1024x1024``
``ACL: total perf: min(ms):1.53076 avg(ms):1.55271``
``JIT: total perf: min(ms):1029.39 avg(ms):1029.92``
* 3D lowp_sq:
``OMP_NUM_THREADS=16 ./tests/benchdnn/benchdnn --mode=pc --matmul --dt=s8:s8:s8 4x1024x1024:1x1024x1024``
``ACL: total perf: min(ms):1.38965 avg(ms):1.4086``
``JIT: total perf: min(ms):1032.73 avg(ms):1033.18``
* 4D lowp:
``OMP_NUM_THREADS=16 ./tests/benchdnn/benchdnn --mode=pc --matmul --dt=s8:s8:f32 …
> Introduces support for 3D and 4D inputs in ACL acl_lowp and acl_lowp_sq matmul.

- tests/benchdnn/inputs/matmul/harness_matmul_generated_ci
Commenting out generated cases observed to crash testing, disabling all other testcases from running. 
These cases should be reenabled pending https://jira.devtools.intel.com/browse/MFDNN-13381.
> [GPU] Drop generated gemm cases causing crashes

- src/gpu/intel/jit/codegen/bank_conflict_allocation.cpp
- src/gpu/intel/jit/codegen/bank_conflict_allocation.hpp
- src/gpu/intel/jit/codegen/codegen.cpp
- src/gpu/intel/jit/codegen/codegen.hpp
- src/gpu/intel/jit/codegen/kernel.hpp
- src/gpu/intel/jit/codegen/register_allocator.hpp
- src/gpu/intel/jit/conv/conv_kernel.hpp
- src/gpu/intel/jit/eltwise_injector.cpp
- src/gpu/intel/jit/eltwise_injector.hpp
- src/gpu/intel/jit/emulated_generator.hpp
- src/gpu/intel/jit/emulation.hpp
- src/gpu/intel/jit/gemm/generator/pieces/post_ops.cxx
- src/gpu/intel/jit/gemm/include/generator.hpp
- src/gpu/intel/jit/generator.hpp
- src/gpu/intel/jit/ir/core.hpp
- src/gpu/intel/jit/ir/ir.cpp
- src/gpu/intel/jit/pooling/pooling_kernel.hpp
- src/gpu/intel/jit/post_op_injector.cpp
- src/gpu/intel/jit/post_op_injector.hpp
- src/gpu/intel/jit/reduction_generator.hpp
- src/gpu/intel/jit/reduction_injector.cpp
- src/gpu/intel/jit/reduction_injector.hpp
- src/gpu/intel/jit/reorder/reorder_kernel.hpp
- src/gpu/intel/jit/v2/conv/kernel.hpp
- third_party/ngen/ngen.hpp
- third_party/ngen/ngen_asm.hpp
- third_party/ngen/ngen_elf.hpp
Adds a new tracing step which tracks the ngen assembly emitted by the IR lowering. Produces output like:
```
[TRACE]  // Prologue
[TRACE]  (W)    and     (1|M0)  r127.2<1>:ud    r0.0<0;1,0>:ud  0xffffffe0:ud
[TRACE]  (W)    and     (1|M0)  r127.0<1>:uw    r0.4<0;1,0>:uw  0xff:uw
[TRACE]  (W)    add     (1|M0)  r127.2<1>:ud    r127.2<0;1,0>:ud        0x40:uw                         {@2}
[TRACE]  (W)    mad     (1|M0)  r127.0<1>:ud    r127.2<0;0>:ud  r127.0<0;0>:uw  0xc0:uw                 {@1}
[TRACE]  (W)    send.ugm        (1|M0)  r1      r127    null:0  0xff000000      0x6228e500              {$0,I@1}
[TRACE]  (W)    add     (1|M0)  r127.0<1>:ud    r127.0<0;1,0>:ud        0x80:uw                         {$0.dst}
[TRACE]  (W)    send.ugm        (1|M0)  r3      r127    null:0  0xff000000 …
```
> xe: jit: enable tracing ir -> ngen

- src/gpu/intel/jit/codegen/codegen.cpp
- src/gpu/intel/jit/codegen/kernel.hpp
- src/gpu/intel/jit/conv/problem.cpp
- src/gpu/intel/jit/ir/core.hpp
- src/gpu/intel/jit/ir/problem.hpp
- src/gpu/intel/jit/v2/conv/bridge.hpp
- src/gpu/intel/jit/v2/conv/builder.cpp
- src/gpu/intel/jit/v2/conv/kernel_desc.cpp
- src/gpu/intel/jit/v2/conv/kernel_desc.hpp
- src/gpu/intel/jit/v2/conv/kernel_desc_2d_reqs.cpp
- src/gpu/intel/jit/v2/conv/plan.cpp
- src/gpu/intel/jit/v2/conv/plan_registry_data.cpp
- src/gpu/intel/jit/v2/conv/planner/bench.cpp
- src/gpu/intel/jit/v2/ir/builder.cpp
- src/gpu/intel/jit/v2/ir/tensor.cpp
- src/gpu/intel/jit/v2/ir/tensor.hpp
Jira: [MFDNN-13025](https://jira.devtools.intel.com/browse/MFDNN-13025)
Changes:
- Added support for fused M dimension (for combined kw/ic blocking for BWD_W)
- Added outer K blocking for better data reuse with Stream-K
- The idea is to split K dimensions into batches and handle every batch in a separate thread wave. This reduced the footprint of A/B tensors accessed by the current thread wave
- Number of K batches is determined by a simple heuristic based on the L3 cache size
- Added more checks for block 2D enabling. This allows to enable 2D loads/stores partially, for one tensor only
Performance data for ResNet-50 on PVC:
| Propagation | Batch size | Data Type | # of layers | Ratio v2-new to v1 | Ratio v2-new to v2-old |
|-------------|------------|-----------|-------------|------------ …
> [GPU] Shapeless conv: improve 1st BWD_W performance

- src/cpu/x64/brgemm/brgemm_utils.cpp
- src/cpu/x64/brgemm/jit_brgemm_amx_uker.cpp
- src/cpu/x64/matmul/amx_blocking_heuristics.cpp
- src/cpu/x64/matmul/amx_blocking_heuristics.hpp
- src/cpu/x64/matmul/brgemm_matmul.cpp
- src/cpu/x64/matmul/brgemm_matmul.hpp
- src/cpu/x64/matmul/brgemm_matmul_copy_utils.cpp
- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
- src/cpu/x64/matmul/brgemm_matmul_utils.hpp
New blocking heuristics for matrix multiplication using AMX include a new k-loop, utilize blocked C, and employ larger N dimensions in BRGEM with LDB2
> x64: matmul: amx blocking heuristics

- include/oneapi/dnnl/dnnl.hpp
- include/oneapi/dnnl/dnnl_types.h
- src/common/c_types_map.hpp
- src/common/dnnl_debug_autogenerated.cpp
- src/common/memory_desc_wrapper.cpp
- src/cpu/aarch64/matmul/jit_int8_kernel_types.hpp
- src/cpu/aarch64/matmul/jit_int8_matmul.cpp
- src/cpu/aarch64/matmul/jit_int8_matmul.hpp
- src/cpu/aarch64/matmul/jit_int8_matmul_utils.cpp
- src/cpu/aarch64/matmul/jit_int8_matmul_utils.hpp
- src/cpu/matmul/cpu_matmul_list.cpp
- tests/benchdnn/dnnl_debug_autogenerated.cpp
This PR introduces the quantised(int8) matmul kernel in OneDNN which gives good speed-ups for quantised model inference on Graviton 3 CPUs.
Kernel supports:
1. Shapes – 2d,3d,4d
2. Zeropoint
- Source – common(s32)
- Weight – common(s32)
- Destination – common(s32)
3. Scales
- Source – common(f32)
- Weight – common(f32),per_oc(f32)
- Destination - common(f32)
4. Bias – mask - 1xN(f32)
5. Dynamic quantisation of Source matrix from f32->int8 based on common policy for scales and zp(This feature is available when the flag `ONEDNN_AARCH64_MATMUL_SRC_QUANT` is enabled at runtime by : 
`export ONEDNN_AARCH64_MATMUL_SRC_QUANT=ON`
```
make test
97% tests passed, 6 tests failed out of 219 …
```
> aarch64: matmul: addition of JIT int8 kernel

- src/cpu/x64/jit_brdgmm_dw_conv.cpp
Brdgmm kernel could not be selected when using the **--attr-post-ops=sum** flag. jit_dw was used instead.
This PR makes it possible to use brdgmm kernel with **sum post-op**
The changes look trivial, In fact, there was already support, but brdgmm could not be dispatched because the function(has_default_values) signature was updated a long time ago but the function call was not updated. As a result, data_type_undef was always used inside, which prevented the brdgmm kernel from being selected
> src: cpu: x64: jit_brdgmm_dw_conw: make brdgmm support fusing sum op

- .github/workflows/clang-tidy.yml
This PR provides fix for fork repositories check.
> ci: clang-tidy: no repo ref

- src/common/sdpa_test_iface.cpp
- src/common/sdpa_utils.hpp
- src/gpu/intel/ocl/micro_sdpa.cpp
This PR updates the configurations for the SDPA kernel to optimized for a head size of 64. These updates improve the performance of small head sizes by 1.1-1.5x on LNL. Performance in other platforms will be posted soon.
```
| mb |  N |  D |   KV |    Q | kdt       | vdt       | mask   | quant                 | sdpa(main) | sdpa(PR) | speedup vs. main |
|----+----+----+------+------+-----------+-----------+--------+-----------------------+------------+----------+------------------|
|  1 | 32 | 64 |  385 |    1 | s8/f16/na | s8/f16/na | causal | per_token_with_groups |      80.75 |     62.5 |            1.292 |
|  1 | 32 | 64 |  513 |    1 | s8/f16/na | s8/f16/na | causal | per_token_with_groups |      91.96 |    70.78 |        1.2992371 |
|  1 | 32 | 64 | 1025 |    1 | s8/f16/na | …
```
> xe: sdpa: improve performance of quantized sdpa with a head size of 64

- tests/benchdnn/dnnl_memory.cpp
- tests/benchdnn/dnnl_memory.hpp
- tests/benchdnn/matmul/matmul.cpp
- tests/benchdnn/matmul/matmul.hpp
- tests/benchdnn/matmul/ref_matmul.cpp
MFDNN-13114
Couple changes to improve the situation reported in the tracker above:
* Avoid unnecessary get_idx calls for each K while it should be done once per a group of K.
* Use `ba` format for weights in ref kernel to avoid bad leading dimensions and have memory dense in K-loop.
Seems to give a significant boost compared to what it was before.
> benchdnn: matmul: resolve the regression introduced by grouped scales and zero-points support

- src/cpu/x64/brgemm/brgemm.cpp
Fixes the following assertion due to offset calculated [here](https://github.com/uxlfoundation/oneDNN/blob/edd2a3e0a3a4314d1e2b894098ef51a84e7b0163/src/cpu/x64/brgemm/jit_brgemm_kernel.cpp#L1126) on GPU large buffer tests on SPR systems by disabling brgemm for large buffers.
```
[rjoursle@sdpdnn630225 ~]$ ~/dnnl/build_debug/tests/benchdnn/benchdnn --mode-modifier=P --ip --engine=gpu --dt=bf16:bf16:f32 --stag=ab --dtag=ab mb21ic13oc133326203
terminate called after throwing an instance of 'Xbyak::Error'
what():  offset is too big
```
Fixes [MFDNN-13161](https://jira.devtools.intel.com/browse/MFDNN-13161).
> cpu: x64: brgemm: fix assertion due to invalid EVEX offset

- src/common/matmul.cpp
- src/cpu/x64/jit_avx512_core_x8s8s32x_convolution.cpp
- src/cpu/x64/jit_avx512_core_x8s8s32x_deconvolution.cpp
- src/cpu/x64/jit_uni_dw_conv_kernel_utils.cpp
- src/cpu/x64/jit_uni_ncsp_convolution.cpp
- src/cpu/x64/jit_uni_reorder_utils.cpp
- src/cpu/x64/jit_uni_x8s8s32x_deconvolution.cpp
- tests/benchdnn/matmul/matmul.cpp
- tests/benchdnn/reorder/cfg.cpp
- tests/benchdnn/reorder/reorder.cpp
- tests/benchdnn/reorder/reorder_aux.cpp
- tests/benchdnn/self/common.cpp
MFDNN-13351 - improve filling for matmul so that benchdnn doesn't report false-positives with relatively big zero-point values.
MFDNN-13377 - Update benchdnn and the library to restrict int4 buffers for byte-alignment only on the most dense dimension.
MFDNN-13360 - Fixup of previous change reducing the scratchpad space - the execute part was misaligned with the updated logic.
MFDNN-13368 - Updated benchdnn filling for reorder to avoid underflow in case of s32 validation with zero-points.
MFDNN-13376 - The product of refactor + a victim of a bug in benchdnn which didn't report cases becoming unimplemented properly. Reporting was fixed, case started returning unimplemented as expected. Unimplemented case was fixed in jit_uni_reorder, and also verbose messages were added.
MFDNN-11868 - Use a …
> Another bucket of fixes (and future bugs...)

- tests/benchdnn/inputs/graph/pattern/f8/f8_conv_add_add_fusion.json
- tests/benchdnn/inputs/graph/pattern/harness_int8_all
- tests/benchdnn/inputs/graph/pattern/int8/int8_bf16_conv_add_relu_mul.json
- tests/benchdnn/inputs/graph/pattern/int8/int8_conv_add_add_fusion.json
- tests/benchdnn/inputs/graph/pattern/int8/int8_matmul_mul_add_mul_fusion.json
Mainly about int8/f8 Conv/matmul + Add fusions. Remove the dequantize op on the src1 of Add.
The original cases were executed with graph dump. Two graphs for two partitions will be dumped (1 for the main fusion, and 1 for the dequantize op). The graph of the main fusion pattern is used here to replace the original case. 
Fixes MFDNN-12928
> benchdnn: inputs: graph: fix test cases related to int8/f8 add

- src/gpu/intel/ocl/gemm/gemm_with_post_ops.cpp
Small PR to fix a concerning-looking verbose message in gemm_with_post_ops_t when that implementation is not needed. The message says "failed to create nested gemm primitive" -- which isn't true; it actually succeeded. Updating verbose to say we're skipping this implementation to use another one.
> xe: ocl: fix gemm_with_po verbose dispatch message

- src/cpu/aarch64/jit_brgemm_conv.cpp
- src/cpu/aarch64/jit_brgemm_conv.hpp
- src/cpu/aarch64/jit_brgemm_conv_bwd.cpp
- src/cpu/aarch64/jit_brgemm_conv_bwd.hpp
- src/cpu/cpu_convolution_list.cpp
This pull request adds support for **BRGEMM backward data (BWD)** on _CPU_ for the _AArch64_ architecture, specifically for block sizes 8 and 16. The following changes have been made to enable this support:
**New Files Added**:
- _jit_brgemm_bwd_data.cpp_ – Implements the JIT kernel for BRGEMM backward data.
- _jit_brgemm_bwd_data.hpp_ – Defines the interface and data structures for the BRGEMM backward data kernel.
**Template Changes**:
The _brgemm_convolution_fwd_t_ template has been updated to support inversion by adding a boolean parameter.
- [ ✓] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [ ✓] Have you formatted the code using clang-format?
> cpu: aarch64: add brgemm bwd data support for block size 8 and 16

- tests/benchdnn/common.cpp
- tests/benchdnn/dnnl_common.cpp
- tests/benchdnn/graph/bench_graph.cpp
- tests/benchdnn/rnn/rnn_task.hpp
- tests/benchdnn/utils/task.hpp
- tests/benchdnn/utils/timer.cpp
- tests/benchdnn/utils/timer.hpp
Add time per test case (asterisk-ed):
```
create: --matmul --dt=s8:u8:f16 --attr-scales=src:common:0.25+dst:common:2+wei:common:0.5 896x2048:2048x4096_n"RNN-T:Encoder_cell3_Input*1"
run: --matmul --dt=s8:u8:f16 --attr-scales=src:common:0.25+dst:common:2+wei:common:0.5 896x2048:2048x4096_n"RNN-T:Encoder_cell3_Input*1"
run ref: --matmul --attr-scales=src:common:0.25+dst:common:2+wei:common:0.5 896x2048:2048x4096_n"RNN-T:Encoder_cell3_Input*1"
4120:PASSED **(17054 ms)** __REPRO: --matmul --dt=s8:u8:f16 --attr-scales=src:common:0.25+dst:common:2+wei:common:0.5 896x2048:2048x4096_n"RNN-T:Encoder_cell3_Input*1"
```
Added execute and create timers into the summary breakdown (asterisk-ed):
```
total: 499.34s; **create_pd: 0.45s (0%);** **create_prim: 0.70s (0%);** fill: 5.03s (1%); **execute: …
```
> benchdnn: add more timers to get better profiling information for regular validation runs

- src/gpu/intel/sycl/device_info.cpp
- src/gpu/intel/sycl/l0/utils.cpp
- src/gpu/intel/sycl/utils.hpp
Level Zero query currently returns wrong result wrt support for atomics by the device. This commit reverts to using ocl query until the issue is fixed in level zero.
This commit can be reverted as level zero fixes the query.
Fixes MFDNN-13201
> gpu: intel: sycl: workaround failing atomics support

- src/common/verbose_msg.hpp
- src/gpu/intel/sycl/utils.cpp
This PR is intended to better enable users to determine runtime problems with oneDNN due to a missing or incorrectly installed OpenCL runtime.
Sample behavior:
```
$ OCL_ICD_VENDORS= ~/dnnl/build_dpcpp/tests/benchdnn/benchdnn --engine=gpu --eltwise 1024
onednn_verbose,v1,info,oneDNN v3.8.0 (commit 2f066a7e703d19b77723a5bf8ff5f781fc6586ee)
onednn_verbose,v1,info,cpu,runtime:TBB,nthr:224
onednn_verbose,v1,info,cpu,isa:Intel AVX-512 with float16, Intel DL Boost and bfloat16 support
onednn_verbose,v1,info,gpu,runtime:DPC++
onednn_verbose,v1,info,gpu,engine,sycl gpu device count:1
onednn_verbose,v1,common,error,runtime,Intel(R) Data Center GPU Max 1100 OpenCL device not found,src/gpu/intel/sycl/utils.cpp:137
onednn_verbose,v1,info,gpu,engine,0,backend:Level Zero,name:Intel(R) Data Center GPU …
```
> common, xe: sycl: improve logging when OpenCL install is missing

- doc/primitives/binary.md
- src/gpu/intel/ocl/gen9_binary.hpp
- src/gpu/intel/ocl/simple_binary.hpp
- tests/benchdnn/binary/binary.cpp
- tests/benchdnn/inputs/binary/test_binary_gpu
Currently the binary primitive doesn't support s32 dtype on GPU, which will affect the reference implementation of SDPA with implicit causal mask
The following change enables support for s32 data types for gpu binary primitive.
Fixes [MFDNN-12984](https://jira.devtools.intel.com/browse/MFDNN-12984)
> gpu: intel: ocl: add s32 support for binary

- src/gpu/intel/ocl/gen9_softmax.cl
- src/gpu/intel/ocl/gen9_wino_conv_fwd_data_fused.cl
- src/gpu/intel/ocl/ocl_post_ops.h
- src/gpu/intel/ocl/ref_convolution.cl
- src/gpu/intel/ocl/rnn/rnn_grid.cl
- src/gpu/intel/ocl/simple_softmax.cl
On older arch, if cl_khr_f64 is unsupported, the compiler throws warning about double literals.
Additionally fixes warning in conv:
`incompatible pointer types initializing '__private float *__private' with an expression of type '__private float2 (*)[1][6]' `
> xe: ocl: prevent double -> float literal conversion [rnn, softmax, (de)conv]

- src/gpu/intel/jit/codegen/codegen.cpp
- src/gpu/intel/jit/codegen/kernel.hpp
- src/gpu/intel/jit/conv/config.cpp
- src/gpu/intel/jit/conv/config.hpp
- src/gpu/intel/jit/conv/conv_kernel.hpp
- src/gpu/intel/jit/ir/hw.hpp
- src/gpu/intel/jit/v2/conv/kernel.hpp
- src/gpu/intel/jit/v2/conv/kernel_desc.hpp
It appears that there are scenarios where ngen_asm will throw unexpectedly fail, even though kernel generation succeeds. This patch prevents functional changes from occurring due to this failure.
Fix for [MFDNN-13424](https://jira.devtools.intel.com/browse/MFDNN-13424)
> xe: jit: codegen: prevent IR -> nGEN assembly functional changes

- cmake/SDL.cmake
- cmake/host_compiler.cmake
- third_party/ngen/ngen_level_zero.hpp
Address a GCC warning caught when using GCC as a DPC++ host compiler.
Fixes [MFDNN-13429](https://jira.devtools.intel.com/browse/MFDNN-13429l)
> ngen: fix missing field intializer warning

- src/graph/backend/dnnl/kernels/sdp_primitive_config.cpp
- src/graph/backend/dnnl/kernels/sdp_primitive_v1.cpp
- src/graph/backend/dnnl/layout_propagator.cpp
- src/graph/backend/dnnl/passes/insert_ops.cpp
- src/graph/backend/dnnl/passes/insert_ops.hpp
- tests/benchdnn/inputs/graph/complex_fusion/harness_mha_all
- tests/benchdnn/inputs/graph/complex_fusion/harness_mha_ci
- tests/benchdnn/inputs/graph/complex_fusion/mha/GQA-fp16-v2.json
Follow up PR based on #2930. Part 2 for addressing MFDNN-12871 which is requested by PyTorch upstream. This PR refined the legacy GQA pattern and added a pass to handle new pattern. Now, the GQA pattern and graph compilation fusion processed pattern as follows.
GQA pattern that graph API support. 
Q[batch size, group num, group size, seq len, head size]
K[batch size, group num, 1, seq len, head size]
V[batch size, group num, 1, seq len, head size]
The processed GQA pattern after graph compilation.
- Added a pass to transform 5D GQA into 4D so that the ukernel can support it.
- Added some check and layout propagation to avoid unnecessary reorder.
```
onednn_verbose,v1,graph,exec,gpu,100002,sdp,bmm1;scale_div;mask_add;softmax;bmm2,,in0_f16:1:strided:undef:32x2x8x384x64:393216s196608s24576s64 …
```
> graph: refine and support GQA pattern with ukernel

- src/gpu/intel/jit/codegen/codegen.cpp
- src/gpu/intel/jit/codegen/kernel.hpp
- src/gpu/intel/jit/codegen/ngen_helpers.hpp
- src/gpu/intel/jit/codegen/operand.hpp
- src/gpu/intel/jit/codegen/reduce.hpp
- src/gpu/intel/jit/codegen/reg_buf.hpp
- src/gpu/intel/jit/codegen/register_scope.hpp
- src/gpu/intel/jit/codegen/reorder.hpp
- src/gpu/intel/jit/ir/core.cpp
- src/gpu/intel/jit/ir/core.hpp
- src/gpu/intel/jit/ir/message.cpp
- src/gpu/intel/jit/ir/send_plan.cpp
- src/gpu/intel/jit/ir/tensor.hpp
- src/gpu/intel/jit/reorder/gen_reorder.cpp
- src/gpu/intel/jit/reorder/reorder_kernel.hpp
Addresses [MFDNN-12529](https://jira.devtools.intel.com/browse/MFDNN-12529).
> xe: jit: reorder: enable fp4<->hf, bf, f conversions

- doc/graph/fusion_patterns/sdpa.md
- doc/graph/operations/Add.md
- doc/graph/operations/Divide.md
- doc/graph/operations/MatMul.md
- doc/graph/operations/Multiply.md
- doc/graph/operations/Softmax.md
- doc/graph/operations/Subtract.md
- doc/graph/programming_model/low_precision.md
- examples/graph/sdpa.cpp
- examples/graph/sdpa_stacked_qkv.cpp
- src/graph/backend/dnnl/kernels/mqa_decomp_config.cpp
- src/graph/backend/dnnl/kernels/sdp_decomp_config.cpp
- src/graph/backend/dnnl/kernels/sdp_primitive_config.cpp
- src/graph/backend/dnnl/patterns/sdp.cpp
- src/graph/interface/op_def.hpp
- src/graph/interface/op_def_constraint.cpp
- src/graph/interface/op_def_constraint.hpp
- tests/benchdnn/inputs/graph/complex_fusion/harness_mha_all
- tests/benchdnn/inputs/graph/complex_fusion/harness_mha_ci
- tests/benchdnn/inputs/graph/complex_fusion/mha/sdpa-plain-implicit-causal-mask-fp32-bs1.json
- tests/benchdnn/inputs/graph/complex_fusion/mha/sdpa-plain-simplified-f16-f32.json
Address MFDNN-13091
The purpose is to align the intermediate data types in the pattern with those in ATen SDPA and GPU ukernel SDPA.
1. matmul/softmax/binary ops are extended to support mixed data types for inputs and outputs.
2. The two SDPA examples are changed to use f32 intermediate data type, rather than bf16 or f16.
3. The backend is changed to dispatch to GPU ukernel SDPA only when f32 intermediate data type is required.
4. Add test cases for f16/bf16 SDPA with f32 intermediate data type.
With these, now a typical f16 SDPA which can be dispatched to GPU ukernel SDPA looks like below:
> graph: fix the intermediate data types in SDPA patterns

- src/cpu/aarch64/acl_thread.cpp
- src/cpu/aarch64/acl_threadpool_scheduler.cpp
- src/cpu/aarch64/acl_threadpool_scheduler.hpp
Default num_threads to max for acl_threadpool. This brings it in line with the other schedulers. This fixes an out-of-bounds crash in upstream frameworks where ops are configured to be single threaded and then are run in parallel.
Also included some cleanup:
- Use `std::mutex` instead of `arm_compute::Mutex` (was a `typedef`)
- Use `std::lock_guard` instead of `arm_compute::lock_guard` (was a minimal wrapper)
- Add missing `thread_local` to the `acl_tp_benchmark_scheduler` (probably accidentally omitted from https://github.com/uxlfoundation/oneDNN/pull/2264)
> cpu: aarch64: default num_threads to max for acl_threadpool

- doc/primitives/convolution.md
- doc/primitives/matmul.md
- doc/programming_model/data_types.md
- src/gpu/intel/jit/conv/config.cpp
Update documentation referecnes to fp8 type support on GPU. 
Previously FP8 support only included cases where fp8 was used after upconversion using native routines. Now includes f8_e4m3 which is upconverted using a more involved routine, incurring greater overhead. 
All current architectures use upconversion to f16 internally to support fp8 types. 
Update checks in jit:conv to allow fp8 support on more architectures.
> [GPU] FP8 Documentation fixup

- src/gpu/intel/ocl/micro_sdpa.cpp
- src/gpu/intel/ocl/micro_sdpa.hpp
This PR optimizes the SDPA kernel for the 256 and 128 head sizes. We achieve this by further differentiating the HPC and Xe2 architectures as well as integrated and discrete GPUs and updating the tiling strategy for quantization scenarios.
Fixes: https://jira.devtools.intel.com/browse/MFDNN-11755
> xe: sdpa: Update additional tile configurations for quantized kernels

- src/cpu/x64/cpu_reducer.cpp
- src/cpu/x64/jit_avx2_1x1_conv_kernel_f32.cpp
Fixes the following failure:
```
442: run: --conv --engine=gpu --dir=BWD_W ic7688iw3oc135342ow3kw1pw0
442: Error: Function 'execute_reorder' at (sources\tests\benchdnn\dnnl_memory.cpp:182) returned 'runtime_error'
```
and
```
$ ~/dnnl/build_clang/tests/benchdnn/benchdnn --conv --engine=gpu -v1 --batch=test_conv_large_gpu
create: --conv --engine=gpu --dir=BWD_W --dt=f64:f64:f64 --stag=axb --dtag=axb ic2iw86368893oc2ow86368893kw1pw0
run: --conv --engine=gpu --dir=BWD_W --dt=f64:f64:f64 --stag=axb --dtag=axb ic2iw86368893oc2ow86368893kw1pw0
0:PASSED (6273 ms) __REPRO: --conv --engine=gpu --dir=BWD_W --dt=f64:f64:f64 --stag=axb --dtag=axb ic2iw86368893oc2ow86368893kw1pw0
create: --conv --engine=gpu --dir=FWD_D --dt=s8:s8:u8 mb46940ic59iw143oc580ow142kw2pw0
run: --conv --engine=gpu --dir=FWD_D …
```
> cpu: x64: fix invalid immediate encoding in cpu_reducer and conv

- src/common/binary.cpp
The PR disables the check for broadcasted dimensions for the conditional tensor during binary select primitive creation. Doing so stops the primitive creation from failing for a broadcasted select input and instead executes the reference implementation. This is done to allow for the Graph API to move from the select composition implementation and use the select primitive instead.
Related to MFDNN-12979
> cpu: binary: disable broadcast check for select op

- src/cpu/x64/jit_avx2_conv_kernel_f32.cpp
- src/cpu/x64/jit_avx512_common_conv_kernel.cpp
- src/cpu/x64/jit_avx512_core_amx_conv_kernel.cpp
- src/cpu/x64/jit_avx512_core_bf16_conv_kernel.cpp
- src/cpu/x64/jit_brgemm_conv_utils.cpp
- src/cpu/x64/jit_primitive_conf.hpp
This is a fix for [MFDNN-13409](https://jira.devtools.intel.com/browse/MFDNN-13409)
- remove unnecessary checks for size in convolutions: we have unified check by using `has_large_size` after #2827 
- update `has_large_size` function: exclude minibatch from size calculation because we process data image by image in all convolutions
Pre-commit shows no new fails excepting those that have already been in CI.
> fix for big shapes pr

- third_party/ngen/ngen.hpp
Addresses MFDNN-13382. When building under SYCL with gcc 12.3 as the host compiler, accuracy failures are seen in certain fp8 kernels. The culprit is a compiler bug that looks similar to a gcc 13 bug noticed earlier. A similar workaround addresses the failure in this situation.
> ngen: workaround for SYCL + GCC 12.3 compiler bug

- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
Fixes MFDNN-13348
`blocked_16n_B_layout_tag` is not initialized correctly and then the result of `bgmmc.blocked_B` could be incorrect. This could cause segfault in the later computation.
> cpu: x64: matmul: correct blocked_B layout initialization

- tests/benchdnn/graph/bench_graph.cpp
- tests/benchdnn/graph/custom_driver.cpp
- tests/benchdnn/graph/graph.cpp
- tests/benchdnn/graph/graph_memory.cpp
- tests/benchdnn/graph/graph_memory.hpp
- tests/benchdnn/graph/ref_partition.cpp
- tests/benchdnn/graph/ref_partition.hpp
- tests/benchdnn/graph/setting_handler.cpp
The PR enables `--mode-modifer=M` for benchdnn graph driver:
1. Avoid creating reference primitives as well as the memories and customized data filling.
2. For customized operations, handle integral inputs specially for indexing values.
3. Otherwise, use fixed value( `0x3F3F3F3F` (0.747059f) ) for data filling.
```
./tests/benchdnn/benchdnn --graph --mode=F --batch=test_graph_all
Output template: perf,%engine%,%prb%,%-time%,%0time%
perf,cpu,--mode=F --graph --case=op/f32/abs.json,0.0561523,0.139608
perf,cpu,--mode=F --graph --case=op/f32/abs_bwd.json,0.0541992,0.064628
perf,cpu,--mode=F --graph --case=op/f32/add.json,0.0571289,0.0702186
perf,cpu,--mode=F --graph --in-shapes=1:- --case=op/f32/add.json,0.0563965,0.0670133
perf,cpu,--mode=F --graph --case=op/f32/avgpool.json,4.81152,10.1638 …
```
> tests: benchdnn: support --mode-modifer=M for graph driver

- scripts/verbose_converter/src/benchdnn_generator.py
For backwards compatibility, we cannot rely on strict type checks, as instances made by a copy of ir.py will not be recognized in benchdnn_generator.py as those from the ir.py bundled with it.
> scripts: verbose converter: allow post-op duck typing

- src/gpu/intel/jit/gemm/generator/pieces/post_ops.cxx
- src/gpu/intel/jit/gemm/include/problem.hpp
This resolves [MFDNN-12758](https://jira.devtools.intel.com/browse/MFDNN-12758).
<details>
<summary>Pass rate (100%)</summary>
```
$ LD_LIBRARY_PATH="../../src:$LD_LIBRARY_PATH" ./benchdnn --matmul --engine=gpu --mode=C --batch=./total_llm_gemm_12758
0:PASSED (21658 ms) __REPRO: --matmul --engine=gpu --dt=s8:u8:f16 --stag=ab --wtag=ba --dtag=ab --attr-scales=src:per_ocic:f16:1x3072+wei:per_oc:f16 --attr-zero-points=src:per_ocic:u8:1x3072+wei:per_oc:u8 --attr-scratchpad=user 1104x3072:3072x16384
1:PASSED (12317 ms) __REPRO: --matmul --engine=gpu --dt=s8:u8:f16 --stag=ab --wtag=ba --dtag=ab --attr-scales=src:per_ocic:f16:1x3072+wei:per_oc:f16 --attr-zero-points=src:per_ocic:u8:1x3072+wei:per_oc:u8 --attr-scratchpad=user 1104x3072:3072x9216
2:PASSED (43251 ms) __REPRO: --matmul --engine=gpu …
```
> src: gpu: intel: jit: gemm: add dual (src+wei) vector zero points

- src/common/sdpa_utils.hpp
- src/gpu/intel/ocl/micro_sdpa.hpp
- src/gpu/intel/ocl/tile_ops.h
This PR backports an error that appeared in SDPA for very small tensors. 
Fixes: https://jira.devtools.intel.com/browse/MFDNN-13392
Backport commits pull from: https://github.com/uxlfoundation/oneDNN/pull/2854 and https://github.com/uxlfoundation/oneDNN/pull/2633
> [rls-v3.7] backport xe: sdpa: add block 2d load store definition for bf16

- src/common/primitive_hashing.cpp
- src/common/primitive_serialization.cpp
- src/common/sdpa_pd.hpp
- src/common/sdpa_test_iface.cpp
- src/common/sdpa_types.hpp
- src/common/sdpa_utils.hpp
- src/common/type_helpers.hpp
- src/common/verbose.cpp
- src/gpu/intel/ocl/micro_sdpa.cl
- src/gpu/intel/ocl/micro_sdpa.cpp
- src/graph/backend/dnnl/kernels/sdp_primitive_config.cpp
- src/graph/backend/dnnl/op_executable.hpp
- tests/gtests/internals/sdpa_internal.hpp
- tests/gtests/internals/test_sdpa.cpp
This PR adds support for the bottom right causal mask for the SDPA micro kernel. 
Fixes: https://jira.devtools.intel.com/browse/MFDNN-13388
> xe: sdpa: Add support for bottom right causal mask type

- src/cpu/ref_binary.hpp
- src/cpu/ref_deconvolution.hpp
- src/cpu/ref_prelu.hpp
- src/cpu/ref_resampling.hpp
- src/cpu/ref_shuffle.hpp
- src/cpu/simple_resampling.hpp
- src/cpu/x64/brgemm/brgemm.cpp
- src/cpu/x64/brgemm/brgemm_utils.cpp
- src/cpu/x64/brgemm/brgemm_utils.hpp
- src/cpu/x64/injectors/jit_uni_binary_injector.cpp
- src/cpu/x64/jit_brgemm_conv_bwd_strided.cpp
- src/cpu/x64/jit_brgemm_conv_bwd_utils.cpp
- src/cpu/x64/jit_brgemm_conv_utils.cpp
- src/cpu/x64/jit_uni_reorder_direct_copy.cpp
- src/cpu/x64/ukernel/brgemm.cpp
It was found during analysis of logs attached to [MFDNN-13286](https://jira.devtools.intel.com/browse/MFDNN-13286) that a test for concat failed because a concat primitive did not recognized that an input contained f64 data. A reorder created by ref_concat_t did nothing (only generate a message in a log) in a release binary; there is only an assert in a debug version.
I also found several other such places. This PR fixes them.
> cpu: skip f64 inputs

- src/gpu/intel/ocl/rnn/cell_common.cpp
- src/gpu/intel/ocl/rnn/cell_compute.h
- src/gpu/intel/ocl/rnn/cell_gru_lbr.cpp
- src/gpu/intel/ocl/rnn/cell_kind_utility.h
- src/gpu/intel/ocl/rnn/rnn_common.h
- src/gpu/intel/ocl/rnn/rnn_grid.cl
- src/gpu/intel/ocl/rnn/rnn_utils.cpp
- src/gpu/intel/ocl/rnn/simple_cell_fusion.cpp
- src/gpu/intel/ocl/rnn/simple_cell_fusion.hpp
Following is my speedup for the testcase reported in the ticket:
```
[hsadia@sdpmkl170255]$  ../build/tests/benchdnn/benchdnn --rnn --engine=gpu --prop=FWD_I --mode=p --alg=LBR_GRU --direction=left2right --cfg=f32,f16 l1t1000mb1sic256slc256dhc256dic256
Output template: perf,%engine%,%impl%,%name%,%prb%,%Gops%,%+ctime%,%-time%,%-Gflops%,%0time%,%0Gflops%
perf,gpu,ocl:simple:any,,--mode=P --rnn --engine=gpu --tag=any:any:any --alg=LBR_GRU l1t1000mb1sic256slc256dhc256dic256,0.786432,551.407,87.036,9.03571**,92.8107**,8.66013
perf,gpu,ocl:simple:any,,--mode=P --rnn --engine=gpu --cfg=f16 --tag=any:any:any --alg=LBR_GRU l1t1000mb1sic256slc256dhc256dic256,0.786432,1168.18,128.708,6.11019,**138.647**,5.67221
tests:2 passed:2 skipped:0 mistrusted:0 unimplemented:0 invalid_arguments:0 failed:0 …
```
> Add LBR_GRU to cell_fusion kernel for MTL dispatch

- cmake/configuring_primitive_list.cmake
- cmake/options.cmake
- doc/build/build_options.md
Internally implementation for `BUILD_GROUP_NORMALIZATION`/`REG_GNORM_P` already exists, however related value for the build option `ONEDNN_ENABLE_PRIMITIVE` was missing, so adding into cmake and updating documentation.
(passed local testing w -DONEDNN_ENABLE_PRIMITIVE="REORDER;GROUP_NORMALIZATION" and `./build/tests/benchdnn/benchdnn --gnorm --batch=test_gnorm_ci`)
Addresses MFDNN-12937.
> cmake, doc: add GROUP_NORMALIZATION value for ONEDNN_ENABLE_PRIMITIVE

- cmake/configuring_primitive_list.cmake
- cmake/options.cmake
- doc/build/build_options.md
Porting https://github.com/uxlfoundation/oneDNN/pull/3025 changes.
> [backport] cmake, doc: add GROUP_NORMALIZATION value for ONEDNN_ENABLE_PRIMITIVE 

- src/common/primitive_hashing.cpp
- src/common/primitive_serialization.cpp
- src/common/sdpa_pd.hpp
- src/common/sdpa_test_iface.cpp
- src/common/sdpa_types.hpp
- src/common/sdpa_utils.hpp
- src/common/type_helpers.hpp
- src/common/verbose.cpp
- src/gpu/intel/ocl/micro_sdpa.cl
- src/gpu/intel/ocl/micro_sdpa.cpp
- src/graph/backend/dnnl/kernels/sdp_primitive_config.cpp
- src/graph/backend/dnnl/op_executable.hpp
- tests/gtests/internals/sdpa_internal.hpp
- tests/gtests/internals/test_sdpa.cpp
Backport of #3012
This PR adds support for the bottom right causal mask for the SDPA micro kernel.
Fixes: https://jira.devtools.intel.com/browse/MFDNN-13388
> [rls-v3.8] xe: sdpa: Add support for bottom right causal mask type

- src/gpu/intel/jit/conv/config.cpp
- src/gpu/intel/jit/conv/ir_builder.cpp
- src/gpu/intel/jit/pooling/ir_builder.cpp
- src/gpu/intel/jit/reorder/ir_builder.cpp
- src/gpu/intel/jit/v2/conv/kernel_desc.cpp
- src/gpu/intel/jit/v2/conv/plan_registry.cpp
- src/gpu/intel/logging.hpp
As the trace output (`gpu_trace()`) is quite verbose now, this PR adds an intermediate level `debug` (`ONEDNN_VERBOSE=debuginfo=160`) for GPU IR primitives to limit output to the final IR and configuration details (no intermediate passes, no assembly dump).
> [GPU] xe: jit: add debug log level and improve logging

- src/gpu/intel/ocl/gen9_pooling.cl
- src/gpu/intel/ocl/gen9_pooling.cpp
- src/gpu/intel/ocl/ocl_post_ops.h
- src/gpu/intel/ocl/ref_convolution.hpp
- src/gpu/intel/ocl/ref_inner_product.hpp
- src/gpu/intel/ocl/ref_matmul.hpp
- src/gpu/intel/primitive_conf.cpp
- src/gpu/intel/primitive_conf.hpp
- tests/benchdnn/inputs/conv/harness_conv_smoke_ref
- tests/benchdnn/inputs/conv/test_conv_gpu
- tests/benchdnn/inputs/ip/harness_ip_smoke_ref
- tests/benchdnn/inputs/ip/test_ip_gpu
- tests/benchdnn/inputs/matmul/harness_matmul_decompression
- tests/benchdnn/inputs/matmul/harness_matmul_smoke_ref
- tests/benchdnn/inputs/matmul/test_matmul_gpu
- tests/benchdnn/inputs/pool/harness_pool_smoke_ref
- tests/benchdnn/inputs/pool/test_pool_gpu
- tests/benchdnn/matmul/matmul.cpp
Addresses https://jira.devtools.intel.com/browse/MFDNN-12444. 
Broaden ocl:ref coverage and add some smoke tests for key compute bound primitives.
> [GPU] Improve reference kernel coverage.

- src/common/matmul.cpp
- src/cpu/platform.cpp
- src/cpu/reorder/simple_reorder.hpp
- src/cpu/x64/jit_uni_reorder_utils.cpp
- src/cpu/x64/jit_uni_x8s8s32x_1x1_conv_kernel.cpp
- src/cpu/x64/jit_uni_x8s8s32x_1x1_convolution.cpp
- src/cpu/x64/jit_uni_x8s8s32x_conv_kernel.cpp
- src/cpu/x64/jit_uni_x8s8s32x_convolution.cpp
- tests/benchdnn/inputs/matmul/harness_matmul_decompression
Fixes MFDNN-13445, MFDNN-13449
OV asked to relax the condition on a single group for odd dense sizes.
> Bug fixes, relax matmul weights decompressions condition for a single group

- tests/benchdnn/graph/ref_partition.cpp
Fix the reference memory initialization issue for performance mode, as `--mode=P` also requires reference memory.
> benchdnn: graph: resume ref memory init for perf mode

- tests/benchdnn/inputs/graph/complex_fusion/harness_mha_all
- tests/benchdnn/inputs/graph/complex_fusion/harness_mha_ci
A follow-up task of [PR#2894](https://github.com/uxlfoundation/oneDNN/pull/2894
) which fixed the intermediate datatypes in SDPA patterns of Graph API. This PR adds more test cases with f32 intermediate data types. As we need to support both f16/bf16 computation, the cases are added through `--dt` knob rather than new JSON files.
The next step might be enhancing the dt rewrite mechanism to support larger coverage.
> benchdnn: inputs: graph: add more cases using f32 intermediate

- src/gpu/intel/jit/ir/reorder.hpp
- src/gpu/intel/jit/reorder/normalization.cpp
Normalizes the layouts used in IR reorder to try to dispatch to 2d reorder more often. Partially addresses [MFDNN-8974](https://jira.devtools.intel.com/browse/MFDNN-8974).
> xe: jit: ir: normalize IR reorder layouts

- src/gpu/intel/jit/gemm/gen_gemm_kernel.cpp
- src/gpu/intel/jit/gemm/generator/pieces/allocators.cpp
- src/gpu/intel/jit/gemm/generator/pieces/allocators.hpp
- src/gpu/intel/jit/gemm/generator/pieces/state.cpp
Fixes two bugs in the virtual flag allocator, one silly one, and one subtle one which seems to be the root cause of several x8x8bf16 failures (e.g. MFDNN-13358).
> xe: jit: gemm: virtual flag allocator fixes

- src/gpu/intel/jit/conv/config.cpp
- src/gpu/intel/jit/conv/problem.cpp
- src/gpu/intel/jit/conv/problem.hpp
- src/gpu/intel/jit/ir/tensor_config.cpp
- src/gpu/intel/jit/ir/tensor_config.hpp
Jira: [MFDNN-12923](https://jira.devtools.intel.com/browse/MFDNN-12923)
Performance data from BMG:
| Case                                                                                             | base perf (GOps/sec) | test perf (GOps/sec) | Ratio |
|--------------------------------------------------------------------------------------------------|----------------------|----------------------|-------|
| --dir=FWD_D --dt=bf16:bf16:bf16 --stag=abx --wtag=abx --dtag=abx mb128ic64ih64oc256oh64kh1ph0    | 3605.594             | 21190.681            | 5.88  |
| --dir=FWD_D --dt=bf16:bf16:bf16 --stag=abx --wtag=abx --dtag=abx mb64ic64ih128oc128oh128kh1ph0   | 3201.723             | 17190.661            | 5.37  |
| --dir=FWD_D --dt=bf16:bf16:bf16 --stag=abx --wtag=abx --dtag=abx …
> xe: conv: avoid reorder with NCHW when possible

- doc/build/build_options.md
- doc/graph/fusion_patterns/gqa.md
- doc/graph/fusion_patterns/sdpa.md
1. Removed the GPU vendor limitation from document.
- https://github.com/uxlfoundation/oneDNN/pull/2676
- https://github.com/uxlfoundation/oneDNN/pull/2971
2. Updated the optimized head size from 256 to 512.
- https://github.com/uxlfoundation/oneDNN/pull/2976
4. Separated d_qk and d_v as we support d_qk != d_v.
- https://github.com/uxlfoundation/oneDNN/pull/2741
> doc: graph: a few document fixes

- tests/benchdnn/graph/ref_partition.cpp
Backport of https://github.com/uxlfoundation/oneDNN/pull/3034
> [backport][rls-v3.8]benchdnn: graph: resume ref memory init for perf mode

- tests/benchdnn/inputs/matmul/harness_matmul_decompression
These test cases  are not supported by cpu and return unimplemented. Revert back to original cases.
Fixup for #2366.
> tests: benchdnn: remove fpmath=f16 for some cases

- third_party/ngen/ngen.hpp
- third_party/ngen/ngen_asm.hpp
- third_party/ngen/ngen_core.hpp
- third_party/ngen/ngen_elf.hpp
- third_party/ngen/ngen_interface.hpp
- third_party/ngen/ngen_pseudo.hpp
Addresses a GTPin request to support the addition of an implicit argument buffer prior to the cross-thread data (normal kernel arguments), by inserting relocations into the prologue.
GTPin uses this for its new HLIF (high-level instrumentation framework) tooling, and in some cases it might be needed for debugging under gdb.
> ngen: add cross-thread data relocations for GTPin

- src/gpu/intel/jit/conv/config.cpp
Related Jira: [MFDNN-13336](https://jira.devtools.intel.com/browse/MFDNN-13336)
No broad performance impact: there are a very few speed-ups and regressions without affecting KPIs much but it helps the above request so let's change the heuristic:
```
perf,gpu,jit:ir,,--mode=F --conv --engine=gpu --dir=FWD_I --dt=u8:s8:s8 --bia-dt=f32 --stag=abcd --attr-post-ops=mul:f32:2+swish:1+linear:2.68555 mb16ic3ih640oc48oh320kh6sh2ph2,16.9162,55.3884,0.922812,18331.2,0.938702,18020.9
perf,gpu,jit:ir,,--mode=F --conv --engine=gpu --dir=FWD_I --dt=u8:s8:s8 --bia-dt=f32 --stag=abcd --attr-post-ops=mul:f32:2+swish:1+linear:2.68555 mb16ic3ih640oc48oh320kh6sh2ph2,16.9162,52.032,0.770729,21948.3,0.784391,21566.1
```
> xe: conv: adjust layout heuristic for small channels

- src/gpu/intel/ocl/binary_common.h
- src/gpu/intel/ocl/gen9_binary.cl
- src/gpu/intel/ocl/gen9_binary.cpp
- src/gpu/intel/ocl/gen9_binary.hpp
- src/gpu/intel/ocl/simple_binary.cl
- src/gpu/intel/ocl/simple_binary.cpp
- src/gpu/intel/ocl/simple_binary.hpp
- src/gpu/intel/primitive_conf.hpp
- tests/benchdnn/binary/binary.cpp
Currently the select algorithm for the binary primitive is only supported on CPU. This PR introduces initial ternary op support for ref gpu binary kernels. 
$$dst[i] = src_2[i] ? src_0[i] : src_1[i]$$
[MFDNN-13247](https://jira.devtools.intel.com/browse/MFDNN-13247)
> [GPU] xe: binary: enable support for select algorithm 

- tests/benchdnn/inputs/graph/complex_fusion/harness_mha_all
- Clean the test cases for JSON file `sdpa-plain-scale-by-mul-f16.json`, which was removed in https://github.com/uxlfoundation/oneDNN/pull/2949.
- Add test cases for multiply scales with `--op-kind` rewrite for `sdpa-plain-simplified-f16-f32.json`
> benchdnn: graph: inputs: clean removed mha test cases

- src/cpu/x64/matmul/amx_blocking_heuristics.cpp
Tomasz discovered correctness error for case:
benchdnn --matmul --allow-enum-tags-only=false --dt=f16:f16:f16 --wtag=ab **--strides=64x1::112x1** -v5 20x36:36x108
This PR is a fix for this error in matmul with stride for matrix A. In the above example the K is 36 but LDA is 64. We can't use extandable_k for such shapes.
> x64: brgemm matmul: update extendable_k_ condition

- examples/graph/graph_example_utils.hpp
- examples/primitives/concat.cpp
- examples/primitives/sum.cpp
- src/common/logging.cpp
- src/common/primitive_attr_quant.hpp
- src/common/reorder.cpp
- src/common/resource.hpp
- src/common/thread_local_storage.hpp
- src/cpu/cpu_memory_storage.hpp
- src/xpu/ocl/buffer_memory_storage.hpp
- src/xpu/sycl/usm_memory_storage.hpp
- src/xpu/sycl/verbose.hpp
- tests/benchdnn/dnnl_common.cpp
- tests/benchdnn/dnnl_memory.cpp
- tests/benchdnn/rnn/rnn.hpp
- tests/benchdnn/self/common.cpp
- tests/benchdnn/utils/parser.cpp
- tests/gtests/internals/test_utils.cpp
- tests/gtests/internals/test_utils.hpp
- tests/gtests/test_concat.cpp
- tests/gtests/test_convolution_backward_data_common.hpp
- tests/gtests/test_convolution_backward_weights_common.hpp
- tests/gtests/test_convolution_forward_common.hpp
- tests/gtests/test_deconvolution.cpp
- tests/gtests/test_sum.cpp
A lot of minor Coverity issues, almost all about using `const auto &`, `std::move` or missing default destructor.
> common: fixing minor Coverity issues

- scripts/fix_header_guards.py
- src/cpu/ppc64/ppc64_gemm_driver.hpp
- src/cpu/ppc64/ppc64_gemm_s8x8s32.hpp
- src/cpu/rv64/rvv_nchw_pooling.hpp
- src/cpu/s390x/helpers.h
- src/cpu/s390x/kernel_s16s16s32.hpp
- src/cpu/s390x/pack.hpp
1. Fix the exit code on failure
2. Exclude files outside of src/ and include/
See the [header guard check](https://github.com/uxlfoundation/oneDNN/actions/runs/14365944947/job/40278772887?pr=3032) from #3032, for example.
> scripts: header check: fix exit codes + ignore tests/examples

- src/common/ittnotify.cpp
- src/common/logging.cpp
2 fixes for issues with spdlog throwing exceptions and 1 for potentially out-of-bounds access of `prim_kind_itt_strings`.
> common: fixes for coverity major & moderate issues

- src/gpu/intel/compute/zero_pool.cpp
- src/gpu/intel/jit/gemm/gen_gemm.cpp
- src/gpu/intel/jit/gemm/gen_gemm.hpp
Closes MFDNN-13250. A memory leak was inadvertently introduced when introducing initial SYCL graph recording support for zero pools in GEMM. The memory leak is expected when under recording mode (temporary measure -- will be replaced with async malloc/free when graph recording support available), but not in regular execution.
> xe: jit: gemm: fix zero pool memory leak under SYCL when not recording

- src/gpu/intel/jit/gemm/generator/pieces/gemm_setup.cxx
- src/gpu/intel/jit/gemm/generator/strategy.cpp
Closes MFDNN-13294, MFDNN-13453. Two fixes, one functional, both for performance:
* (Functional/performance) Upstream gemmstone does not use k blocking by default on newer GPUs (`bk0`), but oneDNN behavior did not match
* (Performance) oneDNN is imposing an arbitrary limit on the C repacking period that isn't needed.
> xe: jit: gemm: misc fixes

- src/common/ittnotify.cpp
- src/common/logging.cpp
> [backport][rls-v3.8] common: fixes for coverity major & moderate issues

- src/graph/backend/dnnl/passes/memory_planning.cpp
- src/graph/backend/dnnl/passes/transform.cpp
- src/graph/interface/graph.cpp
- src/graph/utils/pm/nested_matcher.cpp
- tests/benchdnn/graph/custom_driver.cpp
- tests/benchdnn/graph/deserialize.cpp
- tests/benchdnn/graph/flex_rewrite.cpp
- tests/benchdnn/graph/graph.cpp
- tests/benchdnn/graph/ref_partition.cpp
- tests/benchdnn/graph/setting_handler.cpp
Fixed more coverity minor issues (MFDNN-13480):
- removed a few unused variables.
- used const reference instead.
> graph: use const reference per coverity's warnings

- src/cpu/aarch64/jit_uni_eltwise.cpp
- src/cpu/cpu_eltwise_list.cpp
Currently, PyTorch’s mapping to eltwise algorithms for `BF16` introduces multiple reorder operations:
reorder(BF16 → FP32) → Eltwise → reorder(FP32 → BF16). 
Relevant iDeep PR: https://github.com/intel/ideep/pull/350
This PR proposes moving the BF16-to-FP32 conversion directly into the JIT-generated code. By doing so, we eliminate the need for explicit reorder operations, resulting in performance improvements for these ops.
Benchdnn perf for Gelu ~ similar times for fp32 and bf16 equivalent. 
`OMP_NUM_THREADS=1 ./benchdnn --eltwise   --alg=gelu_erf --alpha=0 --beta=0 --mode=p --dt=bf16  1024x4096` 
Ref implementation: `total perf: min(ms):74.1855 avg(ms):74.2793` 
Current implementation:  `total perf: min(ms):6.7478 avg(ms):6.78948` **~12x speedup** 
FP32 run: `total perf: min(ms):6.71167 …
> cpu: aarch64: Add BF16 support for eltwise JIT via reordering to FP32

- src/graph/backend/dnnl/passes/memory_planning.cpp
- src/graph/backend/dnnl/passes/transform.cpp
- src/graph/interface/graph.cpp
- src/graph/utils/pm/nested_matcher.cpp
- tests/benchdnn/graph/custom_driver.cpp
- tests/benchdnn/graph/deserialize.cpp
- tests/benchdnn/graph/flex_rewrite.cpp
- tests/benchdnn/graph/graph.cpp
- tests/benchdnn/graph/ref_partition.cpp
- tests/benchdnn/graph/setting_handler.cpp
> [rls-v3.8] graph: use const reference per coverity's warnings

- src/cpu/x64/jit_avx512_core_x8s8s32x_1x1_conv_kernel.cpp
- src/cpu/x64/jit_avx512_core_x8s8s32x_1x1_convolution.cpp
- src/cpu/x64/jit_avx512_core_x8s8s32x_1x1_convolution.hpp
Fixes MFDNN-13473 (large buffer case).
The issue is not related to the large shapes directly. Using the large shapes results in falling back to this implementation that had a bug manifesting as a segfault. We recently changed the interface of scales mask but overlooked this place that required some adjustments.
> cpu: x64: fix using new scale mask interface

- src/gpu/intel/ocl/simple_binary.cl
- src/gpu/intel/ocl/simple_binary.cpp
- src/gpu/intel/primitive_conf.hpp
Fixes incorrect results in binary_select with src_2 broadcasting on GPU. 
[MFDNN-13516](https://jira.devtools.intel.com/browse/MFDNN-13516)
> xe: binary_select: fix src_2 broadcasting

- src/cpu/reorder/simple_reorder.hpp
- src/cpu/x64/matmul/brgemm_matmul_reorders.cpp
Backport of https://github.com/uxlfoundation/oneDNN/pull/3070
> [backport][rls-v3.8] fixup: common: matmul: allow single scale/zp group of any size (fixes MFDNN-13507)

- src/cpu/aarch64/jit_sve_1x1_convolution.hpp
- src/cpu/aarch64/jit_sve_convolution.hpp
jit_sve_conv is above acl_conv in the convolution list since it performs better for fp32, however for fpmath_mode::bf16 jit_conv does not support lower precision calculation so we skip it for acl_conv if oneDNN was compiled with ACL
When tested with ResNet50 and `ONEDNN_DEFAULT_FPMATH_MODE=BF16` we see:
- ~1.34x speedup for 8 threads
- ~1.41x speedup for 16 threads
- ~1.17x speedup for 32 threads
These are in line with results when ACL conv was above jit conv for `FPMATH_MODE::BF16`
For a minimal benchdnn reproducer use:
```
OMP_NUM_THREADS=16 ONEDNN_DEFAULT_FPMATH_MODE=BF16 ./build/tests/benchdnn/benchdnn -v5 --mode=p --conv mb1_ic256oc256_ih28oh14kh3sh2dh0ph1_iw28ow14kw3sw2dw0pw1 mb1_ic1024oc2048_ih14oh7kh1sh2dh0ph0_iw14ow7kw1sw2dw0pw0
```
> cpu: aarch64: dispatch fpmath_mode::bf16 conv to ACL

- src/gpu/intel/ocl/ref_reorder.cl
- src/gpu/intel/ocl/ref_reorder.cpp
Addresses the register spill warnings in [MFDNN-13443](https://jira.devtools.intel.com/browse/MFDNN-13443).
> xe: ocl: reorder: prefer SIMD16 mode for ref

- src/gpu/intel/compute/kernel_ctx.hpp
> [rls-v3.8] xe: fix post-op runtime dimension handling

- src/gpu/intel/compute/kernel_ctx.hpp
- src/gpu/intel/ocl/convolution_inner_product.hpp
- src/gpu/intel/ocl/gemm_inner_product.hpp
- src/gpu/intel/ocl/gen9_binary.hpp
- src/gpu/intel/ocl/gen9_pooling.hpp
- src/gpu/intel/ocl/gen9_wino_convolution.hpp
- src/gpu/intel/ocl/ocl_post_ops.h
- src/gpu/intel/ocl/reduction/combined_reduction.hpp
- src/gpu/intel/ocl/reduction/ref_reduction.hpp
- src/gpu/intel/ocl/ref_convolution.hpp
- src/gpu/intel/ocl/ref_eltwise.hpp
- src/gpu/intel/ocl/ref_group_normalization.cpp
- src/gpu/intel/ocl/ref_inner_product.hpp
- src/gpu/intel/ocl/ref_matmul.hpp
- src/gpu/intel/ocl/ref_pooling.hpp
- src/gpu/intel/ocl/ref_resampling.hpp
- src/gpu/intel/ocl/simple_binary.hpp
- src/gpu/intel/ocl/simple_softmax.cl
- src/gpu/intel/primitive_conf.cpp
- src/gpu/intel/primitive_conf.hpp
Fixes the invalid use of DNNL_RUNTIME_DIM_VAL for offset calculations in post-ops that by pure chance is functionally correct. This circumvents a compiler issues exposed by [this iGC change](https://github.com/intel/intel-graphics-compiler/commit/c7b3bb58542d7d91e34271e5c15fa442a0d2fa58) on the workload
```
--matmul --engine=gpu --stag=ab --wtag=ab --dtag=ab --runtime_dims_masks=0:2 --attr-post-ops=prelu:per_oc 3x20:20x4_n"postops+runtime_dims_2d"
```
The constant -9223372036854775808L (DNNL_RUNTIM_DIM_VAL) is parsed as two tokens (-) and (9223372036854775808L). The token 9223372036854775808L is in some sense invalid as it does not fit in the long type, so clang promotes it to long-long which is an i128 by the OpenCL specification. IGC then attempts to perform calculations with this i128 …
> xe: fix post-op runtime dimension handling

- tests/benchdnn/graph/ref_primitive.cpp
- tests/benchdnn/matmul/cfg.cpp
> [backport][rls-v3.8] benchdnn: graph: fix false positives by reducing the matmul range

- src/gpu/intel/ocl/ref_reorder.cl
- src/gpu/intel/ocl/ref_reorder.cpp
> [rls-v3.8] xe: ocl: reorder: prefer SIMD16 mode for ref

- .github/labels.yml
Adds two new labels to cover code changes that are currently left unlabeled.
> github: workflows: added component:common and third_party labels

- src/common/binary.cpp
- src/common/convolution.cpp
- src/common/deconvolution.cpp
- src/common/eltwise.cpp
- src/common/group_normalization.cpp
- src/common/inner_product.cpp
- src/common/layer_normalization.cpp
- src/common/matmul.cpp
- src/common/pooling.cpp
- src/common/primitive_attr.cpp
- src/common/primitive_attr.hpp
- src/common/reduction.cpp
- src/common/resampling.cpp
- src/common/softmax.cpp
- src/cpu/x64/jit_uni_i8i8_pooling.cpp
- src/cpu/x64/jit_uni_pool_kernel.cpp
- src/cpu/x64/jit_uni_pool_kernel.hpp
1) Primitives that use ref_post_ops_t did not catch error cases when a binary post-op has an unsupported src1_desc.data_type during a primitive descriptor creation. Errors were detected only during a primitive execution, and only debug asserts were used, and NAN was used as a result of the operation in release binaries.
The PR has a minimal fix for reference implementations: those errors are caught during a primitive descriptor creation.
Update: Creation of primitives with binary post-op with user_src1_desc.data_type == f64 is disabled for CPU engine.
2) A similar issue existed in jit_uni_pool_kernel_t (used by jit_uni_pooling_fwd_t, jit_uni_pooling_bwd_t) and jit_uni_i8i8_pooling_fwd_ker_t (used by jit_uni_i8i8_pooling_fwd_t):
a) a support of src data type of a binary post-op was not …
> Fix postop support checks during primitive descriptor creation

- doc/primitives/convolution.md
- doc/primitives/matmul.md
- doc/programming_model/data_types.md
- Add fp4/int4 inference support to GPU side of data_type matrix
- Note general limitations on fp4/fp8 support 
- Update conv, matmul primitives with fp4
> Update fp4 Documentation

- src/graph/backend/dnnl/kernels/sdp_decomp.cpp
- src/graph/backend/dnnl/kernels/sdp_decomp.hpp
- src/graph/backend/dnnl/kernels/sdp_decomp_config.cpp
- src/graph/backend/dnnl/kernels/sdp_decomp_config.hpp
- src/graph/backend/dnnl/passes/transform.cpp
- src/graph/backend/dnnl/patterns/sdp.cpp
- Support int8 output softmax with scale and zp in large partition and decompose kernel
- For int8 output softmax
- Only with scale, we would treat the scale as the dst scale
- With scale and zp, or only zp, we would treat the scale and zp as post-binary.
> graph: backend: dnnl: fix int8 sdpa with softmax

- src/gpu/generic/sycl/ref_reorder.cpp
- src/gpu/generic/sycl/ref_reorder.hpp
- src/gpu/generic/sycl/reorder_kernels.hpp
- src/gpu/generic/sycl/sycl_io_helper.hpp
- src/gpu/generic/sycl/sycl_primitive_conf.hpp
- tests/benchdnn/reorder/reorder.cpp
- tests/benchdnn/utils/numeric.cpp
- tests/benchdnn/utils/numeric.hpp
This PR enables zero point support to the SYCL backend's reorder, and adds skips in benchdnn to skip unsupported cases for the SYCL backend
> ref: sycl: enable zp support in reorder and skip unsupported tests

- src/gpu/intel/ocl/gen9_pooling.cpp
The mapping from local_ids to sub_group_local_ids is not specified in the OpenCL specification. Some OpenCL implementations, such as the gen9_pooling implementation, assume this mapping occurs on the vectorized dimension. To avoid this limitation, this patch moves the vectorized dimension to be innermost as that causes the desired behavior (I hope) in the Intel OpenCL runtime. This fixes such an issue that occurs on the large buffer shape:
```
benchdnn --pool --engine=gpu --dir=BWD_D --dt=f16:f16 --tag=axb --alg=avg_p --impl=gen9 mb4294967311ic1iw1ow1kw3pw1
```
Edit: Looks like the original change produced too many performance regressions, so I modified this to be restricted to the pooling implementation. There were some large performance improvements in some cases, so I filed …
> xe: compute: dispatch: map vectorized dim to index 0

- CMakeLists.txt
This is a patch release containing the following changes to v3.7.2:
* Fixed correctness issue in matmul with non-trivial strides for the first tensor on processors with Intel AMX instruction set support (e18c622a3cbf766854b649de695271cfd4c19e89)
* Removed spurious warning messages for SDPA subgraph on Intel GPUs (05541bb8004587eff64a69840a3d75b8245ed099, 9e9a3a6f0a611f5f5a023f2d10e8dac94a75e195)
* Fixed `segfault` in `fp32` matmul with `bf16` math mode on processors with Intel AVX2 instruction set support (7d495ae13d6ce8f9a21a7db29d157e3f34bffb81)
* Fixed performance regression in `bf16` 3D convolution backpropagation on processors with Intel AVX-512 and Intel DL Boost instruction set support (c38e02c577e92080da92c29fb2bf6f9a0b00dbb6, 67afc74d6d681ab6556a12f897a8269e7dbd22f6)
* Worked …
> oneDNN v3.7.3 patch release

- src/gpu/intel/jit/gemm/generator/pieces/post_ops.cxx
To maintain proper precision, inv needs performed on the Tacc data type. This is already handled later in the code, rendering the inversion removed in this PR unnecessary.
Fixes [MFDNN-13468](https://jira.devtools.intel.com/browse/MFDNN-13468).
> xe: jit: gemm: remove invalid inv

- src/gpu/intel/jit/gemm/include/gemmstone/kernel_catalog.hpp
- src/gpu/intel/jit/gemm/selector/kernel_selector.cpp
PR adds one more gemm kernel restriction kind. 
Some kernels currently being tuned for BMG failed ktool's g-tests and so they require this limitation. PR is synced with the latest gemmstone changes.
> [GPU] jit: gemm: add A/B offset restriction (aboffset)

- tests/benchdnn/inputs/matmul/harness_matmul_generated_ci
This reverts commit 4ec1b84f03927d3ac7ec2a4e1bc4d470854a6637 from #2918.
> Revert "tests: benchdnn: inputs: drop generated gemm cases causing crashes

- doc/graph/rst/graph_supported_operations.rst
GenIndex and GreaterEqual ops are added previously in https://github.com/uxlfoundation/oneDNN/pull/2330, but the links were missing. This PR adds the links.
> doc: graph: add link to ops of genindex and greaterequal

- src/cpu/aarch64/acl_convolution_utils.hpp
Temporary fix for https://github.com/uxlfoundation/oneDNN/issues/2303 while the main issue gets resolved in ComputeLibrary.
The bug mentioned in the issue appears when NANs exist in one of the buffers while calling CpuGemmConv2d. This can be resolved by setting the buffer to all 0s. This is however not an ideal solution so the ComputeLibrary team is working on a long-term solution. This fix should be removed once that fix has been merged to ComputeLibrary.
> cpu: aarch64: conv: fix fast math NAN issue

- tests/benchdnn/common.cpp
- tests/benchdnn/common.hpp
- tests/benchdnn/dnnl_common.cpp
- tests/benchdnn/dnnl_common.hpp
Adds zmalloc allocation tracing to make identifying memory allocation issues easier and fixes some of the issues caught by the tracing. Sample use case:
```
$ ~/dnnl/build/tests/benchdnn/benchdnn -v1 --conv --engine=gpu --dir=FWD_D --dt=s8:s8:u8 mb46940ic59iw143oc580ow142kw2pw0
create: --conv --engine=gpu --dir=FWD_D --dt=s8:s8:u8 mb46940ic59iw143oc580ow142kw2pw0
run: --conv --engine=gpu --dir=FWD_D --dt=s8:s8:u8 mb46940ic59iw143oc580ow142kw2pw0
run ref: --conv --engine=cpu --dir=FWD_D --dt=s8:s8:u8 mb46940ic59iw143oc580ow142kw2pw0
[CHECK_MEM][WARNING]: zmalloc allocation exceeded expected size 22.546154 GB
0:PASSED (28311 ms) __REPRO: --conv --engine=gpu --dir=FWD_D --dt=s8:s8:u8 mb46940ic59iw143oc580ow142kw2pw0
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 invalid_arguments:0 …
```
> benchdnn: add zmalloc memory tracing

- src/gpu/intel/jit/gemm/generator/pieces/post_ops.cxx
To maintain proper precision, inv needs performed on the Tacc data type.
Backports #3109.
> [rls-v3.8] xe: jit: gemm: remove invalid inv

- src/gpu/intel/ocl/gemm_matmul.hpp
Apply dim adjustment to src scales as well as wei, fixes this case dispatching to ref because of unadjusted scale mask: 
```
./tests/benchdnn/benchdnn -v5 --matmul --reset --allow-enum-tags-only=0 --engine=gpu:0 --runtime_dims_masks= --dt=s8:u4:f16 --stag=abc --wtag=cab --dtag=abc --strides=:: --attr-post-ops=binary_add:f16:6:abc --attr-scales=src0:per_ocic:f16:1x11008+wei:per_oc:f16:128x1 --attr-zero-points=wei:per_ocic:u8:128x1 --attr-scratchpad=user 1x6x11008:1x11008x4096
create: --matmul --engine=gpu --allow-enum-tags-only=false --dt=s8:u4:f16 --stag=abc --wtag=cab --dtag=abc --attr-scales=src:per_ocic:f16:1x11008+wei:per_oc:f16:128x1 --attr-zero-points=wei:per_ocic:u8:128x1 --attr-post-ops=add:f16:6:abc --attr-scratchpad=user 1x6x11008:1x11008x4096
oneDNN implementation: ocl:ref:any …
```
> [GPU] Apply GEMM dim fixup to src scale

- tests/benchdnn/inputs/conv/shapes_basic_gpu
Fixup for #3120. `shapes_basic_gpu` should be restored as it's used by `test_conv_gpu` input file.
Will replace this file by `shapes_ci_gpu` which has better coverage but need more time to confirm there are no failures with Nightly. This PR is a quick fixup.
> fixup: benchdnn: conv: inputs: improve GPU CI coverage

- src/cpu/x64/matmul/amx_blocking_heuristics.cpp
- src/cpu/x64/matmul/amx_blocking_heuristics.hpp
This PR fixes 
https://jira.devtools.intel.com/browse/MFDNN-13324
https://jira.devtools.intel.com/browse/MFDNN-13503
Matmul performance issues related to blocking strategies.
SPR-E2 56c@2.2GHz | BF16 | INT8
-- | -- | -- 
3D-UNet Inference | 99% | 100%
3D-UNet Inference RT | 101% | 104%
MaskRCNN Inference | 99% | 101%
MaskRCNN Inference RT | 101% | 108%
MaskRCNN Training | 100% | N/A
ResNeXt-101 Inference | 100% | 100%
ResNeXt-101 Inference RT | 100% | 101%
ResNet-50 v1.5 Inference | 100% | 100%
ResNet-50 v1.5 Inference RT | 99% | 100%
ResNet-50 v1.5 Training | 100% | N/A
SSD-ResNet-34 Inference | 99% | 100%
SSD-ResNet-34 Inference RT | 101% | 104%
SSD-ResNet-34 Training | 100% | N/A
Vision Transformer Inference | 100% | 100%
Vision Transformer Inference RT | 99% | 100%
MaskRCNN Inference …
> cpu: x64: matmul: AMX blocking heuristics fixes

- src/cpu/x64/brgemm/jit_brgemm_amx_uker.cpp
Previously, a large offset exceeding INT_MAX would trigger an assertion failure, leading to a segmentation fault. This change modifies the behavior to call a fallback function that correctly handles offsets exceeding the standard range
> cpu: x64: ip: fix integer overflow in offsets

- tests/benchdnn/brgemm/cfg.cpp
- tests/benchdnn/conv/cfg.cpp
- tests/benchdnn/deconv/cfg.cpp
- tests/benchdnn/ip/cfg.cpp
- tests/benchdnn/matmul/cfg.cpp
- tests/benchdnn/utils/cfg.hpp
- tests/benchdnn/utils/cold_cache.cpp
* Update safe_n_acc to return fixed number of elements for very low precision dt.
* Move all logic spread across configs under a base config.
* Utilize a single call across cfgs to re-use the filling logic.
A better version of https://github.com/uxlfoundation/oneDNN/pull/3101 (the commit was reverted on main) which was exposed to the issue after matmul driver coverage was updated between the validation and promotion. Besides, the issue was caught on Nightly coverage which was not validated.
And a fix for cold-cache variable overflow.
> benchdnn: utils: cfg: consolidate adjustment logic under one umbrella

- src/cpu/x64/matmul/amx_blocking_heuristics.cpp
- src/cpu/x64/matmul/amx_blocking_heuristics.hpp
The backport of [#3145](https://github.com/uxlfoundation/oneDNN/pull/3145).
> Backport: cpu: x64: matmul: AMX blocking heuristics fixes (backport v3.8)

- src/gpu/intel/jit/gemm/generator/pieces/gemm_setup.cxx
- src/gpu/intel/jit/gemm/generator/pieces/matrix_multiply.cxx
Addresses MFDNN-13578. Two fixes for dynamic quantization scenarios (int4/8 wei/src + f32 dst):
* C repack period could exceed the k chunk size when using interleaved k-parallelization, which is illegal because different k chunks have different scale factors.
* When only src has grouped scales, kernels could fail to generate due to an indexing glitch.
> xe: jit: gemm: dynamic quantization fixes

- src/gpu/intel/ocl/micro_sdpa.cl
- src/gpu/intel/ocl/micro_sdpa.cpp
- src/gpu/intel/ocl/tile_ops.h
- tests/gtests/internals/test_sdpa.cpp
The micro_sdpa kernel was throwing an overflow warning for when the
PREFETCH_REMAINDER was set to zero. This was caused because the pointer offset
calculation was being done within the function call. Moving the offset
calculation outside of the call fixes the register overflow warning.
Fixes: https://jira.devtools.intel.com/browse/MFDNN-13443
> xe: sdpa: fix register overflow warning in prefetch functions 

- src/common/primitive_serialization.cpp
- tests/benchdnn/dnnl_memory.cpp
Removing some `#ifdef DNNL_EXPERIMENTAL_SPARSE` cases left after sparse promotion, most likely due to complex rebases.
> common: remove DNNL_EXPERIMENTAL_SPARSE remnants

- tests/benchdnn/inputs/matmul/harness_matmul_generated_ci
Almost all issues uncovered by #2434 have been fixed, except for one remaining issue ([MFDNN-13567](https://jira.devtools.intel.com/browse/MFDNN-13567)). This patch suppresses that particular test case for now so that the CI status report passes, which will help prevent introducing regressions. This PR should be reverted once a fix for MFDNN-13567 is merged.
> benchdnn: inputs: matmul: suppress warning while it is fixed

- src/cpu/aarch64/jit_uni_reorder.cpp
- tests/benchdnn/inputs/reorder/test_reorder_float16
This PR adds support for fp16 JIT reorder for data type f16->f16. 
Below are small test case logs that demonstrate performance numbers before and after.
`./tests/benchdnn/benchdnn --reorder --sdt=f16 --ddt=f16 --stag=abc --dtag=aBc8b --mode=p 1x4096x4096`
**(new) jit:uni**: `total perf: min(ms):0.564941 avg(ms):1.01874`
**(old) simple:any**: `total perf: min(ms):25.6047 avg(ms):27.257`
> src: cpu: aarch64: Enable JIT fp16 -> fp16 reorder

- tests/benchdnn/utils/compare.cpp
- tests/benchdnn/utils/fill.cpp
Turned out there is a snowflake that doesn't fill memory in f32 (fused depthwise convolution scales).
And turned out there's a snowflake that doesn't get exp mem for comparison in f32 (compensation buffers of reorders).
Added two changes to address those which should fixed newly introduced failures in Nightly.
> benchdnn: fix Nightly failures after optimizations landed

- src/gpu/intel/compute/kernel_ctx.hpp
One of sign that there is a driver issue is passing tests when kernels were compiled without optimization. To make such investigation easier PR adds this option and env variable in dev mode.
> [GPU] add cl-opt-disable option

- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
It fixes [MFDNN-13311](https://jira.devtools.intel.com/browse/MFDNN-13311). 
`buffer_b_chunk_sz` should be aligned with 
`char *get_buf_B_ptr(int ithr, int k_blk_idx, int n_blk_idx, int gb)` logic implemented here:
https://github.com/uxlfoundation/oneDNN/blob/main/src/cpu/x64/matmul/brgemm_matmul.cpp#L1688
The issue accidentally observed on the big number of threads (>193).
> x64: matmul: Fix buffer B chunk size / Buffer B per thread size

- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
Backport of https://github.com/uxlfoundation/oneDNN/pull/3161
[Nightly Pre-CI](https://ecmd.jf.intel.com/commander/link/jobDetails/jobs/f026bd81-fbe9-f1bf-8e3d-a4bf010d0e2d?objectId=job-f026bd81-fbe9-f1bf-8e3d-a4bf010d0e2d&filterName0=jobsPageSearchMKL-DNN&filterDepth=1)
Fixes all -wtag=abcd cases & no new failures. --wtag=abdc to be fixed in the different PR
> [rls-v3.8] x64: matmul: Fix buffer B per thread size initialization.

- doc/environment.yml
- Added doxygen and graphviz into dependencies as currently both are required to build documentation (will re-evaluate the need for dot/graphviz later).
- Disallowed default channel.
> doc: update environment.yml file

- src/gpu/intel/sycl/l0/utils.cpp
Closes MFDNN-13606. #2245 dropped support for some older Level Zero drivers that do not report systolic availability, causing major performance regressions for these old drivers. This PR manually re-enables systolic for older platforms with known systolic availability which may have such drivers installed.
> xe: sycl: l0: override systolic detection for older platforms

- src/common/verbose.hpp
Partially addresses [MFDNN-13191](https://jira.devtools.intel.com/browse/MFDNN-13191).
> common: verbose: avoid UB for internal primitives

- src/gpu/intel/ocl/gemm_matmul.hpp
Fix build warning on release compilers.
Fixes # [MFDNN-13626](https://jira.devtools.intel.com/browse/MFDNN-13626)
> [GPU][Rls-v3.8] Fix build warning

- src/gpu/intel/compute/kernel_ctx.hpp
- src/gpu/intel/config.hpp
- src/gpu/intel/jit/conv/lookup_table.cpp
- src/gpu/intel/jit/gemm/generator/pieces/problem_utils.cpp
- src/gpu/intel/jit/gemm/generator/strategy_parser.cpp
- src/gpu/intel/microkernels/shim.cpp
- third_party/ngen/ngen_interface.hpp
- third_party/ngen/ngen_opencl.hpp
Fixes #3181.
While investigating #3181, it was found that the oneDNN GPU component had dependencies on locale through the use of `std::stringstream ` for string manipulation. These dependencies occurred for a few different reasons:
1. When generating OpenCL C code, the expected locale is `C` and passing in different locale resulted in invalid syntax due to integer formatting.
2. The ZeBin binary format encodes textual metadata in the binary. By changing the locale, the metadata becomes malformed.
3. Some GPU primitives have strategy databases stored in a human readable format. When parsing these databases, changes in the locale resulted in incorrect parsing.
This PR contains a fix for the above issues identified during manual testing.
> xe: fix locale handling

- rfcs/20251004-rms-norm/README.md
Proposal to extend current Layer Normalization primitive to support RMS normalization via new flag.
Note "open questions" section for providing your opinion on better naming.
[Read here](https://github.com/uxlfoundation/oneDNN/blob/mzhukova/rfcs/20251004-rms-norm/rfcs/20251004-rms-norm/README.md)
Draft of implementation: https://github.com/uxlfoundation/oneDNN/pull/3068
JIRA: https://jira.devtools.intel.com/browse/MFDNN-13287
// Note: Current proposal is aligned with keras RMS normalization, but not Layer Normalization with rms_scaling due to https://github.com/keras-team/keras/issues/21234.
> rfcs: extend layer norm to support root mean square normalization

- tests/benchdnn/graph/graph.cpp
- tests/benchdnn/inputs/graph/pattern/harness_f8_all
- tests/benchdnn/inputs/graph/pattern/harness_f8_ci
Improve the skipping logic for data types with limited support such as fp8. Currently in benchdnn graph driver, the fp8 fusion cases will return several partitions on platforms where fp8 is not supported, and these partitions will be executed separately. However, as we have have independent tests for these separate patterns, we can skip such cases to simplify the testing. 
Before:
```
ONEDNN_VERBOSE=1 ./build/tests/benchdnn/benchdnn --graph --expected-n-partitions=0 --case=pattern/f8/f8_matmul.json
onednn_verbose,v1,info,oneDNN v3.9.0 (commit 692a6a1a577e718408c9015c56b608826eec4548)
onednn_verbose,v1,info,cpu,runtime:OpenMP,nthr:128
onednn_verbose,v1,info,cpu,isa:Intel AVX-512 with Intel DL Boost
onednn_verbose,v1,info,gpu,runtime:none
onednn_verbose,v1,info,graph,backend,0:dnnl_backend …
```
> benchdnn: graph: improve skip logic for cases with unsupported dt

- src/common/sdpa_pd.hpp
- src/common/sdpa_types.hpp
- src/common/sdpa_utils.hpp
- src/common/verbose.cpp
- src/gpu/intel/ocl/micro_sdpa.cpp
- src/gpu/intel/ocl/micro_sdpa.hpp
Adjusts the verbose output of sdpa primitives to align with the standard template. Part of [MFDNN-13623](https://jira.devtools.intel.com/browse/MFDNN-13623).
> common: verbose: adjust sdpa verbose format

- src/gpu/intel/jit/gemm/gen_gemm.hpp
- src/gpu/intel/jit/gemm/gen_gemm_kernel.hpp
- src/gpu/intel/jit/gemm/generator/pieces/post_ops.cxx
- src/gpu/intel/jit/gemm/include/gemmstone/generator.hpp
- third_party/ngen/ngen_emulation.hpp
Initial enabling of e8m0 scales in JIT gemm, baseline for mxfp enabling.
> [GPU] Enable e8m0 JIT gemm scaling

- tests/benchdnn/inputs/graph/test_graph_bf16_gpu
- tests/benchdnn/inputs/graph/test_graph_f16_gpu
- tests/benchdnn/inputs/graph/test_graph_f32_gpu
- tests/benchdnn/inputs/graph/test_graph_f8_gpu
- tests/benchdnn/inputs/graph/test_graph_int8_gpu
- tests/benchdnn/inputs/graph/test_graph_op_gpu
- tests/benchdnn/inputs/graph/test_graph_pattern_gpu
Reorganize gpu tests and change the gpu batch file names.
Previously bf16 op/pattern cases were not tested on all gpu platforms in nightly.
Fixes MFDNN-12927
> benchdnn: inputs: graph: change gpu batch file names

- tests/benchdnn/binary/binary.hpp
- tests/benchdnn/bnorm/bnorm.hpp
- tests/benchdnn/brgemm/bench_brgemm.cpp
- tests/benchdnn/brgemm/brgemm.hpp
- tests/benchdnn/concat/concat.hpp
- tests/benchdnn/conv/conv.hpp
- tests/benchdnn/deconv/deconv.hpp
- tests/benchdnn/eltwise/eltwise.hpp
- tests/benchdnn/gnorm/gnorm.hpp
- tests/benchdnn/graph/graph.hpp
- tests/benchdnn/ip/ip.hpp
- tests/benchdnn/lnorm/lnorm.hpp
- tests/benchdnn/lrn/lrn.hpp
- tests/benchdnn/matmul/matmul.hpp
- tests/benchdnn/pool/pool.hpp
- tests/benchdnn/prelu/prelu.hpp
- tests/benchdnn/reduction/reduction.hpp
- tests/benchdnn/reorder/reorder.hpp
- tests/benchdnn/resampling/resampling.hpp
- tests/benchdnn/rnn/rnn.hpp
- tests/benchdnn/shuffle/shuffle.hpp
- tests/benchdnn/softmax/softmax.hpp
- tests/benchdnn/sum/sum.hpp
- tests/benchdnn/utils/parser.hpp
- tests/benchdnn/utils/settings.hpp
- tests/benchdnn/zeropad/bench_zeropad.cpp
- tests/benchdnn/zeropad/zeropad.hpp
Based on the discussion in #3186, an alternative method to get rid of a single clang-tidy directive :)
I ran this through perf testing (and added a `--perf-template` knob to the graph driver to test that ctor) and everything looks fine.
> tests: benchdnn: refactor settings ctors

- src/gpu/intel/jit/conv/problem.cpp
- src/gpu/intel/jit/conv/problem.hpp
- src/gpu/intel/jit/ir/linear_expr.cpp
- src/gpu/intel/jit/ir/linear_expr.hpp
- src/gpu/intel/jit/v2/conv/bridge.hpp
- src/gpu/intel/jit/v2/conv/kernel_desc.cpp
- src/gpu/intel/jit/v2/conv/kernel_desc.hpp
- src/gpu/intel/jit/v2/conv/kernel_desc_2d_reqs.cpp
- src/gpu/intel/jit/v2/conv/plan_registry.cpp
- src/gpu/intel/jit/v2/conv/problem.cpp
- src/gpu/intel/jit/v2/conv/tensor_utils.cpp
- src/gpu/intel/jit/v2/ir/send.hpp
- src/gpu/intel/jit/v2/ir/tensor.cpp
- src/gpu/intel/jit/v2/ir/tensor.hpp
addresses MFDNN-12455
Assumes innermost dimension has stride 1.
1) Add placeholder stride vars for each tensor.
2) use stride vars in layout_t instead of calcuating based off dims.
3) Infer stride_var reqs for mod and gt/lt reqs :
examples
`ic % 16 == 0  => stride_iw % 16 ==0, stride_ih % 16 ==0, stride_mb % 16 == 0`
`ic*iw < 256 => stride_iw*iw<256  stride_ih < 256 `
This approach was chosen as opposed to limiting spatial dimensions to be dense because it is more general
and reqs would still need to be inferred/generated for non-spatial dimension stride vars.
> [GPU] [conv:v2] add strided tensor support

- CITATION.cff
- README.md
- RELEASE_NOTES.md
This PR includes a release notes draft based on the information from the PRs for the contributors to review. Your additions and corrections are highly appreciated.
> oneDNN v3.8 release notes

- src/common/convolution_pd.hpp
- src/cpu/aarch64/jit_brdgmm_dw_conv.cpp
- src/cpu/aarch64/jit_brgemm_1x1_conv.cpp
- src/cpu/aarch64/jit_brgemm_1x1_conv.hpp
- src/cpu/aarch64/jit_brgemm_conv.cpp
- src/cpu/aarch64/jit_brgemm_conv.hpp
- src/cpu/cpu_convolution_pd.hpp
- src/cpu/gemm_x8s8s32x_convolution.hpp
- src/cpu/ref_convolution_int8.hpp
- src/cpu/x64/jit_avx512_core_amx_1x1_convolution.hpp
- src/cpu/x64/jit_avx512_core_amx_convolution.hpp
- src/cpu/x64/jit_avx512_core_x8s8s32x_1x1_convolution.hpp
- src/cpu/x64/jit_avx512_core_x8s8s32x_convolution.hpp
- src/cpu/x64/jit_brdgmm_dw_conv.cpp
- src/cpu/x64/jit_brgemm_1x1_conv.cpp
- src/cpu/x64/jit_brgemm_1x1_conv.hpp
- src/cpu/x64/jit_brgemm_conv.cpp
- src/cpu/x64/jit_brgemm_conv.hpp
- src/cpu/x64/jit_uni_x8s8s32x_1x1_convolution.hpp
- src/cpu/x64/jit_uni_x8s8s32x_convolution.hpp
- src/gpu/gpu_convolution_pd.hpp
- src/gpu/intel/jit/conv/config.cpp
- src/gpu/intel/ocl/ref_convolution.hpp
- tests/benchdnn/conv/conv.cpp
MFDNN-13563
To split supported cases per engine kind/backends as the call serves a common ground for both of them.
> src: conv: introduce an additional call to attr_scales_ok (fixes MFDNN-13563)

- tests/benchdnn/graph/input_displacer.cpp
- tests/benchdnn/inputs/graph/complex_fusion/harness_mha_all
Resolve MFDNN-13555. The first input of GE should subtract `q_seq_len` then add `kv_seq_len`. Added more testcase where `q_seq_len` != `kv_seq_len`.
> benchdnn: graph: fix input displace for bottom-right casual mask

- src/gpu/generic/sycl/ref_deconvolution.hpp
The PR corrects build failures due to formatting discrepancy in verbose dispatch checks.
Fixes MFDNN-13653.
> gpu: sycl: fix verbose tag check for deconvolution primitive (fixes MFDNN-13653)

- src/gpu/intel/ocl/micro_sdpa_configs.hpp
Description
Some configurations were freezing on LNL systems with a head size of 512. This PR fixes the offending configuration by reducing the tile size of each tile and increasing the number of sub-groups per work-group.
Fixes [MFDNN-13646](https://jira.devtools.intel.com/browse/MFDNN-13646)
Backport of: https://github.com/uxlfoundation/oneDNN/pull/3241
> [v3.8 backport] xe: sdpa: Fix LNL config with head_size of 512

- src/gpu/intel/jit/config/ngen_config.hpp
MFDNN-13661
CPP20 builds are not triggered in preCI.
> fixup: src, tests: fix undefined macro hits

- src/gpu/intel/ocl/rnn/utils.cpp
These regressions occured as a result of changing the k_limit for fused kernels in RNN while LBR_GRU was added to the existing available algorithms.
Machine: PVC 141703
Base Commit: 34d53b4
Following graphs show that the performance was restored.
Regression graph:
Graph after proposed changes:
> intel: ocl: rnn: modify k_limit to fix pvc regression

- src/cpu/x64/matmul/amx_blocking_heuristics.cpp
- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
- src/cpu/x64/matmul/brgemm_matmul_utils.hpp
- tests/benchdnn/inputs/matmul/harness_matmul_generated_ci
Transposed B copy kernel doesn't support arbitrary `N_blk`, for the reference please see: [brgemm_matmul_copy_utils.cpp#L4563](https://github.com/uxlfoundation/oneDNN/blob/8c68c00247971ec96c45388b70f45f3feec17ca4/src/cpu/x64/matmul/brgemm_matmul_copy_utils.cpp#L4563). So `min_N_blk` should be equal `N_blk` in AMX blocking heuristics and will remain unchanged.
Incorrect `need_buf_c` assignment which leads to NANs in the result for the specific case `--reset --skip-impl=ref --stag=bac --wtag=acb --dtag=any --dt=bf16:bf16:f32 1x2680x1662:1x1662x3848` for `nthr >= 165`. 
++ Minor refactoring: removed unused attributes from `brgemm_matmul_conf_t` related to buffer B.
> x64: matmul: Fix nthr issues in matmul

- src/gpu/generic/sycl/ref_convolution.hpp
Adding latest changes from commit e210602  to the `attr_scales_ok` function in the generic sycl implementation.
Change is required as without it native backends and generic sycl do not compile.
> gpu: generic: Change generic sycl attr scales func

- tests/gtests/graph/unit/backend/dnnl/test_binary_op.cpp
- tests/gtests/graph/unit/backend/dnnl/test_convolution.cpp
- tests/gtests/graph/unit/backend/dnnl/test_convtranspose.cpp
- tests/gtests/graph/unit/backend/dnnl/test_interpolate.cpp
- tests/gtests/graph/unit/backend/dnnl/test_large_partition.cpp
- tests/gtests/graph/unit/backend/dnnl/test_matmul.cpp
- tests/gtests/graph/unit/backend/dnnl/test_pool.cpp
- tests/gtests/graph/unit/backend/dnnl/test_select.cpp
- tests/gtests/graph/unit/unit_test_common.hpp
- add `SKIP_IF_NV_GPU` macro
- skip unsupported cases
- fix UT expectations for nv gpu
> gtests: graph: unit: fix failing gtests cases on nv gpu

- src/common/memory_tracking.hpp
- src/cpu/aarch64/matmul/acl_lowp_matmul.cpp
- src/cpu/aarch64/matmul/acl_lowp_matmul.hpp
This pr is to change arm lowp matmul to use latest acl stateless api.
```
./tests/benchdnn/benchdnn --mode=p --matmul --dt=s8:s8:f32 
OMP_NUM_THREADS=4
origin:
1x512:512x512: min(ms):0.0273438 avg(ms):0.0297922
1024x512:512x1024: min(ms):0.535645 avg(ms):0.547256
4096x4096:4096x4096: min(ms):67.917 avg(ms):68.0218
512x512:512x512: min(ms):0.152832 avg(ms):0.157268
stateless lowpmatmul:
1x512:512x512: min(ms):0.0283203 avg(ms):0.0301788
1024x512:512x1024: min(ms):0.546875 avg(ms):0.56036
4096x4096:4096x4096: min(ms):67.8574 avg(ms):67.9895
512x512:512x512: min(ms):0.152588 avg(ms):0.157321
OMP_NUM_THREADS=16
origin:
1x512:512x512: min(ms):0.0334473 avg(ms):0.0356632
1024x512:512x1024: min(ms):0.209717 avg(ms):0.220023
4096x4096:4096x4096: min(ms):23.1809 avg(ms):23.2551
512x512:512x512: …
```
> cpu: aarch64: make lowpmatmul  use stateless acl interface

- src/graph/backend/dnnl/patterns/convtranspose_fusion.cpp
- tests/gtests/graph/unit/backend/dnnl/test_convtranspose.cpp
- tests/gtests/graph/unit/backend/dnnl/test_pass.cpp
Refactored the deconv pattern according to document *DNNL Backend Fusion Pattern Definition*:
1. Replaced `int8` in pattern names with `x8s8x8`
2. Removed the word `fusion` from pattern names
3. Updated comments: changed `[ Abs/Clamp...]*[0,3]` to `[unary/binary]*[0,MAX_REPETITION)`
4. For floating-point patterns, added the `fp_` prefix to their names
Task MFDNN-10451.
> graph: backend: dnnl: deconv pattern name refactor

- src/graph/backend/dnnl/common.cpp
- tests/gtests/graph/unit/unit_test_common.cpp
- tests/gtests/graph/unit/unit_test_common.hpp
- A minor fix for creating memory descriptor from logical tensor as boolean data type is not publicly supported by memory descriptor.
- Use memory's map/unmap function to fill test tensors as some test tensors have device buffers which are not accessible on host side.
> gtests: graph: unit: fix the filling of test tensors

- src/gpu/generic/sycl/convolution_kernels.hpp
- src/gpu/generic/sycl/ref_convolution.cpp
- src/gpu/generic/sycl/sycl_primitive_conf.hpp
Changed indexing to take into account different strides in convolution.
Added zp weights support
Fixed failues for deconv using sycl conv bwd
Changes to the sycl convolution kernel resolve failing benchdnn tests:
```
--mode-modifier=P --conv --engine=gpu --allow-enum-tags-only=false --check-ref-impl=true --dt=u8:s8:u8 --strides=903168x1x4032x9::6422528x1x28672x128 g1mb1ic3ih224oc64oh112kh7sh2ph3n"resnet_50:conv1"
```
```
--mode-modifier=P --conv --engine=gpu --allow-enum-tags-only=false --check-ref-impl=true --dir=BWD_D --dt=u8:s8:u8 --strides=903168x1x4032x9::6422528x1x28672x128 g1mb1ic3ih224oc64oh112kh7sh2ph3n"resnet_50:conv1"
```
```
--mode-modifier=P --deconv --engine=gpu --dir=FWD_I --dt=s8:s8:s8 --attr-scales=src:common:0.25 --attr-post-ops=linear:2:1 …
```
> generic: sycl: Change to indexing in conv kernel

- src/gpu/nvidia/cudnn_conv_inner_product_impl.hpp
- src/gpu/nvidia/cudnn_convolution_impl.hpp
- src/gpu/nvidia/cudnn_gemm_inner_product_impl.hpp
- src/gpu/nvidia/cudnn_matmul_impl.hpp
- src/gpu/nvidia/cudnn_matmul_lt_impl.hpp
- src/gpu/nvidia/cudnn_reorder_impl.hpp
When executing nvidia backend sum, scales are set using `map_memory` to get the device memory, set with values on the host and then `unmap_memory` is called to update the device-side memory.
For buffer memory storages this mapping and unmapping is done using `get_host_access` which gives a host accessor. When the host accessor is destroyed the device memory is updated. This guarantees synchronization with regards to the current queue.
The reorder implementation used uses cuMemcpy to get the scales on host. This is run on the default cuda stream, while the sycl queue submits work on a different stream.
This PR proposes getting the stream that the cuDNN operations are submitted to (created from the sycl queue) and submitting the copy of scales on the same stream with cuMemcpyAsync. This …
> gpu: nvidia: Change nvidia reorder memcpy to async

- src/gpu/intel/jit/gemm/gemm_walk_orders.hpp
- src/gpu/intel/jit/gemm/gen_gemm_kernel.cpp
- src/gpu/intel/jit/gemm/generator/generator.cpp
- src/gpu/intel/jit/gemm/generator/pieces/atomic_fusions.cxx
- src/gpu/intel/jit/gemm/generator/pieces/atomic_fusions.hpp
- src/gpu/intel/jit/gemm/generator/pieces/c_update.cxx
- src/gpu/intel/jit/gemm/generator/pieces/gemm.cxx
- src/gpu/intel/jit/gemm/generator/pieces/gemm_setup.cxx
- src/gpu/intel/jit/gemm/generator/pieces/k_loop.cxx
- src/gpu/intel/jit/gemm/generator/pieces/math_helpers.cxx
- src/gpu/intel/jit/gemm/generator/pieces/post_ops.cxx
- src/gpu/intel/jit/gemm/generator/pieces/state.hpp
- src/gpu/intel/jit/gemm/generator/pieces/stream_k.cxx
- src/gpu/intel/jit/gemm/generator/pieces/walk_orders.cxx
- src/gpu/intel/jit/gemm/generator/strategy.cpp
- src/gpu/intel/jit/gemm/generator/strategy_parser.cpp
- src/gpu/intel/jit/gemm/include/gemmstone/driver_info.hpp
- src/gpu/intel/jit/gemm/include/gemmstone/generator.hpp
- src/gpu/intel/jit/gemm/include/gemmstone/strategy.hpp
A new version of the variable k-slicing ("stream-k") implementation in GEMM, with reduced L3$ footprint and HBM BW. The gemmstone implementation supports 2 separate stream-k phases, which can improve L3$ footprint further in some cases at the expense of sustained HBM/DDR BW. It is not yet enabled in oneDNN as that decision is trickier to make.
> xe: jit: gemm: reduced-cache stream-k implementation

- tests/benchdnn/inputs/graph/complex_fusion/harness_mlp_ci
Fix MFDNN-13430.
Rounding precision issue due to the uncertainty of elements' accumulation order inside the kernel calculation. 
Replace multiply with Subtract(Add is not enough) between 2 matmuls in the test cases. It helps to reduce the intermediate value after binary.
> benchdnn: inputs: graph: replace mul with sub in gated mlp test

- examples/graph/graph_example_utils.hpp
- src/graph/utils/alloc.cpp
- src/graph/utils/ocl_usm_utils.cpp
- src/graph/utils/ocl_usm_utils.hpp
- tests/benchdnn/graph/memory_pool.hpp
Previously we used shared USM by default in benchdnn graph driver for gpu testing. Now changing it to device USM.
This is a follow-up work for f836db436b1327a1cc02c36841c3e9d2acac08e2 and MFDNN-4353.
> benchdnn: graph: use device usm by default

- cmake/host_compiler.cmake
- src/cpu/rnn/ref_rnn.hpp
MFDNN-13664
For host compiler it's a workaround, doesn't add much value to what's already been enabled.
> Fix Wundef build host compiler issue (fixes MFDNN-13664)

- src/cpu/x64/matmul/amx_blocking_heuristics.cpp
Fixes [MFDNN-13675](https://jira.devtools.intel.com/browse/MFDNN-13675). 
Incorrect `need_buf_c` flag setting fix.
> x64: matmul: Fix buffer C usage

- src/cpu/x64/matmul/amx_blocking_heuristics.cpp
Fixes [MFDNN-13675](https://jira.devtools.intel.com/browse/MFDNN-13675). 
Incorrect `need_buf_c` flag setting fix. 
It's a backport of #3274
> [backport] x64: matmul: Fix buffer C usage

- src/common/dnnl_thread.hpp
- src/cpu/gemm_convolution.cpp
- src/cpu/x64/gemm/gemm_utils.hpp
- src/cpu/x64/gemm_bf16_convolution.cpp
Fix PRAGMA_OMP_SIMD usage that generates incorrect code when vectorization is forced.
> cpu: fix omp simd usage that might generate incorrect code

- src/cpu/aarch64/jit_sve_1x1_convolution.hpp
- src/cpu/aarch64/jit_sve_convolution.hpp
When running fast math convolution, we should run ACL instead of JIT. This is a change introduced in https://github.com/uxlfoundation/oneDNN/pull/2838/files. However, this patch was not working when using --attr-fpmath as outlined in https://github.com/uxlfoundation/oneDNN/issues/3266. This is causing the nightly performance tests to fail.
performance:
~2.5x speedups for benchdnn conv cases using --attr-fpmath=bf16
> cpu: aarch64: conv: fix fast math fallback

- src/cpu/simple_layer_normalization.cpp
- src/cpu/simple_layer_normalization.hpp
- src/cpu/x64/jit_uni_layer_normalization.cpp
- src/cpu/x64/jit_uni_layer_normalization.hpp
Continuation of https://github.com/uxlfoundation/oneDNN/pull/3068.
Implements: https://jira.devtools.intel.com/browse/MFDNN-13287.
> cpu: lnorm: extend simple and jit impls to support rms norm

- src/gpu/intel/ocl/micro_sdpa.cl
- src/gpu/intel/ocl/micro_sdpa.cpp
- tests/gtests/internals/test_sdpa.cpp
This PR optimizes SDPA with causal masks by skipping the processing of masked out values. This includes skipping work-groups and reducing the number of iterations of the inner loop of the micro_sdpa kernel. With this change we are seeing a speedup of up to 1.9x over the same kernel before this change.
Additionally this PR uses split barriers instead of the regular OpenCL barrier when reading Q tenor's values into shared memory. This is only faster for first token cases so I have gated the feature behind a kernel definition.
Fixes: [MFDNN-13683](https://jira.devtools.intel.com/browse/MFDNN-13683)
> xe: sdpa: Optimizations for causal mask. Use split barriers for Q tensor

- src/cpu/aarch64/acl_layer_normalization.cpp
acl_layer_normalization does not support RMS mode and needs to be skipped for this case.
**Before**:
```
$ ONEDNN_VERBOSE=all ./build/tests/benchdnn/benchdnn --lnorm --dir=FWD_I --flags=M --dt=f32:bf16 5120x1024
onednn_verbose,v1,info,oneDNN v3.9.0 (commit f0d20cd39c101a16df8c40aa2baa47d1908ac3fc)
...
onednn_verbose,v1,primitive,create:cache_miss,cpu,layer_normalization,acl,forward_inference,src:f32::blocked:ab::f0 dst:f32:a:blocked:ab::f0 stats:undef::undef:::,,flags:M,5120x1024,0.0581055
onednn_verbose,v1,primitive,create:cache_hit,cpu,layer_normalization,acl,forward_inference,src:f32::blocked:ab::f0 dst:f32:a:blocked:ab::f0 stats:undef::undef:::,,flags:M,5120x1024,0.00805664
onednn_verbose,v1,cpu,acl,unsupported: Only Ab4a/Ab8a, BA8b4a/BA4b4a and Acdb8a/Acdb4a destination formats …
```
> fix: aarch64: skip acl_layer_normalization for rms lnorm

- src/gpu/intel/jit/conv/plan.cpp
- src/gpu/intel/jit/conv/tiler.cpp
- src/gpu/intel/jit/pass/strength_reduce.cpp
Jira: [MFDNN-13668](https://jira.devtools.intel.com/browse/MFDNN-13668)
List of changes:
- Fixup for https://github.com/uxlfoundation/oneDNN/pull/2694
- Restored `f16` accumulator with `f16` backward. It is non-compliant with documentation (must use `f32` accumulator) but we need to fix it properly
- Restored `bf16` mixed mode with `mad`
- Improvement/mitigation for https://github.com/uxlfoundation/oneDNN/pull/2935
- Immediate header post-increments are expensive with that PVC WA as it adds `x.dst` dependency
- Mitigation: move post-increments to the end of statement groups to have postponed batched header updates. Need to test this properly but the change should be beneficial for other platforms
- Fixed BWD_D tiling with NCHW and enabled transposition, this is a fixup for …
> [GPU] Convolution: fixups and workarounds to address regressions

- doc/graph/operations/GELU.md
- doc/graph/operations/GELUBackward.md
- include/oneapi/dnnl/dnnl_graph.hpp
- include/oneapi/dnnl/dnnl_graph_types.h
- src/graph/backend/dnnl/passes/lower.cpp
- src/graph/backend/dnnl/passes/utils.hpp
- src/graph/interface/op_def.hpp
- tests/benchdnn/graph/setting_handler.cpp
- tests/benchdnn/inputs/graph/op/f32/gelu.json
- tests/benchdnn/inputs/graph/op/harness_bf16_all
- tests/benchdnn/inputs/graph/op/harness_f16_all
- tests/benchdnn/inputs/graph/op/harness_f32_all
- tests/gtests/graph/unit/interface/test_op_schema_cpu.cpp
Fixes MFDNN-13548
Currently, the GELU operation only supports `erf` based implementation. This PR adds a `mode` attribute to GELU and GELUBackward operation, so the users can specify `tanh` based approximation.
```c++
auto gelu = op(id, op::kind::GELU, "gelu");
gelu.set_attr<std::string>(op::attr::mode, "gelu_tanh"); // this is optional, but default it's gelu_erf.
gelu.add_input(in);
gelu.add_output(out);
graph.add_op(gelu);
```
> graph: extend gelu op to support tanh approximation

- src/graph/backend/dnnl/layout_propagator.cpp
Fix the layout propagation for genindex.  Force the genindex input to be plain.
> graph: backend: dnnl: insert reorder for block input of genindex

- src/gpu/nvidia/cudnn_convolution.hpp
Added missing post ops checks for backward conv, causing failures deconvolution in benchdnn.
With changes correctly skips currently failing tests such as:
```
--mode-modifier=P --deconv --engine=gpu --attr-post-ops=sum:0.5+add:f32+add:u8:per_dim_01+linear:0.5:1.5+mul:f32:per_dim_0+add:s8:per_oc+add:f32:per_dim_01+relu:0.5 ic384iw13oc256ow13kw3pw1n"alexnet:deconv3"
```
> gpu: nvidia: Add skips for unsupported post ops for deconv

- src/gpu/intel/ocl/reusable_softmax.cl
- src/gpu/intel/ocl/reusable_softmax.cpp
- src/gpu/intel/ocl/reusable_softmax.hpp
This seeks to resolve JIRA issues [MFDNN-13238](https://jira.devtools.intel.com/browse/MFDNN-13238) (accelerate slow PyTorch SDPA shapes) and [MFDNN-12346](https://jira.devtools.intel.com/browse/MFDNN-12346) (accelerate and enable reusable half-precision softmax). This request includes two new optimized kernels in addition to the general case kernels for softmax computation:
- vectorized: a kernel utilizing opencl block loads to quickly process longer-softmax-axis problems
- small: a kernel stripped down to handle only up to 16 element softmax-axis-length problems
Disabled on XeHPG; more specialization required for that hardware.
> xe: softmax: softmax reusable acceleration

- tests/gtests/graph/api/ocl/test_cpp_api_engine.cpp
Found by clang 19.1.6 + address sanitizer. Related to [MFDNN-12551](https://jira.devtools.intel.com/browse/MFDNN-12551).
> gtests: graph: cleanup context at end of test

- .github/automation/aarch64/ci.json
- .github/automation/aarch64/get_acl.sh
- .github/automation/aarch64/skipped-tests.sh
The issue causing these failures was fixed in Compute Library 52.0.1
Unskipped tests:
```
cpu-graph-gqa-cpp
cpu-graph-mqa-cpp
cpu-graph-sdpa-cpp
cpu-graph-sdpa-stacked-qkv-cpp
test_graph_unit_dnnl_mqa_decomp_cpu
test_graph_unit_dnnl_sdp_decomp_cpu
```
Partially resolves #2674
> ci: aarch64: remove fixed graph tests from the skip list

- src/graph/backend/dnnl/kernels/sdp_decomp.cpp
- src/graph/backend/dnnl/kernels/sdp_decomp_config.cpp
- src/graph/backend/dnnl/kernels/sdp_decomp_config.hpp
- src/graph/backend/dnnl/passes/transform.cpp
- src/graph/backend/dnnl/passes/transform.hpp
- src/graph/backend/dnnl/patterns/sdp.cpp
- src/graph/backend/dnnl/patterns/utils.hpp
- tests/benchdnn/inputs/graph/complex_fusion/harness_mha_all
- tests/benchdnn/inputs/graph/complex_fusion/harness_mha_ci
- tests/benchdnn/inputs/graph/complex_fusion/mha/codegemma-bf16-f32.json
- tests/benchdnn/inputs/graph/complex_fusion/mha/gemma2-bf16-f32.json
Support the code-gemma and gemma2 pattern from TensorFlow team with larger partition and decompose kernel. In this PR, we support the following 2 new features.
1. We support the[ soft-capping mechanism](https://huggingface.co/blog/gemma2#soft-capping-and-attention-implementations) （tanh+multiply）
2. We support the 5d input GQA in the decompose kernel.
> graph: backend: dnnl: support gemma GQA from tensorflow

- .github/automation/aarch64/skipped-tests.sh
- .github/workflows/ci-aarch64.yml
Also fixes a bug where the testset is empty on platforms where no graph tests are skipped.
> ci: aarch64: simplify skipped test logic

- src/cpu/x64/brgemm/brgemm.cpp
- src/cpu/x64/brgemm/brgemm_types.hpp
- src/cpu/x64/brgemm/brgemm_utils.cpp
- src/cpu/x64/brgemm/jit_brgemm_kernel.cpp
- src/cpu/x64/jit_avx512_core_fp8cvt.cpp
- src/cpu/x64/jit_avx512_core_fp8cvt.hpp
- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
- src/cpu/x64/matmul/brgemm_matmul_utils.hpp
- third_party/xbyak/xbyak_mnemonic.h
Fixes MFDNN-13571
- Only hf8 support is required for now, and using the same weights blocking format as int8
- removing "ne" from some conversion instructions for avx10.2
- update registers decomposition for fp8 conversion
> cpu: x64: enable hf8 support for matmul on AVX10.2

- src/gpu/intel/jit/gemm/gen_gemm.hpp
Restore FP8 support check dropped during rebase. Allows unsupported cases to run on pre-XeHPC platforms.
> [GPU][GEMM] Restore fp8 check

- tests/benchdnn/binary/binary.cpp
- tests/benchdnn/dnnl_common.cpp
- tests/benchdnn/dnnl_common.hpp
- tests/benchdnn/dnnl_memory.cpp
- tests/benchdnn/utils/cold_cache.cpp
- tests/benchdnn/utils/cold_cache.hpp
Workaround for https://jira.devtools.intel.com/browse/MFDNN-13654
Reduce the number of allowed cases when it comes to CPU RAM limit.
> benchdnn: mem_check: reduce the allowed combined memory limit

- tests/gtests/graph/unit/backend/dnnl/test_batch_norm.cpp
- tests/gtests/graph/unit/backend/dnnl/test_convolution.cpp
- tests/gtests/graph/unit/backend/dnnl/test_convtranspose.cpp
- tests/gtests/graph/unit/backend/dnnl/test_large_partition.cpp
- tests/gtests/graph/unit/backend/dnnl/test_pool.cpp
A follow-up PR to skip unsupported gtests cases on NV GPU.
Related tickets:
1. MFDNN-13736
2. MFDNN-13685
3. MFDNN-13687
4. MFDNN-13698
> skip unsupported gtests cases on NV GPU

- CMakeLists.txt
This is a patch release containing the following changes to v3.8:
* Fixed correctness issue in reorder primitive with non-trivial strides on Intel CPUs (a762d3248ee5e04b2348f3a5aeecfa64da4634d8)
* Fixed runtime error in convolution weight gradient on Xe2 architecture-based Intel GPUs (a8fac73036f67657f51c10b385f967c64607e802, c409ef949ea112e8fc1caf480d55a07247b4a702)
* Fixed performance regression in `bf16` convolution on Intel Datacenter GPU Max Series (98170d0f138458f4b3fcefca773be2ef7e73959f, c6bae4aa45dbe9ff9fe4e51173dc301550832e08, c5edd53195f6b1465f4ab4857d64a704bb38e8e1, bb1a5919fbedd4ce078f2fcf368a3e099f6c3942)
* Improved performance of `fp16` matmul with `fp8` compressed weights on Intel GPUs (58f3ec1510a4b10e51e57227229d2b2cfe23f55a, abff1764af8a93dda5c9c8be11c5a1a5da31daa7, …
> oneDNN v3.8.1 patch release

- tests/benchdnn/inputs/matmul/test_matmul_gpu
LLM shapes show fails on rls-v3.9-pc due to revert in #3268 . These are expected, fixed in main, but behavior is preserved in rls-v3.9-pc for OpenVINO. dropping tests for clean CI. 
Fixes # [MFDNN-13735](https://jira.devtools.intel.com/browse/MFDNN-13735)
> [Benchdnn][rls-v3.9-pc] Drop LLM shapes from GPU set

- src/cpu/x64/brgemm/jit_brgemm_kernel.cpp
save and restore reg64_fp8_aux to avoid potential segfault issue.
> cpu: x64: brgemm: fix potential segfault issue for fp8

- src/common/verbose.hpp
Using `ONEDNN_VERBOSE=profile_create` looks for the `exec_profile` verbose flag instead of the `create_profile` verbose flag, which causes the header to not be printed, as well as other logger-related logic getting incorrect flags. This just corrects the behaviour so that `VPROF` calls using the `create` or `create_nested` logtype look for the `create_profile` verbose flag as expected.
> common: verbose: use correct flags for vprof

- doc/primitives/convolution.md
- src/cpu/aarch64/acl_winograd_convolution.cpp
- src/cpu/aarch64/acl_winograd_convolution.hpp
- src/cpu/cpu_convolution_list.cpp
- tests/gtests/test_iface_wino_convolution.cpp
This reverts commit ef1365bfea776be2cf685e1210a87c180f3f6cb3.
Keep Winograd as OpenVINO uses `convolution_auto`
> cpu: aarch64: Revert "cpu: aarch64: Nuke winograd"

- MAINTAINERS.md
I would like to nominate Maria Zhukova @mzhukova for the role of code owner of Arch component. Maria is a member of oneDNN Architecture team at Intel and has a [history of contributions](https://github.com/oneapi-src/oneDNN/pulls?q=is%3Apr+author%3Amzhukova) to the library design and implementation.
> @mzhukova as code owner for Arch

- .github/workflows/performance-aarch64.yml
This enables the performance-aarch64.yml workflow to be triggered manually
via the GitHub Actions UI using `workflow_dispatch`.
- This workflow runs on the same hardware as nightly runs (`c7g.metal`)
- Useful for testing changes without waiting for the nightly pipeline.
> ci: aarch64: Add manual trigger to the performance aarch64 workflow 

- src/cpu/x64/matmul/brgemm_matmul.cpp
This PR fixes correctness failures / segfaults for matmul operation with binary select postop with scalar broadcasting.
Fixes MFDNN-13740.
> cpu: matmul: fix select postop failures for scalar broadcasting

- src/gpu/amd/miopen_gemm_inner_product_impl.hpp
- src/gpu/amd/sycl_hip_utils.hpp
- tests/gtests/sycl/api/test_engine.cpp
Build issues fixes:
1. `ext_oneapi_get_default_context` is deprecated in newest Intel Compiler in favor of `khr_get_default_context`. I have added a check for new implementation based on presence of mandatory `SYCL_KHR_DEFAULT_CONTEXT` macro.
2. added `defined()` guard to `MIOPEN_HAS_INT8X4` macro
> tests: gtest: add check for khr_get_default_context

- src/cpu/aarch64/acl_convolution_utils.hpp
This reverts commit 7400e1615673ab99089592cd776668db1b47a70a.
The underlying issue was fixed in ComputeLibrary 52.0.1
Original patch merged here: https://github.com/uxlfoundation/oneDNN/pull/3138
> cpu: aarch64: revert "cpu: aarch64: conv: fix fast math NAN issue"

- .github/automation/aarch64/skipped-tests.sh
Some graph tests take a very long time to run on debug builds.
[Example CI run](https://github.com/uxlfoundation/oneDNN/actions/runs/15346773848/job/43184820374?pr=3371).
This change allows us to run these only on release builds, significantly speeding up the pipeline.
> ci: aarch64: skip long-running graph tests in debug builds

- .github/workflows/performance-aarch64.yml
Add type property in workflow_call.inputs which was missing earlier for different inputs.
> ci: aarch64: Add relevant types for different inputs in performance testing workflow

- cmake/version.cmake
When building oneDNN outside of the git tree, but inside that of a different repository, the commit hash that is substituted is from the parent repository. This change limits git to the oneDNN root directory, and silences the error message when the git command fails.
For example:
```bash
git clone https://github.com/uxlfoundation/oneDNN.git dnnl
mkdir test_fail
git --git-dir dnnl/.git --work-tree test_fail checkout origin/main .
cmake -S test_fail -B test_fail/build
grep "#define DNNL_VERSION_HASH" test_fail/build/include/oneapi/dnnl/dnnl_version_hash.h
```
Before (out-of-tree):
```
-- CMAKE_BUILD_TYPE is unset, defaulting to Release
...
-- Found Git: /usr/bin/git (found version "2.30.2")
fatal: not a git repository (or any of the parent directories): .git
-- Enabled testing coverage: CI …
```
> build: fix hash sub for out-of-tree builds

- src/cpu/aarch64/jit_uni_binary.cpp
- src/cpu/x64/jit_uni_binary.cpp
- tests/gtests/regression/test_binary_stride.cpp
[MFDNN-9723](https://jira.devtools.intel.com/browse/MFDNN-9723) Binary add returns incorrect results for non-contiguous strides
Incorrect addition results occur when batch size is 1 and the first dimension has a non-trivial, non-contiguous stride. For any batch size greater than 1, results are correct, even with non-contiguous strides.
When batch size equal to 1, the first stride dimension should not matter, so layouts can be treated as the same.
> cpu: binary: fix binary add with non-contiguous strides when bs=1

- src/cpu/aarch64/matmul/acl_matmul.cpp
The ACL default accumulation for the ``fp16`` kernels is to accumulate into ``fp16`` as well, which causes some tests to fail in PyTorch. This PR enables ``fp16`` ACL kernels that accumulate into ``fp32`` when appropriate and consequently creates a path to fix the failing tests.
> Enable FP16 ACL kernels that accumulate into FP32

- MAINTAINERS.md
I propose Renato Arantes (@renato-arantes) as a codeowner for @uxlfoundation/onednn-cpu-aarch64. He has [several contributions over the last few years](https://github.com/uxlfoundation/oneDNN/commits?author=renato-arantes).
cc: @vpirogov
> governance: add Renato Arantes as onednn-cpu-aarch64 codeowner

- README.md
Updated macOS configuration, Intel oneAPI DPC++/C++ Compiler version and added MSVC version to the list of x86-64 verified configurations.
> doc: readme: update list of verified configurations

- src/graph/backend/dnnl/patterns/binary_fusion.cpp
- src/graph/backend/dnnl/patterns/bn_fusion.cpp
- src/graph/backend/dnnl/patterns/eltwise_fusion.cpp
- src/graph/backend/dnnl/patterns/interpolate_fusion.cpp
- src/graph/backend/dnnl/patterns/reduction_fusion.cpp
- src/graph/backend/dnnl/patterns/reorder_fusion.cpp
- tests/gtests/graph/unit/backend/dnnl/test_batch_norm.cpp
- tests/gtests/graph/unit/backend/dnnl/test_binary_op.cpp
- tests/gtests/graph/unit/backend/dnnl/test_eltwise.cpp
- tests/gtests/graph/unit/backend/dnnl/test_interpolate.cpp
- tests/gtests/graph/unit/backend/dnnl/test_pass.cpp
- tests/gtests/graph/unit/backend/dnnl/test_reduce.cpp
- tests/gtests/graph/unit/backend/dnnl/test_reorder.cpp
- tests/gtests/graph/unit/backend/dnnl/test_subgraph_pass.cpp
Refactored the deconv pattern according to document *DNNL Backend Fusion Pattern Definition*:
1. Replaced `int8` in pattern names with `x8`
2. Removed the word `fusion` from pattern names
4. For floating-point patterns, added the `fp_` prefix to their names
Task MFDNN-10454 and MFDNN-10452.
> graph pattern name refactor

- .github/automation/performance/benchdnn_comparison.py
- Make ctime regressions show as a warning instead of an error
- Change problem mismatches in performance tests to an error instead of a warning
> ci: aarch64: make ctime regression a warning

- src/common/matmul.cpp
- src/gpu/intel/jit/gemm/jit_gemm_pd.cpp
- src/gpu/intel/jit/gemm/jit_gemm_pd.hpp
- src/gpu/intel/ocl/gemm_matmul.hpp
- tests/benchdnn/inputs/matmul/harness_matmul_3d_bcast
- tests/benchdnn/inputs/matmul/test_matmul_gpu
Address performance regressions in batched gemm with grouped attrs. Previously disabled 3d->2d reshape to avoid correctness issues, in some cases we can instead reshape grouped dims to preserve correctness and performance. 
Added support for `per_tensor` grouped attrs with 3d->2d reshape to support OV use cases.  
Fixes # https://jira.devtools.intel.com/browse/MFDNN-13651
> [GPU] Modify GEMM attr group to support reshape

- src/graph/backend/dnnl/op_executable.cpp
Added the stream hook to fix the genindex implementation for threadpool runtime.
> graph: backend: dnnl: fix genindex for threadpool runtime

- src/common/memory_tracking.hpp
- src/cpu/rnn/cell_common.cpp
- src/cpu/rnn/cell_gru_lbr.cpp
- src/cpu/rnn/ref_postgemm_gru.cpp
- src/cpu/rnn/ref_postgemm_gru_lbr.cpp
- src/cpu/rnn/ref_postgemm_lstm.cpp
- src/cpu/rnn/ref_postgemm_rnn.cpp
- src/cpu/rnn/ref_rnn.cpp
- src/cpu/rnn/rnn_utils.cpp
- src/cpu/rnn/rnn_utils.hpp
- src/cpu/x64/rnn/brgemm_cell_common_bwd.cpp
- src/cpu/x64/rnn/brgemm_cell_common_fwd.cpp
- src/cpu/x64/rnn/jit_uni_rnn_common_postgemm.hpp
It was found during analysis of performance regression in RNN that memory for "scratch gates" was requested from a scratchpad incorrectly: its size was calculated in bytes, but then this value was used as a number of array elements for memory "booking". Moreover, the size of "scratch gates" was taken into account when another (common) block size was calculated and necessary offsets were calculated, but that subblock and corresponding offsets were not used.
Some other similar cases were found too.
Just changing the size of allocated scratch gates was not enough, as different implementations used different LD values. Buffer overflow did not happen because memory size was large enough (sometimes too large).
The PR reduces an amount of space requested by RNN primitive, especially for …
> cpu: rnn: remove unnecessary memory allocations

- src/gpu/intel/ocl/ocl_philox.cl
- src/gpu/intel/ocl/ocl_philox.h
- tests/benchdnn/dnnl_memory.cpp
- tests/benchdnn/dnnl_memory.hpp
Systems with data compression enabled by the driver by default wont generate meaningful performance data with `benchdnn ... --mode=F `
- Reuse [ocl_philox.h](https://github.com/oneapi-src/oneDNN/blob/main/src/gpu/intel/ocl/ocl_philox.h) routine to directly fill gpu mem with random vals via a dedicated opencl kernel. 
Fixes [MFDNN-12589](https://jira.devtools.intel.com/browse/MFDNN-12589)
> benchdnn: memory: gpu: enable support for RNG memory fill

- src/graph/backend/dnnl/passes/transform.cpp
- tests/benchdnn/binary/binary.cpp
- tests/benchdnn/graph/custom_driver.cpp
- tests/benchdnn/graph/custom_driver.hpp
- tests/benchdnn/graph/ref_partition.cpp
- tests/benchdnn/graph/setting_handler.cpp
- tests/benchdnn/graph/utils.cpp
- tests/benchdnn/utils/data_kind.cpp
- tests/benchdnn/utils/data_kind.hpp
With the recent support of select primitive, benchdnn graph also needs to enable validation with select primitive as the reference and remove the customized driver as well as its reference implementation for select.
> benchdnn: graph: support validation through select primitive

- third_party/xbyak/xbyak.h
This change relaxes the opmask assignment check in `setOpmaskIdx` to allow setting the same opmask index multiple times on a Xbyak register, instead of throwing an exception on any repeated assignment. 
Previously, assigning an opmask index that was already set would always result in a runtime error. With this update, an exception is only thrown if a different opmask index is assigned.
This behavior was problematic in scenarios where the same opmask might be set more than once during JIT code generation, such as when handling binary post-ops with tail processing and comparison operations.
Addresses MFDNN-7033
The change has been upstreamed to Xbyak: https://github.com/herumi/xbyak/pull/209
> xbyak: allow repeated assignment of the same opmask index

- src/gpu/intel/ocl/reusable_softmax.hpp
Utilizing subgroup size 32 for softmax leads to unexpected incorrect behavior in some circumstances. Reverting back to 16 for the time being until size 32 is investigated.
> xe: softmax: drop 32 subgroup size due to accuracy issues

- .github/automation/performance/benchdnn_comparison.py
- .github/automation/performance/inputs/matmul_nightly
The nightly performance tests are failing due to benchdnn no longer accepting underscores for the matmul operator
> ci: aarch64: Fix nightly performance tests

- src/gpu/intel/ocl/micro_sdpa.cl
Bugfix for compilation error happening for aligned non-blocked Q loads. 
Example failure on xe2-bmg: 
```
./tests/benchdnn/benchdnn --graph --engine=gpu --dt=0:f16+1:f16+2:f16+3:f16+7:f16+8:f16 --case=complex_fusion/mha/MHA-stable_diffusion-inf-fp32-bs1.json
```
Tested manually since this test case passes in CI...
> xe: sdpa: compilation error bugfix with non-blocking Q loads

- src/cpu/x64/jit_brgemm_conv_utils.cpp
Fix for [MFDNN-13813](https://jira.devtools.intel.com/browse/MFDNN-13813)
In general the computational complexity in `est_eff` and `est_eff_1x1` functions should decrease from O(nthr*nthr) to O(1) after this PR.
For convolution mb1_ic4oc16_id128kd3sd1dd0pd1 from MFDNN-13813 I see initialization time reduced ~50X for 448 threads
This PR updates the efficiency estimation for brgemm convolution by introducing a new thread partition estimation and adjusting several blocking parameters. Key changes include:
Addition of the grid_coverage function to compute block coverage in a 2D grid.
Revision of the efficiency estimation logic in est_eff and est_eff_1x1, including thread-load estimation.
Updates to sp and sp_block calculations to incorporate the is_os_blocking condition.
> brgemm convolution: blocking: update efficiency estimation including extra loop removing

- src/gpu/intel/ocl/micro_sdpa.cpp
This is limited due to a limited availability of builtin_IB_subgroup_block_[read|write] for blocks with k of 64 which is required by kernels for head sizes of > 256
Fixes: MFDNN-13806
> xe: sdpa: limit 2d block writes to sizes below head size of 256

- src/cpu/x64/brgemm/brgemm_containers.cpp
- src/cpu/x64/jit_brgemm_1x1_conv.hpp
[MFDNN-13801](https://jira.devtools.intel.com/browse/MFDNN-13801)
[CPU] Fixed two core dump issues in primitives brgemm_1x1_convolution_fwd_t: 
1. Core dump at model compilation stage
2. Core dump at kernel execution stage
> cpu: x64: fix brgemm_1x1_convolution core dump

- doc/primitives/matmul.md
- src/common/matmul.cpp
- src/gpu/intel/jit/gemm/gen_gemm.hpp
- src/gpu/intel/jit/gemm/gen_gemm_kernel.cpp
- src/gpu/intel/jit/gemm/generator/pieces/gemm_setup.cxx
- src/gpu/intel/jit/gemm/generator/pieces/quantization.cxx
- src/gpu/intel/jit/gemm/jit_gemm_pd.cpp
- src/gpu/intel/ocl/ref_matmul.hpp
- tests/benchdnn/inputs/matmul/harness_matmul_decompression
- tests/benchdnn/matmul/matmul.cpp
Permit decompression of fp4 weights in GEMM, reusing strategies for int4. 
Fixes # MFDNN-13543
> [GPU] GEMM enable Fp4 weights decompression

- src/gpu/intel/ocl/ref_layer_normalization.cl
- src/gpu/intel/ocl/ref_layer_normalization.cpp
- src/gpu/intel/ocl/ref_layer_normalization.hpp
- src/gpu/intel/ocl/reusable_lnorm.cl
- src/gpu/intel/ocl/reusable_lnorm.cpp
- src/gpu/intel/ocl/reusable_lnorm.hpp
- src/gpu/intel/ocl/reusable_vectorized_lnorm.cl
- src/gpu/intel/ocl/reusable_vectorized_lnorm.cpp
- src/gpu/intel/ocl/reusable_vectorized_lnorm.hpp
- src/gpu/intel/ocl/simple_layer_normalization.cl
- src/gpu/intel/ocl/simple_layer_normalization.cpp
- src/gpu/intel/ocl/simple_layer_normalization.hpp
- src/gpu/intel/ocl/vectorized_lnorm.cl
- src/gpu/intel/ocl/vectorized_lnorm.cpp
- src/gpu/intel/ocl/vectorized_lnorm.hpp
- src/gpu/intel/primitive_conf.hpp
- tests/benchdnn/lnorm/lnorm.cpp
- tests/gtests/test_layer_normalization.cpp
Implements: https://jira.devtools.intel.com/browse/MFDNN-13581 
- Added GPU support for RMS normalization in layer norm.
- Added skip_mean bool parameter to invoke RMS.
- Extended testing [gtests & benchdnn] with GPU cases.
Following: https://github.com/uxlfoundation/oneDNN/pull/3068
> [GPU] Add Root Mean Square (RMS) normalization support to lnorm

- src/gpu/intel/jit/codegen/reg_buf.hpp
- src/gpu/intel/jit/codegen/reorder.hpp
- src/gpu/intel/jit/conv/gen_convolution.cpp
This is a follow-up after [CVS-167104](https://jira.devtools.intel.com/browse/CVS-167104).
Changes:
- Added `reg_buf_t::check_bounds()` check for release builds
- Updated `gen_convolution.cpp` to print errors in case of `status::runtime_error`
> xe: conv: check GRF access bounds in release build

- src/gpu/intel/compute/compute_engine.cpp
- src/gpu/intel/compute/compute_engine.hpp
- src/gpu/intel/compute/device_info.hpp
- src/gpu/intel/ocl/micro_sdpa.cpp
- src/gpu/intel/ocl/utils.cpp
- src/gpu/intel/ocl/utils.hpp
- src/gpu/intel/sycl/utils.cpp
- src/gpu/intel/sycl/utils.hpp
This is to help [MFDNN-4562](https://jira.devtools.intel.com/browse/MFDNN-4562), and #2988 in particular. PR removes the `intel/ocl` -> `intel/sycl` dependency which will allow to exclude `intel/ocl` directory for SYCL runtime builds in the future.
After the PR OpenCL kernel compilation for SYCL is isolated here:
https://github.com/uxlfoundation/oneDNN/blob/b4b345d3f3ac6814dda2acbc2cdfcfa498ac9c92/src/gpu/intel/sycl/utils.cpp#L307-L315
Tagging @spalicki as this piece also needs proper handling for full transition in #2988.
> xe: refactor microkernels check

- src/graph/backend/dnnl/op_executable.cpp
- tests/gtests/graph/unit/backend/dnnl/test_subgraph_pass.cpp
Create matmul src and weight mds with any layout only when they are constant
Fix MFDNN-13714
| HW       | mha cases speedup |
| :------- | :---------------------- |
| PVC      | 1.21x   |
| BMG      | 1.17x   |
| Arc-A770 |  1.30x   |
| SPR      | 1.01x   |
| model                          | dtype | HW  | inductor speedup | eager speedup |
| :----------------------------- | :---- | :-- | ----------------: | ------------: |
| GPT2ForSequenceClassification  | fp32  | PVC |           1.06203 |       1.05513 |
| GPT2ForSequenceClassification  | fp16  | PVC |           1.39628 |       1.35299 |
| GPT2ForSequenceClassification  | bf16  | PVC |           1.40592 |       1.35395 |
| PLBartForConditionalGeneration | fp32  | PVC |           1.07212 |       0.99772 |
| PLBartForConditionalGeneration …
> graph: backend: dnnl: make matmul use any layout format only for constant cases

- src/cpu/x64/jit_brgemm_conv_utils.cpp
> Backport: cpu: x64: conv: fix segfault for f16

- src/graph/backend/dnnl/dnnl_backend.hpp
It turned out that the clang 12 used in sanitizer tests still needs this workaround.
> Revert "graph: backend: dnnl: drop the WA for gcc4.8"

- doc/rst/index.rst
- doc/ukernel/operations/brgemm.md
- doc/ukernel/operations/transform.md
- src/cpu/x64/cpu_isa_traits.cpp
This PR documents fp8 support in ukernel API.
Bonus typo fixes:
* Missing spaces in ISA descriptions
* Wording in developer guide index
> Adding fp8 to ukernel documentation

- src/gpu/intel/jit/gemm/generator/microkernel_provider.cpp
- src/gpu/intel/ocl/micro_sdpa.cl
- src/gpu/intel/ocl/micro_sdpa.cpp
- src/gpu/intel/ocl/micro_sdpa.hpp
- src/gpu/intel/ocl/micro_sdpa_configs.cpp
- src/gpu/intel/ocl/micro_sdpa_configs.hpp
- src/gpu/intel/ocl/tile_ops.h
- tests/gtests/internals/test_sdpa.cpp
This PR enables fp32 support in the fused SDPA primitive. The primary motivation of this change was for the sake of reduced memory usage through the fused kernel. Nevertheless, certain hardware (specifically xe2) and smaller head sizes tend to show a performance improvement against the primitives only implementation. With larger head and sequence sizes, performance degrades and the primitives based implementation may be more performant.
This PR has been rebased upon the config changes introduced in #3322 (to be merged shortly after final reviews) please ignore all but the last commit(s) in the meantime.
> sdpa fma f32

- .github/automation/performance/benchdnn_comparison.py
- .github/automation/performance/inputs/matmul_nightly
fp16 fastmath matmul tests are accidentally running on the performance tests, these have been disabled. The ctime regression output has also been modified to also show the problem it failed on.
> ci: aarch64: ignore fp16 fastmath tests

- src/gpu/intel/sycl/l0/utils.cpp
- src/gpu/intel/sycl/l0/utils.hpp
- src/gpu/intel/sycl/utils.cpp
- src/gpu/intel/sycl/utils.hpp
- src/xpu/ocl/utils.cpp
- src/xpu/ocl/utils.hpp
- src/xpu/utils.cpp
- src/xpu/utils.hpp
All changes are guarded by `DNNL_EXPERIMENTAL_SYCL_KERNEL_COMPILER` build option:
1. Add L0 native kernel binary retrieval
2. Use SYCL kernel compiler for microkernels check
3. Remove OCL-L0 device mapping
4. Remove OCL engine creation from SYCL code
> src: gpu: intel: sycl: remove additional OCL dependencies

- doc/advanced/sparsity.md
Fixing minor documentation observation (reference: https://uxlfoundation.github.io/oneDNN/dev_guide_sparsity.html).
> doc: fix levels in sparse memory formats

- src/gpu/intel/jit/gemm/gen_gemm.cpp
- src/gpu/intel/jit/gemm/jit_gemm_pd.cpp
- src/gpu/intel/jit/gemm/jit_gemm_pd.hpp
Post-ops for A/B/C each have their own handling code, potentially leading to bug escapes. This PR refactors post-op initialization to simplify the related logic, and so that A/B/C scales are handled in one block and can easily be extended for future features. Additionally refactors a few functions to be defined where they're used and to reduce type conversions.
The first commit is from #3498 and will be dropped upon merging (that PR, then this one).
> xe: gemm: refactor post ops and quantization

- src/cpu/x64/brgemm/jit_brgemm_amx_uker.cpp
- tests/benchdnn/inputs/matmul/harness_matmul_regression_bf16
> [backport] cpu: x64: brgemm: enable per_oc_d broadcast strategy for AMX

- .github/automation/performance/inputs/matmul_nightly
- .github/automation/performance/inputs/shapes_3d_perf
Increasing the size of 3d shapes for the nightly matmul performance tests as it is causing a false positive in the ci
> cpu: aarch64: perf: increase 3d matmul shape for perf tests

- src/gpu/gpu_sdpa_list.cpp
- src/gpu/intel/jit/gemm/gen_gemm.cpp
- src/gpu/intel/jit/gemm/gen_gemm.hpp
- src/gpu/intel/jit/gemm/gen_gemm_kernel.cpp
- src/gpu/intel/jit/gemm/gen_gemm_kernel.hpp
- src/gpu/intel/jit/gemm/generator/pieces/map.hpp
- src/gpu/intel/jit/gemm/generator/pieces/post_ops.cxx
- src/gpu/intel/jit/gemm/jit_gemm_pd.cpp
- src/gpu/intel/jit/gemm/jit_gemm_pd.hpp
- src/gpu/intel/ocl/gemm_matmul.hpp
Fixes several issues in quantization code, each with their own commit. Also renames variables used in gemm code to rely on A/B names instead of SRC/WEI whenever possible, to ensure variable naming consistency.
High-impact bugs fixed:
- In some cases, common scales/zero-points were emitting invalid instructions leading to accuracy issues. They now generate correctly.
- Some valid cases were getting skipped without reason, which now go to the optimized implementation.
- When reshaping GEMM layers to reduce dimensions, dst scales were not getting reshaped with the other scales.
- Reduced strictness of dst scales support via jit:gemm:any, which was overly-restrictive.
- Some `per_ocic` quantization cases with M=1 or N=1 were treated as 1D, although gemmstone requires these to be labeled as …
> [GPU] various quantization fixes

- src/gpu/intel/jit/codegen/codegen.cpp
- src/gpu/intel/jit/codegen/kernel.hpp
- src/gpu/intel/jit/codegen/reduce.hpp
- src/gpu/intel/jit/codegen/reorder.hpp
- src/gpu/intel/jit/codegen/send.hpp
- src/gpu/intel/jit/conv/config.cpp
- src/gpu/intel/jit/conv/config.hpp
- src/gpu/intel/jit/ir/config.hpp
- src/gpu/intel/jit/ir/hw.hpp
- src/gpu/intel/jit/ir/ir.cpp
- src/gpu/intel/jit/ir/ir.hpp
- src/gpu/intel/jit/v2/conv/kernel_desc.hpp
This PR removes 3 dependencies from IR code generation. In particular, this PR replaces the generation of hardcoded dpas meta data, atomic send meta data, and signal header generation with an IR pass which automatically determines their necessity. In addition, this removes the v1:conv configuration parameter `vec_size` out of shared structure `exec_config_t`, and removes the codegen dependency on `exec_config_t`, as `exec_config_t` is only necessary for the interface setup.
> jit: simplify ir codegen dependencies

- src/gpu/intel/jit/codegen/kernel.hpp
The ngen::emul functionality has be signficantly increased since the removed branch was added. This PR removes this complexity so that we can just rely on ngen::emul directly. Additionally, this provides a workaround for [MFDNN-13917](https://jira.devtools.intel.com/browse/MFDNN-13917).
> xe: jit: codegen: remove unnecessary emul workaround

- src/gpu/intel/jit/conv/ir_builder.cpp
Jira: [MFDNN-13928](https://jira.devtools.intel.com/browse/MFDNN-13928)
Popped-up after #3525. I saw/dispatched a bunch of unrelated issues in Xe-LPG in pre-commit ([MFDNN-13917](https://jira.devtools.intel.com/browse/MFDNN-13917)) so this particular issue was overlooked.
> xe: conv: fix bias reduce condition

- tests/benchdnn/common.cpp
- tests/benchdnn/utils/cold_cache.cpp
- tests/benchdnn/utils/fill.cpp
[MFDNN-13874](https://jira.devtools.intel.com/browse/MFDNN-13874)
Here there was only one config which was static, which captured the first data type in it and used it for any further data types.
@yair-obodovsky reported that cold-cache is not working on CPU which has become a victim of memory prefilling optimization when number of buffers for the problem exceeded 100.
Also using cold-cache might trigger a report of misconducted memory which is expected. It was disabled.
> benchdnn: fixes to cold cache and perf mode filling

- doc/graph/fusion_patterns/sdpa.md
- examples/CMakeLists.txt
- examples/graph/sdpa_bottom_right_causal_mask.cpp
- include/oneapi/dnnl/dnnl_graph.h
- include/oneapi/dnnl/dnnl_graph.hpp
- src/graph/backend/dnnl/common.cpp
- src/graph/backend/dnnl/common.hpp
- src/graph/backend/dnnl/kernels/large_partition.cpp
- src/graph/backend/dnnl/op_executable.hpp
- src/graph/interface/logical_tensor.hpp
- src/graph/interface/tensor.cpp
- src/graph/interface/tensor.hpp
- tests/benchdnn/graph/graph_memory.cpp
- tests/gtests/graph/api/test_cpp_api_tensor.cpp
- Extract the new API changes from #3454 
- Create scalar tensor with `tensor::make_scalar_tensor(logical_tensor, void*)` instead of the original constructor.
- `scalar_tensor.get_data_handle()` returns nullptr.
- `scalar_tensor.set_data_handle()` raises error.
- Benchdnn graph driver is changed accordingly to use the new method to create scalar tensor.
- Fix DNNL backend for creating `dnnl::memory` from a scalar tensor without engine.
- Add an example for SDPA with bottom-right causal mask which requires scalar tensor to define the patter. It's also a new feature for oneDNN v3.9, so I think we may need to backport this one as well.
> api: graph: fix scalar tensor creation and usage

- tests/benchdnn/graph/utils.cpp
The PR adds an index check to avoid overflow and fix the address sanitizer failure.
> benchdnn: graph: check index range while checking contiguous mem

- src/graph/interface/partition_hashing.cpp
- src/graph/interface/partition_hashing.hpp
- tests/gtests/graph/unit/interface/test_compiled_partition.cpp
- tests/gtests/graph/unit/interface/test_partition_hashing.cpp
Found in MFDNN-13693, not about solving the MFDNN-13693 itself, but a potential issue.
Different fpmath mode may has different kernel implementation, shouldn't cache hit if fpmath is different. Also following the implementation of primitive hashing([here](https://github.com/uxlfoundation/oneDNN/blob/main/src/common/primitive_hashing.cpp#L226))
> graph: interface: combine fpmath into compiled partition cache key

- src/cpu/x64/matmul/brgemm_matmul_copy_utils.cpp
> Backport: cpu: x64: matmul: correct bf16 conversion in copy_b_transpose

- src/gpu/intel/ref_inner_product.cl
#3558 missed adding one of the unused dimension arguments to APPLY_POST_OPS_SERIAL.
> xe: fix ref_inner_product call to APPLY_POST_OPS

- src/graph/backend/dnnl/kernels/sdp_primitive_config.cpp
Local test results:
```bash
$ ./tests/benchdnn/benchdnn --graph --engine=gpu --mode=P --case=complex_fusion/mha/gqa-plain-implicit-causal-mask-fp32-bs1.json
Output template: perf,%engine%,%prb%,%-time%,%0time%
perf,gpu,--mode=P --graph --engine=gpu --case=complex_fusion/mha/gqa-plain-implicit-causal-mask-fp32-bs1.json,0.08016,0.0902972
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 invalid_arguments:0 failed:0 listed:0
total perf: min(ms):0.08016 avg(ms):0.0902972
total: 5.07s; create_pd: 0.00s (0%); create_prim: 0.65s (13%); fill: 0.00s (0%); execute: 0.00s (0%);
$ _ONEDNN_GRAPH_SDPA_FORCE_PRIMITIVE=1 ./tests/benchdnn/benchdnn --graph --engine=gpu --mode=P --case=complex_fusion/mha/gqa-plain-implicit-ca
usal-mask-fp32-bs1.json
Output template: perf,%engine%,%prb%,%-time%,%0time% …
```
> graph: backend: dnnl: enable f32 sdpa with gpu ukernel opt

- src/cpu/aarch64/jit_brgemm_conv.cpp
This PR aims to create a workaround for a test failure caused by PR #3552 until a definitive solution is developed. To reproduce the test failure, you need to run:
`DNNL_VERBOSE=all OMP_NUM_THREADS=1 ./tests/benchdnn/benchdnn --conv --dt=u8:s8:f32 --skip-impl=ref,x64:gemm mb1ic64ih1iw33oc1oh1ow33kh1kw24ph0pw23n"l_pad_exceeds_ow_block"`
Fixes #3591
> cpu: aarch64: Fix nightly test crash caused by PR #3552

- src/cpu/x64/matmul/amx_blocking_heuristics.cpp
- src/cpu/x64/matmul/amx_blocking_heuristics.hpp
- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
- src/cpu/x64/matmul/brgemm_matmul_utils.hpp
- src/cpu/x64/matmul/postops_estimator.hpp
Estimate the size of the post-operation for the blocking heuristics. Avoid splitting dimension K if bound on post-processing , and incorporate post-processing information into the core work partitioning algorithm.
> cpu: x64: matmul: Adjust heuristics for postops bound layers

- src/cpu/x64/jit_uni_binary.cpp
- src/cpu/x64/jit_uni_binary_kernel.cpp
- tests/benchdnn/inputs/binary/harness_binary_regression
Revert https://github.com/uxlfoundation/oneDNN/pull/2778, which is causing a segfault in [PR](https://jira.devtools.intel.com/browse/MFDNN-13940).
> Revert "cpu: x64: binary: Supporting per_w broadcast strategy (#2778)"

- src/cpu/rnn/ref_rnn.cpp
- src/cpu/rnn/rnn_utils.hpp
- src/cpu/x64/gemm/gemm_driver.cpp
- src/cpu/x64/rnn/brgemm_cell_common_fwd.cpp
- src/cpu/x64/rnn/brgemm_cell_common_fwd.hpp
- src/cpu/x64/rnn/rnn_brgemm_utils.cpp
The PR fixes some performance regressions (compared to the version 3.3): [MFDNN-12215](https://jira.devtools.intel.com/browse/MFDNN-12215)
Changes:
-   "merged gemm layer" calculation is enabled in case of LBR_GRU (for AVX2) cell type; this was used in 3.3 but disappeared later;
-   "merged gemm layer" calculation is divided into smaller parts (better distribution between threads);
-   matrix block width ("n_block" parameter) is increased in case of AVX2 with mb=1, i.e. when matrix-vector multiplication is performed on each iteration (brgemm generates better jit-code for AVX2 if its parameter N=32 compared to N=16; performance difference is about 1.5);
-  only one thread is used for iteration calculations for small problems in case of AVX2 if TBB is used; this removes significant overhead …
> Fix performance regressions in RNN

- src/gpu/intel/ref_group_normalization.cl
- src/gpu/intel/ref_group_normalization.cpp
Attempt to fix the eternal register spill warnings emitted by ref_gnorm_fwd.
> xe: ocl: avoid ref_gnorm fwd register spills

- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
Fixes MFDNN-13919
Most of the regressed shapes are dispatched to gemm.
> cpu: x64: matmul: dispatch shapes with small K to gemm

- src/graph/interface/graph.cpp
- src/graph/interface/partition.cpp
As title, build failure when turn on `ONEDNN_ENABLE_GRAPH_DUMP` which is introduced by #3464
> graph: interface: fix namespace of stringstream

- examples/getting_started.cpp
- examples/gpu_opencl_interop.cpp
- examples/primitives/batch_normalization.cpp
- examples/primitives/lrn.cpp
- examples/sycl_interop_buffer.cpp
- examples/sycl_interop_usm.cpp
Another minor observation corrected (seems like at least examples/doc/include don't have other mentions of operation desc).
> examples: remove description of outdated concept

- .github/workflows/aarch64-acl.yml
There is no need to download ACL if it is already in cache. We just need to check that it exists. This will save CI time.
> ci: remove unneccesary ACL restoration

- src/gpu/intel/compute/kernel.hpp
- src/gpu/intel/gpu_primitive.hpp
- src/gpu/intel/ocl/kernel.cpp
- src/gpu/intel/ocl/kernel.hpp
- src/gpu/intel/rnn/grid.cpp
- src/gpu/intel/sycl/interop_kernel.cpp
- src/gpu/intel/sycl/interop_kernel.hpp
- tests/benchdnn/matmul/ref_matmul.cpp
[MFDNN-13649](https://jira.devtools.intel.com/browse/MFDNN-13649)
Kernel dump error was reported by @rjoursler (thank you!) and the fix was picked up from https://github.com/uxlfoundation/oneDNN/pull/3180 (@rjoursler, thanks again!).
Checked that both backends now report hashes. They did, and I found a difference in generated kernels for OCL and SYCL backends for RNN problems for which a cache skew issue was reported.
> fixups: kernel dump for SYCL and benchdnn matmul reference

- examples/gpu_opencl_interop.cpp
- examples/sycl_interop_buffer.cpp
fixup for step failure introduced by https://github.com/uxlfoundation/oneDNN/commit/e53d60c50002908a9901bc3e5ede2ebc08af753d update
> examples: fix copyright check step failure

- tests/benchdnn/graph/bench_graph.cpp
- tests/benchdnn/graph/flex_rewrite.cpp
- tests/benchdnn/graph/flex_rewrite.hpp
Fix MFDNN-13808. Currently, illegal rewriting in a test batch will terminate the whole program. This PR:
1. Improve error handling in the rewriter to report a SKIPPED instead of terminating directly.
2. Reorganize the functions in the flexible rewriter and add more comments.
> benchdnn: graph: improve error handling to skip illegal rewrite cases

- tests/gtests/graph/unit/interface/test_compiled_partition.cpp
CP cache won't cache hit if `CPU_RUNTIME=SYCL` as sycl device and context is different.
> gtests: graph: unit: fix cp cache sycl cpu runtime check

- src/gpu/intel/reduction/ref_reduction.cl
Limits the maximum unroll of loops in the reference reduction kernel, to prevent register spills. Since the loop bounds are known at compile time, the compiler tries to aggressively unroll the loops (in a way that depends on the specific dimensions in the problem), so randomly some cases will spill registers and cause a warning.
> xe: reduction: reduce register spills

- src/cpu/cpu_reduction_list.cpp
- src/cpu/ref_reduction.cpp
- src/cpu/ref_reduction.hpp
- src/cpu/scale_utils.cpp
- src/cpu/scale_utils.hpp
- src/cpu/x64/matmul/brgemm_matmul.cpp
- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
- tests/benchdnn/common.cpp
- tests/benchdnn/dnnl_common.cpp
- tests/benchdnn/matmul/ref_matmul.cpp
- tests/benchdnn/utils/cold_cache.cpp
- tests/benchdnn/utils/fill.cpp
This PR is a backport of:
#3556 (cold-cache fixes)
#3625 (ref reduction change)
#3629 (the part fixing benchdnn matmul ref)
#3653 (cpu brgemm matmul fixes)
> [rls-v3.9] Backports of functional fixes

- include/oneapi/dnnl/dnnl_types.h
- include/oneapi/dnnl/dnnl_ukernel.h
- include/oneapi/dnnl/dnnl_ukernel_types.h
- transform-related functionality was incorrectly marked as brgemm group
- `*` is not handled very well, options are either using `\c` or simply `` (which results into nicer table displayed and all the reference to dnnl_ still work)
> doc: resolve a few warnings

- src/gpu/intel/jit/codegen/codegen.cpp
Comparison operations use a flag register which forces SIMD16. This is problematic when padding to 16 elements exceeds the size of the allocated register buffer.
Addresses [MFDNN-13970](https://jira.devtools.intel.com/browse/MFDNN-13970).
This is not a backport per se, as the issue does not reproduce on main.
> [rls-v3.9] xe: jit: codegen: limit comparison binary op SIMD

- src/gpu/intel/jit/codegen/codegen.cpp
- tests/benchdnn/inputs/binary/harness_binary_regression
These operations use a flag register which forces SIMD16. This is problematic when padding to 16 elements exceeds the size of the allocated register buffer.
Related to [MFDNN-13970](https://jira.devtools.intel.com/browse/MFDNN-13970), though it does not currently reproduce on main. "Forward-port" of #3648.
> xe: jit: codegen: limit comparison binary op SIMD

- src/gpu/intel/gemm/gemm_with_post_ops.cpp
- src/gpu/intel/gpu_post_ops.hpp
- src/gpu/intel/ocl_math_utils.h
- src/gpu/intel/ocl_post_ops.h
- src/gpu/intel/ocl_types.h
- src/gpu/intel/primitive_conf.cpp
- src/gpu/intel/primitive_conf.hpp
- src/gpu/intel/reduction/combined_reduction.cpp
- src/gpu/intel/reduction/ref_reduction.cpp
- src/gpu/intel/ref_convolution.cpp
- src/gpu/intel/ref_eltwise.cpp
- src/gpu/intel/ref_group_normalization.cpp
- src/gpu/intel/ref_inner_product.cpp
- src/gpu/intel/ref_matmul.cpp
- src/gpu/intel/ref_pooling.cpp
- src/gpu/intel/ref_resampling.cpp
- src/gpu/intel/simple_binary.cpp
- src/gpu/intel/simple_softmax.cpp
- src/gpu/intel/xe_binary.hpp
- src/gpu/intel/xe_pooling.cpp
- src/gpu/intel/xe_wino_convolution.cpp
Enables OpenCL kernels to take runtime arguments. In particular, the following are moved to runtime arguments:
```
// eltwise
alpha
beta
scale (when not 0 or 1)
// sum
zero point (when non-zero)
scale (when not 0 or 1)
// prelu,binary
non-broadcasted dimension strides
```
This is a byproduct of working to understand high level requirements for post-ops in the ir based gemm (with the ultimate goal of enabling bias support).
> xe: enable runtime post-op arguments for OpenCL kernels

- src/gpu/intel/compute/kernel.hpp
This fixes segfaults in batch normalization with `ONEDNN_VERBOSE=all` as some kernels may be empty.
> fixup: gpu: add debug capabilities for kernels

- src/common/memory_tracking.hpp
PR fixes this assertion on PVC with debug build:
```
$ ./build/tests/benchdnn/benchdnn --matmul --engine=gpu --dt=f16:f16:u8 --stag=bac --wtag=abc --dtag=bac --skip-impl=ref 1x425x183:1x183x7189
benchdnn: ../src/xpu/ocl/buffer_memory_storage.cpp:124: virtual std::unique_ptr<dnnl::impl::memory_storage_t> dnnl::impl::xpu::ocl::buffer_memory_storage_t::get_sub_storage(size_t, size_t) const: Assertion `offset % ocl_engine_impl->get_buffer_alignment() == 0' failed.
Aborted (core dumped)
```
> common: fix alignment for nested scratchpads

- src/common/verbose.hpp
Avoids unexpected compilation failures when injecting logging interfaces into third-party source code.
> common: add missing namespace for verbose defines

- .github/automation/aarch64/ci.json
- README.md
- cmake/ACL.cmake
- src/cpu/aarch64/acl_reorder.cpp
- src/cpu/aarch64/acl_reorder.hpp
The ACL reorder API has been updated to allow users to specify whether to transpose or not transpose for each reorder.
A previous PR https://github.com/uxlfoundation/oneDNN/pull/2992 had been merged but reverted due to some regressions. This PR enables the API but disables ACL reorders for those that show regressions.
> Update ACL reorder API without introducing regressions

- src/gpu/intel/micro_sdpa.cpp
- src/gpu/intel/micro_sdpa.hpp
- src/gpu/intel/sdpa_utils.h
This PR addresses a performance regression in SDPA due to superfluous index calculations moving to runtime as part of the reusable machinery. A check has been added to ensure we can drop the redundant terms and the index calculation macro has been further simplified.
> xe: sdpa: simplify batch calculation for non-blocked cases

- src/gpu/intel/ocl/micro_sdpa.cpp
- src/gpu/intel/ocl/micro_sdpa.hpp
- src/gpu/intel/ocl/sdpa_utils.h
Backport of #3680. Addresses a Pytorch model validation performance regression for v3.9.
> [rls-v3.9] xe: sdpa: simplify batch calculation for non-blocked cases

- src/gpu/generic/shuffle_by_reorder.hpp
- src/gpu/gpu_shuffle_list.cpp
Shuffle by reorder has no Intel-specific dependencies, so move it into the generic namespace.
By pure luck, partially addresses [MFDNN-13823](https://jira.devtools.intel.com/browse/MFDNN-13823).
> gpu: make shuffle-by-reorder generic

- src/gpu/intel/jit/gemm/selector/kernel_selector.cpp
> xe: jit: gemm: restore Xe3 tag in selector

- src/graph/backend/dnnl/common.cpp
- src/graph/backend/dnnl/passes/transform.cpp
- src/graph/backend/dnnl/passes/utils.cpp
- src/graph/backend/dnnl/subgraph.cpp
- src/graph/backend/dnnl/utils.hpp
- Use the utility functions from src/common and remove the duplicated ones.
- Change the return value of fmap to avoid a false warning with GCC 13.
- Compare 1.f and -1.f directly and remove compare_float() as it's not used elsewhere.
> graph: backend: dnnl: fix utility functions

- .github/labels.yml
Update cpu-aarch64 label to include ci files
> ci: aarch64: Update labels

- .github/automation/aarch64/skipped-tests.sh
- src/cpu/aarch64/matmul/brgemm_matmul_reorders.cpp
Fixes illegal instructions and/or correctness bugs on other platforms.
> cpu: aarch64: skip unsupported ISAs in brgemm_matmul_matrix_B_reorder_t

- .github/automation/aarch64/skipped-tests.sh
- src/cpu/aarch64/jit_uni_reorder.cpp
- tests/benchdnn/inputs/reorder/harness_reorder_compensation
The "fast return" path in `jit_uni_reorder` does not support compensation and needs to be skipped accordingly.
This should allow `test_benchdnn_modeC_conv_int8_cpu` to be removed from the CI skip-list.
Example failure:
**Before:**
```sh
$ ./build/tests/benchdnn/benchdnn --reorder --mode=C --sdt=f32 --stag=abc --ddt=s8 --dtag=cab --oflag=zp_comp:3 79x78x2
[   0][0:0] exp_f32:           1 exp:           1 got:           0 diff:       1 rdiff:       1
[   2][0:2] exp_f32:          -1 exp:          -1 got:           0 diff:       1 rdiff:       1
[   3][0:3] exp_f32:          -4 exp:          -4 got:           0 diff:       4 rdiff:       1
[   4][0:4] exp_f32:         -80 exp:         -80 got:           0 diff:      80 rdiff:       1
[   5][0:5] exp_f32:           1 exp:           1 got: …
```
> cpu: aarch64: jit_reorder: no fast_return if compensation needed

- src/cpu/rv64/rvv_nchw_pooling.cpp
- src/cpu/rv64/rvv_nchw_pooling.hpp
This PR enhances the RISC-V RVV pooling implementation in oneDNN by fixing two key issues: 
- The first change moves set_default_params() earlier in the constraint checks to ensure default memory formats are set before calling is_dense(), allowing the RVV max pooling kernel to be selected for more valid configurations.
- The second fix addresses a segmentation fault in the MaxPooling kernel caused by invalid pooling windows (zero or negative size) due to padding and strides. A guard was added to skip such cases safely, preventing out-of-bounds memory access.
Previously, the RVV max pooling kernel was being incorrectly skipped for valid configurations because the is_dense() check in its constraint list was evaluated before the call to `set_default_params()`. Since `dst_md()` could still …
> cpu: riscv: pooling: fix kernel selection and edge case segfault in MaxPooling

- tests/benchdnn/inputs/matmul/test_matmul_ci
- tests/benchdnn/inputs/matmul/test_matmul_gpu
- ~~Add skip in `skip_unimplemented_prb` to cover GPU ref gaps, CPU unimplemented in CI~~
- Add batched gemm with reshape, per_tensor attributes tests to CI to avoid escapes.
> [Benchdnn] Move GEMM attr tests

- src/graph/backend/dnnl/dnnl_op_def.hpp
- src/graph/backend/dnnl/fusion_info.hpp
- src/graph/backend/dnnl/internal_attrs.hpp
- src/graph/backend/dnnl/kernels/mqa_decomp_config.cpp
- src/graph/backend/dnnl/kernels/mqa_decomp_config.hpp
- src/graph/backend/dnnl/kernels/sdp_decomp_config.cpp
- src/graph/backend/dnnl/kernels/sdp_decomp_config.hpp
- src/graph/backend/dnnl/kernels/sdp_primitive_config.cpp
- src/graph/backend/dnnl/layout_propagator.cpp
- src/graph/backend/dnnl/layout_propagator.hpp
- src/graph/backend/dnnl/op_executable.cpp
- src/graph/backend/dnnl/op_executable.hpp
- src/graph/backend/dnnl/passes/compile_ops.cpp
- src/graph/backend/dnnl/passes/insert_ops.cpp
- src/graph/backend/dnnl/passes/layout_propagation.cpp
- src/graph/backend/dnnl/passes/memory_planning.cpp
- src/graph/backend/dnnl/passes/memory_planning.hpp
- src/graph/backend/dnnl/passes/transform.cpp
- src/graph/backend/dnnl/passes/utils.cpp
- src/graph/backend/dnnl/passes/utils.hpp
- src/graph/backend/dnnl/subgraph.cpp
- src/graph/backend/dnnl/subgraph.hpp
- src/graph/interface/c_types_map.hpp
- src/graph/utils/attribute_value.hpp
- tests/gtests/graph/unit/backend/dnnl/test_insert_ops_cpu.cpp
- tests/gtests/graph/unit/backend/dnnl/test_internal_attrs_cpu.cpp
- tests/gtests/graph/unit/backend/dnnl/test_layout_propagator_cpu.cpp
- tests/gtests/graph/unit/backend/dnnl/test_op_executable.cpp
- tests/gtests/graph/unit/backend/dnnl/test_subgraph_pass.cpp
Preliminary work for MFDNN-13442. The main purpose of this PR is to bind the `fusion_info` as an attribute directly onto the op, rather than using a `fusion_info_key` to reference a container(currently a vector store in `fusion_info_mgr`) that manages the fusion info.
> graph: backend: dnnl: backend refactor of adding fusion info attr

- include/oneapi/dnnl/dnnl_graph.hpp
- include/oneapi/dnnl/dnnl_ukernel.hpp
Doxygen seems to have an issue parsing through nested groups and namespaces, but giving it a small hint helps.
Also explored option to update Doxygen, but this currently produces enormous amount of warnings.
This should take care of the 3 remaining doc warnings.
> doc: give doxygen a hint wrt nested groups

- src/cpu/cpu_inner_product_list.cpp
- src/cpu/ref_inner_product_int8.hpp
- src/cpu/x64/brgemm/brgemm.cpp
- src/cpu/x64/matmul/brgemm_matmul.cpp
- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
- src/cpu/x64/matmul_inner_product.hpp
- tests/benchdnn/inputs/matmul/test_matmul_ci
- tests/benchdnn/inputs/matmul/test_matmul_int8
> Enable f16 dst for s8/u8 inputs in matmul and matmul-based ip

- MAINTAINERS.md
Siddhartha has been a contributor and maintainer for onednn-cpu-aarch64 for over a year: https://github.com/uxlfoundation/oneDNN/commits?author=Sqvid
> governance: Add Siddhartha Menon to onednn-devops

- cmake/platform.cmake
Required to fix build issues with new GEMM implementation.
Workaround for #3749.
> cmake: add "-mcpu=power10 -mmma" to cross-compilation flags

- src/cpu/x64/ukernel/brgemm.cpp
Fixup for https://github.com/uxlfoundation/oneDNN/pull/3701, one more fixup for ukernel dst_scales implementation that slipped away.
> fixup: cpu: x64: brgemm: handle src and wei scales inside the kernel

- src/gpu/intel/conv/jit/plan.cpp
- src/gpu/intel/conv/jit/plan_utils.hpp
- src/gpu/intel/gemm/jit/generator_dsl/builder.cpp
- src/gpu/intel/jit/codegen/reduce.hpp
- src/gpu/intel/jit/codegen/reorder.cpp
- src/gpu/intel/jit/dsl/decl.hpp
- src/gpu/intel/jit/dsl/dsl.cpp
- src/gpu/intel/jit/dsl/dsl.hpp
- src/gpu/intel/jit/grf_usage.cpp
- src/gpu/intel/jit/ir/core.cpp
- src/gpu/intel/jit/ir/core.hpp
- src/gpu/intel/jit/ir/epilogue.cpp
- src/gpu/intel/jit/ir/fma.cpp
- src/gpu/intel/jit/ir/ir.cpp
- src/gpu/intel/jit/ir/ir.hpp
- src/gpu/intel/jit/ir/kernel_info.hpp
- src/gpu/intel/jit/ir/problem.hpp
- src/gpu/intel/jit/ir/reduce.cpp
- src/gpu/intel/jit/ir/slm_reduce_builder.cpp
- src/gpu/intel/jit/ir/tensor.cpp
- src/gpu/intel/jit/ir/tensor.hpp
- src/gpu/intel/jit/pass/simplify.cpp
- src/gpu/intel/jit/pass/slm.cpp
PR extends the IR/DSL functionality and includes other minor changes.
Full list of changes:
- IR changes:
- Introduced `assign_t`
- Extended `shuffle_t` to support SIMD types (used by `dsl::extract` to extract i-th component from a SIMD expression)
- Added left/right shift and xor operations support
- Adjusted type deduction to take into account SIMD types
- Extended `type_t` to support `type[elems]` as a shortcut for `type.with_elems(elems)`
- DSL changes
- Added `dsl::ctx_t::new_ir_api()` to enable new IR semantics with `assign_t` and without alloc/let
- We should fully migrate to the new semantics in the future and drop this flag
- Migrated DSL to rely on `jit::layout_t` instead of v2 (which is possible after #3604)
- Introduced `dsl::def_slm()` to allocate SLM tensors
- Introduced …
> GPU DSL extensions

- src/cpu/x64/brgemm/brgemm_utils.cpp
- src/cpu/x64/brgemm/jit_brdgmm_kernel.cpp
- src/cpu/x64/brgemm/jit_brdgmm_kernel.hpp
- src/cpu/x64/brgemm/jit_brgemm_amx_uker.cpp
- src/cpu/x64/brgemm/jit_brgemm_kernel.cpp
- src/cpu/x64/injectors/injector_utils.cpp
- src/cpu/x64/injectors/injector_utils.hpp
This PR:
- encapsulate registers save/restore operations
- It will be easier to switch register scratchpad from the using stack space to something else if needed
- register "offset" variables offsets are removed
- registry scratchpad calculates required space itself
- "conditional_register_preserve_guard_t" usage removed from brgemm kernels code since they use push/pop which changes the stack register and contradicts how we use the stack to store other registers.
- most actively used registers can use the extended set of GPR on DMR and this avoids extra read-write operations.
Notes: 
- the first commit is just some code refactoring - move big lambda function as separate method
- masked operations with registers from extended set (r16,...) doesn't work well under current sde.  So I don't …
> Xbyak::Reg64 extension to support more transparent save/restore operations and use APX extended GPR set

- cmake/options.cmake
- doc/build/build_options.md
- doc/sphinx/conf.py.in
Along with deployment procedure changes this PR adds a little widget to pick specific version of documentation:
Live demo: https://vpirogov.github.io/oneDNN/
Closes #2843
> Added version selector for Github pages documentation

- src/gpu/intel/gemm/jit/generator/pieces/copy_plan.cpp
- src/gpu/intel/jit/codegen/ngen_helpers.hpp
- src/gpu/intel/jit/codegen/reorder.cpp
- src/gpu/intel/jit/codegen/reorder.hpp
- src/gpu/intel/jit/grf_usage.cpp
- src/gpu/intel/jit/ir/core.cpp
- src/gpu/intel/jit/ir/core.hpp
- src/gpu/intel/jit/ir/send_plan.cpp
- src/gpu/intel/reorder/jit.cpp
This will be the first of 2 (or 3) PRs to address [MFDNN-13450](https://jira.devtools.intel.com/browse/MFDNN-13450). This PR introduces an extra reorder to re/un-packed message payloads and adds additional int4 handling in the copy planner to support this. With these changes, the restrictions on 4-bit types is that the innermost block has stride 1 and that either: (1) the number of inner contiguous elements is divisible by 8 so loads are dense, or (2) the innermost block is divisible by 2 so the block is coterminous with a scattered message slot.
A side-effect of this PR is that it also addresses [MFDNN-13975](https://jira.devtools.intel.com/browse/MFDNN-13975).
> [GPU] Relax IR message slot size restrictions - Part 1

- src/cpu/x64/brgemm/jit_brgemm_kernel.cpp
Fix for:
- MFDNN-14103: [SPR][DMR] Matmul (bf16) failed with SegFault
- MFDNN-14104: [SPR][DMR][NVL] Convolution failed with SegFault
> x64: brgemm kernel: fix reg_buf_aux

- src/cpu/x64/brgemm/jit_brdgmm_kernel.hpp
Fix for MFDNN-14102 ([NVL][DMR] Correctness issue in Convolution)
> x64: brdgmm kernel: fix reg_aux_wei_scales register for APX

- src/cpu/aarch64/brgemm/brgemm.cpp
- src/cpu/aarch64/brgemm/brgemm_utils.cpp
- src/cpu/aarch64/brgemm/jit_brgemm_kernel.cpp
This PR extends the BRGEMM (Batch-Reduce General Matrix Multiplication) kernel to support bf16 data type.
Major Code Changes:
• Support for data type bf16:bf16:f32 and bf16:bf16:bf16
• Support for bias data type bf16 and f32
Other minor changes added accordingly in some files.
Perf Timings (ms)  Compared with f32 for single core:
| Shapes | f32:f32:f32 | bf16:bf16:f32 | bf16:bf16:bf16 | 
|:----------:|:----------:|:----------:|:----------:|
|512x768:768x768 | 8.02 | 3.94 | 3.97 |
|197x3072:3072x768 | 30.93 | 7.07 | 7.08 |
General
[✓] Do all unit and benchdnn tests (make test and make test_benchdnn_*) pass locally for each commit? Yes
```./test_matmul```
[----------] Global test environment tear-down
[==========] 64 tests from 8 test suites …
> cpu: aarch64: brgemm: Extend support for bf16 in BRGEMM Kernel

- src/cpu/cpu_convolution_list.cpp
- src/cpu/ref_convolution.hpp
This PR adds support for f32:f32:u8, f32:f32:s8, bf16:bf16:u8 and bf16:bf16:s8 data types configurations in convolution and deconvolution.
Addresses [MFDNN-7683](https://jira.devtools.intel.com/browse/MFDNN-7683)
> cpu: conv: enable f32:f32:x8 and bf16:bf16:x8 in conv and deconv

- src/gpu/intel/conv/ref.cl
- src/gpu/intel/conv/ref.cpp
Fixes [MFDNN-14100](https://jira.devtools.intel.com/projects/MFDNN/issues/MFDNN-14100), which is a compilation error due to an incorrect AS_SUM_DATA_T definition.
> xe: conv: switch ref_conv to use ocl_io.h

- src/graph/backend/dnnl/kernels/sdp_primitive_config.cpp
As title, int8 sdpa is not support in ukernel, add check for it.
```
ONEDNN_VERBOSE=1,filter=graph ./tests/benchdnn/benchdnn --graph --engine=gpu --case=/home/gta/xiangguo/oneDNN/build/graph-100001.json
onednn_verbose,v1,graph,info,pattern,load,dnnl_graph_passes.json
onednn_verbose,v1,info,oneDNN v3.10.0 (commit 8393842cd4f3ae3b75c6e63a4e82fddad0ea4f40)
onednn_verbose,v1,info,cpu,runtime:OpenMP,nthr:224
onednn_verbose,v1,info,cpu,isa:Intel AVX-512 with float16, Intel DL Boost and bfloat16 support 
onednn_verbose,v1,info,gpu,runtime:DPC++
onednn_verbose,v1,info,gpu,engine,sycl gpu device count:8 
onednn_verbose,v1,info,gpu,engine,0,backend:Level Zero,name:Intel(R) Data Center GPU Max 1550,driver_version:1.6.33276,binary_kernels:enabled
onednn_verbose,v1,info,gpu,engine,1,backend:Level …
```
> graph: backend: dnnl: fix ukernel check for int8 sdpa

- src/cpu/x64/brgemm/jit_brdgmm_kernel.hpp
Fix brgdmm convolutions segfault on DMR and NVL in Nightly testing
> x64: brdgmm kernel: fix reg_aux1_A and reg_aux1_B for saving

- src/gpu/intel/gemm/jit/generator/pieces/copy_plan.cpp
- src/gpu/intel/jit/codegen/reorder.cpp
- src/gpu/intel/jit/codegen/reorder.hpp
Addresses [MFDNN-14083](https://jira.devtools.intel.com/browse/MFDNN-14083).
1. Breaks up reorders if registers are otherwise exhausted (may help with reorder failures in #3727 CI +@petercad)
2. Maintains overlaps when compacting input layouts for temporary buffers, leading to less register pressure.
3. Changed `CopyPlan::optimizeConcatenate` to measure overlap in terms of elements instead of elements*stride so operands can have different strides.
> [GPU] copy plan IR reorder fixups

- src/common/convolution.cpp
- src/common/deconvolution.cpp
- src/gpu/generic/sycl/ref_convolution.hpp
- src/gpu/intel/conv/jit/config.cpp
- src/gpu/intel/conv/jit_v2.cpp
- src/gpu/intel/conv/ref.cl
- src/gpu/intel/matmul/ref.cl
- src/gpu/intel/matmul/ref.hpp
- src/gpu/intel/primitive_conf.cpp
- src/gpu/intel/primitive_conf.hpp
- tests/benchdnn/dnn_types.cpp
- tests/benchdnn/inputs/conv/option_gpu_ci
- tests/benchdnn/inputs/conv/test_conv_ci
- tests/benchdnn/inputs/deconv/test_deconv_ci
Continuation of [MFDNN-13410](https://jira.devtools.intel.com/browse/MFDNN-13410) effort.
**Summary:**
- Extended OCL (de)conv impl to support host-side scalars scales and zps
- Moved "generic" check for unsupported combinations to other impls
- Added new macros for HOST_SCALE and HOST_ZP
- In benchdnn, set mask to 0 with HOST_SCALAR policy as this is a default property for host-side scalar memory and conv pre-processing relies on mask value
- Rebased matmul to new macros
> host-side scalar scales and zps support for (de)conv ref ocl

- src/cpu/aarch64/jit_uni_dw_conv_kernel_utils.hpp
- tests/benchdnn/inputs/conv/harness_conv_regression_general
This  fixes Conv dw (BF16) with Bias-dt=BF16. Bug introduced as part of this PR: https://github.com/uxlfoundation/oneDNN/pull/3441
I've added a fix and added unit testcases.
The failure was reported by unit test fails in this PR: https://github.com/pytorch/pytorch/pull/157994 
Example test : 
```
./benchdnn --conv --dt=bf16 --dir=FWD_I --bia-dt=bf16  g4mb2_ic4oc4_ih6oh4kh3sh1dh0ph0_iw6ow4kw3sw1dw0pw0
```
> cpu: aarch64: fix scratchpad memory initialization

- src/gpu/intel/sdpa/configs.cpp
- src/gpu/intel/sdpa/micro.cpp
- tests/gtests/internals/test_sdpa.cpp
Refactor GTest internal tests to use the combine generator to generate test cases. Update a couple of broken configs for f32 with head size of 128.
> xe: sdpa: Refactor internal tests for SDPA

- src/cpu/aarch64/acl_post_ops.cpp
- src/cpu/aarch64/acl_post_ops.hpp
The class `acl_post_ops_t`, commonly used by ACL operations, supports element-wise operations that have an ACL implementation only (e.g. ACL `inner_product` + ACL `gelu_erf`). This PR extends the class to handling arbitrary element-wise post-ops, e.g. an ACL `inner_product` followed by a JIT activation. 
**Command:**
```bash
>>> ONEDNN_VERBOSE=all ./tests/benchdnn/benchdnn --mode=R --ip --attr-post-ops=eltwise_swish --dt=f32 mb1ic256oc256
```
**Output before change:**
`inner_product` falls back to `gemm:ref` to support JIT `eltwise_swish`.
```bash
onednn_verbose,v1,info,oneDNN v3.10.0 (commit ffa3f03e1a5ecc648741ca37de69f4ad9aafc3ad)
onednn_verbose,v1,info,cpu,runtime:OpenMP,nthr:48
onednn_verbose,v1,info,cpu,isa:AArch64 SVE (256 bits)
onednn_verbose,v1,info,gpu,runtime:none …
```
> cpu: aarch64: support arbitrary eltwise post-ops in acl_post_ops_t

- src/gpu/intel/conv/ref.cl
- src/gpu/intel/gemm/with_post_ops.cl
- src/gpu/intel/include/io.h
Fixes OCL build errors from [MFDNN-14125](https://jira.devtools.intel.com/projects/MFDNN/issues/MFDNN-14125).
> xe: fix fp4 load/write handling in ocl_io.h

- src/cpu/aarch64/matmul/jit_int8_kernel_types.hpp
- src/cpu/aarch64/matmul/jit_int8_matmul.cpp
Previously JIT INT8 matmul supported the tags:
- s8:s8:f32(src in s8, wei in s8, dst in f32)
- u8:u8:f32(src in u8, wei in u8, dst in f32)
This PR
- Adds support for tag u8:s8:f32(src in u8, wei in s8, dst in f32).
- Corrects the loading of weights zero-points when there is a buffer instead of a single value.
```
make test
99% tests passed, 1 tests failed out of 226
Total Test time (real) = 1020.21 sec
206 - test_benchdnn_modeC_graph_ci_cpu (Failed)
Output from these tests are in: /home/shreyas/G/shr-fuj/oneDNN_open_source/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
make: *** [Makefile:71: test] Error 8
```
- [y] Do all unit and benchdnn tests (`make test` and …
> aarch64: matmul: Added u8_s8_f32 support for jit int8 matmul

- src/cpu/matmul/cpu_matmul_list.cpp
- src/cpu/rv64/rvv_matmul.cpp
- src/cpu/rv64/rvv_matmul.hpp
- src/cpu/rv64/rvv_postops.hpp
This PR introduces an optimized MatMul (Matrix Multiplication) kernel for RISC-V. The implementation provides significant performance improvements for GEMM (General Matrix-Matrix Multiplication) operations by utilizing RVV intrinsics.
This initial version lays the groundwork for RVV acceleration in MatMul, focusing on common use cases while establishing a framework for future extensions.
* **RVV-Optimized Kernels**: Added `rvv_matmul_rowmajor` and `rvv_matmul_colmajor` kernels to handle different weight memory layouts efficiently.
* **FP32 Data Type Support**: The implementation is specialized for `f32` data type operations.
* **Bias and ReLU Support**: Integrates support for bias addition and fused ReLU post-operation, handled via the `rvv_postops` handler.
* **Layout-Specific …
> cpu: riscv: matmul: add RVV row/col kernels with bias, ReLU post-op

- src/common/softmax.cpp
- src/cpu/ref_softmax.hpp
- src/cpu/x64/jit_uni_softmax.cpp
- src/cpu/x64/jit_uni_softmax.hpp
- src/gpu/intel/softmax/simple.hpp
- tests/benchdnn/inputs/softmax/test_softmax_ci
This is a requirement for fp8 SDPA built under Graph API.
> softmax: add dst fp8 support

- src/gpu/intel/sdpa/configs.cpp
- src/gpu/intel/sdpa/micro.cl
- src/gpu/intel/sdpa/micro.cpp
- src/gpu/intel/sdpa/micro.hpp
This PR addresses a minor performance regression when handling remainder cases for the number of queries. The parameter has been restored to compile time. This shouldn't significantly increase recompilations since the transition from first to second token usually involves a config change anyways. Runtime branching logic causes a slowdown for both remainder/non-remainder cases.
Before:
```
Output template: perf,%engine%,%prb%,%-time%,%0time%
--mode=P --graph --engine=gpu --memory-kind=usm_device --cold-cache=all --dt=0:s8+1:f16+2:s8+3:f16+4:f16+6:s8+7:f16+8:s8+27:f16+50:f16 --in-shapes=0:2x10x64x77*abcd+1:2x10x1x77+2:2x10x1x77+3:2x10x1024x64*abcd+6:2x10x77x64*abcd+7:2x10x77x1+8:2x10x77x1 --op-attrs=100:group_shape:1x1x64x1+600:group_shape:1x1x1x64 --attr-fpmath=f16:true …
```
> xe: sdpa: revert remainder_q to compile time

- tests/gtests/graph/unit/backend/dnnl/CMakeLists.txt
- tests/gtests/graph/unit/backend/dnnl/test_sdp_decomp.cpp
As the title. Found in MFDNN-14122.
> gtest: graph: unit: limit sdpa decompose kernel test runtime and times

- src/cpu/x64/jit_brgemm_conv_utils.cpp
- tests/benchdnn/inputs/conv/harness_conv_regression_general
backport of https://github.com/uxlfoundation/oneDNN/pull/3854
> x64: fix brgconv k tail (backport)

- src/cpu/x64/jit_uni_pool_kernel.cpp
backport of https://github.com/uxlfoundation/oneDNN/pull/3876
> x64: pool: fix illegal instruction

- tests/gtests/graph/unit/backend/dnnl/CMakeLists.txt
- tests/gtests/graph/unit/backend/dnnl/test_sdp_decomp.cpp
> [Backport] [Graph] gtest: graph: unit: limit sdpa decompose kernel test runtime and times

- src/gpu/intel/gemm/jit_xe_hp_systolic.cpp
- src/gpu/intel/softmax/simple.hpp
This PR is adding checks to avoid failures for double blocked format for softmax/mamtul. Since Matmul gives input to softmax layers when used in larger context and we don't have any particular tests in benchdnn for this, we will just return unimplemented for such cases from init prim to avoid the false illusion. 
This is to avoid cases like: [MFDNN-13673](https://jira.devtools.intel.com/browse/MFDNN-13673)
> [GPU] Checks for double blocked format softmax/matmul

- .github/automation/aarch64/ci.json
The current perf failures we see in nightly are due to a deliberate change where we changed f16:f16:f16 accumulation from f16 to f32. Updating the baseline should get rid of this false positive
> ci: aarch64: upgrade baseline version to v3.9

- .github/automation/aarch64/ci.json
- README.md
- cmake/ACL.cmake
- src/cpu/aarch64/acl_inner_product.cpp
- src/cpu/aarch64/acl_inner_product.hpp
Enable stateless inner product ACL operator.
**Note: This is blocked on the pending ACL release.**
We have demonstrated approximate equivalence.
`./benchdnn  --ip --mode=P --batch=./inputs/ip/test_ip_acl`
  | Stateless | Stateless | Original / stateful | Original / stateful
-- | -- | -- | -- | --
#Threads | min (ms) | avg (ms) | min (ms) | avg (ms)
  | 143.575 | 147.564 | 143.291 | 148.028
1 | 1424.93 | 1437.58 | 1414.54 | 1420.89
4 | 455.091 | 461.349 | 455.923 | 462.691
8 | 257.072 | 262.212 | 255.249 | 260.269
16 | 144.153 | 148.067 | 143.126 | 147.343
> cpu: aarch64: Enable stateless ACL inner product/fully connected.

- src/cpu/x64/brgemm/brgemm.cpp
- src/cpu/x64/brgemm/brgemm_utils.cpp
[MFDNN-13836](https://jira.devtools.intel.com/browse/MFDNN-13836)
This addresses the issue that some data type combinations crash or produce incorrect results instead of returning unimplemented.
sde -gnr -- ./benchdnn --brgemm --dt=bf16:bf16:f8_e4m3 32x32:32x32
sde -gnr -- ./benchdnn --brgemm --dt=bf16:bf16:f8_e5m2 32x32:32x3
Crashed because the float8 output type is not supported.
brgemm.cpp already contained the logic to handle this case for the f16 data type.
The same logic for f16 was used for the bf16 input data type.
**Additionally** bf16 was add to the list of supported dest data types for the f16 case.
sde -gnr -- ./benchdnn --brgemm --dt=f16:bf16:f32 32x32:32x32
The brgemm_utils.cpp is updated to identify mixed f16, bf16 inputs and correctly not set the is_f16 flag.
Behavior of …
> cpu: x64: brgemm: fix data type check

- tests/benchdnn/graph/ref_partition.cpp
skip all failing cases after correctness check on NV platforms
> tests: benchdnn: graph: skip cases with correctness issue on NV GPU

- src/graph/backend/dnnl/dnnl_backend.cpp
- src/graph/backend/dnnl/patterns/binary_matmul_binary.cpp
- src/graph/backend/dnnl/patterns/fusions.hpp
- src/graph/backend/dnnl/patterns/pattern_matcher_pass.hpp
- tests/benchdnn/inputs/graph/complex_fusion/bmb/binary-matmul-binary-bf16.json
- tests/benchdnn/inputs/graph/complex_fusion/bmb/binary-matmul-binary-f32.json
- tests/benchdnn/inputs/graph/complex_fusion/harness_bmb_all
- tests/benchdnn/inputs/graph/complex_fusion/harness_bmb_ci
- tests/benchdnn/inputs/graph/test_graph_ci
- tests/benchdnn/inputs/graph/test_graph_fusions
- tests/benchdnn/inputs/graph/test_graph_fusions_gpu
Fix MFDNN-14020
- Extended the number of post-ops to 20.
- Added a new special pattern with binary ops chain + matmul + binary ops chain. Currently implemented through binary primitive and matmul primitive.
- Added corresponding test cases.
> graph: backend: dnnl: binary chain + matmul + binary chain pattern

- src/common/primitive_hashing.cpp
- src/common/primitive_serialization.cpp
- src/common/sdpa_pd.hpp
- src/common/sdpa_test_iface.cpp
- src/common/sdpa_types.hpp
- src/common/sdpa_utils.hpp
- src/common/type_helpers.hpp
- src/common/verbose.cpp
- src/gpu/intel/include/math_utils.h
- src/gpu/intel/sdpa/micro.cl
- src/gpu/intel/sdpa/micro.cpp
- src/gpu/intel/sdpa/micro.hpp
- src/gpu/intel/sdpa/ref.hpp
- src/graph/backend/dnnl/op_executable.hpp
- tests/gtests/internals/sdpa_internal.hpp
- tests/gtests/internals/test_sdpa.cpp
PR implements host-side (and device-side) scalar support in SDPA primitive.
Addresses https://jira.devtools.intel.com/browse/MFDNN-13611 
based on https://github.com/uxlfoundation/oneDNN/pull/3506
> [GPU] Add host side scalars support in SDPA primitive

- tests/benchdnn/dnnl_common.hpp
When mode-modifier=P is specified, it changes the scratchpad mode to user, and automatically converts the scratchpad memory object into real opposed to library when it'll be allocated inside the library.
Fixes [MFDNN-14161](https://jira.devtools.intel.com/browse/MFDNN-14161)
> benchdnn: manually unmap scratchpad memory object

- src/gpu/intel/gemm/jit/pd.cpp
- src/gpu/intel/gemm/ref.cl
- src/gpu/intel/gemm/ref.hpp
- src/gpu/intel/gemm/with_post_ops.cpp
- src/gpu/intel/matmul/gemm.hpp
... also disallow gemm w post ops impl and jit impls
continuation of [MFDNN-14148](https://jira.devtools.intel.com/browse/MFDNN-14148)
optimized impls would be covered in [MFDNN-14149](https://jira.devtools.intel.com/browse/MFDNN-14149)
> gpu: intel: extend ref ocl gemm to support host zero points

- src/cpu/aarch64/acl_post_ops.cpp
- src/cpu/aarch64/acl_post_ops.hpp
This reverts commit 0abc32b19a9d7f48f3f76b097798a0ae7e968ffb.
Reverts #3767
Causes a segfault in lowp matmul:
```sh
$ ONEDNN_VERBOSE=profile_exec ./build/tests/benchdnn/benchdnn --graph --mode=R --in-shapes=0:16x256+1:256x1+2:1x1 --case=pattern/int8/int8_matmul_logistic_fusion.json
onednn_verbose,v1,info,oneDNN v3.10.0 (commit 216a37ebdc4efea56b2d8ca598980aa12bc8539e)
onednn_verbose,v1,info,cpu,runtime:OpenMP,nthr:1
onednn_verbose,v1,info,cpu,isa:AArch64 SVE (256 bits)
onednn_verbose,v1,info,gpu,runtime:none
onednn_verbose,v1,info,graph,backend,0:dnnl_backend
onednn_verbose,v1,primitive,info,template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
onednn_verbose,v1,graph,info,template:operation,engine,partition_id,partition …
```
> revert: cpu: aarch64: "support arbitrary eltwise post-ops..." 

- src/gpu/intel/gemm/jit/gen_kernel.cpp
Some strategies use `variable` beta strategies: 
```
onednn_verbose,v1,info,gpu,gemm,catalog entry:E gemm SSS TNN 16 4 aB4x2 aB4x2 aB wg 2x8x4 kr kc4 cab4 ks8 nse bo bk0 sm sn kb sr dm
onednn_verbose,v1,info,gpu,gemm,kernel:gemm SSS TNN 16 4 1 - aB4x2{cc} aB4x2{cc} aB{cc/bb} cab4 ks8 wg 2x8x4 kr kc4 k32 sm sn nse di dm sr kb fm np bm16777216 bn16777216 bk16777216
```
This commit allows `-` to be provided as a policy to `GEMM_KERNEL` during debug.
> [GPU] GEMM: Enable `-` alpha/beta policy in debug

- src/cpu/aarch64/jit_sve_1x1_convolution.cpp
- src/cpu/aarch64/jit_sve_convolution.cpp
Fixes all failures of the "modernize-use-nullptr" clang-tidy check on the AArch64 path.
> cpu: aarch64: fix modernize-use-nullptr clang-tidy failures

- src/cpu/x64/jit_uni_ncsp_convolution.hpp
- tests/benchdnn/benchdnn.cpp
- tests/benchdnn/common.cpp
- tests/benchdnn/common.hpp
- tests/benchdnn/doc/knob_summary.md
- tests/benchdnn/utils/parser.cpp
- tests/benchdnn/utils/summary.cpp
- tests/benchdnn/utils/summary.hpp
A new summary option providing the statistics of implementations used over the selected batch, enabled by default.
Designed to help to validate dispatching (that a new version doesn't make optimized version called less times than it should).
It's also helpful to understand the status quo in automated validation.
Feature preview:
> benchdnn: introduce implementation summary option support

- src/cpu/x64/brgemm/jit_brdgmm_kernel.cpp
- src/cpu/x64/brgemm/jit_brdgmm_kernel.hpp
- src/cpu/x64/brgemm/jit_brgemm_kernel.cpp
- src/cpu/x64/injectors/injector_utils.cpp
- src/cpu/x64/injectors/injector_utils.hpp
Update to use reg_savable_t in brgemm kernels to optimize GPR save/restore operations
> x64: brgemm kernels: APX registers update

- src/cpu/aarch64/jit_uni_reorder.cpp
Enables vector loads for AArch64 jit:uni reorder when inner blocking size differs from reg_unroll parameter. This enables for example reorder fp32 ba -> bf16 BA8b4a to use ldr(QReg…) instead of ld1(vX.s[0]…). 
Example code snippet generated for each load before this patch:
8c:	0d4082e0 	ld1	{v0.s}[0], [x23]
90:	0d409300 	ld1	{v0.s}[1], [x24]
94:	4d408320 	ld1	{v0.s}[2], [x25]
98:	4d409340 	ld1	{v0.s}[3], [x26]
And after:
88:	3dc002e0 	ldr	q0, [x23]
**Performance improvement:**
Command: `benchdnn --reorder --allow-enum-tags-only=0 --sdt=f32 --ddt=bf16 --stag=ba --dtag=BA8b4a --mode=p 4096x4096`
OMP_NUM_THREADS=1 is ~4.1x faster and OMP_NUM_THREADS=16 is ~1.7x faster after patch.
ctest:
Only `191 - test_benchdnn_modeC_matmul_multidims_cpu` fails before and after patch.
benchdnn --reorder …
> cpu: aarch64: Extend vector loads for AArch64 jit:uni reorder

- src/common/memory_tracking.hpp
- src/cpu/aarch64/acl_pooling.cpp
- src/cpu/aarch64/acl_pooling.hpp
Make pooling use stateless pooling op from ACL.
```
./tests/benchdnn/benchdnn --pool --mode=P --dt=f16:f16 --tag=axb --alg=avg_np ic64ih56oh56kh3ph1
stateful:
OMP_NUM_THREADS=4
total perf: min(ms):0.301025 avg(ms):0.318544
OMP_NUM_THREADS=16
total perf: min(ms):0.121338 avg(ms):0.131665
stateless:
OMP_NUM_THREADS=4
total perf: min(ms):0.304443 avg(ms):0.320418
OMP_NUM_THREADS=16
total perf: min(ms):0.123047 avg(ms):0.133939
```
> cpu: aarch64: modify acl_pooling for stateless functions

- examples/gpu_opencl_interop.cpp
- examples/graph/gpu_opencl_getting_started.cpp
We have a couple examples that unlike others fail when GPU is not found. This changes aligns the behavior.
Fixes #1961.
> examples: added missing GPU engine check to OpenCL examples

- cmake/platform.cmake
In [MFDNN-14221](https://jira.devtools.intel.com/browse/MFDNN-14221), we caught a vector OOB access with the MSVC debug C++ library. This PR enables similar checks for Debug and ONEDNN_DEV_MODE builds on Linux to improved cross-platform debugging.
As an example for the aforementioned bug caught by this:
```Bash
$  ctest -R gpu-cnn-inference-f32-cpp --output-on-failure
Test project /nfs/pdx/home/rjoursle/dnnl/build
Start 6: gpu-cnn-inference-f32-cpp
1/1 Test #6: gpu-cnn-inference-f32-cpp ........Subprocess aborted***Exception:   1.60 sec
/usr/include/c++/13/bits/stl_vector.h:1128: constexpr std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = long int; _Alloc = std::allocator<long int>; reference = long int&; size_type = long unsigned int]: …
```
> cmake: enable stdlib debug mode for debug builds

- examples/graph/gqa.cpp
- src/graph/backend/dnnl/kernels/sdp_decomp.cpp
- src/graph/backend/dnnl/kernels/sdp_primitive.cpp
- src/graph/backend/dnnl/passes/transform.cpp
- src/graph/backend/dnnl/subgraph.cpp
- src/graph/interface/logical_tensor.cpp
- src/graph/interface/tensor.cpp
- src/graph/interface/tensor.hpp
- tests/gtests/graph/api/test_cpp_api_logical_tensor.cpp
- Support f32 host scalar in logical tensor and tensor. Previously only s32 was supported and used to pass sequence length.
- Updated the existing GQA example to define attention scale as a host scalar.
> graph: support f32 host scalar and use it in the gqa example

- src/cpu/aarch64/jit_uni_pool_kernel.cpp
This change fixes a condition inside jit_uni_pool_kernel::post_ops_ok which disables binary post-ops with BF16 or F16 data-types. This was highlighted after running clang-tidy with the `misc-redundant-expression` check.
> cpu: aarch64: fix erroneous binary operation post_op comparison

- src/cpu/aarch64/matmul/acl_lowp_matmul.cpp
- src/cpu/aarch64/matmul/acl_lowp_matmul_sq.cpp
- src/cpu/aarch64/matmul/acl_matmul_utils.cpp
clang-tidy fixes for readability-container-size-empty warning
> cpu: aarch64: fix readability-container-size-empty

- src/cpu/x64/brgemm/jit_brdgmm_kernel.cpp
brdgmm kernel: request temporal register only if needed. In brdgmm initialization in `vmm_allocator_helper_t` we reserve temporal registers only for certain conditions. So we must use these registers only under these conditions.
This is a fix for [MFDNN-14146](https://jira.devtools.intel.com/browse/MFDNN-14146)
> x64: brdgmm kernel: fix temporal registers usage

- .github/automation/aarch64/skipped-tests.sh
- src/cpu/gemm_x8s8s32x_convolution.cpp
- src/cpu/gemm_x8s8s32x_convolution_utils.cpp
- src/cpu/gemm_x8s8s32x_convolution_utils.hpp
Fixed an issue where minibatch was not used when calculating the offset
used by the `ref_post_ops kernel` for binary post-ops.
Also added a check for supported post-op `POLICY`/`MASK` values in
`gemm_x8s8s32x_convolution_utils::post_ops_ok()`
Fixes: #3803
> cpu: gemm_x8s8s32x_conv: fix post_op application

- src/cpu/aarch64/jit_uni_batch_normalization.cpp
In this one-line if statement only the first line of the `LDR_ASSERT` macro would be conditionally handled & not the second.
This fix ensures that upon macro expansion the second line is also only ran if use_global_stats() is false by encapsulating `LDR_ASSERT` in `do { ... } while(0)` (and similarly with `STR_ASSERT` to prevent a similar bug from occurring).
This was flagged after running clang-tidy with the bugprone-multiple-statement-macro check.
> cpu: aarch64: ensure LDR_ASSERT and STR_ASSERT are expanded fully

- src/cpu/gemm/gemm.cpp
- src/cpu/rv64/gemm/rvv_gemm_f32.cpp
- src/cpu/rv64/gemm/rvv_gemm_f32.hpp
- src/cpu/rv64/gemm/rvv_gemm_utils_f32.cpp
- src/cpu/rv64/gemm/rvv_gemm_utils_f32.hpp
This PR introduces a SIMD-optimized f32 GEMM kernel for the RISC-V 64-bit architecture, leveraging the RISC-V Vector (V) Extension.
The existing generic GEMM implementation in oneDNN (`ref_gemm`) relies on `PRAGMA_OMP_SIMD` for auto-vectorization. However, current RISC-V toolchains do not effectively vectorize this code, leading to suboptimal performance on RV64 platforms. This commit addresses this critical performance gap by providing a manually optimized SIMD implementation, `rvv_gemm_f32`, which is dispatched from `extended_sgemm`.
This optimization is integrated directly into the low-level `extended_sgemm` function. This provides two major benefits:
1.  It accelerates direct `sgemm` calls across the library.
2.  It boosts the performance of high-level primitives that rely on this …
> cpu: riscv: gemm: add f32 gemm SIMD optimization with RISC-V V Extension

- src/cpu/x64/jit_gemm_x8s8s32x_convolution_utils.cpp
Fixes virtual `jit_pp_ker_t::operator()` interface (the main one was updated in #3942).
> cpu: x64: fix virtual interface

- cmake/host_compiler.cmake
This PR removes outdated workaround for oneDNN SYCL build with `ONEDNN_DPCPP_HOST_COMPILER` option.
Underlying issue was fixed in Intel DPC++/C++ Compiler 2025.0.
> Restored deprecated declarations warning for oneAPI DPC++/C++ Compiler 2025.3 and newer

- src/cpu/x64/brgemm/brgemm.cpp
- src/cpu/x64/brgemm/brgemm_types.hpp
- src/cpu/x64/brgemm/brgemm_utils.cpp
- src/cpu/x64/brgemm/jit_brgemm_amx_uker.cpp
- src/cpu/x64/matmul/amx_blocking_heuristics.cpp
- src/cpu/x64/matmul/amx_blocking_heuristics.hpp
- src/cpu/x64/matmul/brgemm_matmul.cpp
- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
- src/cpu/x64/matmul/brgemm_matmul_utils.hpp
When the K dimension is not aligned to the cache line, loading matrix A can degrade the performance of highly optimized BRGEMMs by up to 2×. To prevent this, matrix A is copied to an aligned buffer on the fly, ensuring proper cache line alignment. This avoids misaligned memory accesses and reduces L1 bandwidth usage, resulting in improved overall performance.
> x64: cpu: matmul: Fuse copy of A in cases of unaligned K dimension

- src/cpu/cpu_pooling_list.cpp
- src/cpu/rv64/rvv_nchw_pooling.cpp
- src/cpu/rv64/rvv_nchw_pooling.hpp
This PR fixes the templatization issue by:
- Removing template arguments
- Adding data type checking for proper dispatching
All other features remain unchanged.
We test the changes using the RISC-V GNU toolchain(14.2) and verify the functionality under the QEMU RISCV64 emulator with cmd:
```
ONEDNN_VERBOSE=1 ./benchdnn --pool --dt=f32 --dir=FWD_I --batch=inputs/pool/set_all
```
All tests passed with proper dispatching confirmed. Calls to the implemented `rvv_nchw_pooling` can be traced by searching for `RISCV64GCV` in:
- [test_pool_ci_rvv.log](https://github.com/user-attachments/files/22354164/test_pool_ci_rvv.log)
- [N/A] Have you included information on how to …
> cpu: rv64: nchw_pooling: fix: de-templatization

- tests/benchdnn/dnnl_common.cpp
- tests/benchdnn/dnnl_common.hpp
- tests/benchdnn/eltwise/eltwise.cpp
- tests/benchdnn/eltwise/ref_eltwise.cpp
#3888 didn't help since after execution scratchpad gets mapped back and new compare memory could still trigger a check error.
So this PR reverts that PR and just counts scratchpad towards mapped memory with a note that it can be reverted if/when lazy mapping is implemented for benchdnn memories.
A valid warning popped in eltwise driver where an excessive memory was kept. This was adjusted though a trick, and also extra reorder on backward path was removed.
Fixes [MFDNN-14232](https://jira.devtools.intel.com/browse/MFDNN-14232)
> benchdnn: fix mem check (yet another time)

- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
Fixes MFDNN-14252.
This PR disables the GEMV code path when reduction is requested. Reduction is used to calculate bias gradients in matmul-IP (BWD_WB). It can be enabled later for GEMV cases if needed.
> cpu: x64: disable src reduction for gemv

- src/cpu/x64/jit_avx512_core_x8s8s32x_conv_kernel.hpp
Fixes [MFDNN-14253](https://jira.devtools.intel.com/browse/MFDNN-14253).
Collapsed with vmm_bias which gets filled out of the loop.
> fixup: cpu: x64: avx512_core_int8_conv: handle scales inside the kernel

- tests/benchdnn/conv/ref_conv.cpp
- tests/benchdnn/eltwise/eltwise.cpp
- tests/benchdnn/inputs/gnorm/shapes_ci
- tests/benchdnn/inputs/gnorm/test_gnorm_smoke
Fixup for #4016, forgot about graph driver.
Since the implementation cost to pass a work around is huge, just restored the previous state for graph exclusively.
[MFDNN-14195](https://jira.devtools.intel.com/browse/MFDNN-14195)
[MFDNN-14261](https://jira.devtools.intel.com/browse/MFDNN-14261)
[MFDNN-14267](https://jira.devtools.intel.com/browse/MFDNN-14267)
> fixup: benchdnn: eltwise: clean up excessive memory objects

- src/gpu/intel/gemm/host_scalars.cpp
- src/gpu/intel/gemm/host_scalars.hpp
- src/gpu/intel/gemm/jit.cpp
- src/gpu/intel/gemm/jit/pd.cpp
- src/gpu/intel/gemm/jit/pd.hpp
PR addresses https://jira.devtools.intel.com/browse/MFDNN-14149.
Provided with limited (below) support of host side scalars for only scales attribute (zero points are still not supported yet). This feature is implemented via Alpha parameter what seemed to be the fastest way to give a chance frameworks to try it in the nearest release. Hopefully this way will be reworked later in order to find more standard method also applicable to convolution.
Limitation: host scalar dst scales are supported in jit gemm if there are no postops.
> [GPU] jit: gemm: limited support of host scalar scales implemented via Alpha

- src/common/memory_tracking.cpp
- src/common/memory_tracking.hpp
- src/common/primitive.cpp
- src/common/primitive_exec_types.cpp
- src/common/primitive_exec_types.hpp
- src/common/primitive_iface.cpp
This PR removes grantor dependency on exec_ctx which appeared with adding CPU SYCL support. There are a bunch of comments explaining dependencies and purposes.
`exec_ctx_t` must be removed from the grantor to unblock PImpl implementation that will be introduced for `exec_ctx_t` to support Async runtime, otherwise, there'll be double capture of the same context leading to a memory leak.
> common: remove exec_ctx member from grantor

- src/gpu/intel/gemm/jit/pd.cpp
Cases with host scalars can result in common scales to hit dim count, added handling to avoid invalid loop bounds.
> [GPU][GEMM] Avoid ub in quant attr 

- src/gpu/intel/gemm/jit/generator/pieces/copy_plan.cpp
- src/gpu/intel/gemm/jit/pd.cpp
Backport 4-bit reorder handling from upstream, replace `(i4-i4)->copythrough(w)->upconvert->downconvert`  conversion steps with `(i4-i4)->upconvert->downconvert`. 
Adds a shorter path for reorders that start from at least byte-strided int4 values.
> xe: gemm: copy_plan: backport int4 special case

- .github/automation/aarch64/test.sh
- .github/automation/aarch64/wiki_utils.py
- .github/workflows/ci-aarch64.yml
- .github/workflows/nightly-aarch64.yml
- add a fix for the git bisect conflicting with the wiki causing the wiki update to fail
- add a fix for git bisect picking up on non-failing tests due to output truncation
- fix edge case where success status hash was being updated when one of the ci matrices succeeded
> ci: aarch64: Fix git bisect false positives and wiki failure

- .github/automation/clang-format.sh
- .github/workflows/pr-linter.yml
Avoids checking the entire repository every time a change is made. The old behavior is still preserved for anyone relying on it but I have made it faster by using `find -exec` rather than a `for` loop.
> ci: only run clang-format on changed files

- src/cpu/aarch64/jit_uni_dw_convolution.cpp
kh_t_padding = max(0, t_pad - oh) which is only correct for stride_h == 1. For stride_h > 1 the window origin
is at input row `oh_inp = oh * stride_h`.
Fixes: #4074
> cpu: aarch64: top padding stride inclusion, jit 256 depthwise bw kernel
