include/mkldnn.hpp

Signed-off-by: caozhong <zhong.z.cao@intel.com>

Add engine query in C++ interface

---

README.md

mklml_gnu and mklml_intel updates

---

include/mkldnn.hpp
include/mkldnn_types.h
src/common/c_types_map.hpp
src/common/memory.cpp
src/common/memory_desc_wrapper.cpp
src/common/memory_desc_wrapper.hpp
src/common/mkldnn_debug.cpp

More updates for tensorflow integration
- api: add dhwio data layout
- fix fwd pooling: initialize src format

Add dhwio data layout

---

README.md

Preferred Networks recently released [Menoh](https://github.com/pfnet-research/menoh), an inference engine for running ONNX model using MKL-DNN.
Add a link to Menoh.

Add Menoh to the list of applications using MKL-DNN

---

src/cpu/ref_softmax.cpp

This PR is replacing sum computation with cblas::sasum (for MKL builds) or with omp simd reduction(+:) for non-MKL builds of MKL-DNN.
**_Performance impact:_**
PaddlePaddle/OCR (test_analyzer_ocr)  softmax operator works **~9%** faster with proposed changes in  MKL-DNN
_**Notes:**_
- Assembly code generated during MKL-DNN builds was inspected before and after adding vectorization pragmas and compiler took adventage of pragma to have summing vectorized.
- Softmax Unit tests of MKL-DNN are successfully passing for both MKL and no-MKL builds of MKL-DNN

Optimization to softmax forward with MKL ASUM and omp simd reduction

---

README.md

MKL-DNN is shipped with PyTorch.

Add PyTorch as a user

---

src/cpu/jit_uni_i8i8_pooling.cpp

Fix for u8/s8 pooling
Tested on 
> --pool
> --cfg=u8,s8 
> --alg=AVG_P,AVG_NP 
> --dir=FWD_I 
> --tag=nhwc
> ic35ih20iw30oh17ow14kh4kw3sh1sw2
> ic35ih19iw30oh17ow14kh4kw3sh1sw2ph1pw0
> ic35ih20iw33oh17ow14kh4kw6sh1sw2
> ic35ih19iw33oh17ow14kh4kw6sh1sw2ph1pw0
> ic35ih37iw16oh17ow14kh4kw3sh2sw1
> ic35ih36iw16oh17ow14kh4kw3sh2sw1ph1pw0
> ic35ih37iw19oh17ow14kh4kw6sh2sw1
> ic35ih36iw19oh17ow14kh4kw6sh2sw1ph1pw0
> ic35ih37iw30oh17ow14kh4kw3sh2sw2
> ic35ih36iw30oh17ow14kh4kw3sh2sw2ph1pw0
> ic35ih37iw33oh17ow14kh4kw6sh2sw2
> ic35ih36iw33oh17ow14kh4kw6sh2sw2ph1pw0
> ic35ih20iw42oh17ow14kh4kw3sh1sw3
> ic35ih20iw41oh17ow14kh4kw3sh1sw3
> ic35ih20iw45oh17ow14kh4kw6sh1sw3
> ic35ih20iw44oh17ow14kh4kw6sh1sw3
> ic35ih52iw16oh17ow14kh4kw3sh3sw1
> ic35ih51iw16oh17ow14kh4kw3sh3sw1
> …

src: cpu: jit i8 pooling: avx2: fix dst store mask for i8 average

---

examples/cpu_rnn_inference_f32.cpp
examples/cpu_rnn_inference_int8.cpp

The rnn examples are pretty quiet just outputting "ok". That change just logs some variables and the exec time.

Add some logs to the rnn examples

---

rfcs/20200428-openvino-int8-support/README.md

Here is a [link to the rendered document](https://github.com/igorsafo/oneDNN/tree/rfcs/rfcs/20200428-openvino-int8-support).

rfc: openvino int8 pipeline support

---

README.md

Adding SINGA to the applications. See [release notes ](http://singa.apache.org/docs/download-singa/#v300-18-april-2020)for more information about the use of DNN in SINGA.

add Apache SINGA to applications

---

rfcs/20200710-reduction/README.md

[Rendered version](https://github.com/igorsafo/oneDNN/blob/rfcs/rfcs/20200710-reduction/README.md)

rfc: reduction primitive

---

rfcs/20200812-multidim-matmul/README.md

Link to [rendered doc](https://github.com/oneapi-src/oneDNN/tree/nivas/multidim-matmul/rfcs/20200812-multidim-matmul)

rfc: multidim matmul

---

README.md

[minor] Fix typo in README.md

---

src/common/memory_debug.cpp
src/common/utils.cpp

Patches needed to compile on FreeBSD.

---

src/cpu/aarch64/acl_convolution_utils.cpp
src/cpu/aarch64/acl_convolution_utils.hpp
src/cpu/aarch64/acl_winograd_convolution.cpp
src/cpu/aarch64/acl_winograd_convolution.hpp
src/cpu/cpu_convolution_list.cpp
tests/gtests/test_iface_wino_convolution.cpp

This PR introduces the support of Winograd algorithm for two-dimesional convolutions on AArch64 with the help of Arm Compute Library routines. Implementation follows the approach as detailed in the PR [#820](https://github.com/oneapi-src/oneDNN/pull/820) and RFC [#795](https://github.com/oneapi-src/oneDNN/pull/795). Winograd kernels from Compute Library will be called for `algorithm::convolution_winograd` or `algorithm::convolution_auto` (if launch heuristics are satisfied). Introduction of Winograd leads to ~8% speedup for ResNet50 and ~70% speedup for VGG19 on AArch64 compared to only GEMM-based version.
- New acl\_winograd\_convolution.cpp/.hpp files added in `src/cpu/aarch64` directory;
- acl\_gemm\_convolution\_utils renamed to …

Adding Arm Compute Library-based Winograd convolution

---

src/cpu/aarch64/acl_gemm_convolution.hpp

Convolutions from Compute Library do not support all the activation functions for `s8`/`u8` datatypes. However, unsupported configurations are not handled properly at the moment in `init_conf_gemm()` checks due to an issue recently discovered in ACL v20.11 (`.validate()` does not return the expected error code). This small fix provides a temporary solution by explicitly checking the unsupported configurations at the stage of primitive descriptor initialisation.

src: cpu: aarch64: add checks for supported int8 ACL activations

---

src/cpu/aarch64/cpu_isa_traits.cpp

Small typo correction.
- [N/A] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally?

misc: fix typo in Advanced SIMD

---

src/cpu/aarch64/acl_convolution_utils.cpp

oneDNN ignores right and bottom padding values if they do not have an effect on a convolution (see also [issue #824](https://github.com/oneapi-src/oneDNN/issues/824)). In the case of Compute Library the situation is similar except the right and  bottom padding values have to be non-negative (`unsigned int`). This small fix provides a check for -1 in the padding from oneDNN side to setup ACL-based convolution correctly.

src: cpu: aarch64: correct padding values for ACL-based conv. setup

---

README.md

Adds [Flashlight](https://github.com/facebookresearch/flashlight) as a framework using oneDNN.
Checklist N/A

Add Flashlight to readme

---

README.md
doc/build/build_options.md

This PR covers minor changes to the description of Arm Compute Library in the
documentation.
Specifically  a deprecation notice has been issued for the the Computer Vision
functions in Compute Library, and they will be removed in future, see:
https://github.com/ARM-software/ComputeLibrary
Hence this PR changes the description of Compute Library from:
> Arm Compute Library is an open-source library for computer vision and
> machine learning applications
to:
> Arm Compute Library is an open-source library for machine learning
> applications
- [N/A] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally?
- …

doc: update Arm Compute Library description.

---

.github/automation/.drone.yml
src/cpu/aarch64/jit_uni_reorder.cpp

This PR fixes debug build on AArch64 and adds CI to check if there is no build error for debug mode.

aarch64: fix debug build error (-Werror=sign-compare) on AArch64

---

doc/performance_considerations/profilers.md

misc: fix typo in doc/performance_considerations/profilers.md

---

rfcs/20210219-cache-compiled-gpu-kernels/README.md

rfc: cache-compiled-gpu-kernels fix a typo

---

src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64_gen.h

fix: aarch64: I-cache coherency

---

src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64/xbyak_aarch64_util.h

Because Linux supports `getauxval` function to get CPU features, Xbyak_aarch64 is modified to use it instead of reading the system register directly. I believe this patch fixes #1025

aarch64: use getauxval for Linux to get CPU features

---

.github/automation/.drone.yml
src/cpu/aarch64/cpu_isa_traits.hpp
src/cpu/aarch64/jit_generator.hpp
src/cpu/aarch64/jit_uni_reorder.cpp

This PR adds JIT implementation for ASIMD/SVE128/SVE256 isa of AArch64.

cpu: aarch64: reorder: add jit impl. ASIMD/SVE128/SVE256

---

rfcs/20210510-sum-with-zero-point/README.md

Fixes for rfc "sum with zero point".

rfc: fixes for sum with zp

---

rfcs/20210519-single-pass-bnorm/README.md

[link to rendered document](https://github.com/oneapi-src/oneDNN/tree/gtrzebia/rfc/single-pass-bnorm/rfcs/20210519-single-pass-bnorm)

rfc: bnorm: single-pass formula for calculating mean and variance

---

rfcs/20210510-conda-forge-distribution/README.md

This RFC is to discuss conda-forge distribution.
[Link to a rendered document](https://github.com/igorsafo/oneDNN/tree/rfcs/rfcs/20210510-conda-forge-distribution).

RFC: conda-forge distribution

---

rfcs/20210129-optimize-pd-creation/README.md

This RFC describes a proposal on optimization of primitive descriptor creation.
[Link to rendered document](https://github.com/oneapi-src/oneDNN/blob/fab9e19628682f178d743d05d3f2b4a2a17dc0ad/rfcs/20210129-optimize-pd-creation/README.md)

rfc: optimize pd creation

---

rfcs/20210628-usm-support-for-opencl/README.md

This RFC describes a proposal on introducing USM support for oneDNN OpenCL runtime.
[Link to rendered document](https://github.com/densamoilov/oneDNN/tree/dsamoylo/rfcs/usm-for-opencl/rfcs/20210628-usm-support-for-opencl)
@vladimir-paramuzov

rfc: add USM support for OpenCL

---

rfcs/20210624-persistent-cache/README.md

[Link to rendered document](https://github.com/densamoilov/oneDNN/tree/dsamoylo/rfcs/persistent-cache/rfcs/20210624-persistent-cache)
@Jianhui-Li @TaoLv @vladimir-paramuzov

rfc: proposal on persistent cache in oneDNN

---

src/common/ittnotify/ittnotify.h
src/common/ittnotify/ittnotify_config.h
src/common/ittnotify/ittnotify_static.c
src/common/ittnotify/legacy/ittnotify.h

These changes fix MinGW build.
Due to multiple issues related to ittnotify update the decision is to fixup the issue until we are able to migrate to the newer version of ittnotify. Thanks @markdryan for the fixup.
Fixes #1142

Fix MinGW build issues with ittnotify (close #1142)

---

rfcs/20210624-persistent-cache/README.md

I slightly updated the proposal on persistent cache. Conceptually nothing has changed.
The list of changes:
* Added definition of C API
* Changed name `binary` to `blob` 
* Removed `binary_kind` as there is no need in it
* Changed data structure for storing the `binary` (`blob`) from two-dimensional to one-dimensional array
[Rendered document](https://github.com/densamoilov/oneDNN/tree/dsamoylo/rfcs%2Fupdate-persistent-cache-rfc/rfcs/20210624-persistent-cache)

rfc: update proposal on persistent cache

---

src/common/impl_list_item.hpp
src/common/utils.hpp
src/cpu/cpu_binary_list.cpp
src/cpu/cpu_concat.cpp
src/cpu/cpu_reduction_list.cpp
src/cpu/cpu_shuffle_list.cpp
src/cpu/cpu_sum.cpp
src/cpu/matmul/cpu_matmul_list.cpp
src/gpu/gpu_binary_list.cpp
src/gpu/gpu_concat_list.cpp
src/gpu/gpu_gemm_list.cpp
src/gpu/gpu_matmul_list.cpp
src/gpu/gpu_reduction_list.cpp
src/gpu/gpu_reorder_list.cpp
src/gpu/gpu_shuffle_list.cpp
src/gpu/gpu_sum_list.cpp
src/gpu/gpu_zero_pad_list.cpp
src/gpu/nvidia/cudnn_concat.cpp
src/gpu/nvidia/cudnn_reorder_impl.cpp
src/gpu/nvidia/cudnn_sum.cpp
src/gpu/nvidia/sycl_cuda_engine.cpp

Low-hanging fruit, so let's just do it. Using C++11 syntax.

cpu, common: add constexprs

---

rfcs/20220111_consolidate-avx512/README.md

[link to RFC document](https://github.com/oneapi-src/oneDNN/tree/msotoflo/rfc_consolidate-avx512/rfcs/20220111_consolidate-avx512).
The implementation that seems the most feasible is Option 1, but let me know what are your thoughts.

[RFC] Consolidate AVX512 CPU ISA

---

src/cpu/x64/injectors/jit_uni_eltwise_injector.cpp

The primitive is crashing as the code it generates to ensure that the
stack is 16 byte aligned actually ensures that it is always 8 byte
aligned.  We should be adding 32 + the potential alignment offset
instead of 40 + the alignment offset, as described in the comments
in the code.
Signed-off-by: Mark Ryan <mark.d.ryan@intel.com>
@densamoilov can you check this?  The issue seems to have been introduced by [#1cc4fd7291cdfdba43a3cf0fa71265c02ac47d93](https://github.com/oneapi-src/oneDNN/commit/1cc4fd7291cdfdba43a3cf0fa71265c02ac47d93).  Prior to this commit the code arranged for the stack to always be 16 byte aligned, and after this commit it is always 8 byte aligned, as far as I can tell.  For example consider that the stack is 16 byte aligned at the start of this code
```
h->mov(h->rbx, …
```

cpu: eltwise: Fix crash in eltwise_pow on Windows

---

src/common/memory_desc_wrapper.hpp
src/cpu/reorder/simple_reorder.hpp
tests/benchdnn/reorder/reorder.cpp

[rls-v2.5] Fix simple reorder

---

src/common/memory_desc_wrapper.hpp
src/cpu/reorder/simple_reorder.hpp
tests/benchdnn/reorder/reorder.cpp

Backport of https://github.com/oneapi-src/oneDNN/pull/1335

[rls-v2.6] Fix simple reorder

---

src/cpu/aarch64/acl_utils.cpp

Re-adds broadcasting functionality to `acl_binary_t` and `acl_prelu_fwd_t` which was accidentally removed in #1408.
As far as I know, there is no straightforward way to add a test for which implementation is picked. This is potentially something to return to later.

cpu: aarch64: fix broadcasting in acl binary/prelu

---

src/cpu/aarch64/acl_convolution_utils.cpp

This PR fixes a recently identified issue (https://github.com/oneapi-src/oneDNN/issues/1421#issuecomment-1185589357)
in the Aarch64 build with Compute Library. A recent update to the winograd
kernels in ACL have added support for arbitrary padding when oneDNN expects this
case to throw an exception in the reference kernels.
To reproduce: build oneDNN with ACL off the main branch from MLPlatform.org and
run the `test_iface_wino_convolution` test.
This patch disallows large padding configurations in the ACL winograd
integration to make it consistent with the oneDNN library.
- [N/A ] Have you submitted performance data that demonstrates performance improvements?
- [N/A] …

cpu: aarch64: acl: disallow large padding in ACL wino to be consist with oneDNN

---

.github/automation/.azure-pipeline.yml
.github/automation/build.bat
.github/automation/build.sh
.github/automation/env/clang.sh
src/cpu/x64/jit_brgemm_conv_bwd.cpp

Ubuntu 18.04 is deprecated in Azure. This PR updates version to 22.04 and also introduces a knob to control clang version.

Update Ubuntu 18.04 in Azure CI to 22.04

---

src/cpu/aarch64/jit_primitive_conf.hpp
src/cpu/aarch64/jit_uni_pool_kernel.cpp
src/cpu/aarch64/jit_uni_pool_kernel.hpp
src/cpu/aarch64/jit_uni_pooling.cpp
src/cpu/aarch64/jit_uni_pooling.hpp
src/cpu/aarch64/jit_uni_reorder.hpp

This PR add support SVE512 jit-ed injector for pooling.

cpu: aarch64: pooling: add jit-ed injector support

---

src/cpu/aarch64/injectors/jit_uni_eltwise_injector.cpp

This patch fixes the JIT-ed implementation of forward gelu_erf for AArch64 SVE environment.
For example, the following `benchdnn` test patterns, which are included `tests/benchdnn/inputs/conv/test_conv_all`, will be passed correctly.
```
--conv --skip-impl=ref --attr-post-ops=gelu_erf g1ic3iw5oc16ow5kw3pw1n"1d_conv:1st"
--conv --skip-impl=ref --attr-post-ops=gelu_erf g1ic3iw5oc17ow5kw3pw1n"1d_conv:1st_tail"
--conv --skip-impl=ref --attr-post-ops=gelu_erf g1ic3iw8oc17ow4kw3sw2pw1n"1d_conv:1st_stride_tail"
--conv --skip-impl=ref --attr-post-ops=gelu_erf g1ic16iw5oc16ow5kw1pw0n"1d_conv:1x1"
--conv --skip-impl=ref --attr-post-ops=gelu_erf g1ic17iw5oc17ow5kw1pw0n"1d_conv:1x1_tail"
--conv --skip-impl=ref --attr-post-ops=gelu_erf g1ic17iw8oc17ow4kw1sw2pw0n"1d_conv:1x1_stride_tail"
--conv …
```

cpu: aarch64: eltwise: fix gelu_erf_compute_vector_fwd

---

rfcs/20220608-make-opdesc-and-md-opaque/README.md

[Link ](https://github.com/densamoilov/oneDNN/tree/dsamoylo/rfcs/make-opdesc-and-md-opaque/rfcs/20220608-make-opdesc-and-md-opaque)to the document.
@TaoLv, @Jianhui-Li @jgong5 @vladimir-paramuzov @dmitry-gorokhov @yiqianglee

rfc: add proposal on making opdesc and md opaque

---

rfcs/20221024-persistent-cache-api-for-ocl-engine/README.md

[Link to document](https://github.com/densamoilov/oneDNN/tree/dsamoylo/rfcs/add-engine-persistent-cache-api/rfcs/20221024-persistent-cache-api-for-ocl-engine)

rfc: add proposal on extending persistent cache API

---

.github/automation/.drone.yml
.github/automation/build_acl.sh
cmake/ACL.cmake
doc/build/build_options.md

Update Compute Library required version to 22.08

cpu: aarch64: build: update Compute Library required version to 22.08

---

src/cpu/aarch64/jit_sve_512_x8s8s32x_conv_kernel.cpp
src/cpu/aarch64/jit_uni_dw_conv_kernel_utils.hpp

This PR fixes invalid scale_offset load. For example, the following pattern of SEGV will be corrected.
```
./benchdnn --conv --mode=c --dir=FWD_I --cfg=s8s8f32 --attr-oscale="per_oc:5*" g1ic3iw5oc17ow5kw3pw1n"1d_conv:1st_tail"
```

cpu: aarch64: conv: fix SEGV of scale_offset data

---

src/cpu/aarch64/injectors/jit_uni_eltwise_injector.cpp
src/cpu/aarch64/injectors/jit_uni_eltwise_injector.hpp
src/cpu/aarch64/jit_uni_eltwise.cpp

This PR cleans up API of JIT-ed impl. of eltwiswe for SVE.

cpu: aarch64: eltwise: cleanup api of jit-ed impl. for v3.0

---

rfcs/20221229-rnn-bwd-w-accumulation/README.md

A [link](https://github.com/igorsafo/oneDNN/tree/rfcs/rfcs/20221229-rnn-bwd-w-accumulation) to the rendered version.

rfcs: rnn: bwd: skip weights accumulation

---

src/gpu/nvidia/cudnn_binary.hpp

Adding support for bf16 Binary primitive in cuDNN.
Supported scope:
Supported Data Types : bf16
Testing scope:
Test output file:
[test_binary_all.txt](https://github.com/oneapi-src/oneDNN/files/10857276/test_binary_all.txt)
General

BF16 support for cuDNN binary primitive.

---

src/cpu/aarch64/jit_uni_batch_normalization_s8.cpp

This patch adds the JIT-ed functions of scale, shift and relu for s8.
Thank you!

aarch64: bnorm: scale, shift and relu for s8

---

src/cpu/aarch64/cpu_isa_traits.hpp
src/cpu/aarch64/jit_uni_batch_normalization_s8.cpp
src/cpu/aarch64/xbyak_aarch64/src/err_impl.h
src/cpu/aarch64/xbyak_aarch64/src/util_impl.cpp
src/cpu/aarch64/xbyak_aarch64/src/util_impl.h
src/cpu/aarch64/xbyak_aarch64/src/util_impl_linux.h
src/cpu/aarch64/xbyak_aarch64/src/util_impl_mac.h
src/cpu/aarch64/xbyak_aarch64/src/util_impl_windows.h
src/cpu/aarch64/xbyak_aarch64/src/xbyak_aarch64_impl.h
src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64/xbyak_aarch64.h
src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64/xbyak_aarch64_adr.h
src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64/xbyak_aarch64_code_array.h
src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64/xbyak_aarch64_err.h
src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64/xbyak_aarch64_gen.h
src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64/xbyak_aarch64_inner.h
src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64/xbyak_aarch64_label.h
src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64/xbyak_aarch64_util.h
src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64/xbyak_aarch64_version.h

This patch updates Xbyak_aarch64 to the latest version.
Thank you!

Xbyak aarch64 20230214

---

src/cpu/aarch64/jit_uni_binary.cpp
src/cpu/aarch64/jit_uni_binary.hpp
src/cpu/aarch64/jit_uni_binary_kernel.cpp
src/cpu/aarch64/jit_uni_binary_kernel.hpp

https://github.com/oneapi-src/oneDNN/issues/1541

aarch64: binary: fix compare inplace

---

src/common/compiler_workarounds.hpp

Supported compilation with gcc-12 (using docker image from docker.hub `gcc:12.2.0`)

Compilation with gcc-12

---

src/cpu/aarch64/acl_deconvolution.hpp

This PR enables the `fast math mode` (i.e. when `ONEDNN_DEFAULT_FPMATH_MODE` is set to `BF16` or `ANY`
to allow the use of BF16 kernels when available on the hardware) for the deconvolution primitive
which makes use of the Compute Library for the Arm® architecture (ACL), optimised for AArch64 targets.
The fast math mode offers performance improvement of up to ~2.7x on AArch64.
Changes are also made when querying for the ACL convolution method, following recent optimization in ACL.

cpu: aarch64: deconv: Enable fast math mode for ACL deconvolution

---

src/gpu/nvidia/cudnn_deconvolution.hpp

Added bf16 datatype support for Deconvolution.
Forward
Backward
Benchdnn: Passed
NVIDIA A100, NVIDIA H100
NVIDIA A100
Refer Below
[Deconvolution_bf16.zip](https://github.com/oneapi-src/oneDNN/files/10954755/Deconvolution_bf16.zip)

Nvidia Backend: bf16 support added for Deconvolution

---

src/gpu/amd/README.md

Added README file for the AMD backend.
This file describes the environment setup, build command and primitive wise features and limitation.

Adding readme file for AMD backend

---

src/cpu/aarch64/cpu_isa_traits.hpp
src/cpu/aarch64/jit_generator.hpp
src/cpu/aarch64/jit_uni_deconv_zp_pad_str_kernel.cpp

This allows the library to be compiled for Windows on ARM devices with MSVC - this is a follow on from #1648

Add support for Windows on ARM devices with MSVC

---

rfcs/20230420-kernel-cache/README.md

[Link to rendered document](https://github.com/densamoilov/oneDNN/tree/dsamoylo/rfcs/kernel-cache/rfcs/20230420-kernel-cache)
This is a proposal on a high level design of kernel cache.

rfcs: proposal on kernel cache

---

rfcs/20221010-add-ocl-ooo-queue/README.md

[Link to the document](https://github.com/densamoilov/oneDNN/tree/dsamoylo/rfcs/add-ocl-ooo-queue/rfcs/20221010-add-ocl-ooo-queue)
@vladimir-paramuzov

rfc: add a proposal on enabling ooo queue for OpenCL runtime

---

rfcs/20230913-packed-sparse-weights/README.md

[Link to rendered doc](https://github.com/densamoilov/oneDNN/tree/dsamoylo/rfcs/packed-sparse-weights/rfcs/20230913-packed-sparse-weights)

rfcs: add proposal on introducing packed sparse weights

---

rfcs/20231002-Compute-type/README.md

Rendered documents [here](https://github.com/mgouicem/oneDNN/tree/mgouicem/rfcs/compute_type/rfcs/20231002-Compute-type)

rfcs: proposal for weights decompression

---

rfcs/20231108-gpt-quantization/README.md

Here is the [link](https://github.com/igorsafo/oneDNN/tree/rfcs-gpt-quantization/rfcs/20231108-gpt-quantization)

rfcs: gpt-quantization

---

rfcs/20240308-md-serialization/README.md

[Link](https://github.com/mgouicem/oneDNN/tree/mgouicem/rfcs/serialize_md/rfcs/20240308-md-serialization) to rendered document.

rfcs: proposal for memory descriptor serialization.

---

src/gpu/sycl/prelu_kernels.hpp

Fixes failures of benchdnn tests of prelu SYCL implementation - `./tests/benchdnn/benchdnn --prelu --engine=gpu --batch=test_prelu_gpu` on A100 with cuDNN implementations disabled. Two issues are fixed:
- some broadcasting strategies not handled (previous default case was not doing any computation)
- reading uninitialized memory if the number of dimensions is less than max and `calculate_shared_axes` code path is used.

gpu: sycl: prelu: fix benchdnn failures

---

src/gpu/gpu_sdpa_list.cpp
src/gpu/intel/jit/gemm/microkernel_provider.cpp

- Fixes compilation errors for SDPA/microkernels
- @petercad please review

build: fix micro sdpa build errors

---

src/cpu/reorder/cpu_reorder_pd.hpp

Check all pointers are initialized in cpu_reorder_pd

---

cmake/ACL.cmake
src/cpu/aarch64/matmul/acl_lowp_matmul.hpp
src/cpu/matmul/cpu_matmul_list.cpp

Backport of #1885 to unreleased rls-v3.5
@dzarukin

Backport src: cpu: aarch64: add ACL s8:s8:f32 matmul

---

src/cpu/aarch64/acl_convolution_utils.cpp

Backport of #1948 
Update direct vs indirect conv heuristics:
- Remove fall through to direct conv for low thread counts
- Do not fall though to direct conv for small convolutions when the datatype is BF16.
- [ YES ] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [ YES ] Have you formatted the code using clang-format?

Backport cpu: aarch64: conv: Update direct vs indirect conv heuristics

---

src/gpu/generic/sycl/pooling_kernels.hpp
src/gpu/generic/sycl/ref_pooling.cpp
src/gpu/generic/sycl/ref_pooling.hpp
src/gpu/generic/sycl/sycl_primitive_conf.hpp

gpu: sycl: pooling: Reduce argument size

---

src/cpu/x64/jit_avx512_core_amx_conv_kernel.hpp

The code changes in this PR were generated automatically by the Permanence AI Coder and reviewed by @fwph & @jweese. This PR updates memory allocation in `jit_avx512_core_amx_bwd_data_kernel_t `by using utils::make_unique for object management of the private members `eltwise_injector_` and `bwd_data_copy_kernel_` instead of raw pointers.

cpu: x64: improve memory management safety for jit_avx512_core_amx_conv_kernel

---

src/gpu/generic/sycl/matmul_kernels.hpp
src/gpu/generic/sycl/sycl_post_ops.hpp

Bugfix matmul not building. This happened due to two conflicting PRs being merged at the same time. This applies the refactor from https://github.com/oneapi-src/oneDNN/pull/2063 to matmul https://github.com/oneapi-src/oneDNN/pull/2054

generic: sycl: matmul: bugfix post ops not building

---

src/gpu/generic/sycl/ref_matmul.cpp
src/gpu/generic/sycl/ref_matmul.hpp

Adds support for runtime dimensions to SYCL matrix multiplication.

generic: sycl: matmul: add support for runtime dims

---

src/gpu/generic/sycl/ref_convolution.hpp
src/gpu/generic/sycl/ref_deconvolution.hpp
src/gpu/generic/sycl/ref_softmax.hpp

Cherry-pick of https://github.com/oneapi-src/oneDNN/pull/2146 to the release branch.

generic: SYCL: convolution/deconvolution/softmax: add missing checks

---

src/gpu/generic/sycl/binary_kernels.hpp

Cherry pick of https://github.com/oneapi-src/oneDNN/pull/2105 into the release branch.

generic: sycl: binary: bugfix post ops with blocked formats

---

src/graph/backend/dnnl/platform.cpp

cpu: aarch64: Remove private ACL headers

---

src/gpu/generic/sycl/ref_softmax.hpp

This PR cherry picks 565b18fd2b61fedb6946caa71ba7f347a05e4a6f into release 3.6 branch.

generic: sycl: softmax: bugfix checks

---

src/gpu/generic/sycl/ref_convolution.cpp
src/gpu/generic/sycl/ref_convolution.hpp

This PR cherry picks fc02fd637a5a648e1b9bf374bcc1838f95e9bff5 into release 3.6 branch.

generic: sycl: deconvolution: bugfix post-ops

---

src/cpu/aarch64/jit_uni_dw_convolution.hpp

fixup: src: replace implementations' pd ctor with base class ctor

---

.github/automation/test_aarch64.sh

remove aarch64 ci solved testcases from skip list.
wait for PR: https://github.com/oneapi-src/oneDNN/pull/2215 to be merged.

github: workflows: update skip test on aarch64 ci

---

src/common/utils.hpp

Some SyCL and OCL builds with GCC host compiler fail due to false-positive format-truncation warning in first `snprintf`, this workaround prevents that.

common: workaround for GCC 8 format-truncation warning

---

src/graph/utils/pm/nested_matcher.cpp
tests/gtests/graph/unit/utils.hpp
tests/gtests/graph/unit/utils/test_pattern_matcher_cpu.cpp

Fix the port set to in_port_map.

graph: utils: pm: fix fill_local_in_map

---

cmake/platform.cmake
scripts/verbose_converter/src/benchdnn_generator.py
scripts/verbose_converter/src/ir.py
scripts/verbose_converter/src/parse.py
src/common/verbose.cpp
tests/benchdnn/graph/graph.cpp
tests/benchdnn/graph/graph.hpp

It should fix the copyright checker failures in CI. Happy new year!

copyright: update copyright year 2025

---

src/gpu/intel/jit/conv/config.cpp
src/gpu/intel/jit/conv/gen_convolution.cpp
src/gpu/intel/jit/conv/tiler.cpp

PR fixes broken tuning support in convolution after 038d73f8bd.

xe: conv: fix tuning support

---

src/gpu/intel/jit/conv/config.cpp

PR fixes https://jira.devtools.intel.com/browse/MFDNN-12894.

xe: conv: apply skip-w optimization for large strides

---

src/common/primitive_hashing.cpp
src/common/sdpa_pd.hpp
src/common/sdpa_types.hpp
src/common/sdpa_utils.hpp
src/common/serialization.cpp
src/common/type_helpers.hpp
src/gpu/intel/ocl/micro_sdpa.cl
src/gpu/intel/ocl/micro_sdpa.cpp
src/gpu/intel/ocl/tile_ops.h
src/graph/backend/dnnl/kernels/sdp_primitive_config.cpp

This PR add support for causal masks to the micro_sdpa kernel. I have built this on top of the #2330.

xe: sdpa: Causal mask support

---

src/gpu/intel/jit/gemm/generator/pieces/k_loop.cxx

Fixes potential issues in grouped quantization cases where the k loop check could happen too early, clashing with flag register usage by scale/zp loads in case virtual flag registers are in use. The existing mechanism for timing the k loop check is a bit fragile; this patch makes it more robust by disallowing usage of the k loop check flag once the check has been made.
Xe2 example failing case prior to this patch:
```
--matmul --engine=gpu --dt=f16:s4:f16 --wtag=acb --attr-scales=wei:per_ocic:f16:128x1 --attr-zero-points=wei:per_ocic:u4:128x1 --attr-fpmath=f16:true --skip-impl=ref 3x96x512:3x512x64
```

xe: jit: gemm: robust flag register handling in k loop check

---

src/gpu/intel/ocl/gemm/gemm_with_post_ops.cl
src/gpu/intel/ocl/gemm/gemm_with_post_ops.cpp
src/gpu/intel/ocl/gemm_inner_product.cpp
src/gpu/intel/ocl/gemm_inner_product.hpp
src/gpu/intel/ocl/ocl_io.h
src/gpu/intel/ocl/reduction/combined_reduction.cl
src/gpu/intel/primitive_conf.cpp
src/gpu/intel/primitive_conf.hpp

Fixes [MFDNN-12893](https://jira.devtools.intel.com/browse/MFDNN-12893).

xe: ocl: gemm: fix post-op typing for gemm_with_po

---

src/gpu/intel/jit/gemm/gen_gemm_kernel.cpp

Resolves issue where debug strategies submitted with `GEMM_KERNEL="<strat>"` behaved differently than identical strategy read from db.

[GPU] Fix  jit GEMM debug strategy submission

---

src/gpu/intel/jit/codegen/codegen.cpp
src/gpu/intel/jit/conv/gen_convolution.cpp
src/gpu/intel/jit/conv/normalization.cpp
src/gpu/intel/jit/gemm/generator/pieces/matrix_access.cxx
src/gpu/intel/jit/gemm/generator/pieces/walk_orders.cxx
src/gpu/intel/jit/ir/blocking.cpp
src/gpu/intel/jit/ir/epilogue.cpp
src/gpu/intel/jit/ir/fma.hpp
src/gpu/intel/jit/ir/slm_reduce_builder.cpp
src/gpu/intel/jit/ir/tensor.hpp
src/gpu/intel/jit/ngen/ngen.hpp
src/gpu/intel/jit/ngen/ngen_gen12.hpp
src/gpu/intel/jit/ngen/ngen_gen8.hpp
src/gpu/intel/jit/ngen/ngen_pseudo.hpp
src/gpu/intel/jit/pooling/config.hpp
src/gpu/intel/jit/pooling/ir_builder.cpp
src/gpu/intel/jit/v2/ir/tensor.cpp
src/gpu/intel/ocl/custom_reorder.cpp
src/gpu/intel/ocl/reduction/atomic_reduction.cpp

Partially addresses MFDNN-12963.

[GPU] Coverity fixes

---

src/cpu/x64/jit_avx512_common_conv_kernel.cpp

Disabling dilation values (`> INT_MAX`) to avoid `int` overflow.
In future we may change `jcp` fields from `int` to `size_t`, but there are a lot of dependencies in a many places of the code, so it's better to disable it for now.
[MFDNN-12967](https://jira.devtools.intel.com/browse/MFDNN-12967)

x64: conv: handle dilation int overflow (fixes MFDNN-12967)

---

src/gpu/intel/jit/codegen/reorder.hpp

This resolves [MFDNN-12989](https://jira.devtools.intel.com/browse/MFDNN-12989).

src: gpu: intel: jit: fix div-by-0 when aligning hs=0 grf regions

---

src/gpu/intel/jit/emulation.hpp
src/gpu/intel/ocl/gemm/gemm_with_post_ops.cl
src/gpu/intel/ocl/gemm/gemm_with_post_ops.cpp
src/gpu/intel/ocl/ocl_conversion.h
src/gpu/intel/ocl/ocl_io.h

Backport of #2373 to rls-v3.7.

[rls-v3.7] xe: fix various GEMM issues

---

examples/tutorials/matmul/cpu_matmul_quantization.cpp
src/common/sdpa_utils.hpp
tests/gtests/dnnl_test_common.hpp
tests/gtests/test_sum.cpp

[backport][rls-v3.7] Arch: coverity fixes (fixed MFDNN-12954)

---

src/graph/backend/dnnl/op_executable.cpp
src/graph/utils/pm/nested_matcher.cpp
tests/benchdnn/graph/setting_handler.cpp

[rls-v3.7] graph: fix coverity issues

---

src/common/memory_tracking.hpp
src/gpu/generic/sycl/README.md
src/gpu/generic/sycl/reduction_kernels.hpp
src/gpu/generic/sycl/ref_reduction.cpp
src/gpu/generic/sycl/ref_reduction.hpp
src/gpu/generic/sycl/simple_reduction.cpp
src/gpu/generic/sycl/simple_reduction_kernels.hpp
src/gpu/generic/sycl/sycl_primitive_conf.hpp
src/gpu/gpu_reduction_list.cpp
src/xpu/sycl/types.hpp
tests/gtests/test_reduction.cpp

gpu: generic: implement SYCL reduction

---

src/gpu/intel/ocl/reusable_softmax.cpp

The current reusable softmax implementation relies on work group collective functions. If the total size of the workgroup isn't a multiple of the subgroup size the OpenCL runtime will perform the reduction with the inactive portion of the subgroup producing incorrect results in the wg_max and wg_add reductions. 
Since reusable softmax reduces the <1024 sizes it is creating incorrect reference results for SDPA testing that targets similar data sizes.

xe: softmax: workaround for bug in wg_reduce

---

src/graph/backend/dnnl/kernels/sdp_decomp_config.cpp
src/graph/backend/dnnl/passes/transform.cpp

backport from https://github.com/oneapi-src/oneDNN/pull/2384

[rls-v3.7] graph: backend: fix select binary related issues

---

src/gpu/intel/ocl/micro_sdpa.cl
src/gpu/intel/ocl/micro_sdpa.cpp
src/gpu/intel/ocl/micro_sdpa.hpp

[Backport][Fix] Enable Bf16 in Micro SDPA

---

src/gpu/intel/ocl/micro_sdpa.cl
src/gpu/intel/ocl/micro_sdpa.cpp
src/gpu/intel/ocl/micro_sdpa.hpp

This PR is a fix for enabling bf16 for sdpa and addresses some minor feedback for the previous PR @2344

Fix: Enable BF16 SDPA

---

include/oneapi/dnnl/dnnl.hpp
include/oneapi/dnnl/dnnl_common.hpp
include/oneapi/dnnl/dnnl_graph.hpp
include/oneapi/dnnl/dnnl_graph_ocl.hpp
include/oneapi/dnnl/dnnl_graph_sycl.hpp
include/oneapi/dnnl/dnnl_ocl.hpp
include/oneapi/dnnl/dnnl_sycl.hpp
include/oneapi/dnnl/dnnl_threadpool.hpp
include/oneapi/dnnl/dnnl_ukernel.hpp
tests/benchdnn/graph/deserialize.cpp

Backport of PR #2400 for rls-v3.7.

[rls-v3.7][MHA][CPU] common: fix for mha cpu regression

---

src/gpu/intel/jit/emulation.hpp

Backport of #2375 to rls-v3.7.

[Backport v3.7] xe: jit: gemm: implement qqw mul instructions

---

src/gpu/intel/jit/gemm/generator/pieces/matrix_access.cxx
src/gpu/intel/jit/ngen/ngen_pseudo.hpp
src/gpu/intel/jit/pooling/ir_builder.cpp

[rls-v3.7][GPU] Coverity fixups

---

src/graph/backend/dnnl/fusion_info.cpp
src/graph/utils/pm/nested_matcher.cpp
src/graph/utils/pm/pass_manager.cpp
tests/benchdnn/graph/custom_driver.hpp
tests/benchdnn/graph/parser.cpp

More coverity fixes as explained by each commit message.

graph: more coverity fixes

---

src/gpu/intel/jit/gemm/selector/kernel_evaluator.cpp
src/gpu/intel/jit/gemm/xe_hp_systolic_gemm.cpp
src/gpu/intel/jit/ir/send_plan.cpp
third_party/ngen/ngen_register_allocator.hpp

Fixes most UBSan issues from [Weekly CI](https://intel-ci.intel.com/efcff291-0bce-f199-b913-a4bf010d0e2d). Compare with [this branch](https://intel-ci.intel.com/efd228c0-7d5a-f1aa-b16c-a4bf010d0e2d).

[GPU] UBSan fixes

---

src/gpu/intel/jit/gemm/gen_gemm.cpp
src/gpu/intel/jit/gemm/gen_gemm_kernel.cpp
src/gpu/intel/jit/gemm/include/type.hpp
src/gpu/intel/jit/gemm/xe_hp_systolic_gemm.cpp

[rls-v3.7] xe: jit: gemm: fix invalid use of 2d messages 

---

src/gpu/intel/jit/gemm/selector/kernel_selector.cpp

xe: jit: gemm: reuse xe2 strategies on xe3

---

src/common/reduction_pd.hpp
src/gpu/intel/ocl/reduction/atomic_reduction.cpp
src/gpu/intel/ocl/reduction/combined_reduction.cl
src/gpu/intel/ocl/reduction/combined_reduction.cpp

[Backport v3.7] xe: reduction: fixup exceptions on zero dims

---

src/gpu/intel/ocl/ocl_math_utils.h

[rls-v3.7] xe: ocl: add missing type enablement

---

src/cpu/x64/matmul/brgemm_matmul_utils.cpp

Backport: cpu: x64: matmul: fixes correctness issue about tags

---

src/gpu/intel/jit/conv/config.cpp

This resolves [MFDNN-13021](https://jira.devtools.intel.com/browse/MFDNN-13021).

src: gpu: intel: jit: conv: fix reorder zp precomp page faults

---

src/gpu/intel/jit/conv/config.cpp

This resolves [MFDNN-13021](https://jira.devtools.intel.com/browse/MFDNN-13021).

(v3.7 backport) src: gpu: intel: jit: conv: fix reorder zp precomp page faults

---

tests/benchdnn/dnnl_common.cpp

PR fixes [MFDNN-13071](https://jira.devtools.intel.com/browse/MFDNN-13071). Thanks to @dzarukin for helping with the fix.

benchdnn: fix and limit scratchpad check to CPU

---

src/cpu/x64/injectors/jit_uni_eltwise_injector.cpp

backport of https://github.com/oneapi-src/oneDNN/pull/2485

x64: injectors: eltwise: fix potential int underflow (backport)

---

src/gpu/intel/jit/gemm/xe_hp_systolic_gemm.cpp

[GPU] backport gemm fix

---

src/cpu/x64/matmul/brgemm_matmul_reorders.cpp

cpu: x64: disable small shapes for brgemm matmul reorder

---

src/cpu/x64/utils/jit_io_helper.cpp
tests/benchdnn/inputs/reorder/harness_reorder_regression

x64: utils: jit_io_helper: fix xf16 store from Xmm (backport)

---

src/common/ittnotify.cpp
tests/gtests/dnnl_test_common.hpp

One is coming from a Coverity, another one from user experience.

Some more minor issue fixes

---

src/cpu/matmul/gemm_x8s8s32x_matmul.cpp

cpu: matmul: correct ldc for gemm matmul

---

src/cpu/matmul/gemm_x8s8s32x_matmul.cpp

backport: cpu: matmul: correct ldc for gemm

---

doc/ukernel/operations/transform.md
src/cpu/x64/brgemm/capi/brgemm_api.cpp

cpu: x64: ukernel: transform: add incorrect ldb check

---

third_party/ngen/ngen.hpp

Fix errors introduced by asserts targetted at `movi` hoist into correct locations. 
Fixes # MFDNN-13113

[GPU] Hoist movi address restrictions

---

src/cpu/x64/matmul/brgemm_matmul_utils.hpp

It seems that when we introduced support for non-trivial strides in 78979db92f5b899f142ac2651b1787df7f968944 we also introduced a bug for the case when B tensor is in `ba` format and `K == 1`.
When K == 1 we always pick "ab" format for B (see set_or_check_B_tag) regardles of whether the actual tag was "ab" or  "ba".
Since the implementation assumes the "ab" format is used we cannot use bgmmc.B_strides[1] directly as the strides could be specified for "ba" therefore we need to use bgmmc.N instead.
Fixes MFDNN-13030.

cpu: x64: matmul: fix strides for weights in ba when K == 1

---

src/gpu/intel/jit/gemm/jit_gemm_pd.cpp

[GPU][v3.7] Gemm: remove invalid src post-ops condition

---

src/cpu/x64/jit_uni_reorder_direct_copy.cpp

Changing dispatching in `jit_uni_reorder_direct_copy_t` for unsupported cases.
Fixes [MFDNN-13118](https://jira.devtools.intel.com/browse/MFDNN-13118).

x64: reorder: change dispatching for xf16 and blocks_size < 8 (fixes MFDNN-13118)

---

src/gpu/intel/jit/conv/config.cpp

xe: conv: add heuristic to perform reorder for plain layouts

---

examples/tutorials/matmul/cpu_sgemm_and_matmul.cpp

Coverity fixes

---

src/cpu/reorder/simple_sparse_reorder.hpp
src/cpu/x64/jit_uni_binary_kernel.cpp
src/cpu/x64/jit_uni_i8i8_pooling.cpp
src/cpu/x64/jit_uni_pool_kernel.hpp
src/cpu/x64/jit_uni_reorder_direct_copy.cpp
src/cpu/x64/lrn/jit_avx512_common_lrn_bwd_base.cpp
src/cpu/x64/lrn/jit_avx512_common_lrn_bwd_nhwc.cpp
src/cpu/x64/lrn/jit_avx512_common_lrn_fwd_base.cpp
src/cpu/x64/lrn/jit_avx512_common_lrn_fwd_nhwc.cpp

Partially fixes MFDNN-12964
Fixes potential overflow/underflow, and dereference null pointer issue

cpu: fixes some coverity issues(overflow, dereference null pointer issues)

---

src/cpu/aarch64/brgemm/brgemm.cpp
src/cpu/aarch64/brgemm/brgemm.hpp
src/cpu/aarch64/jit_brgemm_1x1_conv.cpp
src/cpu/aarch64/jit_brgemm_conv.cpp
src/cpu/aarch64/matmul/brgemm_matmul.cpp
src/cpu/x64/brgemm/brgemm.cpp
src/cpu/x64/brgemm/brgemm.hpp
src/cpu/x64/brgemm/brgemm_types.hpp
src/cpu/x64/brgemm/brgemm_utils.cpp
src/cpu/x64/brgemm/brgemm_utils.hpp
src/cpu/x64/brgemm/capi/brgemm_api.cpp
src/cpu/x64/brgemm/jit_brgemm_kernel.cpp
src/cpu/x64/jit_brdgmm_dw_conv.cpp
src/cpu/x64/jit_brgemm_1x1_conv.cpp
src/cpu/x64/jit_brgemm_conv.cpp
src/cpu/x64/jit_brgemm_conv_bwd_strided.cpp
src/cpu/x64/jit_brgemm_conv_bwd_w.cpp
src/cpu/x64/jit_brgemm_conv_utils.cpp
src/cpu/x64/jit_brgemm_conv_utils.hpp
src/cpu/x64/jit_brgemm_inner_product.cpp
src/cpu/x64/jit_brgemm_inner_product.hpp
src/cpu/x64/jit_brgemm_inner_product_utils.cpp
src/cpu/x64/jit_primitive_conf.hpp
src/cpu/x64/matmul/brgemm_matmul.cpp
src/cpu/x64/rnn/rnn_brgemm_utils.cpp
tests/benchdnn/brgemm/brgemm.cpp
tests/gtests/internals/test_brgemm.cpp

This is backport of #2420 to rls-v3.7

[backport] x64: updates for brgemm kernel and avx2 brgemm convolutions

---

src/cpu/x64/jit_brgemm_conv_utils.cpp

[Backport]: cpu: x64: brgemm: update conditions for zp with big ow

---

src/cpu/x64/matmul/brgemm_matmul_utils.cpp
src/cpu/x64/matmul/brgemm_matmul_utils.hpp
tests/benchdnn/inputs/matmul/harness_matmul_regression_bf16
tests/benchdnn/inputs/matmul/harness_matmul_regression_float16
tests/benchdnn/inputs/matmul/harness_matmul_regression_int8

Fixes for matmul tensors with unit dimensions

---

src/cpu/x64/brgemm/brgemm_utils.cpp

This a fix for [MFDNN-13143](https://jira.devtools.intel.com/browse/MFDNN-13143)
After commit [x64: brgemm: update non-amx blocking](https://github.com/oneapi-src/oneDNN/commit/744a255f69cf062cae061583648d0fc606e01c38) the brgemm_blocking selects for this convolution `n_bcast_1_load = true`, `bd_block = 3` and `ld_block2 = 4`.  But for such blocking we have a `bd_tail = 1` which is smaller than padding. As result brgemm implementation returns `unimplemented` for this shape and it goes to reference implementation.
The PR checks both `bd_block` and `bd_tail` against padding and tries to find a smaller `ld_block2` that will give `bd_block` and `bd_tail` more than padding.

x64: brgemm: update blocking for big virtual padding

---

src/cpu/gemm_x8s8s32x_convolution_utils.cpp
tests/benchdnn/dnnl_common.cpp

non-x64: fix couple issues (fixes MFDNN-13038 and fixes MFDNN-13031)

---

src/cpu/x64/jit_uni_binary_kernel.cpp
src/cpu/x64/jit_uni_i8i8_pooling.cpp
src/cpu/x64/jit_uni_pool_kernel.hpp
src/cpu/x64/jit_uni_reorder_direct_copy.cpp
src/cpu/x64/lrn/jit_avx512_common_lrn_bwd_base.cpp
src/cpu/x64/lrn/jit_avx512_common_lrn_bwd_nhwc.cpp
src/cpu/x64/lrn/jit_avx512_common_lrn_fwd_base.cpp
src/cpu/x64/lrn/jit_avx512_common_lrn_fwd_nhwc.cpp

[Backport]cpu: fixes some coverity issues(overflow, dereference null pointer issues) 

---

src/cpu/ref_deconvolution.hpp

Jira: https://jira.devtools.intel.com/browse/MFDNN-13154

cpu: ref_deconv: extend bias limitation check

---

src/cpu/cpu_engine.cpp
src/cpu/reorder/simple_sparse_reorder.hpp
src/cpu/rnn/ref_rnn.cpp
src/cpu/rnn/rnn_utils.hpp
src/cpu/sycl/engine.hpp
src/cpu/x64/matmul/brgemm_matmul_utils.cpp

* #2587 - there is no tracker
* #2589 - MFDNN-13148 and MFDNN-12386
* #2598 - MFDNN-13062
* #2611 - MFDNN-13075

Backport critical fixes to rls-v3.7

---

.github/automation/commit-msg-check.py
src/gpu/amd/miopen_binary.cpp
src/gpu/amd/miopen_binary.hpp
src/gpu/amd/miopen_convolution.cpp
src/gpu/amd/miopen_deconvolution.cpp
src/gpu/amd/miopen_eltwise.cpp
src/gpu/amd/miopen_inner_product.cpp
src/gpu/amd/miopen_lrn.cpp
src/gpu/amd/miopen_matmul_executor.hpp
src/gpu/amd/miopen_pooling.cpp
src/gpu/amd/miopen_reduction.cpp
src/gpu/amd/miopen_reorder.cpp
src/gpu/amd/miopen_reorder.hpp
src/gpu/amd/miopen_softmax.cpp

amd: fix build errors (fixes MFDNN-13026 and fixes MFDNN-13141)

---

src/common/ittnotify.cpp
src/cpu/ref_deconvolution.hpp
src/cpu/x64/gemm_bf16_inner_product.hpp
src/cpu/x64/jit_avx512_core_amx_conv_kernel.cpp
src/cpu/x64/jit_brdgmm_dw_conv.cpp
src/cpu/x64/jit_brgemm_conv_bwd_strided.cpp

Backport of library fixes from #2335 
Additional Coverity fix for ITT_Notify functionality.

[backport][rlsv-3.7] CPU bias support fixes and Coverity fix

---

src/cpu/x64/brgemm/jit_brgemm_kernel.cpp

This PR replaces `int` with `dim_t` in jit_brgemm_kernel.cpp to avoid overflows. Xbyak properly handles the situations when offsets are > `INT32_MAX` by throwing the corresponding exception, which is much better than an undefined behavior resulting in crashes or incorrect results.

cpu: x64: brgemm: use dim_t instead of int

---

src/gpu/nvidia/cudnn_eltwise_impl.hpp

gpu: nvidia: fix relu type cast for dimension (backport) (#2519)

---

src/cpu/x64/jit_uni_ncsp_convolution.cpp

Fixes MFDNN-13174 and MFDNN-13169.
This PR fixes two bugs:
* Memory leaks (`memory_t` was allocated but never released).
* Incorrect memory handling. Since the classic CPU primitives are re-used for SYCL CPU runtime it is prohibited to create `memory_t` objects for raw pointers for nested primitives.
The bugs were originally introduced in 3426b9c8a51 but were concealed due to another bug that was fixed in #2587.

Fix memory handling inside primitive

---

src/graph/backend/dnnl/patterns/sdp.cpp
src/graph/backend/dnnl/patterns/utils.hpp

sdpa primitive has supported bf16 dtype recently, enable this data type in graph side also.

graph: backend: dnnl: enable bf16 sdpa w/ implicit causal mask

---

src/cpu/x64/brgemm/jit_brgemm_kernel.cpp

Fixes MFDNN-13170.
This PR fixes the condition for identifying the need to process K tail.

Fix condition for identifying the need to process K tail

---

src/cpu/x64/matmul/brgemm_matmul_copy_utils.cpp
src/cpu/x64/matmul/brgemm_matmul_utils.cpp

Backport: fixes failure/segfault in brgemm matmul 

---

src/gpu/intel/jit/v2/conv/bridge.hpp
src/gpu/intel/jit/v2/conv/kernel_desc.cpp
src/gpu/intel/jit/v2/conv/problem.cpp
src/gpu/intel/jit/v2/conv/problem.hpp

Partial fix for https://jira.devtools.intel.com/browse/MFDNN-13188.

xe: conv_v2: disable Stream-K in deterministic mode

---

src/common/sdpa_utils.hpp
src/gpu/intel/jit/gemm/generator/microkernel_provider.cpp
src/gpu/intel/jit/gemm/generator/pieces/k_loop.cxx
src/gpu/intel/jit/gemm/generator/pieces/remask.cxx
src/gpu/intel/jit/gemm/include/generator.hpp
src/gpu/intel/ocl/micro_sdpa.cpp
src/gpu/intel/ocl/micro_sdpa.hpp

This PR fixes several out of resources exceptions and out of bound accesses on DG2 and BMG. These commits addresses MFDNN-13057.

xe: sdpa: Fix several out of resources exceptions in sdpa

---

src/gpu/intel/jit/gemm/generator/microkernel_provider.cpp
src/gpu/intel/jit/gemm/generator/pieces/k_loop.cxx
src/gpu/intel/jit/gemm/generator/pieces/remask.cxx
src/gpu/intel/jit/gemm/include/generator.hpp
src/gpu/intel/ocl/micro_sdpa.cpp

This PR fixes several out of resources exceptions and out of bound accesses on DG2 and BMG. These commits partially addresses MFDNN-13057.

[backport rls-v3.7] xe: sdpa: Fix several out of resources exceptions in sdpa

---

src/graph/backend/dnnl/patterns/sdp.cpp
src/graph/backend/dnnl/patterns/utils.hpp

backport https://github.com/oneapi-src/oneDNN/pull/2640 to enable bf16 sdpa primitive w/ implicit causal mask support.

[backport rls-v3.7] graph: backend: dnnl: enable bf16 sdpa w/ implicit causal mask

---

tests/benchdnn/dnnl_common.cpp
tests/benchdnn/dnnl_common.hpp
tests/benchdnn/doc/knobs_common.md

[backport][rls-v3.7] gpu: nvidia: amd: generic: ignore check-ref-impl

---

src/cpu/x64/jit_avx512_core_amx_conv_kernel.cpp
src/cpu/x64/jit_brgemm_conv_utils.cpp

x64: conv: add limitation for huge shape sizes (backport)

---

src/cpu/x64/jit_avx512_core_amx_conv_kernel.cpp
src/cpu/x64/jit_avx512_core_bf16_convolution.cpp
src/cpu/x64/jit_brgemm_conv_utils.cpp

fixes [MFDNN-13152](https://jira.devtools.intel.com/browse/MFDNN-13152)

x64: conv: fix int overflows (fixes MFDNN-13152)

---

src/cpu/x64/jit_avx512_core_amx_conv_kernel.cpp
src/cpu/x64/jit_avx512_core_bf16_convolution.cpp
src/cpu/x64/jit_brgemm_conv_utils.cpp

x64: conv: fix int overflows (backport)

---

.github/automation/performance/bench_performance.sh
.github/automation/performance/inputs/conv
.github/automation/performance/inputs/eltwise

Update the list of PR performance tests with the most recent and relevant model shapes and ops

ci: aarch64: update PR performance test list

---

src/cpu/x64/jit_avx512_core_amx_conv_kernel.cpp
src/cpu/x64/jit_avx512_core_bf16_convolution.cpp
src/cpu/x64/jit_brgemm_conv_utils.cpp

x64: conv: fix huge shape limitation calculation

---

tests/benchdnn/common.cpp
tests/benchdnn/dnn_types.cpp
tests/benchdnn/dnnl_common.cpp
tests/benchdnn/graph/flex_rewrite.cpp
tests/benchdnn/graph/graph_memory.cpp
tests/benchdnn/graph/ref_primitive.cpp
tests/benchdnn/graph/setting_handler.cpp
tests/gtests/graph/unit/backend/dnnl/test_binary_op.cpp
tests/gtests/graph/unit/backend/dnnl/test_large_partition.cpp
tests/gtests/graph/unit/backend/dnnl/test_matmul.cpp
tests/gtests/graph/unit/backend/dnnl/test_pass.cpp
tests/gtests/graph/unit/backend/dnnl/test_pool.cpp
tests/gtests/test_iface_weights_format.cpp

These are all from the clang-tidy CI step.

tests: address some clang-tidy complaints

---

src/gpu/generic/sycl/batch_normalizations_kernels.hpp
src/gpu/generic/sycl/pooling_kernels.hpp
src/gpu/generic/sycl/sycl_io_helper.hpp
src/gpu/generic/sycl/sycl_utils.hpp
src/xpu/sycl/types.hpp

Fixes clang-format hits, copyright issues from e4c2266026d93285a260d989cb4b6729209f6661.

xpu, gpu: sycl: fixup minor issues

---

src/gpu/intel/jit/v2/conv/kernel_desc_2d_reqs.cpp

xe: conv_v2: fix block 2D reqs generation

---

scripts/verbose_converter/tests/dataset_simple

Addresses [MFDNN-13181](https://jira.devtools.intel.com/browse/MFDNN-13181).

scripts: verbose converter: tests: correct pool driver name

---

tests/benchdnn/inputs/matmul/test_matmul_fp4

Effort to avoid long test times in CPU sim.

Skip ref for fp4 in benchdnn

---

src/gpu/intel/jit/gemm/xe_hp_systolic_gemm.cpp

Addresses [MFDNN-12988](https://jira.devtools.intel.com/browse/MFDNN-12988).

xe: jit: gemm: correct signed/unsigned compare

---

src/cpu/x64/jit_avx512_core_bf16_convolution.cpp

x64: conv: fix potential int overflow

---

tests/benchdnn/inputs/matmul/test_matmul_large_gpu

[GPU] tests: remove large buffer matmul shapes going to ref

---

tests/benchdnn/deconv/deconv.cpp

tests: benchdnn: update skip impl prb on deconv for gpu

---

tests/benchdnn/inputs/matmul/test_matmul_large_gpu

[GPU] [backport] tests: benchdnn: matmul: skip cases going to ref

---

src/cpu/nchw_pooling.cpp

Small changes that improve performance of simple_nchw pooling implementation (nchw_pooling_fwd_t/nchw_pooling_bwd_t) in the following cases: max pooling in forward direction, average pooling in backward direction.
Both versions of the library were built with g++ 8.3.0. Tests run on JF5300-B11A332T.
The script used for testing:
```
export KMP_AFFINITY=granularity=fine,compact,1,0
export OMP_NUM_THREADS=56
export LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH
libiomp5_loc=/home/sdp/akharito/19.0/20210329_000000/lnx32e/compiler/lib/intel64_lin
export LD_PRELOAD=${libiomp5_loc}/libiomp5.so
numactl --physcpubind=0-55 --membind=0 ./benchdnn -v5 --mode=p --pool "$@"
```
| script arguments (56 threads, mb=500) | original (ms) | fixed (ms) | ratio |
| --- | --- | --- | --- |
| --dt=f32:f32 --alg=avg_np …

cpu: pooling: improve nchw_pooling performance

---

src/gpu/intel/jit/codegen/kernel.hpp
src/gpu/intel/jit/ir/config.hpp
src/gpu/intel/jit/ir/ir.hpp
src/gpu/intel/jit/ir/ir_builder.cpp
src/gpu/intel/jit/ir/ir_builder.hpp
src/gpu/intel/jit/ir/tensor.hpp
src/gpu/intel/jit/pooling/config.hpp
src/gpu/intel/jit/reorder/ir_builder.cpp
src/gpu/intel/jit/v2/conv/builder.cpp
src/gpu/intel/jit/v2/conv/gen_convolution.cpp
src/gpu/intel/jit/v2/conv/kernel_desc.cpp
src/gpu/intel/jit/v2/conv/kernel_desc.hpp

(3.8-pc backport) src: gpu: intel: jit: eliminate thread_local expr_t for tgs

---

src/gpu/intel/jit/codegen/kernel.hpp
src/gpu/intel/jit/ir/config.hpp
src/gpu/intel/jit/ir/ir.hpp
src/gpu/intel/jit/ir/ir_builder.cpp
src/gpu/intel/jit/ir/ir_builder.hpp
src/gpu/intel/jit/ir/tensor.hpp
src/gpu/intel/jit/pooling/config.hpp
src/gpu/intel/jit/reorder/ir_builder.cpp
src/gpu/intel/jit/v2/conv/builder.cpp
src/gpu/intel/jit/v2/conv/gen_convolution.cpp
src/gpu/intel/jit/v2/conv/kernel_desc.cpp
src/gpu/intel/jit/v2/conv/kernel_desc.hpp

(3.7 backport) src: gpu: intel: jit: eliminate thread_local expr_t for tgs

---

src/gpu/intel/jit/conv/config.cpp
src/gpu/intel/jit/conv/ir_builder.cpp
src/gpu/intel/jit/conv/lookup_table_data.cpp
src/gpu/intel/jit/conv/plan.cpp
src/gpu/intel/jit/conv/plan.hpp
src/gpu/intel/jit/conv/problem.cpp
src/gpu/intel/jit/conv/tiler.cpp

[backport][GPU] Convolution: improve small IC/OC performance

---

src/cpu/x64/jit_avx2_1x1_conv_kernel_f32.cpp
src/cpu/x64/jit_avx2_conv_kernel_f32.cpp
src/cpu/x64/jit_avx512_common_1x1_conv_kernel.cpp
src/cpu/x64/jit_avx512_common_conv_kernel.cpp
src/cpu/x64/jit_avx512_core_amx_1x1_conv_kernel.cpp
src/cpu/x64/jit_avx512_core_amx_conv_kernel.cpp
src/cpu/x64/jit_avx512_core_bf16_1x1_conv_kernel.cpp
src/cpu/x64/jit_avx512_core_bf16_conv_kernel.cpp
src/cpu/x64/jit_avx512_core_x8s8s32x_1x1_conv_kernel.cpp
src/cpu/x64/jit_avx512_core_x8s8s32x_conv_kernel.cpp
src/cpu/x64/jit_brdgmm_dw_conv.cpp
src/cpu/x64/jit_brgemm_conv_bwd_utils.cpp
src/cpu/x64/jit_brgemm_conv_utils.cpp
src/cpu/x64/jit_primitive_conf.hpp
src/cpu/x64/jit_sse41_1x1_conv_kernel_f32.cpp
src/cpu/x64/jit_sse41_conv_kernel_f32.cpp
src/cpu/x64/jit_uni_dw_conv_kernel_utils.cpp
src/cpu/x64/jit_uni_x8s8s32x_1x1_conv_kernel.cpp
src/cpu/x64/jit_uni_x8s8s32x_conv_kernel.cpp

cpu: conv: disable huge shapes to avoid potential overflows

---

src/cpu/x64/jit_uni_binary_kernel.cpp

[forward-port] cpu: x64: jit_binary_kernel: pass src2_dt unconditionally

---

src/graph/backend/graph_compiler/core/src/runtime/microkernel/cpu/brgemm_onednn.cpp

maintain GC code.
change brgemm to new process , final before use.
Validate by IPEX GC backend. cc @chunyuan-w

graph: backend: graph_compiler: src: fix brgemm coredump issue

---

tests/gtests/test_pooling_forward.cpp

gtest: pool: remove test case with ih=0

---

doc/build/build.md
doc/rst/index.rst

Hi @vpirogov 
The acronym oneDNN has been added on the index page.
The make -j command update has been incorporated.

doc: build: minor fixes

---

src/cpu/x64/jit_brgemm_conv_utils.cpp

cpu: x64: brgemm: update conditions for zp with big ow (#2558)

---

src/common/primitive_attr_quant.cpp
src/common/primitive_attr_quant.hpp
src/common/serialization.hpp
src/gpu/intel/jit/v2/conv/bridge.hpp
src/gpu/intel/jit/v2/conv/builder.cpp
src/gpu/intel/jit/v2/conv/gen_convolution.cpp
src/gpu/intel/jit/v2/conv/kernel_desc.cpp
src/gpu/intel/jit/v2/conv/kernel_desc.hpp
src/gpu/intel/jit/v2/conv/problem.hpp
tests/benchdnn/inputs/conv/option_set_v2

Jira: [MFDNN-13245](https://jira.devtools.intel.com/browse/MFDNN-13245)

[GPU] Shapeless conv: add scales support

---

src/cpu/x64/jit_uni_pool_kernel.cpp

Fix of [MFDNN-13373](https://jira.devtools.intel.com/browse/MFDNN-13373).
Also a message to the log about a shape restrictions failure is added.

cpu: x64: pooling: fix comparison warning

---

src/gpu/intel/jit/generator.hpp

The unique_ptr used for dbg_memory_ is incompatible with the ngen_asm changes.

xe: jit: remove shared virtual memory interface

---

src/gpu/intel/jit/binary_format.cpp
src/gpu/intel/jit/codegen/kernel.hpp
src/gpu/intel/jit/emulated_generator.hpp
src/gpu/intel/jit/gemm/gen_gemm_kernel.cpp
src/gpu/intel/jit/gemm/gen_gemm_kernel.hpp
src/gpu/intel/jit/gemm/include/generator.hpp
src/gpu/intel/jit/generator.hpp
src/gpu/intel/jit/generator_base.hpp
src/gpu/intel/jit/reduction_generator.hpp
src/gpu/intel/jit/v2/conv/kernel_desc.cpp
src/gpu/intel/ocl/engine.cpp
src/gpu/intel/ocl/kernel.cpp
src/gpu/intel/ocl/kernel.hpp
src/gpu/intel/sycl/engine.hpp
src/gpu/intel/sycl/sycl_interop_gpu_kernel.cpp
src/gpu/intel/sycl/sycl_interop_gpu_kernel.hpp
third_party/ngen/ngen_level_zero.hpp
third_party/ngen/ngen_sycl.hpp

Jira: [MFDNN-12443](https://jira.devtools.intel.com/browse/MFDNN-12443)

[GPU] Enable SYCL generator for nGEN kernels

---

src/cpu/x64/brgemm/brgemm_utils.cpp

The code in brgemm_blocking function is awkward and confusing.
This PR is the first step to make it smaller and little bit more readable without changing the logic.

x64: brgemm: blocking function update

---

src/gpu/generic/sycl/README.md
src/gpu/generic/sycl/rnn/cell_common.cpp
src/gpu/generic/sycl/rnn/ref_rnn.cpp
src/gpu/generic/sycl/rnn/rnn_kernels.hpp
src/gpu/generic/sycl/rnn/rnn_utils.hpp
src/gpu/generic/sycl/sycl_primitive_conf.hpp

Expands the SYCL RNN implementation to support r2l, bidirectional concat and sum.

generic: sycl: Adding support for RNN FWD r2l, sum & concat

---

third_party/ngen/ngen_auto_swsb.hpp

Backport of #2935 to `rls-v3.8-pc`.

ngen: update PVC WAR bug workaround

---

src/gpu/intel/ocl/ref_reorder.hpp
tests/benchdnn/reorder/cfg.cpp

Addresses [MFDNN-13418](https://jira.devtools.intel.com/browse/MFDNN-13418).

[GPU] reorder: enable more type combinations

---

scripts/verbose_converter/src/benchdnn_generator.py
scripts/verbose_converter/src/ir.py
scripts/verbose_converter/src/parse.py

Partially addresses [MFDNN-13423](https://jira.devtools.intel.com/browse/MFDNN-13423) by correcting the default tag in binary post ops. Updated CI test sets to follow.
[VC tests](https://intel-ci.intel.com/f00f3acb-d997-f16b-9b43-b49691d8dc7c)

scripts: verbose converter: fix default binary post-op tag + QoL improvements

---

src/cpu/x64/matmul/brgemm_matmul_utils.cpp

Backport: cpu: x64: matmul: correct blocked_B layout initialization

---

src/gpu/intel/jit/gemm/generator/pieces/post_ops.cxx
src/gpu/intel/jit/gemm/include/problem.hpp

[v3.8-pc backport] src: gpu: intel: jit: gemm: add dual (src+wei) vector zero points

---

CITATION.cff
CMakeLists.txt

Update project version (3.8.0 to 3.9.0) in CMakeLists on main branch. PR will be merged right after creation of v3.8 release branch.

Update project version (3.8.0 to 3.9.0) in CMakeLists

---

src/gpu/intel/sycl/l0/utils.cpp

It turns out the atomics support is to be queried in LZ from device module property, and not from device property. This removes the call to OCL to query atomics support and uses the proper query in LZ.
Fixes MFDNN-13201

gpu: intel: sycl: l0: remove dependency to OCL for atomics query

---

src/gpu/intel/sycl/l0/utils.cpp

[backport] gpu: intel: sycl: l0: remove dependency to OCL for atomics query

---

src/cpu/aarch64/jit_brgemm_post_ops.hpp
src/cpu/aarch64/jit_sve_conv_kernel.cpp
src/cpu/aarch64/jit_uni_1x1_conv_utils.hpp
src/cpu/aarch64/jit_uni_deconv_zp_pad_str_kernel.cpp
src/cpu/rnn/cell_common.cpp
src/cpu/rnn/ref_rnn.cpp
src/cpu/rnn/rnn_utils.hpp
src/cpu/x64/jit_avx512_core_amx_conv_kernel.cpp
src/cpu/x64/jit_brgemm_conv_bwd_w.cpp
src/cpu/x64/jit_brgemm_conv_bwd_w.hpp
src/cpu/x64/jit_brgemm_post_ops.cpp
src/cpu/x64/jit_generator.hpp
src/cpu/x64/jit_transpose_utils.cpp
src/cpu/x64/jit_uni_deconv_zp_pad_str_kernel.cpp
src/cpu/x64/jit_uni_reorder.cpp
src/cpu/x64/lrn/jit_avx512_common_lrn_bwd_base.cpp
src/cpu/x64/lrn/jit_avx512_common_lrn_fwd_base.cpp
src/gpu/intel/jit/conv/message_patterns.hpp

fix assert condition with string literals

---

src/cpu/x64/jit_brdgmm_dw_conv.cpp

Brdgmm kernel already has the support of sum w/ data type.

cpu: x64: brdgmm: enable sum with different data type

---

src/cpu/x64/matmul/brgemm_matmul_utils.cpp

Backport: cpu: x64: matmul: update set_or_check_B_tag

---

src/gpu/intel/jit/ir/post_ops.hpp

This partially resolves [MFDNN-13355](https://jira.devtools.intel.com/browse/MFDNN-13355).
'Partially' here means 'to the extent of what can be done from within oneDNN as opposed to the framework using it'.
| #  | main, fp32 (ms) | main, int8 (ms) | PR, int8 (ms) | fp32/int8 (%) | fp32/PR (%) | int8/PR (%) | test (int8) |
|-----|-----|-----|-----|-----|-----|-----|-----|
| 1  | 0.146523   | 0.0968121  | 0.0970956  | 151.34 | 150.90 | 99.70  | --conv --engine=gpu --dir=FWD_D --dt=s8:s8:f32 --stag=acdb --wtag=abcde --dtag=acdb --attr-post-ops=eltwise_swish:1.0 --attr-scales=src0:common:0.5+dst:common:0.5+wei:per_oc --attr-zero-points=src0:common:1 --attr-scratchpad=user g1152mb128_ic1152oc1152_ih7oh7kh3sh1dh0ph1_iw7ow7kw3sw1dw0pw1 |
| 2  | 0.177889   | 0.129435   | 0.129818   | 137.43 | …

src: gpu: intel: jit: ir: add restrictions on conv-based precomputed zps

---

src/gpu/intel/jit/utils/iterator.hpp

Addresses [MFDNN-13336](https://jira.devtools.intel.com/browse/MFDNN-13336).

xe: jit: utils: prefer incrementing tiles by a factor of 2

---

doc/build/build_options.md
doc/graph/fusion_patterns/gqa.md
doc/graph/fusion_patterns/sdpa.md

[rls-v3.8] doc: graph: a few document fixes

---

src/common/matmul.cpp
src/cpu/platform.cpp
src/cpu/reorder/simple_reorder.hpp
src/cpu/x64/jit_uni_reorder_utils.cpp
src/cpu/x64/jit_uni_x8s8s32x_1x1_conv_kernel.cpp
src/cpu/x64/jit_uni_x8s8s32x_1x1_convolution.cpp
src/cpu/x64/jit_uni_x8s8s32x_conv_kernel.cpp
src/cpu/x64/jit_uni_x8s8s32x_convolution.cpp
tests/benchdnn/inputs/matmul/harness_matmul_decompression

[backport][rls-v3.8] Bug fixes, relax matmul weights decompressions condition for a single group

---

tests/benchdnn/graph/input_displacer.cpp
tests/benchdnn/graph/input_displacer.hpp

To support bottom-right casual mask( [RFC ](https://github.com/uxlfoundation/oneDNN/blob/yixin/rfc/graph-api-bottom-right-causal-mask/rfcs/20250314-graph-api-bottom-right-causal-mask/README.md)), Graph API will introduce scalar logical tensor. In current SDPA scenarios, the scalar values are relevant with sequence lengths, hence it requires input displacement with shape information.
The work in the PR includes: 
1. Support scalar displacement for `Add`->`Sub`->`GE` operation chain.
2. Resolve the TODO( [link ](https://github.com/uxlfoundation/oneDNN/blob/633978a82ec14ccc01a9cccaf173e89c25cbbc89/tests/benchdnn/graph/input_displacer.hpp#L37)) in input displacer by moving `fill_cfg` into the displacement arguments.

benchdnn: graph: support input displace for scalar

---

src/gpu/intel/jit/conv/config.cpp
src/gpu/intel/jit/utils/iterator.hpp

[rls-v3.8] [GPU] Conv + reorder heuristics tweaks

---

src/cpu/reorder/simple_reorder.hpp
src/cpu/x64/matmul/brgemm_matmul_reorders.cpp

fixup: common: matmul: allow single scale/zp group of any size (fixes MFDNN-13507)

---

src/gpu/intel/jit/gemm/gen_gemm.hpp

The current initialization is "non-standard". This PR switches to explicitly setting the stride. In addition, the stride selection heuristics were improved after noting poor behavior on size 1 dimensions.

xe: jit: gemm: fix any md initialization

---

src/cpu/x64/jit_avx512_core_x8s8s32x_1x1_conv_kernel.cpp
src/cpu/x64/jit_avx512_core_x8s8s32x_1x1_convolution.cpp
src/cpu/x64/jit_avx512_core_x8s8s32x_1x1_convolution.hpp

cpu: x64: fix using new scale mask interface

---

src/cpu/aarch64/acl_eltwise.cpp
src/cpu/aarch64/jit_uni_eltwise_int.cpp

cpu: aarch64: fix is_dense check for eltwise

---

src/graph/backend/dnnl/kernels/mqa_decomp_config.cpp
src/graph/backend/dnnl/passes/transform.cpp

Fix the `lift_up_post_add_for_matmul`. Remove the add op as a consumer.

graph: backend: dnnl: fix the lift_up_post_add_for_matmul pass

---

src/gpu/intel/ocl/binary_common.h
src/gpu/intel/ocl/gen9_binary.cl
src/gpu/intel/ocl/gen9_binary.cpp
src/gpu/intel/ocl/gen9_binary.hpp
src/gpu/intel/ocl/simple_binary.cl
src/gpu/intel/ocl/simple_binary.cpp
src/gpu/intel/ocl/simple_binary.hpp
src/gpu/intel/primitive_conf.hpp
tests/benchdnn/binary/binary.cpp

Backport of https://github.com/uxlfoundation/oneDNN/pull/3010 and https://github.com/uxlfoundation/oneDNN/pull/3078

[rls-v3.8] gpu: binary: enable select algorithm

---

src/cpu/x64/matmul/brgemm_matmul_reorders.cpp

Fixes [MFDNN-13463](https://jira.devtools.intel.com/browse/MFDNN-13463).

cpu: x64: matmul: add missing CHECK

---

src/gpu/intel/ocl/multi_po_reorder_binary.hpp

Addresses [MFDNN-10726](https://jira.devtools.intel.com/browse/MFDNN-10726).

xe: binary: expand support for reorder-based impl

---

src/cpu/x64/jit_avx512_core_amx_conv_kernel.cpp
src/cpu/x64/jit_brgemm_conv_utils.cpp

Fixes MFDNN-12878
Before commit:
> perf,cpu,brg_conv_fwd:avx10_1_512_amx,,--mode=CP --conv --allow-enum-tags-only=false --dt=u8:s8:f32 --stag=acb --dtag=acb --attr-scales=wei:per_oc --attr-zero-points=src:common:1 --attr-scratchpad=user mb1ic32iw43264oc32ow43264kw11pw5,0.97459,7813.32,**45.6975**,21.327,46.4772,20.9692
After commit:
> perf,cpu,brg_conv_fwd:avx512_core_vnni,,--mode=CP --conv --allow-enum-tags-only=false --dt=u8:s8:f32 --stag=acb --dtag=acb --attr-scales=wei:per_oc --attr-zero-points=src:common:1 --attr-scratchpad=user mb1ic32iw43264oc32ow43264kw11pw5,0.97459,56.5872,**0.0576172**,16914.9,0.0636223,15318.4

cpu: x64: conv: disable zp with large zp buffer on AMX

---

src/gpu/intel/ocl/ref_convolution.cl

Fixes: [MFDNN-13440](https://jira.devtools.intel.com/browse/MFDNN-13440)
Backport of:
- https://github.com/uxlfoundation/oneDNN/pull/3099

[backport][rls-v3.8] fixup: gpu: conv: post-op mem access

---

src/gpu/intel/jit/gemm/gen_gemm.hpp

[GPU] Fixup gemm acc, zp limit (rls-v3.8)

---

src/gpu/intel/jit/gemm/gen_gemm.hpp

Port 2 fixes from #2916 that cause invalid strategies to be generated: 
- Disable weights zp in cases where weights are not upconverted during decompression. 
- Use float accumulator for cases with 2d weights scale.
Fixes # [MFDNN-13351](https://jira.devtools.intel.com/browse/MFDNN-13351)

[GPU] Fixup gemm acc, zp limit

---

src/gpu/intel/ocl/ref_convolution.cl

Fixes: [MFDNN-13440 ](https://jira.devtools.intel.com/browse/MFDNN-13440)

fixup: gpu: conv: post-op mem access

---

src/gpu/intel/jit/codegen/codegen.cpp

Jira: [MFDNN-13505](https://jira.devtools.intel.com/browse/MFDNN-13505)

xe: jit: reduce header register reuse

---

src/gpu/intel/ocl/gemm_matmul.hpp

[GPU] Apply GEMM dim fixup to src scale (rls-v3.8)

---

src/cpu/x64/brgemm/jit_brgemm_amx_uker.cpp

backport https://github.com/uxlfoundation/oneDNN/pull/3107

[v3.8 backport] cpu: x64: ip: fix integer overflow in offsets

---

src/gpu/intel/jit/emulated_generator.cpp

[GPU] xe: jit: copyright fix

---

src/graph/backend/dnnl/kernels/sdp_decomp.cpp
src/graph/backend/dnnl/kernels/sdp_decomp_config.cpp

Add datatype check for K and V in the decompose kernel.

graph: backend: dnnl: add datatype check for K and V

---

src/gpu/intel/jit/gemm/generator/pieces/copy_plan.cpp

Closes MFDNN-13566. The copy planner was correctly catching violations of the PVC byte swizzling restrictions due to non-trivial subregister offsets, but it wasn't actually fixing them.

xe: jit: gemm: offset legalization for PVC byte swizzle rules

---

src/gpu/intel/ocl/bnorm/gen9_bnorm_bwd.cl
src/gpu/intel/ocl/generic_reorder.cl
src/gpu/intel/ocl/micro_sdpa.cl
third_party/ngen/ngen_opencl.hpp

Backport of:
- https://github.com/uxlfoundation/oneDNN/pull/3178

[rls-v3.8] fixup: xe: ocl kernel warning fix

---

src/gpu/intel/ocl/ocl_overrides.md

PR documents cl_opt_disable option that was involved by https://github.com/uxlfoundation/oneDNN/pull/3188

[GPU] ocl: document cl_opt_disable option

---

src/gpu/intel/jit/gemm/gen_gemm.hpp
src/gpu/intel/ocl/gemm_matmul.hpp

Backport of #3195 
[Nightly Scope CI](https://ecmd.jf.intel.com/commander/link/jobDetails/jobs/f0264480-c23c-f168-b840-a4bf010d0e2d?objectId=job-f0264480-c23c-f168-b840-a4bf010d0e2d&filterName0=jobsPageSearch&filterDepth=1)

[GPU][rls-v3.8] Fix gemm batch dim handling

---

src/gpu/intel/jit/codegen/reorder.hpp

Addresses [MFDNN-13607](https://jira.devtools.intel.com/browse/MFDNN-13607).

xe: jit: codegen: align src regs to grf boundary for null dst

---

src/gpu/intel/ocl/gemm_matmul.hpp

Port #3209 .
[CI LINK](https://ecmd.jf.intel.com/commander/link/jobDetails/jobs/f029d09a-f8d3-f196-8181-a4bf010d0e2d?objectId=job-f029d09a-f8d3-f196-8181-a4bf010d0e2d&filterName0=jobsPageSearch&filterDepth=1)
[Build CI](https://ecmd.jf.intel.com/commander/link/jobDetails/jobs/f029f491-5486-f185-b840-a4bf010d0e2d)

[GPU] Fix build warning

---

src/gpu/intel/compute/kernel_ctx.hpp
src/gpu/intel/config.hpp
src/gpu/intel/jit/conv/lookup_table.cpp
src/gpu/intel/jit/gemm/generator/pieces/problem_utils.cpp
src/gpu/intel/jit/gemm/generator/strategy_parser.cpp
src/gpu/intel/microkernels/shim.cpp
third_party/ngen/ngen_interface.hpp
third_party/ngen/ngen_opencl.hpp

[rls-v3.8] xe: fix locale handling

---

src/gpu/intel/jit/conv/config.cpp
src/gpu/intel/jit/gemm/generator/pieces/address_setup.cxx
src/gpu/intel/jit/gemm/generator/pieces/loop_sequencer.cpp
src/gpu/intel/jit/gemm/generator/pieces/loop_sequencer.hpp
src/gpu/intel/jit/ir/blocking.hpp
src/gpu/intel/jit/ir/primitive_plan.hpp
src/gpu/intel/jit/ir/problem.cpp
src/gpu/intel/jit/ir/slm_reduce_builder.hpp
src/gpu/intel/jit/pass/simplify.cpp
src/gpu/intel/jit/v2/conv/kernel_desc.cpp
src/gpu/intel/jit/v2/conv/plan_registry.cpp
src/gpu/intel/jit/v2/conv/planner/search.cpp
third_party/ngen/ngen_auto_swsb.hpp
third_party/ngen/ngen_emulation.hpp
third_party/ngen/ngen_sycl.hpp

Addresses most current Coverity hits.
Includes a fix for a compilation warning with DPC++ 2025.2.

[GPU] address coverity hits

---

src/gpu/intel/ocl/gemm_matmul.hpp

[GPU][rls-v3.8] Allow matmul dim reshape with some post-ops

---

src/gpu/intel/ocl/gemm_matmul.hpp

Fix perf regression introduced by #3195 . Allow reshaping dimensions of batched gemms with broadcast dims when the dim being eliminated will not impact the correctness of batched post-ops. Previously this was too strict and stoped reshape on cases that could support it correctly. 
Fixes [MFDNN-13632](https://jira.devtools.intel.com/browse/MFDNN-13632)

[GPU] Allow matmul dim reshape with some post-ops

---

src/gpu/intel/ocl/reduction/atomic_reduction.cpp

Addresses [MFDNN-13454](https://jira.devtools.intel.com/browse/MFDNN-13454). The heuristic that decides when to use atomic reductions in the ocl:atomic implementation was overly cautious (since using atomic reductions requires additional pre- and post-work overhead). This relaxes the heuristic to allow atomic reductions when there is enough reduction workload to justify the overhead (i.e. each thread's time is significant compared to the overhead).
See end-to-end performance data below. Since reduction is often only a small portion of model execution times, reduction performance is more extreme - typically around 2x improvement on affected models and up to 3x at the model level and 15x at the layer level.
ATS-M + DG2:
|                                model/primitive …

xe: reduction: improve atomic reduction heuristic

---

doc/ukernel/operations/transform.md
examples/ukernels/cpu_brgemm.cpp
include/oneapi/dnnl/dnnl_ukernel.h
include/oneapi/dnnl/dnnl_ukernel.hpp
src/cpu/x64/ukernel/brgemm.cpp
src/cpu/x64/ukernel/brgemm.hpp
src/cpu/x64/ukernel/transform.hpp

PR implements the first part of the proposal from https://github.com/uxlfoundation/oneDNN/pull/2893 and also updates some cosmetics leftovers from older PRs.

ukernel: exception free mode

---

src/cpu/x64/matmul/amx_blocking_heuristics.cpp
src/cpu/x64/matmul/brgemm_matmul_utils.cpp
src/cpu/x64/matmul/brgemm_matmul_utils.hpp

[backport] x64: matmul: Fix nthr issues in matmul

---

tests/benchdnn/common.cpp
tests/benchdnn/utils/task.hpp

More precise timing for GPU on Linux now.

benchdnn: fix case timer for parallel creation scenario

---

src/cpu/x64/matmul/amx_blocking_heuristics.cpp
src/gpu/intel/jit/gemm/gen_gemm.hpp
src/gpu/intel/ocl/gemm_matmul.hpp

Revert batch GEMM fixes for rls-v3.9-pc only to preserve functional and performance behavior for frameworks, fixes will continue in main and frameworks will need to correct behavior for rls-v3.9. 
Fixes # [MFDNN-3651](https://jira.devtools.intel.com/browse/MFDNN-13651)

[GPU] Revert batch GEMM fixes for v3.9-pc

---

src/gpu/intel/jit/conv/plan.cpp
src/gpu/intel/jit/conv/tiler.cpp
src/gpu/intel/jit/pass/strength_reduce.cpp

[GPU] Convolution: fixups and workarounds to address regressions

---

cmake/platform.cmake
src/cpu/x64/jit_uni_reorder_direct_copy.cpp
tests/benchdnn/dnnl_memory.cpp
tests/benchdnn/matmul/matmul.cpp
tests/benchdnn/self/compare.cpp
tests/benchdnn/self/norm.cpp
tests/benchdnn/self/res.cpp
tests/benchdnn/utils/parser.cpp

[MFDNN-13672](https://jira.devtools.intel.com/browse/MFDNN-13672)
[MFDNN-13191](https://jira.devtools.intel.com/browse/MFDNN-13191)

Benchdnn validation fixes, jit_direct_copy reorder fix, sanitizer fixes (fixes MFDNN-13672, MFDNN-13191)

---

src/gpu/nvidia/cudnn_convolution.hpp

Introducing checks for the padding of winograd convolution in nvidia backend ensuring that padding is not larger than the filter in each respective dimension. Resolves failing benchdnn configurations:
```
./tests/benchdnn/benchdnn --mode-modifier=P --conv --engine=gpu --stag=nhwc --alg=wino ic16ih10oc16oh18kh3ph5
./tests/benchdnn/benchdnn --mode-modifier=P --conv --engine=gpu --alg=wino mb32ic16ih10oc16oh18kh3ph5
```
see MFDNN-13298
- [ x ] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [ x ] Have you formatted the code using clang-format?

gpu: nvidia: Add checks for wino conv

---

src/gpu/intel/jit/codegen/reduce.hpp

Jira: [MFDNN-13715](https://jira.devtools.intel.com/browse/MFDNN-13715)

xe: jit: fix bf16 -> f32 reduce

---

src/gpu/intel/jit/gemm/gen_gemm.hpp
src/gpu/intel/jit/gemm/jit_gemm_pd.cpp
src/gpu/intel/jit/gemm/jit_gemm_pd.hpp
src/gpu/intel/jit/gemm/xe_hp_systolic_gemm.cpp

Refactor jit::gemm attr handling:
- hoist into jit_gemm_pd.
- apply to both jit:gemm and jit:xe_hp, fixing some validation gaps.
- separate initialization and checking for supported cases.
Fixes # https://jira.devtools.intel.com/browse/MFDNN-13625

[GPU] Refactor GEMM attr handling

---

src/cpu/x64/jit_uni_reorder_direct_copy.cpp

cpu: x64: jit_reorder: direct_copy: restrict plain-strided cases

---

src/cpu/cpu_convolution_list.cpp
src/cpu/cpu_deconvolution_list.cpp
src/cpu/x64/jit_brgemm_conv_bwd_strided.cpp
src/cpu/x64/jit_brgemm_conv_utils.cpp
src/cpu/x64/jit_brgemm_deconv.cpp

cpu: x64: enable hf8 support for conv, deconv on AVX10.2

---

third_party/ngen/ngen_emulation.hpp

Fix region advance in case of crossing register boundary, correctly set offset.
Fixes # MFDNN-13705

[NGEN] Fixup region advance for emulation

---

LICENSE

Update to copyrights in LICENSE file.

common: update LICENSE copyrights

---

src/gpu/intel/jit/conv/config.cpp

Jira: [MFDNN-13707](https://jira.devtools.intel.com/browse/MFDNN-13707)

xe: conv: drop incorrect move

---

src/gpu/intel/jit/gemm/generator/pieces/post_ops.cxx

Addresses [MFDNN-12906](https://jira.devtools.intel.com/browse/MFDNN-12906). Binary postops are loaded and executed one-at-a-time currently. This PR improves performance of binary post-ops by grouping load operations together, improving memory access.
This is from BMG, but other platforms have similar performance gains. This lists all models with >10% change (no regressions observed):
|                                                    model                                                               |  e984ded81  |  5a319fa7c  | ratio |
| :--------------------------------------------------------------------------------------------------------------------- | ----------: | ----------: | ----: |
| p0.minicpm-1b-sft.FP16-4BIT.inf.fp16.ov.baseline_mb32 …

xe: jit: gemm: group binary postop loads

---

.github/automation/performance/inputs/reorder_nightly
.github/workflows/ci-aarch64.yml

- skip performance tests for MacOS
- increase shape for reorder perf tests to avoid false positives

ci: aarch64: update performance tests

---

src/cpu/x64/matmul/amx_blocking_heuristics.cpp

fix performance degradation related to issue:
https://jira.devtools.intel.com/browse/MFDNN-13324

cpu: x64: matmul: fix blocking heuristics for l2 set issues

---

src/cpu/x64/jit_uni_reorder.cpp

Fixes MFDNN-13835
fp8 pooling on NVL will hit an assertion about "invalid isa or fp8 emulation not available" in jit_uni_reorder and then cause failure. Enabling fp8 support in reorder on NVL can fix this issue.
Example of failing case:
```c++
DNNL_MAX_CPU_ISA=AVX10_2_512 sde -nvl -- ./tests/benchdnn/benchdnn -v5 --pool --dt=f8_e4m3:f8_e4m3 --alg=avg_p ic32iw300ow151kw3sw2pw1
create: --pool --dt=f8_e4m3:f8_e4m3 --alg=avg_p ic32iw300ow151kw3sw2pw1
benchdnn: src/cpu/x64/jit_uni_reorder.cpp:626: dnnl::impl::cpu::x64::tr::jit_uni_reorder_kernel_f32_t::process_unroll_generic_step(int, const int*, const int*, const int*, const int*, const int*, bool)::<lambda(Xbyak::Xmm, const Xbyak::Operand&, dnnl::impl::data_type_t)>: Assertion `!"invalid isa or fp8 emulation not " "available"' failed. …
```

cpu: x64: enable fp8 support in reorder on NVL

---

src/gpu/intel/jit/gemm/jit_gemm_pd.cpp

Fixes build warning in vs2022/ocl.

[GPU] Fixup implicit conversion

---

cmake/platform.cmake

This PR adds support for dynamically detecting whether the current RISC-V toolchain supports RVV intrinsics (version 1.0) during CMake configuration. Based on the result, it sets the appropriate `-march` flag automatically:
- `-march=rv64gcv` if RVV intrinsics are supported
- `-march=rv64gc` otherwise
Leverages the existing CAN_COMPILE_RVV_INTRINSICS CMake variable — originally used to check RVV intrinsic support — to dynamically set the -march flag at configure time.
Validated using the riscv-gnu-toolchain version 14.2. The toolchain was built with support for the RISC-V Vector Extension (RVV) version 1.0, and the dynamic -march flag selection logic worked correctly during the CMake configuration and build.
This enables clean and portable builds of oneDNN across RISC-V toolchains with or …

build: risc-v: dynamic selection of -march for RV64

---

src/cpu/x64/jit_brgemm_conv_utils.cpp

cpu: x64: conv: fix segfault for f16

---

src/cpu/x64/jit_brgemm_conv_utils.cpp

brgemm convolution: blocking: update efficiency estimation including extra loop removing

---

tests/benchdnn/graph/utils.hpp

So far, there are some feature gaps between Intel GPU and Nvidia GPU, as these gaps can't be fixed in short term, related cases always report unsuccessful status in benchdnn graph, we need to skip those cases on NV GPU.

tests: benchdnn: graph: add skip logic for NV GPU

---

src/cpu/x64/brgemm/brgemm_containers.cpp
src/cpu/x64/jit_brgemm_1x1_conv.hpp

Backport: cpu: x64: fix brgemm_1x1_convolution core dump

---

src/gpu/intel/ocl/simple_layer_normalization.cl

Fixes: [MFDNN-13882 
](https://jira.devtools.intel.com/browse/MFDNN-13882)

gpu: intel: lnorm: fix total_sum scope

---

doc/build/build_options.md

The link has been corrected as per the product validation check.

doc: build: corrected link

---

src/gpu/intel/jit/gemm/gen_gemm.cpp
src/gpu/intel/jit/gemm/gen_gemm.hpp
src/gpu/intel/jit/gemm/jit_gemm_pd.cpp
src/gpu/intel/jit/gemm/jit_gemm_pd.hpp
tests/benchdnn/inputs/matmul/harness_matmul_3d_bcast

- Separate handling for edge case dim counts with non-trivial grouped attr.
- Fix scale batch offset computation
- Additional test cases
- Fix type initialization for zp in cases with `swap_ab`
Fixes # [MFDNN-13688](https://jira.devtools.intel.com/browse/MFDNN-13688)

[GPU] Fixup gemm attr

---

src/gpu/intel/jit/gemm/jit_gemm_pd.cpp

Addresses [MFDNN-13869](https://jira.devtools.intel.com/browse/MFDNN-13869). Quantized wei attributes were not appropriately detecting per_ocic cases that are equivalent to per_oc cases (which can be optimized further) due to dimension ordering issues. This is a quick fix to restore performance.

xe: gemm: fixup per_oc zp detection

---

tests/benchdnn/graph/allocator.cpp
tests/benchdnn/graph/allocator.hpp
tests/benchdnn/graph/graph_memory.cpp
tests/benchdnn/graph/memory_pool.hpp

complete task of JIRA 13799.
enable a simple benchdnn graph cpu mem_pool as gpu mem_pool.

tests: benchdnn: graph: enable cpu mem_pool

---

src/graph/backend/dnnl/passes/lower.cpp

graph: backend: dnnl: add reduction dimention check for NV GPU

---

CITATION.cff
CMakeLists.txt

Update project version (3.9.0 to 3.10.0) in CMakeLists and CITATION on main branch.

Update project version (3.9.0 to 3.10.0) in CMakeLists and CITATION

---

src/cpu/x64/brgemm/jit_brdgmm_kernel.cpp
src/cpu/x64/brgemm/jit_brgemm_amx_uker.cpp
src/cpu/x64/brgemm/jit_brgemm_kernel.cpp
src/cpu/x64/jit_brgemm_post_ops.cpp
src/cpu/x64/jit_generator.hpp
src/cpu/x64/jit_uni_reorder.cpp
src/cpu/x64/utils/jit_io_helper.cpp
src/cpu/x64/utils/jit_io_helper.hpp

cpu: x64: fix correct when using int8 sat cvt

---

src/cpu/x64/brgemm/jit_brdgmm_kernel.cpp
src/cpu/x64/brgemm/jit_brgemm_amx_uker.cpp
src/cpu/x64/brgemm/jit_brgemm_kernel.cpp
src/cpu/x64/jit_brgemm_post_ops.cpp
src/cpu/x64/jit_generator.hpp
src/cpu/x64/jit_uni_reorder.cpp
src/cpu/x64/utils/jit_io_helper.cpp
src/cpu/x64/utils/jit_io_helper.hpp

Backport: cpu: x64: fix correct when using int8 sat cvt (#3516)

---

src/gpu/intel/jit/conv/ir_builder.cpp
src/gpu/intel/jit/conv/plan.cpp

xe: conv: fix bias type initialization

---

src/cpu/x64/jit_uni_binary.cpp

backport of https://github.com/uxlfoundation/oneDNN/pull/3570

x64: binary: fix op_type assertion (backport)

---

src/gpu/intel/jit/conv/ir_builder.cpp

Backport of https://github.com/uxlfoundation/oneDNN/pull/3573.

xe: conv: fix bias reduce condition

---

include/oneapi/dnnl/dnnl_common_types.h
include/oneapi/dnnl/dnnl_types.h
src/gpu/intel/jit/CMakeLists.txt
src/gpu/intel/jit/v2/conv/planner/CMakeLists.txt
src/gpu/intel/jit/v2/conv/planner/bench.cpp
src/gpu/intel/jit/v2/conv/planner/bench.hpp

[GPU] Fix build error after compiler update

---

src/cpu/x64/matmul/brgemm_matmul_copy_utils.cpp

cpu: x64: matmul: correct bf16 conversion in copy_b_transpose

---

src/gpu/intel/compute/device_info.cpp
src/gpu/intel/compute/device_info.hpp
src/gpu/intel/jit/codegen/kernel.hpp
src/gpu/intel/jit/generator.hpp
src/gpu/intel/jit/ir/hw.hpp
src/gpu/intel/jit/utils/ngen_type_bridge.hpp
src/gpu/intel/ocl/device_info.cpp
src/gpu/intel/ocl/hw_info.cpp
src/gpu/intel/ocl/hw_info.hpp
src/gpu/intel/sycl/device_info.cpp
src/gpu/intel/sycl/l0/utils.cpp
src/gpu/intel/sycl/l0/utils.hpp

Fixes [MFDNN-13917](https://jira.devtools.intel.com/browse/MFDNN-13917).

xe: jit: workaround hardware read suppression bug 

---

src/cpu/rnn/ref_rnn.cpp
src/cpu/rnn/rnn_utils.hpp
src/cpu/x64/gemm/gemm_driver.cpp
src/cpu/x64/rnn/brgemm_cell_common_fwd.cpp
src/cpu/x64/rnn/brgemm_cell_common_fwd.hpp
src/cpu/x64/rnn/rnn_brgemm_utils.cpp

Backport of [PR #3291](https://github.com/uxlfoundation/oneDNN/pull/3291) to 3.8

Fix performance regression in RNN

---

src/gpu/intel/jit/ir/message.cpp
tests/gtests/internals/test_sdpa.cpp

Found in the latest Coverity report.

Fix erroneous fallthrough

---

src/graph/backend/dnnl/kernels/sdp_primitive_config.cpp

[rls-v3.9] graph: backend: dnnl: enable f32 sdpa with gpu ukernel

---

doc/graph/fusion_patterns/sdpa.md
examples/CMakeLists.txt
examples/graph/sdpa_bottom_right_causal_mask.cpp
include/oneapi/dnnl/dnnl_graph.h
include/oneapi/dnnl/dnnl_graph.hpp
src/graph/backend/dnnl/common.cpp
src/graph/backend/dnnl/common.hpp
src/graph/backend/dnnl/kernels/large_partition.cpp
src/graph/backend/dnnl/op_executable.hpp
src/graph/interface/logical_tensor.hpp
src/graph/interface/tensor.cpp
src/graph/interface/tensor.hpp
tests/benchdnn/graph/graph_memory.cpp
tests/gtests/graph/api/test_cpp_api_tensor.cpp

[rls-v3.9] api: graph: fix scalar tensor creation and usage

---

src/cpu/cpu_reduction_list.cpp
src/cpu/ref_reduction.cpp
src/cpu/ref_reduction.hpp

[MFDNN-13875](https://jira.devtools.intel.com/browse/MFDNN-13875)

cpu: reduction: remove templated arguments from ref impl

---

src/graph/backend/dnnl/passes/utils.cpp
tests/gtests/graph/api/test_c_api_compile.cpp
tests/gtests/graph/unit/backend/dnnl/test_subgraph_pass.cpp

Fix MFDNN-13459 and MFDNN-13693

graph: backend: dnnl: disable conv binary fusion on NV GPU

---

tests/gtests/internals/test_sdpa.cpp

Partial backport of #3602 and backport of #3652.

[rls-v3.9] Backport Coverity + UBSan SDPA test fixes

---

src/gpu/generic/ref_sum.hpp

This addresses [MFDNN-13947](https://jira.devtools.intel.com/browse/MFDNN-13947).

src: gpu: intel: sycl: do not wait on graph recording

---

tests/gtests/internals/test_sdpa.cpp
tests/gtests/internals/test_utils.hpp

Additional synchronization was necessary for the SYCL runtime to function properly and avoid intermittent failures. 
Fixes: [MFDNN-13937](https://jira.devtools.intel.com/browse/MFDNN-13937)

xe: sdpa: test: additional synchronization in write for sycl runtime

---

src/cpu/rnn/rnn_utils.hpp
src/cpu/x64/jit_avx512_core_bf16_conv_kernel.cpp
src/cpu/x64/jit_avx512_core_x8s8s32x_conv_kernel.cpp
src/cpu/x64/jit_brgemm_conv_utils.cpp
src/cpu/x64/matmul/amx_blocking_heuristics.cpp

backport of https://github.com/uxlfoundation/oneDNN/pull/3637 and https://github.com/uxlfoundation/oneDNN/pull/3672

x64: fix major coverity issues (backport)

---

src/cpu/x64/rnn/brgemm_cell_common_fwd.cpp

This PR is a continuation of [#3291](https://github.com/uxlfoundation/oneDNN/pull/3291) and contains a performance regression fix for problems mentioned in [MFDNN-12215](https://jira.devtools.intel.com/browse/MFDNN-12215) when OpenMP library is used (only for AVX2 as in #3291).
Performance comparison between the version 3.3.3, the main branch, and this PR for the problems mentioned in MFDNN-12215 follows (8 threads were used):
```
ADL (Intel(R) Core(TM) i9-12900) + OpenMP,  8 threads, ms
3.3.3   main   pr
1     0.137   0.23  0.092
2     0.139   0.22  0.096
3     0.133   0.22  0.089
4     0.139   0.21  0.092
9     0.126   0.25  0.137
10    0.132   0.24  0.139
11    0.54    0.42  0.42
12    0.55    0.42  0.42
(Problems 5-8 are the same as 1-4; 13-16 are the same as 9-12)
```
Performance for …

Fix performance regressions in RNN

---

src/graph/backend/dnnl/passes/lower.cpp
src/graph/backend/dnnl/passes/utils.cpp
tests/benchdnn/inputs/graph/complex_fusion/harness_mha_all

backport https://github.com/uxlfoundation/oneDNN/pull/3670 to rls-v3.9.

[backport] graph: backend: dnnl: support sdpa training with a special case of kv_seq_len=1

---

src/common/utils.cpp

Fix compile errors on Windows
Fixes #3698

Fix for #3698

---

src/graph/backend/dnnl/passes/transform.cpp

graph: backend: dnnl: disable concat support with 0 dim src on NV GPU

---

.github/automation/aarch64/skipped-tests.sh
src/cpu/aarch64/jit_uni_reorder.cpp
src/cpu/aarch64/matmul/brgemm_matmul_reorders.cpp
tests/benchdnn/inputs/reorder/harness_reorder_compensation

**Original PRs:**
- #3733
- #3718 
- #3724

Backport into v3.9 of aarch64 reorder bug-fixes

---

RELEASE_NOTES.md

This PR includes a release notes draft based on the information from the PRs for the contributors to review. Your additions and corrections are highly appreciated.

oneDNN v3.9 release notes

---

src/gpu/intel/jit/gemm/generator/pieces/copy.cxx

addresses [MFDNN-13916](https://jira.devtools.intel.com/browse/MFDNN-13916)

xe: jit: gemm: add sync before copy_plan

---

src/cpu/x64/jit_uni_reorder.cpp

cpu: x64: jit_reorder: no fast_return if compensation needed

---

src/gpu/intel/sdpa/micro.cl
src/gpu/intel/sdpa/micro.cpp

This pull request introduces improvements to the SDPA (Scaled Dot-Product Attention) microkernel implementation for Intel GPUs, mainly to better support Grouped Query Attention (GQA) and more accurately handle "thin" query cases. The changes affect both the OpenCL kernel (`micro.cl`) and its configuration and launch logic in C++ (`micro.cpp`). The most important changes are summarized below:
* Updated the kernel launch and indexing logic in the `micro_sdpa` kernel to batch query tokens across the N dimension of the KQ and VS kernels when processing second token GQA cases. This reframes the kernel logic for the KQ matmul by treating the groups of queries in the same KV group as a separate token.
* Moved the calculation of tile offsets (`sg_i0_kq`, `sg_j0_kq`) outside of the main loop in …

xe: sdpa: Optimize GQA 2nd token cases by batching accross kv groups

---

src/gpu/intel/conv/jit/config.cpp

Jira: [MFDNN-14065](https://jira.devtools.intel.com/browse/MFDNN-14065)
Theoretically the implementation should support loads for any post-op layouts but need to test first.

xe: conv: drop post-op layout check

---

src/graph/backend/dnnl/fusion_info.cpp

Segfault issue for Gemma sdpa case in decompose kernel, found in local test, missed part of changes for select, original CI didn't catch such issue, it was caused by code rebase in #3748

graph: backend: dnnl: fix post select md creation

---

src/gpu/intel/gemm/jit/generator/pieces/copy.cxx

closes [MFDNN-14048](https://jira.devtools.intel.com/browse/MFDNN-14048)

[GPU] fixup sync in copy plan

---

src/common/host_scalar_memory_storage.hpp

Fixes [MFDNN-14098](https://jira.devtools.intel.com/browse/MFDNN-14098).
The issue is with older GCC compiler complaining on out-of-bounds access, that shouldn't be true, as there are checks for allowed sizes in place.
Extending checks just in case and also changing to more straightforward copy.
// possible alternative is to add ~ignore pragma

common: minor refactoring to resolve compiler warning

---

src/cpu/x64/matmul/brgemm_matmul_utils.cpp

Fixed B transform LDB2 which can cause a segfault.

cpu: x64: matmul: Fixed B transform LDB2

---

src/cpu/x64/matmul/brgemm_matmul_utils.cpp

backport of:
https://github.com/uxlfoundation/oneDNN/pull/3782

cpu: x64: matmul: Fixed B transform strides

---

src/cpu/x64/brgemm/jit_brgemm_amx_uker.cpp

fixes issue:
https://jira.devtools.intel.com/browse/MFDNN-14092

cpu: x64: jit_brgemm_amx_uker: Fixed amx ops count for prefetch

---

README.binary.in
README.md
doc/programming_model/data_types.md

Updated tables on data type support to make them pretty.

doc: updated data type support tables for clarity

---

src/cpu/aarch64/jit_uni_dw_conv_kernel_utils.hpp
tests/benchdnn/inputs/conv/harness_conv_regression_general

Backport https://github.com/uxlfoundation/oneDNN/pull/3755

cpu: aarch64: fix scratchpad memory initialization

---

src/gpu/intel/gemm/jit.hpp
src/gpu/intel/gemm/jit/pd.cpp
src/gpu/intel/gemm/jit/pd.hpp

 [GPU][rls-v3.9] Loosen GEMM k-parallel restriction for attrs

---

src/gpu/intel/jit/gemm/jit_gemm_pd.cpp

Backport of [PR3860](https://github.com/uxlfoundation/oneDNN/pull/3860) .

[GPU][rls-v3.9] Fixup post-ops k-parallel skip

---

cmake/platform.cmake

The Zvfh extension, an optional extension of the RISC-V V (Vector) extension which was ratified in June 2023, enables FP16 SIMD operations. Utilizing FP16 can boost neural network performance, as it potentially doubles the number of elements processed per vector instruction while also reducing memory bandwidth.
The implementation checks for Zvfh support after confirming the presence of the base Vector (V) extension. It uses `check_cxx_source_compiles` with the `-march=rv64gcv_zvfh` flag. If the toolchain supports Zvfh, the build system will:
- Set the appropriate `-march` flag to enable Zvfh for compilation.
- Define the `DNNL_RISCV_USE_ZVFH_INTRINSICS` preprocessor macro, allowing C++ code to conditionally compile Zvfh-specific intrinsic paths.
If Zvfh is not available, the build system …

cpu: risc-v: build: add Zvfh extension support detection

---

src/gpu/intel/jit/ir/epilogue.cpp
tests/benchdnn/inputs/conv/test_conv_regression_gpu

Jira: [MFDNN-14081](https://jira.devtools.intel.com/browse/MFDNN-14081)

fixup: xe: conv: drop post-op layout check

---

src/gpu/intel/matmul/gemm.hpp

Addresses [MFDNN-14112](https://jira.devtools.intel.com/browse/MFDNN-14112). Recent changes try to preempt failing cases, but they were too strict. Instead, we rely on the return status of `memory_desc_reshape` directly to skip reshaping.
Bit of context: the `md_ok` check was added before the `safe_reshape` check was added. The latter is the better solution (allowing more cases through reshapes), making the `md_ok` checks obsolete.

xe: gemm: relax reshaping requirements

---

src/gpu/intel/jit/codegen/reorder.cpp

Addresses [MFDNN-14118](https://jira.devtools.intel.com/browse/MFDNN-14118).

xe: jit: dispatch to 2d reorder more often

---

src/gpu/intel/conv/jit/tiler.cpp

Jira: [MFDNN-14011](https://jira.devtools.intel.com/browse/MFDNN-14011)
PR skips tiles that include batch dimension with NCHW layouts. Otherwise we end up with both tile dimensions being strided which is usually very inefficient. Also added a check to not use NCHW with backward by weights and bias to avoid costly reduction due to non-matching register layouts.

xe: conv: fix tile selection for NCHW

---

src/gpu/intel/compute/kernel_arg_list.hpp

PR to address request in [MFDNN-14152](https://jira.devtools.intel.com/browse/MFDNN-14152).
Locally validated with internal micro sdpa changes.

gpu: intel: extend append to support host storage

---

src/cpu/x64/matmul/brgemm_matmul_utils.cpp

this fixes:
https://jira.devtools.intel.com/browse/MFDNN-14097

cpu: x64: matmul: fix wei_n_blk when using a b buffer

---

src/gpu/intel/gemm/jit/generator/pieces/compute_utils.hpp
src/gpu/intel/gemm/jit/generator/pieces/copy.cxx
src/gpu/intel/gemm/jit/generator/pieces/gemm.cxx
src/gpu/intel/gemm/jit/generator/pieces/gemm_setup.cxx
src/gpu/intel/gemm/jit/generator/pieces/k_loop.cxx
src/gpu/intel/gemm/jit/generator/pieces/layout_utils.cpp
src/gpu/intel/gemm/jit/generator/pieces/problem_utils.cpp
src/gpu/intel/gemm/jit/generator/pieces/register_allocation.cxx
src/gpu/intel/gemm/jit/generator/pieces/register_layout.cpp
src/gpu/intel/gemm/jit/generator/pieces/tlb_warmup.cxx
src/gpu/intel/gemm/jit/generator/strategy_parser.cpp
src/gpu/intel/gemm/jit/include/gemmstone/problem.hpp

Syncs gemmstone from the upstream repository, and fixes some minor formatting issues.

xe: gemm: gemmstone sync

---

src/graph/utils/pm/nested_matcher.cpp

Fix nullptr dereference at error logging in graph::utils

---

src/gpu/intel/jit/gemm/gen_gemm.hpp
src/gpu/intel/ocl/gemm/gemm_with_post_ops.hpp
src/gpu/intel/ocl/rnn/grid.cpp

Backport of https://github.com/intel-innersource/libraries.performance.math.onednn/pull/3925 .

[GPU][rls-v3.9] GEMM IP Fix 

---

src/cpu/matmul/ref_matmul.cpp

Fix for int4-mlp failure.
Fixes MFDNN-14220

cpu: matmul: int4 decompression fixup

---

src/gpu/intel/include/math_utils.h
src/gpu/intel/sdpa/micro.cl

PR fixes https://jira.devtools.intel.com/browse/MFDNN-14197,

[GPU] SDPA: fix ukernel bf16 to float conversion

---

src/gpu/intel/gemm/jit/generator/pieces/copy.cxx
src/gpu/intel/gemm/jit/generator/pieces/copy_plan.cpp

Addresses [MFDNN-14114](https://jira.devtools.intel.com/browse/MFDNN-14114).

xe: copy plan: extend max SIMD to cover at most 2 GRFs

---

cmake/FindBLAS.cmake
cmake/TBB.cmake
cmake/host_compiler_id.cmake
cmake/options.cmake
cmake/win/TBBConfig.cmake

Please include a summary of the change. Please also include relevant motivation and context. See [contribution guidelines](https://github.com/uxlfoundation/oneDNN/blob/main/CONTRIBUTING.md) for more details. If the change fixes an issue not documented in the project's Github issue tracker, please document all steps necessary to reproduce it.
fix typos

cmake: fix typos

---

src/cpu/matmul/gemm_bf16_matmul.cpp
src/cpu/matmul/gemm_f32_matmul.cpp

It was found during implementing [MFDNN-13994](https://jira.devtools.intel.com/browse/MFDNN-13994) that GeMM-Matmul works very slowly in some cases for fp32 tensors. The reason was in creation of a kernel that processes post-ops in cases when this could be avoided. Then the kernel run using all available threads which introduced significant overhead.
The case of bf16 tensors is not reproducible using RNN but is similar.
This PR fixes this performance issue.
Measured on SPR CPU.
fp32
```
main branch:
$ OMP_NUM_THREADS=48 ./tests/benchdnn/benchdnn --mode=p --matmul --dt=f32 --attr-post-ops=sum:2.0 256x1:1x256
Output template: perf,%engine%,%impl%,%name%,%prb%,%Gops%,%+ctime%,%-time%,%-Gflops%,%0time%,%0Gflops%
perf,cpu,gemm:jit:f32,,--mode=P --matmul --attr-post-ops=sum:2 …
```

cpu: matmul: do not use redundant kernel

---

src/cpu/aarch64/jit_uni_dw_convolution.cpp

Fixed the jit_uni_dw_convolution_bwd_weights_t kernel by changing trimming to be done on a per oh basis (rather than calculated at the block level). This would allow us to enable/fix the following test in PyTorch: https://github.com/pytorch/pytorch/blob/edd9e07aff2b2256ffe267ae4d72d27b67185ca4/test/nn/test_convolution.py#L533

cpu: aarch64: fix jit 256 bwd weights path

---

src/common/matmul.cpp
src/gpu/intel/gemm/jit.hpp
src/gpu/intel/gemm/jit/gen_kernel.cpp
src/gpu/intel/gemm/jit/gen_kernel.hpp
src/gpu/intel/gemm/jit/generator/microkernel_provider.cpp
src/gpu/intel/gemm/jit/generator/pieces/gemm_setup.cxx
src/gpu/intel/gemm/jit/generator/pieces/k_loop.cxx
src/gpu/intel/gemm/jit/generator/pieces/quantization.cxx
src/gpu/intel/gemm/jit/include/gemmstone/kernel_selector.hpp
src/gpu/intel/gemm/jit/include/gemmstone/strategy.hpp
src/gpu/intel/gemm/jit/selector/kernel_selector.cpp
tests/benchdnn/inputs/matmul/harness_matmul_decompression
tests/benchdnn/matmul/ref_matmul.cpp
tests/benchdnn/utils/numeric.hpp

closes [MFDNN-13798](https://jira.devtools.intel.com/browse/MFDNN-13798)

[GPU] Add gemm support for gs16 weights decompression.

---

.github/automation/aarch64/bisect_ctest.py
.github/automation/aarch64/ctest_utils.py
.github/automation/aarch64/git_bisect.sh
.github/automation/aarch64/wiki_utils.py
.github/workflows/ci-aarch64.yml
.github/workflows/nightly-aarch64.yml

- Increase git bisect coverage
- Fix perf tests not running in precommit

ci: aarch64: fixes for git bisect, perf, and wiki pipelines

---

src/cpu/x64/jit_brgemm_conv.cpp
src/cpu/x64/jit_brgemm_conv.hpp
src/cpu/x64/jit_brgemm_conv_comp_pad_kernel.cpp
src/cpu/x64/jit_brgemm_conv_utils.cpp
src/cpu/x64/jit_primitive_conf.hpp

Backport: cpu: x64: improve performance for brgconv w/zp that using large buffer

---

CITATION.cff
CMakeLists.txt

Updated project version (3.10.0 to 3.11.0) in CMakeLists and CITATION on main branch. Will be merged after release branch creation.

Updated project version (3.10.0 to 3.11.0) in CMakeLists and CITATION 

---

src/cpu/aarch64/matmul/acl_matmul_utils.cpp

There were issues were memory tag formats that shouldn't have been accepted were accepted by gemm:acl. The reason behind this is discussed here https://github.com/uxlfoundation/oneDNN/issues/2175#issuecomment-2431603405.
For example, the case:
--matmul --stag=adbc --wtag=adbc --dtag=acbd 14x6x1x253:1x1x253x1_n"dot_prod_w_B_full_bcast"
Now correctly skips gemm:acl and falls to gemm:jit, whereas before it failed.
- [Y] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [Y] Have you formatted the code using clang-format?
- [Y] Have you submitted performance data that demonstrates performance improvements?
- [Y] Have you included information on how to reproduce the issue (either in a github issue or in this PR)?
- [Y] Have you added …

cpu: aarch64: memory stride detection update
