uxlfoundation/oneDNN

- tests/gtests/CMakeLists.txt
- tests/gtests/mkldnn_test_common.hpp
- tests/gtests/test_batch_normalization.cpp
- tests/gtests/test_concat.cpp
- tests/gtests/test_convolution_relu_forward_common.hpp
- tests/gtests/test_eltwise.cpp
- tests/gtests/test_inner_product_forward.cpp
- tests/gtests/test_lrn_backward.cpp
- tests/gtests/test_lrn_forward.cpp
- tests/gtests/test_relu.cpp
- tests/gtests/test_sum.cpp
make precision-losing type conversions explicit.
warnings from a particularly paranoid compiler, sxc++, generally for:
- double->float,
- int->float,
- size_t->int and
- float|double -> some data_t
> gtests typeconversions

- include/mkldnn.hpp
- src/cpu/cpu_simple_concat.hpp
- src/cpu/cpu_simple_sum.hpp
- src/cpu/gemm_convolution.hpp
- src/cpu/gemm_convolution_utils.cpp
- src/cpu/ref_batch_normalization.cpp
- src/cpu/ref_eltwise.cpp
- src/cpu/ref_lrn.cpp
- src/cpu/simple_reorder.hpp
- tests/gtests/test_eltwise.cpp
- more int vs size_t issues
- simple_reorder has many changes where the conversion to data_t<type_o>
is done a little too early. 
- one case of moving the alpha,beta test
up a few lines in ker lambda ker (to mirror other cases).
- Also a couple of cases where intermediate calcs are forced to
float/double, and then finally converted to some data_t.
(some of these may need to be revisited for int data_t support, later,
but at least the conversions are visible in the code for now.)
ref_eltwise decides to keep intermediate values as floating point.
... (oh, I think it slipped my mind to keep the corresponding gtests calcs with double )
> More type conversion stuff.

- CMakeLists.txt
UNIT8_MAX and similar macros are not part of C++ standard. Must define
__STDC_LIMIT_MACROS and __STDC_CONSTANT_MACROS before using that.
See https://stackoverflow.com/questions/986426/
> Fix compile error about UNIT8_MAX not defined

- tests/benchdnn/conv/conv.hpp
Running benchdnn for tests that requires a lot of memory sometimes results in segfaults. The real issue is an integer overflow in several inlined functions that are used to calculate memory allocation size.
> Int promotion in benchdnn

- tests/benchdnn/mkldnn_memory.hpp
" /* Is it ugly enough? */ " ... I used to be OK with this correct code, but ...
... now it is generates an ICE in the new compiler we're running for the NEC Aurora vector processor. This PR seems to circumvent the ICE. The common-code ugliness is moved to a new private *initialize* function, and the constructor idioms look simpler and more similar.
The "if (active_) reorder(...)" mod seems pedantically OK, but please think about it.
I like the most recent release. :+1:
> ICE workaround for nc++

- scripts/prepare_mkl.sh
some systems do not have curl available, it will be nice to check for availability of either curl or wget.
> check for curl or wget availability in prepare_mkl script

- README.md
The new MKL-DNN backend is merged ([9677](https://github.com/apache/incubator-mxnet/pull/9677)) into MXNET master branch.
Add a link to MXNET.
> Add MKL-DNN based deep learning framework

- src/common/inner_product_pd.hpp
Fix inner product pd query errors.
> Inner product pd change

- include/mkldnn.hpp
- include/mkldnn_types.h
I am trying to add a sentinel to enum type `mkldnn_memory_format_t` in mkldnn_types.h. So from framework side, we can set dedicated unit test to monitor the data format change in mkldnn. If new data format is added to mkldnn, we need check framework code to see if code should be adjusted to handle the new data format.
Since a PR should be submitted to mxnet to change the dependency version of mkldnn. If data format is changed in the new version of mkldnn, the dedicated test case will be failed at pre-checkin phase. So this kind of error will not happen in user's workloads.
> Add sentinel to enum type mkldnn_memory_format_t

- include/mkldnn.hpp
Extend pooling API for Tensorflow integration.
- add pooling_forward::primitive_desc::src_primitive_desc()
- add pooling_backward::primitive_desc::diff_dst_primitive_desc()
> Add src_primitive_desc to pooling primitive desc

- cmake/MKL.cmake
- cmake/platform.cmake
When using the gold linker on Linux systems the build fails due to a linkage error. The root cause is that the MKL-ML library uses libdl for shared object functions such as `dlopen` and `dladdr` but does not explicitly link against it. With the (default) BFD linker this does not pose a problem because it resolves these symbols transitively from libiomp5.so's dependency to libdl. However the gold linker has stricter rules for symbol resolution and does not look up transitive references.
See [this link](https://fedoraproject.org/wiki/GoldIncompatibilities) for more information about the incompatibilities between gold and BFD linkers.
Below is the typical `undefined reference` error when building with the gold linker:
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CCXX_FLAGS='-fuse-ld=gold' .. …
```
> build: link to libdl

- tests/benchdnn/common.cpp
fix compiler "specified bound equals destination size [-Werror=stringop-truncation]" warning as error message.
> fix stringop-truncation

- README.md
The DeepLearning4J framework also uses MKL-DNN by default now if you use the nd4j-native-platform as the backend dependency. 
See https://github.com/deeplearning4j/deeplearning4j/pull/5622 for the commit.
> Add DL4J to README.md

- scripts/prepare_mkl.bat
- scripts/prepare_mkl.sh
Fix ` scripts/prepare_mkl.sh` and `.bat` to avoid downloading `mklml` twice when executing it again.
> Avoid downloading `mklml` twice

- src/cpu/gemm/gemm.cpp
Using volatile for synchronization is unsafe: https://github.com/google/sanitizers/wiki/ThreadSanitizerAboutRaces#volatile
This popped up in one of our test under thread sanitizer.
> Fix data race in gemm.cpp

- src/common/utils.hpp
`__FUNCSIG__` is not defined on MINGW, but we can use `__PRETTY_FUNCTION__` instead.
> fix compilation error on MINGW

- cmake/OpenMP.cmake
I would like to propose this change that allows linking against the Intel OpenMP runtime (if found) even if mkl-dnn is not built with MKL.
> Allow linking to Intel OpenMP runtime without MKL

- cmake/MKL.cmake
This change limits the searching for mkl_rt only in the lib path corresponding to the include path where `mkl_cblas.h` is found. This change makes the distinguish bewteen MKL and MKLML more reliable, when the system has both of them installed in different locations.
> Better handling of full mkl / mklml check

- src/cpu/cpu_reducer.hpp
- src/cpu/gemm/gemm.hpp
- src/cpu/gemm/gemm_utils.hpp
- src/cpu/jit_avx512_common_convolution_winograd.hpp
- src/cpu/jit_uni_dw_conv_kernel_f32.hpp
- src/cpu/jit_uni_eltwise.hpp
- src/cpu/jit_uni_lrn_kernel_f32.hpp
- src/cpu/jit_uni_pool_kernel_f32.hpp
Currently, code that uses the specializations in question will
accidentally and erroneously specialize the primary template. The
reason this appears to "work" is a pure accident due to the way the
linker currently works. The code violates the one-definition-rule,
and all programs depending on it are ill-formed, no diagnostic
required (i.e. running all such programs has undefined behaviour).
Additionally, declaring explicit instantiations is also good
practice, since it declares intent and prevents accidental later
explicit specializations (it would be an error to declare those
after the extern declaration of the explicit instantiation had been
seen).
Explicit specializations and instantiations are declared in .hpp
files near the respective template.
(Found by @tkoeppe by compiling with …
> Add declarations of explicit specializations and instantiations.

- src/cpu/jit_generator.hpp
- src/cpu/jit_uni_eltwise.cpp
`vcvtps2dq(vmm_aux1 | h->T_rd_sae, vmm_src);` rounds down.
Then,
* vcmpps with _cmp_nle_us always returns False
* vmm_aux3 is always set to zero
* vsubps does not change vmm_aux1
So these three mnemonics are not necessary.
> vcmpps is unnecessary

- src/cpu/jit_uni_i8i8_pooling.cpp
@tprimak 
please distribute.
Tested together with PR #467 and separately with the following configs:
> --cfg=s8 --cfg=u8
> --dir=FWD_I --tag=acdb --alg=AVG ic23ih60iw60oh31ow31kh3kw4sh2sw2ph1pw1n"wip"
> --dir=FWD_I --tag=acdb --alg=AVG ic14ih60iw60oh31ow31kh3kw2sh2sw2ph1pw1n"wip"
> --dir=FWD_I --tag=acdb --alg=AVG ic17ih60iw60oh31ow31kh4kw3sh2sw2ph1pw1n"wip"
> --dir=FWD_I --tag=acdb --alg=AVG ic14ih60iw60oh31ow31kh2kw3sh2sw2ph1pw1n"wip"
> --dir=FWD_I --tag=acdb --alg=AVG ic25ih60iw60oh31ow31kh2kw4sh2sw2ph1pw1n"wip"
> --dir=FWD_I --tag=acdb --alg=AVG ic28ih60iw60oh31ow31kh4kw2sh2sw2ph1pw1n"wip"
Not tested
> --dir=FWD_I --tag=acdb --alg=AVG ic528ih14oh14kh3ph1n"googlenet_v1:inception_4e/pool"
> 
> #avx2 #slightly incorrect result.
> --dir=BWD_D --tag=aBcd8b --alg=AVG …
> src: cpu: jit i8 pooling: avx2: fix src load mask for i8 average

- src/common/utils.cpp
- src/common/utils.hpp
- src/common/verbose.cpp
GCC9 causing build failure:
recipe-sysroot/usr/include/bits/string_fortified.h:106:34: error: 'char* __builtin_strncpy(char*, const char*, long unsigned int)'
output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
|   106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
|       |
Signed-off-by: Naveen Saini <naveen.kumar.saini@intel.com>
> common: utils: fix potential string truncation in mkldnn_getenv()

- doc/primitives/eltwise.md
- include/mkldnn.hpp
- include/mkldnn_types.h
- src/common/c_types_map.hpp
- src/common/eltwise.cpp
- src/common/math_utils.hpp
- src/common/mkldnn_debug_autogenerated.cpp
- src/common/primitive_attr.cpp
- src/cpu/jit_uni_eltwise.cpp
- src/cpu/jit_uni_eltwise.hpp
- src/cpu/ref_eltwise.cpp
- tests/benchdnn/dnn_types.cpp
- tests/benchdnn/dnn_types.hpp
- tests/benchdnn/eltwise/bench_eltwise.cpp
- tests/benchdnn/eltwise/eltwise.cpp
- tests/benchdnn/inputs/eltwise/test_eltwise_all
- tests/benchdnn/inputs/eltwise/test_eltwise_bfloat16
- tests/gtests/test_convolution_eltwise_forward_common.hpp
- tests/gtests/test_convolution_eltwise_forward_f32.cpp
- tests/gtests/test_convolution_eltwise_forward_x8s8f32s32.cpp
- tests/gtests/test_eltwise.cpp
Hi,
Changes discussed here are introducing support to SWISH activation (https://arxiv.org/pdf/1710.05941.pdf)
as part of a eltwise primitve
Scope of changes:
- CPU only (no GPU support)
- Reference and unified jitted FWD
- Reference BWD
- unit tests 
- benchDNN extented for swish eltwise
> Swish activation support

- tests/CMakeLists.txt
- tests/generate_c_symbols_refs.sh
This fixes up the test script and cmake call to just use the shell, rather than
requiring /bin/bash explicitly, and removes some bashisms. This is relevant for
packaging on distributions/containers that may not have this layout. A run of
the script produces the same output as before.
pass locally?
github issue or in this PR)?
> tests/generate_c-symbols_refs.sh: do not require /bin/bash explicitly

- src/cpu/gemm/f32/jit_avx_gemv_t_f32_kern.cpp
Removed duplicate check for non-negative unroll_y
Please include a summary of the change. Please also include relevant
motivation and context. See
[contribution guidelines](https://github.com/intel/mkl-dnn/blob/master/CONTRIBUTING.md)
for more details. If the change fixes an issue not documented in the project's
Github issue tracker, please document all steps necessary to reproduce it.
pass locally?
github issue or in this PR)?
> [jit] redundant non-negative unroll_y check

- src/cpu/CMakeLists.txt
https://github.com/intel/mkl-dnn/pull/658 introduced a regex list filter to src/cpu/CMakeLists.txt
This feature is only available for Cmake 3.6 onwards which will cause the build to fail if `DNNL_ENABLE_JIT_PROFILING` is not set (e.g. for an AArch64 build) an the host machine has CMake 3.5 or older.
This patch replaces with `filter(REMOVE_ITEM ...` for compatibility with older versions of Cmake.
Note: this should not be encountered by the standard commit tests. Builds on AArch64 will encounter this line, but with no AArch64 CI this will not get tested. I hope to address this with a PR or RFC in the very near future.
Fixes # no issue raised.
pass locally?
_yes, but given it's a CMake change outside the scope of the current CI, it's not entirely relevant.)
_no changes made to sources._
_not …
> build: replace unnecessary use of CMake 3.6 feature

- cmake/platform.cmake
As discussed in #679, building `/src/cpu/jit_avx512_common_convolution_winograd.cpp` on AArch64 with `-Werror` causes a build failure as a result of the warning about over aligned types.
To reproduce (building with GCC 9.2 on AArch64, RHEL 8)...
```
mkdir build
cd build
cmake -DDNNL_WERROR=ON ..
make -j
```
Results in errors of the form:
```
src/cpu/jit_avx512_common_convolution_winograd.cpp: In function ‘void dnnl::impl::cpu::input_transform_data(int, const dnnl::impl::cpu::jit_conv_winograd_conf_t&, float*, float*, bool)’:
src/cpu/jit_avx512_common_convolution_winograd.cpp:434:46: warning: requested alignment 64 is larger than 16 [-Wattributes]
434 |     alignas(64) float Iw[alpha][alpha][simd_w];
|                                              ^
```
...builds without `-DDNNL_WERROR=ON` …
> bug: do not error on overaligned types in AArch64 build.

- tests/gtests/test_gemm_common.hpp
Following on from the discussion in #678, this PR disables the Packed GEMM tests for non x86 targets.
Fixes #678 
- [partial] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`)
pass locally?
Note, owing to the scope of the changes, full benchdnn tests have not been run. Passes unit tests and validation on AArch64 builds as shown here: https://cloud.drone.io/nSircombe/mkl-dnn/10
Demo CI for AArch64 discussed in #679 defend against regression.
github issue or in this PR)?
> bug: testing: dissables Packed GEMM test for non-x86 targets

- tests/benchdnn/dnnl_memory.cpp
Please include a summary of the change. Please also include relevant
motivation and context. See
[contribution guidelines](https://github.com/oneapi-src/oneDNN/blob/master/CONTRIBUTING.md)
for more details. If the change fixes an issue not documented in the project's
Github issue tracker, please document all steps necessary to reproduce it.
pass locally?
github issue or in this PR)?
> Fix libsysinfo detection on BSDs because libsysinfo is an external library there.

- .github/automation/.drone.yml
- cmake/platform.cmake
This PR corrects a mistake in the AArch64 Drone CI Clang pipeline introduced in #694.
Currently the .drone.yaml config fails to set `CC=clang` and `CXX=clang++` causing the build and test to run with GCC (this can be seen in the existing logs, see [line 1090](https://cloud.drone.io/oneapi-src/oneDNN/8/2/2)).
In addition, AArch64 specific changes to `DEF_ARCH_OPT_FLAGS`, and disabling of `DNNL_ENABLE_JIT_PROFILING` added with #658 for GCC are replicated for the Clang build in `cmake/platform.cmake`.
pass locally?
Unit tests pass with clang and gcc, but `test_benchdnn_bnorm_cpu` *failed* with clang build. This will need further investigation, and I would like to pursue as a separate issue. Fixing this bug will facilitate this. 
Not …
> bug: build: ci: fix Clang builds for AArch64 CI.

- src/common/utils.hpp
Signed-off-by: caozhong <zhong.z.cao@intel.com>
IDIV slows down tight loop. In one of my poking, loop suffers extreme stall. Observable in VTune and tests
Before patch:
perf,cpu,--reorder --sdt=f32 --ddt=f32 --stag=nChw8c --dtag=nchw 1x256x14x14,5.0176e-05,0.0151367,3.31485,0.0164791,3.04482
perf,cpu,--reorder --sdt=f32 --ddt=f32 --stag=nChw16c --dtag=nchw 1x256x14x14,5.0176e-05,0.00805664,6.22791,0.00891358,5.62917
After patch:
perf,cpu,--reorder --sdt=f32 --ddt=f32 --stag=nChw8c --dtag=nchw 1x256x14x14,5.0176e-05,0.00756836,6.62971,0.00818725,6.12856
perf,cpu,--reorder --sdt=f32 --ddt=f32 --stag=nChw16c --dtag=nchw 1x256x14x14,5.0176e-05,0.00683594,7.34003,0.0074625,6.72375
8c have 1/4 instructions compare to 16c in inner loop.
> IDIV hurts performance of loop

- rfcs/20200106-prelu/README.md
[Rendered document](https://github.com/piotrchmiel/oneDNN/tree/prelu_rfc/rfcs/20200106-prelu)
RFC concerns introduction of PRelu support in oneDNN. PReLU is specific variant of LeakyReLU, where alpha is learnable parameter. Full motivation is described inside document.
> rfc: introduce prelu primitive

- rfcs/20200609-logsigmoid/README.md
[Rendered document](https://github.com/piotrchmiel/oneDNN/tree/logsigmoid/rfcs/20200609-logsigmoid)
RFC concerns introduction of logsigmoid op support in oneDNN. Full motivation is described inside document.
> rfc: introduce logsigmoid support

- src/cpu/x64/jit_uni_reorder.cpp
Cache blocking heuristic for uni reorder was hard to fix in general, even with cache blocking done right, its complexity O(n^2) still quite high for cache reside cases. for example, when reorder from blocking format, write complexity killed the performance. This implementation use 8x8 or 16x16 SIMD transpose to deal with reorder, generally improve reorder performance in nchw <--> nChw(X)c cases, and both directions can have comparable performance.
- [ ✅] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally?
- [✅] Have you formatted the code using clang-format?
- [No need ] Have you added relevant tests?
- [ No need] Have you provided motivation for adding a new feature?
- [No need ] Have you added relevant regression tests?
- [No need?] Have you included …
> Improve reorder performance in single blocking format cases

- cmake/FindBLAS.cmake
- cmake/options.cmake
- doc/build/build_options.md
This PR updates the work simplify vendor BLAS based builds on AArch64 contained in #741 
1. Documentation is updated to detail the `DNNL_BLAS_VENDOR` option.
In the list of options, only `NONE` and `ARMPL` are given as values for `DNNL_BLAS_VENDOR`.  A new sub-section "Vendor BLAS Libraries" has been added with further details - this also lists `MKL`, `OPENBLAS` and `ANY` as permitted values for debug / development. These are already mentioned in `cmake/options.cmake`, so could be omitted from the docs here if the preference is not to list such development options.
2. Updates FindBLAS to work with the free version of Arm Performance Libraries
When linking to `libarmpl_lp64_mp.so` there is now an explicit dependence on `libgfortran` - this was not required in subscription product, as this …
> build: document DNNL_BLAS_VENDOR and add support for Free ArmPL.

- src/common/bfloat16.hpp
- tests/gtests/CMakeLists.txt
- tests/gtests/internals/CMakeLists.txt
- tests/gtests/internals/test_bfloat16.cpp
Avoids a potentially lossy float-bfloat16-float round-trip for `b += a`,
when `a` is a 32-bit `float` and `b` is a `bfloat16_t`. Might yield a
significant performance improvement.
> bfloat16: add operator+=(a) overload for float as argument type

- src/CMakeLists.txt
Compatible with vs2017/2019 cmake.
> Fix Windows CMake when build as submodule

- src/common/bfloat16.hpp
- tests/gtests/internals/test_bfloat16.cpp
Added a converting constructor and an assignment operator template from
any integer type to `bfloat16_t`. Allows significantly faster conversion
and assignment from integer than when using `bfloat16_t(float)` or
`operator=(float)`, by avoiding an `fpclassify(f)` call, and skipping
the cases for denormal floats and NaNs.
> bfloat16: faster conversion and assignment from integer types

- src/cpu/gemm_convolution_utils.cpp
Declared the local variable `zero_val` within the function body of
`im2col` const, to avoid the following error from a Release build of
Visual Studio 2019 version 16.7.1 (compiler version 19.27.29111 for x64):
> D:\oneDNN\src\cpu\gemm_convolution_utils.cpp(401): fatal error C1001: Internal compiler error.
> (compiler file 'd:\agent\_work\7\s\src\vctools\Compiler\Utc\src\p2\main.c', line 195)
>  To work around this problem, try simplifying or changing the program near the locations listed above.
> If possible please provide a repro here: https://developercommunity.visualstudio.com
> Please choose the Technical Support command on the Visual C++
>  Help menu, or open the Technical Support help file for more information
>   CL!RaiseException()+0x69
>   CL!RaiseException()+0x69
> …
> cpu: make local zero_val const, to avoid internal compiler error vs2019

- rfcs/20200207-global-primitive-cache/README.md
Promoting an updated RFC on global primitive cache in oneDNN which should've been promoted several months ago (it was approved internally and implemented).
> rfc: global primitive cache support

- rfcs/20200731-Using-Arm-Compute-Library-kernels-on-AArch64/README.md
The goal for this RFC is to demonstrate an approach for providing optimized implementations of machine learning operators in oneDNN, on AArch64, based on the open-source [Arm Compute Library](https://github.com/arm-software/ComputeLibrary).
[Rendered document](https://github.com/diaena/oneDNN/tree/arm-rfc/rfcs/20200731-Using-Arm-Compute-Library-kernels-on-AArch64)
Others involved: @nSircombe [@cfRod](https://github.com/cfRod)  [@alenik01](https://github.com/alenik01)
> rfc: prototype integration with ArmCL

- rfcs/20200428-openvino-int8-support/README.md
This is a small fixup for the RFC "Openvino int8 pipeline support (#765)". This change simplifies the way memory is provided to execute() when multiple post ops are used. Implementation already uses new approach (commit: db23af2edd518e6c0d90716d50a28c607ce67719).
> fixup: rfc: openvino int8 pipeline support (#765)

- src/cpu/x64/jit_avx512_core_amx_1x1_convolution.cpp
```
mkl-dnn/src/cpu/x64/jit_avx512_core_amx_1x1_convolution.cpp:151:28: internal compiler error: in maybe_undo_parenthesized_ref, at cp/semantics.c:1705
size_t dst_offset = (is_1d) ? dst_d.blk_off(mb, oc, ow)
^~~~~~~~~~
```
@CaoZhongZ
> workaround gcc internal error

- rfcs/20200804-primitive-fallback/README.md
This RFC presents several options for a potential primitive fallback mechanism in oneDNN.
[Link to rendered document](https://github.com/sbogusev/oneDNN/blob/sbogusev/rfc_primitive_fallback/rfcs/20200804-primitive-fallback/README.md)
> rfc: primitive fallback

- rfcs/20200820-dpcpp-primitives/README.md
This RFC describes a proposal on introducing a mechanism for writing DPCPP kernels in the library.
[Link to the rendered document](https://github.com/oneapi-src/oneDNN/blob/6be508f9054f80e5af163cdb22c43605c0781196/rfcs/20200820-dpcpp-primitives/README.md)
> rfc: add support for DPCPP primitives

- rfcs/20200618-headers/README.md
This RFC suggests a change in oneDNN headers structure and introduces a new oneapi-friendly namespace.
[Rendered document](https://github.com/rsdubtso/mkl-dnn/tree/rsdubtso/rfcs/headers/rfcs/20200618-headers)
Tagging @nSircombe, @kruus, @kawakami-k. Unfortunately, this is urgent.
> rfc: headers and namespaces structure

- rfcs/20200713-benchdnn-ci-input-files/README.md
[Rendered document](https://github.com/oneapi-src/oneDNN/tree/dzarukin/rfcs/new_ci_inputs/rfcs/20200713-benchdnn-ci-input-files)
RFC concerns update of benchdnn input files for CI validation. Motivation and further details are inside the document.
> rfc: update benchdnn ci input files

- .github/automation/.drone.yml
- .github/automation/build.sh
- .github/automation/build_acl.sh
Recent work (#820) added Arm Compute Library as an optional dependency for Aarch64 builds. This is currently absent from the AArch64 CI running on Drone CI.
This PR implements additional stages in `.drone.yml` which build oneDNN against Compute Library and run the CI.
An additional shell script, `build_acl.sh` has been added to clone and build Compute Library.
_Note: due to a clash of macro names between oneDNN and Compute Library (specifically STRINGIFY), the oneDNN build will fail with -Werror, as used for CI runs. To avoid this, STRINGIFY in Compute Library is renamed before the build.
This clash will be corrected in a future Compute Library release._
- [ X ] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally?
- [ not applicable ] Have you formatted …
> ci: adds ACL build to CI on aarch64.

- rfcs/20201102-convert-verbose-into-benchdnn-problem/README.md
This RFC describes a proposal for a tool that will allow to convert DNNL_VERBOSE output into benchdnn problems. Thanks @echeresh for a valuable input.
[Link to a rendered document](https://github.com/dzarukin/oneDNN/tree/dzarukin/rfcs/verbose_to_benchdnn/rfcs/20201102-convert-verbose-into-benchdnn-problem).
> rfc: convert verbose output into benchdnn problems

- src/cpu/aarch64/jit_uni_reorder.cpp
- src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64_util.h
This is a small fixup for the issue mentioned in #871 (an odd number printed when the first primitive descriptor is created on Aarch64).
> src: cpu: aarch64: remove debug prints

- src/cpu/aarch64/acl_gemm_convolution.hpp
- src/cpu/aarch64/acl_gemm_convolution_utils.cpp
This PR introduces minor modifications to enable the support of NHWC (`acdb`) memory layout on AArch64. At the moment it is not supported, because Arm Compute Library requires use of the same tags for all three tensors. Such a layout leads to 20% - 40% speedup on AArch64 compared to the default `abcd` for the use-cases like ResNet50 and VGG19.
The relevant changes are introduced in acl\_gemm\_convolution\_utils.cpp. Also the value of GEMM\_IMPL\_STR was changed to "gemm:acl" in acl\_gemm\_convolution.hpp, which allows to track the calls to ACL with `DNNL_VERBOSE=2`.
- [N/A] Does RFC document …
> Enabling the support of `acdb` memory layout on AArch64

- rfcs/20201011-max-pooling-with-global-indices/README.md
This RFC proposes a way to support global indices feature for a max pooling operation.
Link to a rendered document: https://github.com/oneapi-src/oneDNN/tree/dzarukin/rfcs/max_pooling_global_indices/rfcs/20201011-max-pooling-with-global-indices
> rfc: api: define max pooling with global indices

- rfcs/20201202-dnnl-verbose-extension/README.md
This RFC proposes a DNNL_VERBOSE functionality extensions with timestamps providing an ability to log oneDNN calls properly during application execution.
[Link to a rendered document](https://github.com/dzarukin/oneDNN/tree/dzarukin/rfcs/dnnl_verbose_extension/rfcs/20201202-dnnl-verbose-extension)
> rfc: dnnl_verbose_extension

- rfcs/20201119-change-memory-init-behavior/README.md
This RFC describes issues related to memory initialization with respect to zero padding blocked data and presents a few options to address the issue. 
[Link to the rendered document](https://github.com/oneapi-src/oneDNN/tree/rjoursle/rfcs_change_memory_init_behavior/rfcs/20201119-change-memory-init-behavior)
> rfc: memory: change memory to reduce zero_pad overhead

- .github/automation/.drone.yml
- .github/automation/build_acl.sh
This PR updates the version of Arm Compute Library used in the DroneCI
pipelines, introduced with #853, to the latest release
[20.11](https://arm-software.github.io/ComputeLibrary/v20.11/).
With 20.11, the `STRINGIFY` macro present in previous Compute Library releases
has been renamed, and no longer conflicts with oneDNN. As a result, the
work-around implemented [previously](https://github.com/oneapi-src/oneDNN/blob/7bd73fb5297425e3d38a80a49559f55fdbad2d8c/.github/automation/build_acl.sh#L60)
is no longer required.
> ci: aarch64: update Compute Library version

- src/cpu/aarch64/cpu_barrier.cpp
- src/cpu/aarch64/cpu_barrier.hpp
- src/cpu/aarch64/cpu_isa_traits.hpp
- src/cpu/aarch64/jit_generator.hpp
- src/cpu/aarch64/jit_uni_batch_normalization.cpp
- src/cpu/aarch64/jit_uni_batch_normalization.hpp
- src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64_util.h
- src/cpu/cpu_batch_normalization_list.cpp
This PR adds JIT support of batch_normalization_f32 for AArch64.
It includes JIT implementation for both SVE 512 and ASIMD.
There is no need to make a new tests for this PR, 
> cpu: aarch64: add JIT implementation for batch_normalization_f32

- src/sycl/capi/capi_stream.cpp
- tests/gtests/sycl/api/test_stream.cpp
- improve `sycl_interop::make_stream` to support create a stream with CPU SYCL Queue.
- add test case
- improve sycl interop example to create engine and stream with user provided queue.
> sycl: interop: make cpu stream

- src/cpu/aarch64/cpu_isa_traits.hpp
- src/cpu/aarch64/injectors/injector_utils.hpp
- src/cpu/aarch64/injectors/jit_uni_eltwise_injector.cpp
- src/cpu/aarch64/injectors/jit_uni_eltwise_injector.hpp
- src/cpu/aarch64/jit_generator.hpp
- src/cpu/aarch64/jit_uni_eltwise.cpp
- src/cpu/aarch64/jit_uni_eltwise.hpp
- src/cpu/aarch64/jit_uni_reorder.cpp
- src/cpu/cpu_eltwise_list.cpp
This PR adds JIT support of eltwise f32 for AArch64.
At this time, pow and sigmoid, recently implemented for x64, are not supported. `status_t jit_uni_eltwise_fwd_t<isa, d_type>::pd_t::init(engine_t *engine)` returns `status::unimplemented;`, if either pow or sigmoid is specified. 
There is no need to add a new tests for this PR, 
> cpu: aarch64: add JIT implementation for eltwise_f32

- src/cpu/aarch64/jit_generator.hpp
- src/cpu/aarch64/jit_uni_batch_normalization.cpp
- src/cpu/aarch64/jit_uni_batch_normalization_s8.cpp
- src/cpu/aarch64/jit_uni_batch_normalization_s8.hpp
- src/cpu/cpu_batch_normalization_list.cpp
This PR adds JIT support of batchnoorm s8 for AArch64.
There is no need to add a new tests for this PR, 
> cpu: aarch64: add JIT implementation for batch_norm_s8

- src/cpu/aarch64/cpu_isa_traits.hpp
- src/cpu/aarch64/jit_generator.hpp
- src/cpu/aarch64/jit_primitive_conf.hpp
- src/cpu/aarch64/jit_uni_i8i8_pooling.cpp
- src/cpu/aarch64/jit_uni_i8i8_pooling.hpp
- src/cpu/aarch64/jit_uni_pool_kernel.cpp
- src/cpu/aarch64/jit_uni_pool_kernel.hpp
- src/cpu/aarch64/jit_uni_pooling.cpp
- src/cpu/aarch64/jit_uni_pooling.hpp
- src/cpu/aarch64/jit_uni_reorder.cpp
- src/cpu/cpu_pooling_list.cpp
This PR adds JIT support of pooling for AArch64.
Related RFC https://github.com/oneapi-src/oneDNN/pull/841
Related PR https://github.com/oneapi-src/oneDNN/pull/850
There is no need to add a new tests for this PR,
> cpu: aarch64: add JIT implementation for pooling

- src/cpu/aarch64/cpu_barrier.cpp
- src/cpu/aarch64/cpu_reducer.cpp
- src/cpu/aarch64/cpu_reducer.hpp
- src/cpu/aarch64/jit_op_imm_check.hpp
- src/cpu/aarch64/jit_primitive_conf.hpp
- src/cpu/aarch64/jit_sve_512_conv_kernel.cpp
- src/cpu/aarch64/jit_sve_512_conv_kernel.hpp
- src/cpu/aarch64/jit_sve_512_convolution.cpp
- src/cpu/aarch64/jit_sve_512_convolution.hpp
- src/cpu/cpu_convolution_list.cpp
- tests/gtests/test_iface_attr.cpp
This PR adds JIT support of convolution_f32 for AArch64.
Related PR #850
- "benchdnn --conv --batch=inputs/conv/test_conv_ci" is OK. 
- "test_conv_all" is OK. ~~still running...~~ : (The test_conv_gpu outputted 200 unimplemented.)
There is no need to make a new tests for this PR,
> cpu: aarch64: add JIT implementation for convolution_f32

- src/cpu/aarch64/jit_generator.hpp
- src/cpu/aarch64/jit_uni_i8i8_pooling.cpp
- src/cpu/aarch64/jit_uni_pool_kernel.cpp
This PR fixes build error -Werror and no return of non-void function.
> cpu: aarch64: remove unused variable and fix no return function

- examples/example_utils.hpp
Signature of memcpy is:
```c++
class queue {
...
public:
...
event memcpy(void* dest, const void* src, size_t num_bytes);
};
```
the parameters in `example_utils.hpp` are in opposite order.
> examples: properly call sycl::queue::memcpy

- src/cpu/aarch64/jit_uni_reorder.cpp
This PR fixes bugs of AArch64 JIT reorder (SEGV and miscalculation) for the pattern below.
```bash
./benchdnn --reorder --skip-impl="ref:simple" --sdt=f32 --ddt=s8 --stag=abx --dtag=abx --attr-oscale="per_dim_1:0.125*" --attr-post-ops="'sum'" 2x64x1x1
```
If the test below is run
```
./benchdnn --reorder --batch=inputs/reorder/test_reorder_all 
```
, the two test patterns below is FAILED, and the others are PASSED.
```
[   6][0x0x1x1] exp_f32:9.22337e+18 exp:9.22337e+18 got:9.22337e+18 diff:5.49756e+11 rdiff:5.96046e-08
[  13][0x0x2x3] exp_f32:9.22337e+18 exp:9.22337e+18 got:9.22337e+18 diff:5.49756e+11 rdiff:5.96046e-08
[  20][0x0x4x0] exp_f32:9.22337e+18 exp:9.22337e+18 got:9.22337e+18 diff:5.49756e+11 rdiff:5.96046e-08
[  27][0x0x5x2] exp_f32:9.22337e+18 …
```
> cpu: aarch64: reorder: fix SEGV and misuse of temporally register

- src/gpu/nvidia/cudnn_conv_inner_product_impl.hpp
The current version does not build with cudDNN 8 since there are some changes in the API. Building with cuDNN 8 results in a failure, as I described in issue #885.
Deprecated calls in cuDNN 8 used in oneDNN:
- cudnnGetConvolutionBackwardDataAlgorithm
- cudnnGetConvolutionBackwardFilterAlgorithm
- cudnnGetConvolutionForwardAlgorithm
All of them were replaced by `_v7` calls. They could have been replaced by cuddnFind... counterparts, but because they do not behave in the same way, I decided to use the `_v7` functions. API changed, and now cuDNN functions return a list of the possible algorithms to choose instead of returning the fastest one. Therefore, I implemented a simple algorithm to choose the fastest suitable algorithm from the list.
Because `_v7` functions build successfully with …
> gpu: Fix compilation errors in NVIDIA GPUs with cuDNN 8

- rfcs/20210122-oneapi-cmake-support/README.md
This RFC describes proposal on CMake support in oneDNN for oneAPI.
[Link to rendered document](https://github.com/oneapi-src/oneDNN/blob/bc2f7e432760ac7cc9b249a4435bcb842a22a7ae/rfcs/20210122-oneapi-cmake-support/README.md)
> rfc: proposal on CMake support for oneAPI

- src/cpu/aarch64/jit_sve_512_conv_kernel.cpp
- src/cpu/aarch64/jit_sve_512_conv_kernel.hpp
- src/cpu/aarch64/jit_sve_512_convolution.hpp
This PR fixes the build error which is undefined function call in jit_sve_512_convolution.hpp
#964
> cpu: aarch64: fix undefined function call

- src/cpu/aarch64/jit_uni_softmax.cpp
- src/cpu/aarch64/jit_uni_softmax.hpp
- src/cpu/cpu_softmax_list.cpp
This PR adds JIT support of softmax for AArch64.
There is no need to add a new tests for this PR, 
> cpu: aarch64: add JIT implementation for softmax

- doc/performance_considerations/profilers.md
- src/common/utils.cpp
This PR change the default value of DNNL_JIT_PROFILE on AArch64 into `2 (Enables basic Linux perf integration)`, because `1 (Enables VTune Amplifier integration)` is meaningless for AArch64 and outputs warning messages. https://github.com/oneapi-src/oneDNN/blob/63c8b5ce84b0be266d1edad0420390f2e131cb29/src/cpu/jit_utils/jit_utils.cpp#L93-L96.
> cpu: aarch64: change DNNL_JIT_PROFILE default value to 2

- .github/automation/.drone.yml
- src/cpu/aarch64/jit_uni_reorder.cpp
This PR for rls-v2.1 is the backport of RFC #967.
The fixes in this patch are identical to those of RFC #967 for the master branch.
> aarch64: fix debug build error (-Werror=sign-compare) on AArch64

- rfcs/20200818-adaptive-pooling/README.md
- rfcs/20200818-adaptive-pooling/pooling.md
Rfc document for adaptive pooling.
[Link to rendered document.](https://github.com/oneapi-src/oneDNN/tree/bkocot/adaptive-pooling/rfcs/20200818-adaptive-pooling)
> rfc: Support adaptive pooling.

- src/cpu/aarch64/jit_generator.hpp
- src/cpu/aarch64/jit_uni_eltwise_int.cpp
- src/cpu/aarch64/jit_uni_eltwise_int.hpp
- src/cpu/cpu_eltwise_list.cpp
This PR adds JIT support of integer eltwise for AArch64.
There is no need to add a new tests for this PR, 
> cpu: aarch64: add JIT implementation for eltwise_int

- src/cpu/aarch64/jit_sve_512_conv_kernel.cpp
- src/cpu/aarch64/jit_sve_512_conv_kernel.hpp
This PR is support the hw transpose optimization for aarch64/convolution_f32 JIT.
Using the same method as JIT for AVX_512.
/* Optimization: when `output-width == 1' deploy a special case of the
* JIT-Kernel by unrolling with regards to height instead of width for
* the source and filter tensors. The JIT-Kernel also transposes the
* strides for the input and filter memory access. */
Related PR #931
Using FX700 with A64FX(2GHz),
% ./tests/benchdnn/benchdnn --conv --mode=P --dir=BWD_WB --cfg=f32_full mb7ic128ih102iw19oc256oh100ow1kh3kw19ph0pw0n"small-spatial:3"
w/o this optimization : 21.3855 ms average, using gemm:ref
with the optimization : 2.39671 ms average, using jit:sve_512
- [N/A] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally? …
> cpu: aarch64: support hw transpose optimization for convolution_f32

- src/cpu/aarch64/acl_convolution_utils.cpp
- src/cpu/aarch64/acl_convolution_utils.hpp
- src/cpu/aarch64/acl_gemm_convolution.cpp
- src/cpu/aarch64/acl_gemm_convolution.hpp
This PR introduces support for `sum` post-op in the case of GEMM-based convolution on AArch64 (`acl_gemm_convolution_fwd_t`). It supports the use case where a convolution is followed by two operations: `sum` and `eltwise` activation. Examples include a ResNet50 inference in TensorFlow framework, where it enables the use of NHWC memory layout for all the primitives thus completely eliminating `reorder` calls which results in ~70% performance gain for FP32. Implementation follows the same approach as was detailed in RFC [#795](https://github.com/oneapi-src/oneDNN/pull/795).
- Two post-ops in the form of sum together with eltwise activation are now supported
for a convolution on AArch64 (`--attr-post-ops="'sum;relu;'"` in benchdnn terms);
- The changes …
> src: cpu: aarch64: add sum+relu post-ops support on AArch64

- cmake/SDL.cmake
This pull request enables FCC (Fujitsu C/C++ compiler) to build oneDNN. 
FCC has the two operation modes below.
- simulating gcc version 6.1
- clang mode based on LLVM 7.1.0
This patch is for clang mode of FCC, which does not support `-fstack-protector-all`.
> cmake: support Fujitsu C++ compiler

- cmake/ACL.cmake
- doc/build/build.md
- doc/build/build_options.md
- src/cpu/aarch64/acl_convolution_utils.cpp
- src/cpu/aarch64/acl_convolution_utils.hpp
- src/cpu/aarch64/acl_indirect_gemm_convolution.cpp
- src/cpu/aarch64/acl_indirect_gemm_convolution.hpp
- src/cpu/cpu_convolution_list.cpp
This PR introduces support for [indirect convolution](https://arxiv.org/pdf/1907.02129.pdf) algorithm for two-dimensional convolutions on AArch64 with the help of Arm Compute Library routines. Implementation follows the same approach as was detailed in RFC [#795](https://github.com/oneapi-src/oneDNN/pull/795). This indirect implementation provides 10% - 40% speedup for FP32 on ResNet50 shapes compared to `acl_gemm_convolution_fwd_t`, especially at high core counts.
- New `acl_indirect_gemm_convolution.cpp/.hpp` files added in `src/cpu/aarch64` directory;
- New implementation `acl_indirect_gemm_convolution_fwd_t` added in `src/cpu/cpu_convolution_list.cpp`;
- This implementation supports only `NHWC` memory layout, respective launch heuristics introduced in …
> cpu: aarch64: Add support for ACL-based indirect convolution

- src/cpu/aarch64/cpu_barrier.cpp
- src/cpu/aarch64/cpu_barrier.hpp
- src/cpu/aarch64/jit_primitive_conf.hpp
- src/cpu/aarch64/jit_sve_512_1x1_conv_kernel.cpp
- src/cpu/aarch64/jit_sve_512_1x1_conv_kernel.hpp
- src/cpu/aarch64/jit_sve_512_1x1_convolution.cpp
- src/cpu/aarch64/jit_sve_512_1x1_convolution.hpp
- src/cpu/aarch64/jit_uni_1x1_conv_utils.hpp
- src/cpu/cpu_convolution_list.cpp
This PR adds JIT support of convolution_fp32 with kernel size 1x1 for AArch64.
There is no need to make a new tests for this PR,
> cpu: aarch64: add JIT implementation for 1x1 convolution_fp32

- src/cpu/aarch64/injectors/jit_uni_eltwise_injector.cpp
- src/cpu/aarch64/jit_sve_512_conv_kernel.cpp
- src/cpu/aarch64/jit_sve_512_conv_kernel.hpp
This PR adds eltwise injector for JIT-ed fp32 common convolution of AArch64.
> aarch64: conv: add eltwise injector for JIT-ed fp32 common conv

- rfcs/20210219-cache-compiled-gpu-kernels/README.md
This RFC describes a proposal on switching to caching compiled GPU kernels.
[Link to rendered document](https://github.com/oneapi-src/oneDNN/blob/1290b1f52bcd35104534cd18e5e2bd8268a9ca15/rfcs/20210219-cache-compiled-gpu-kernels/README.md)
> rfs: proposal on caching compiled gpu kernels

- src/cpu/aarch64/jit_sve_512_x8s8s32x_conv_kernel.cpp
- src/cpu/aarch64/jit_sve_512_x8s8s32x_conv_kernel.hpp
- src/cpu/aarch64/jit_sve_512_x8s8s32x_convolution.cpp
- src/cpu/aarch64/jit_sve_512_x8s8s32x_convolution.hpp
- src/cpu/cpu_convolution_list.cpp
- tests/benchdnn/conv/conv.cpp
This PR adds JIT support of convolution_x8s8s32x for AArch64.
Related PR #850
convolution_x8s8s32x + eltwise are not supported. If PostOp is specified, status::unimplemented will be returned.
There is no need to add a new tests for this PR,
> cpu: aarch64: Add JIT implementation for INT8 Convolution to rls-v2.2

- .github/automation/.drone.yml
- .github/automation/build_acl.sh
- README.md
- cmake/ACL.cmake
- doc/build/build.md
- doc/build/build_options.md
This PR updates the minimum required version of Compute Library to the newly released [v21.02](https://arm-software.github.io/ComputeLibrary/v21.02/), which contains fixes for several bugs present in v20.11. v21.02 requires C++14, hence CMake flags are added to select it and ensure `c++14` (not `gnu14`) is used. [A previous PR](https://github.com/oneapi-src/oneDNN/pull/905) added this feature but was abandoned - now is a more appropriate time to add it as we now have a version of Compute Library that requires `--std=c++14`.
The affected DroneCI pipelines and relevant build documentation are also updated accordingly.
- [N/A] Have you included …
> Update required Compute Library version to 21.02

- src/cpu/aarch64/cpu_barrier.cpp
- src/cpu/aarch64/jit_uni_dw_conv_kernel_f32.cpp
- src/cpu/aarch64/jit_uni_dw_conv_kernel_f32.hpp
- src/cpu/aarch64/jit_uni_dw_conv_kernel_utils.hpp
- src/cpu/aarch64/jit_uni_dw_convolution.cpp
- src/cpu/aarch64/jit_uni_dw_convolution.hpp
- src/cpu/cpu_convolution_list.cpp
This PR adds JIT support of FP32 dw convolution for AArch64.
There is no need to make a new tests for this PR,
> cpu: aarch64: add a JIT implementation for FP32 dw convolution

- src/cpu/aarch64/jit_sve_512_x8s8s32x_conv_kernel.cpp
- src/cpu/aarch64/jit_sve_512_x8s8s32x_conv_kernel.hpp
- src/cpu/aarch64/jit_sve_512_x8s8s32x_convolution.cpp
- src/cpu/aarch64/jit_sve_512_x8s8s32x_convolution.hpp
- src/cpu/cpu_convolution_list.cpp
- tests/benchdnn/conv/conv.cpp
This PR adds JIT support of convolution_x8s8s32x for AArch64.
Related PR #850
convolution_x8s8s32x + eltwise are not supported. If PostOp is specified, status::unimplemented will be returned.
There is no need to add a new tests for this PR,
> cpu: aarch64: Add JIT implementation for INT8 Convolution

- rfcs/20210223-batch-norm-scale-only/README.md
This RFC is to discuss options how to improve usability for a single scale memory argument when no shifts are used.
[Link to a rendered document](https://github.com/dzarukin/oneDNN/blob/dzarukin/rfcs/batch_norm_shift_scale_support_v2/rfcs/20210223-batch-norm-scale-only/README.md).
> rfc: batch normalization: support only scale memory argument

- rfcs/20210223-batch-norm-scale-only/README.md
A small fixup for "batch normalization: support only scale memory argument".
Changes:
- add information about scaleshift semantics in case of separate scale and shift parameters
- add arguments for backward pass
- shift flag 0x16 -> 0x10
> fixup: rfc: batch normalization: support only scale memory argument

- examples/CMakeLists.txt
- src/CMakeLists.txt
- src/common/memory_debug.cpp
- src/common/utils.cpp
Enable further compiling capabilities: compiling for Unix-based systems and cross-compiling from Windows. No functional change in previously existing build configurations.
Fixes #1029 #1031 #1032.
> Enable further compiling capabilities: compiling for Unix-based systems and cross-compiling from Windows

- rfcs/20210415-gpu-only/README.md
This RFC describes a proposal on introducing GPU only configurations.
[Link to rendered doc](https://github.com/oneapi-src/oneDNN/tree/03b4637f8c315f12710be4be215ad1be91651a4c/rfcs/20210415-gpu-only)
> rfc: proposal on GPU only configurations

- tests/benchdnn/doc/driver_matmul.md
I think the example (line 101 and line 109) should be mb2m10n20k30 and not the mb2m10n20k3, is that right?
> Fix mistake in benchdnn matmul driver documentation

- src/cpu/aarch64/acl_indirect_gemm_convolution.hpp
error: 'arm_compute::Scheduler' has not been declared
There is a missing include which leads to a compilation error
The issue shows up in testing with the Compute Library master, so it is
currently working with the 21.02 release, as used in the CI,
see: https://github.com/oneapi-src/oneDNN/blob/ca6ca816faa92025a231f3ff1d110b73c5a460c1/.github/automation/build_acl.sh#L21
However, this change is required to support builds from the tip of the Compute Library master, and future releases.
###Bug fixes
> cpu: aarch64: missing include for arm_compute::Scheduler

- rfcs/20210510-sum-with-zero-point/README.md
This RFC is to discuss the way of supporting sum with zero-point.
[Link to a rendered document.](https://github.com/oneapi-src/oneDNN/tree/bkocot/rfc/sum-with-zp/rfcs/20210510-sum-with-zero-point)
> rfc: support sum with zero-point

- src/cpu/aarch64/acl_gemm_convolution.hpp
- src/cpu/aarch64/acl_indirect_gemm_convolution.hpp
- src/cpu/aarch64/acl_winograd_convolution.hpp
Adding linear thread binding implementation for Compute Library primitives in oneDNN.
It gives improved performance at high thread counts in BenchDNN ResNet50 benchmark.
> cpu: aarch64: implemented thread binding for ACL calls

- src/cpu/aarch64/injectors/jit_uni_eltwise_injector.cpp
- src/cpu/aarch64/injectors/jit_uni_eltwise_injector.hpp
This PR improves the JIT-ed code of eltwise for AArch64 SVE 512.
> src: cpu: aarch64: eltwise: optimize jit-ed code for SVE512

- .github/automation/.drone.yml
- .github/automation/build_acl.sh
- README.md
- cmake/ACL.cmake
- doc/build/build_options.md
Updates minimum Compute Library version for builds on AArch64 with the
Compute Library backend. Updates from 21.02 to 21.05
- DroneCI build updated
- Docs updated
- CMake updated
> aarch64: build: update Compute Library min. version to v21.05

- src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64/xbyak_aarch64.h
This PR fixes gcc-11 compile error for AArch64 (#1085).
> src: cpu: aarch64: fix gcc-11 compile error

- src/cpu/aarch64/acl_gemm_convolution.cpp
- src/cpu/aarch64/acl_gemm_convolution.hpp
- src/cpu/aarch64/acl_indirect_gemm_convolution.cpp
- src/cpu/aarch64/acl_indirect_gemm_convolution.hpp
- src/cpu/aarch64/acl_winograd_convolution.cpp
- src/cpu/aarch64/acl_winograd_convolution.hpp
This PR removes workaround introduced previously in [PR#820](https://github.com/oneapi-src/oneDNN/pull/820) (GEMM-based convolution), [PR#886](https://github.com/oneapi-src/oneDNN/pull/886) (Winograd-based convolution), and [PR#973](https://github.com/oneapi-src/oneDNN/pull/973) (indirect convolution). With the v21.05 release of Compute Library this workaround is not needed anymore. Minimum Compute Library version in oneDNN has recently been updated in [PR#1081](https://github.com/oneapi-src/oneDNN/pull/1081).
- [N/A ] Have you submitted performance data that demonstrates performance improvements?
- [N/A] Have you included information on how to reproduce the issue …
> src: cpu: aarch64: remove dependence on scratchpad memory to store bias

- tests/benchdnn/rnn/rnn.cpp
The changes introduced in 79be1a9 always define DNNL_X64, which breaks a check for unsupported test cases in benchdnn rnn tests.
Fixes #1108
> tests: benchdnn: rnn: fix check for unsupported cases

- src/cpu/aarch64/acl_convolution_utils.cpp
- src/cpu/aarch64/acl_convolution_utils.hpp
- src/cpu/aarch64/acl_gemm_convolution.cpp
- src/cpu/aarch64/acl_gemm_convolution.hpp
- src/cpu/aarch64/acl_indirect_gemm_convolution.hpp
- src/cpu/aarch64/acl_inner_product.cpp
- src/cpu/aarch64/acl_inner_product.hpp
- src/cpu/aarch64/acl_inner_product_utils.cpp
- src/cpu/aarch64/acl_inner_product_utils.hpp
- src/cpu/aarch64/acl_utils.cpp
- src/cpu/aarch64/acl_utils.hpp
- src/cpu/aarch64/acl_winograd_convolution.hpp
- src/cpu/cpu_inner_product_list.cpp
This PR introduces support for [inner product](https://oneapi-src.github.io/oneDNN/dev_guide_inner_product.html) operation for AArch64 with the help of Arm Compute Library routines. It provides improved performance on NLP workloads on AArch64 CPUs compared to the reference variant. This implementation falls in line with the same approach as was detailed in the original RFC [#795](https://github.com/oneapi-src/oneDNN/pull/795).
- New `acl_inner_product.cpp/.hpp` files added in `src/cpu/aarch64` directory;
- New implementation `acl_inner_product_fwd_t` added in `src/cpu/cpu_inner_product_list.cpp`;
- Some refactoring was performed for ACL-related functions in `src/cpu/aarch64` directory: common functions were grouped in the `acl_utils.cpp/.hpp` files.
- …
> src: cpu: aarch64: add support for ACL-based inner product

- cmake/blas.cmake
In order to find the right include path for ArmPL, CMake searches for `blas.h`,
which ArmPL provides. However, depending on the enviroment, it is possible for
CMake to pick up `blas.h` from a different BLAS library, such as OpenBLAS, and
choose an incorrect include path as a result.
This PR updates `blas.cmake` to look for `armpl.h` when setting the BLAS
inlude path instead,
_Note: changes are restricted to the build system, and have no material impact
on functioning of the library under normal conditions._
_Note: changes are restricted to the build system, and have no material impact
on functioning of the library under normal conditions._
> build: fix to include path for ArmPL builds.

- rfcs/20210211-convolution-int8-dst/README.md
RFC for API changes required to enable int8 destination type for float convolutions.
> RFC for f16/f32 -> int8 convolution

- src/cpu/aarch64/acl_convolution_utils.cpp
- src/cpu/aarch64/acl_convolution_utils.hpp
- src/cpu/aarch64/acl_gemm_convolution.cpp
- src/cpu/aarch64/acl_gemm_convolution.hpp
- src/cpu/aarch64/acl_indirect_gemm_convolution.cpp
- src/cpu/aarch64/acl_indirect_gemm_convolution.hpp
- src/cpu/aarch64/acl_inner_product.hpp
- src/cpu/aarch64/acl_winograd_convolution.cpp
- src/cpu/aarch64/acl_winograd_convolution.hpp
This PR introduces support for the `sum` post-op followed by an activation for indirect and Winograd convolution implementations on AArch64, which increases the coverage of use cases compared to an activation only. Part of the code base is also templated to reduce its size. Implementation follows the same approach as was detailed in RFC [#795](https://github.com/oneapi-src/oneDNN/pull/795).
- Two post-ops in the form of sum together with eltwise activation are now supported for indirect (`acl_indirect_gemm_convolution_fwd_t`) and Winograd (`acl_wino_convolution_fwd_t`) convolutions on AArch64;
- The function `execute_forward_conv_acl` is templated to reduce the code base size.
- [N/A] Have you submitted performance data that demonstrates performance …
> src: cpu: aarch64: add support for 'sum+act' post-ops

- src/cpu/aarch64/acl_convolution_utils.hpp
- src/cpu/aarch64/acl_eltwise.cpp
- src/cpu/aarch64/acl_eltwise.hpp
- src/cpu/aarch64/acl_eltwise_utils.cpp
- src/cpu/aarch64/acl_eltwise_utils.hpp
- src/cpu/aarch64/acl_gemm_convolution.cpp
- src/cpu/aarch64/acl_gemm_convolution.hpp
- src/cpu/aarch64/acl_indirect_gemm_convolution.hpp
- src/cpu/aarch64/acl_inner_product.cpp
- src/cpu/aarch64/acl_inner_product.hpp
- src/cpu/aarch64/acl_utils.cpp
- src/cpu/aarch64/acl_utils.hpp
- src/cpu/aarch64/acl_winograd_convolution.hpp
- src/cpu/cpu_eltwise_list.cpp
This PR introduces support for standalone element-wise activations for AArch64 with the help of Arm Compute Library functionality. Such a use-case is important because activations are not always fused with the preceding convolution. Also thread-safe access to `resource_t` is implemented with the help of lock guards. This implementation falls in line with the same approach as was detailed in the original RFC [#795](https://github.com/oneapi-src/oneDNN/pull/795).
- New `acl_eltwise.cpp/.hpp`, `acl_eltwise_utils.cpp/.hpp` files added in `src/cpu/aarch64` directory;
- New implementation `acl_eltwise_fwd_t` added in `src/cpu/cpu_eltwise_list.cpp`, FP32 and signed INT8 datatypes are supported;
- Lock guards were introduced to all `resource_t` access points in …
> src: cpu: aarch64: add support for standalone activations

- src/common/verbose.cpp
The current condition check is as the following, which will check and set version_printed variable then check verbose.
if (!version_printed.test_and_set() && verbose.get() > 0)
This will cause a problem if verbose is set to 1 in middle of execution, even the verbose is 0, version_printed has already been set. So when verbose is set to 1, the version_printed had already been set, and thus, the version info will not be printed.
Swap order of these 2 conditions solves this problem.
if (verbose.get() > 0 && !version_printed.test_and_set())
- [Y] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [Y] Have you formatted the code using clang-format?
- [Y] Have you included information on how to reproduce the issue …
> fix a logical bug to show onednn version info in verbose

- src/gpu/jit/ngen/ngen_utils.hpp
This fixes compilation on non-x86 arches
Fixes #1137
Signed-off-by: Nicolas Chauvet <kwizart@gmail.com>
> Drop uneeded immintrin.h

- src/cpu/aarch64/acl_utils.cpp
Removes linear thread binding for Compute Library primitives originally introduced in #1063.
Profiling of TensorFlow workloads using both Compute Library and oneDNN C++ primitives demonstrates that the use of linear thread binding in Compute Library starves the non-Compute Library primitives of threads, leading to a net negative impact in performance.
> cpu: aarch64: remove thread binding for Compute Library primitive

- .github/automation/.drone.yml
- .github/automation/build_acl.sh
- README.md
- cmake/ACL.cmake
- doc/build/build_options.md
- doc/programming_model/attributes_fpmath_mode.md
- src/cpu/aarch64/acl_convolution_utils.cpp
- src/cpu/aarch64/acl_convolution_utils.hpp
- src/cpu/aarch64/acl_gemm_convolution.hpp
- src/cpu/aarch64/acl_indirect_gemm_convolution.hpp
`DNNL_ACL_ENABLE_FAST_MATH` is a runtime environment variable that can be used to enable fast math computation in Arm Compute Library for fp32 models. If this variable is set, Compute Library will dispatch bfloat16 kernels where available, provided the hardware supports bfloat16 instructions. Note that this may introduce a drop in accuracy. By default this variable is set to false.
Usage:
~~~sh
$ DNNL_ACL_ENABLE_FAST_MATH=1 benchdnn --conv ...
~~~
File changes:
```
src/cpu/aarch64/acl_convolution_utils.cpp         | 9 +++++++--
src/cpu/aarch64/acl_convolution_utils.hpp         | 1 +
src/cpu/aarch64/acl_gemm_convolution.hpp          | 3 ++-
src/cpu/aarch64/acl_indirect_gemm_convolution.hpp | 2 +-
doc/build/build_options.md                        | 20 ++++++++++++++++----
```
> cpu: aarch64: add fastmath support from Compute Library

- src/sycl/sycl_stream_cpu_thunk.cpp
- src/sycl/sycl_stream_cpu_thunk.hpp
- src/sycl/sycl_stream_submit_cpu_primitive.cpp
- src/sycl/sycl_utils.hpp
Codeplay host task was removed from DPC++. So the code would fallback on using single_task and thus made compilation impossible. This commit removes single_task and uses codeplay_host_task as a fallback for older versions of DPC++.
> src: sycl: removing the use of single_task

- cmake/version.cmake
If a user has set log.showSignature = true, then build will break
because DNNL_VERSION_HASH define will be overrun by muliple lines about
the signature of the commit.
If a user has customized core.abbrev-- e.g. Linux kernel developers are
encouraged to set it to 12-- then each build could display a commit hash
string of differing lengths. The git default is "auto", so length of the
hash string could change depending on, e.g., the number of commits in
this repository. That's probably undesirable. By explicitly overriding
abbrev on the command line, it ensures all builds going forward will
generate a hash of the same length (namely, the entire commit hash).
With --oneline one and only one line of output ought to appear, and it
will be the commit hash.
Signed-off-by: Joe Konno …
> version.cmake: tweak git log invocation

- .github/automation/.drone.yml
- .github/automation/build_acl.sh
- README.md
- cmake/ACL.cmake
- doc/build/build_options.md
- doc/programming_model/attributes_fpmath_mode.md
- src/cpu/aarch64/acl_convolution_utils.cpp
- src/cpu/aarch64/acl_convolution_utils.hpp
- src/cpu/aarch64/acl_gemm_convolution.hpp
- src/cpu/aarch64/acl_indirect_gemm_convolution.hpp
(originally introduced as #1150)
This PR add fastmath support from Compute Library-enabled builds. 
The implementation makes use of existing environment variable `DNNL_DEFAULT_FPMATH_MODE`. If this variable is set to `BF16` or `ANY`, Compute Library will dispatch bfloat16 kernels where available, provided the hardware supports bfloat16 instructions.
> [rls-v2.4] cpu: aarch64: add fastmath support from Compute Library

- src/cpu/aarch64/matmul/acl_matmul.cpp
- src/cpu/aarch64/matmul/acl_matmul.hpp
- src/cpu/aarch64/matmul/acl_matmul_utils.cpp
- src/cpu/aarch64/matmul/acl_matmul_utils.hpp
- src/cpu/matmul/cpu_matmul_list.cpp
This PR introduces support for [matmul](https://oneapi-src.github.io/oneDNN/dev_guide_matmul.html) operation for AArch64 with the help of
Compute Library for the Arm Architecture (ACL) routines. It provides improved performance on NLP workloads on AArch64 CPUs compared to the reference variant. This implementation falls in line with the same approach as was detailed in the original RFC [#795](https://github.com/oneapi-src/oneDNN/pull/795).
- New `acl_matmul.cpp/.hpp` files added in a new matmul sub-directory `src/cpu/aarch64` directory;
- New implementation `acl_matmul_t` added in `src/cpu/matmul/cpu_matmul_list.cpp`;
- An `acl_matmul_utils.cpp/.hpp` was also added.
pass locally?
###Bug fixes
- [N/A] Have you added …
> [rls-v2.4] src: cpu: aarch64: matmul: add support for matmul on aarch64

- src/cpu/aarch64/matmul/acl_matmul.cpp
- src/cpu/aarch64/matmul/acl_matmul.hpp
- src/cpu/aarch64/matmul/acl_matmul_utils.cpp
- src/cpu/aarch64/matmul/acl_matmul_utils.hpp
- src/cpu/matmul/cpu_matmul_list.cpp
This PR introduces support for [matmul](https://oneapi-src.github.io/oneDNN/dev_guide_matmul.html) operation for AArch64 with the help of
Compute Library for the Arm Architecture (ACL) routines. It provides improved performance on NLP workloads on AArch64 CPUs compared to the reference variant. This implementation falls in line with the same approach as was detailed in the original RFC [#795](https://github.com/oneapi-src/oneDNN/pull/795).
- New `acl_matmul.cpp/.hpp` files added in a new matmul sub-directory `src/cpu/aarch64` directory;
- New implementation `acl_matmul_t` added in `src/cpu/matmul/cpu_matmul_list.cpp`;
- An `acl_matmul_utils.cpp/.hpp` was also added.
pass locally?
###Bug fixes
- [N/A] Have you added …
> src: cpu: aarch64: matmul: add support for matmul on aarch64

- tests/benchdnn/CMakeLists.txt
- tests/benchdnn/dnnl_common.cpp
- tests/gtests/gtest/CMakeLists.txt
> Fixes compatibility issues with QNX for test suite

- src/cpu/aarch64/acl_convolution_utils.cpp
- src/cpu/aarch64/acl_inner_product_utils.cpp
- src/cpu/aarch64/acl_softmax.cpp
- src/cpu/aarch64/acl_softmax.hpp
- src/cpu/aarch64/acl_utils.hpp
- src/cpu/cpu_softmax_list.cpp
- tests/benchdnn/inputs/softmax/test_softmax_all
- tests/benchdnn/inputs/softmax/test_softmax_ci
This PR adds a softmax primitive which makes use of the Compute Library for the Arm architecture (ACL), optimised for AArch64 targets. Implementation follows the approach as detailed in the PR [#820](https://github.com/oneapi-src/oneDNN/pull/820) and RFC [#795](https://github.com/oneapi-src/oneDNN/pull/795). This primitive offers up to a ~50% speedup, particularly for low thread counts and moderate-large problem sizes. An empirically derived heuristic guards against performance regressions, deferring to the reference implementation when the performance gains do not outweigh the overhead of calling ACL. The primitive can only be used in forward inference mode.
- New `acl_softmax.hpp/cpp` files add in `src/cpu/aarch64` directory
- Heuristics in …
> Softmax acl

- doc/performance_considerations/verbose.md
- src/cpu/aarch64/acl_convolution_utils.cpp
- src/cpu/aarch64/acl_inner_product_utils.cpp
- src/cpu/aarch64/acl_utils.hpp
- src/cpu/aarch64/matmul/acl_matmul_utils.cpp
ACL uses a validate step as part of the initialisation.
This should be carried out for every ACL layer used.
As a result, primitives need a validate step for each
layer used, such as in [acl_matmul_utils.cpp](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/aarch64/matmul/acl_matmul_utils.cpp).
Validate calls added:
ACL Convolution
- ActivationLayer
- ArithmeticAddition
ACL Inner Product
- ArithmeticAddition
- [N/A] …
> cpu: aarch64: add missing validate calls for ACL primitives

- src/gpu/jit/conv/tensor.cpp
Compiling with Intel oneAPI DPC++ Compiler 2021.3 or later with GPU support results in a compile error:
> [build] oneDNN/src/gpu/jit/conv/tensor.cpp:132:39: error: use of overloaded operator '==' is ambiguous (with operand types 'dnnl::impl::dim_t' (aka 'long') and 'dnnl::impl::gpu::jit::stride_t')
> [build]                 ir_assert(prev_stride == b.block * b.stride);
> [build]                           ~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~
I could reproduce this with:
- Intel oneAPI DPC++ Compiler 2021.3
- DPC++ daily (https://github.com/intel/llvm.git be9d7fdd563c336677c4ef6c8e093c128646a4fb)
> gpu: jit: fix compile error for DPCPP compiler 2021.3+

- tests/benchdnn/conv/conv.cpp
- tests/benchdnn/conv/conv_common.hpp
The Winograd convolution implemented from Compute Library for the Arm Architecture (ACL),
is not currently being called in benchdnn tests due to differing requirements in conv.cpp.
This PR adds a clause for AArch64 to the wino section in the conv benchdnn driver,
so that the ACL winograd implementation can be picked up.
- [N/A] Does RFC document follow the [template](https://github.com/oneapi-src/oneDNN/blob/rfcs/rfcs/templa …
> cpu: aarch64: benchdnn: add aarch64 clause to conv driver for wino

- .github/automation/.drone.yml
- .github/automation/build_acl.sh
- README.md
- cmake/ACL.cmake
- doc/build/build_options.md
- src/cpu/aarch64/acl_inner_product_utils.cpp
- src/cpu/aarch64/matmul/acl_matmul_utils.cpp
The latest Arm Compute Library release (https://arm-software.github.io/ComputeLibrary/v21.11/)
comes with further support for bf16 fast-math for the inner product and matmul operators.
Changes to the oneDNN source code follow the same approach as in the previous PR https://github.com/oneapi-src/oneDNN/pull/1150,
where this support was added for the convolution operator only.
Additional changes were made to the documentation and the CI to reflect the version bump.
> cpu: aarch64: bump ACL v21.11 and enable further support for fastmath

- src/cpu/aarch64/acl_eltwise_utils.hpp
Remove superflous header file include of "cpu/cpu_convolution_pd.hpp".
- [n/a] Have you submitted performance data that demonstrates performance improvements?
- [n/a] Have you published an RFC for the new feature?
- [n/a] Was the RFC approved?
- [n/a] Have you added relevant tests?
- [n/a] Have you included information on how to reproduce the issue (either in a github issue or in this PR)?
- [n/a] Have you added relevant regression tests?
- [n/a] Does RFC document follow the [template](https://github.com/oneapi-src/oneDNN/blob/rfcs/rfcs/template.md#onednn-design-document-rfc)?
- [n/a] Have you added a link to the rendered document?
> cpu: aarch64: remove superflous header include

- src/cpu/aarch64/acl_softmax.cpp
- src/cpu/aarch64/acl_softmax.hpp
Extends #1175, adding logsoftmax to the existing `acl_softmax_fwd_t`. The heuristic has been tweaked based on data for more cores and on different machines, but is broadly similar. The performance difference between the Compute Library for Arm (ACL) and the reference implementation is similar for logsoftmax and softmax, so the same heuristic is used.
> cpu: aarch64: add logsoftmax to ACL softmax primitive

- rfcs/20211207-softmax-v2/README.md
This RFC covers extension of softmax operation descriptor to cover destination data type and also alg_kind to fuse logsoftmax API.
[Link to rendered document](https://github.com/dzarukin/oneDNN/tree/dzarukin/rfcs/softmax_v2/rfcs/20211207-softmax-v2)
> rfc: softmax v2 with dst md

- rfcs/2022014-layernorm-v2/README.md
This RFC covers the oneDNN vision of layer normalization supporting different input/output data types implicitly for users, and provides an example how the technical changes could be addressed.
[Rendered Document](https://github.com/tvtrimel/oneDNN/blob/tvtrimel-rfcs-implicit-layernorm/rfcs/2022014-layernorm-v2/README.md)
> rfcs: support separate i/o types in layer normalization

- rfcs/20210519-single-pass-bnorm/README.md
These changes extend the original RFC with information that was placed "here and there" in the discussions for the feature;
The changes don't change the initial proposal with adding an experimental build, but they clarify behavior for integration and validation of the feature:
- Extend verbose to emphasize an experimental build
- Modify benchdnn to avoid false-positive issues
- Enable all experimental features by default in an experimental build
- Extend regular testing to cover experimental builds
- Move experimental features to default build based on feedback from users
The motivation for a separate build:
- least impact to end users (we limit experimental build for frameworks use to experiment)
- zero-effort integration (once experimental build is obtained all experiment features are …
> rfc: update: bnorm: single-pass formula for calculating mean and variance (#1065)

- src/cpu/x64/injectors/jit_uni_eltwise_injector.hpp
```
src/cpu/x64/injectors/jit_uni_eltwise_injector.hpp:165:21: warning: bitwise operation between different enumeration types ‘dnnl::impl::cpu::x64::cpu_isa_t’ and ‘dnnl::impl::cpu::x64::cpu_isa_bit_t’ is deprecated [-Wdeprecated-enum-enum-conversion]
165 |         return (isa & cpu_isa_bit_t::avx512_common_bit)
|                 ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> cpu: fix warning about binary op on two different enums

- src/cpu/x64/jit_uni_x8s8s32x_conv_kernel.hpp
This is not valid C++:
```c++
Klass<T>(const Klass<T> &);
```
I don't know what old compiler used to allow this, but GCC 11.2.1 doesn't.
Error was:
```
/home/tjmaciei/src/oneDNN/src/cpu/x64/jit_uni_x8s8s32x_conv_kernel.hpp: At global scope:
/home/tjmaciei/src/oneDNN/src/common/utils.hpp:64:7: error: expected unqualified-id before ‘const’
64 |     T(const T &) = delete; \
|       ^~~~~
/home/tjmaciei/src/oneDNN/src/cpu/x64/jit_uni_x8s8s32x_conv_kernel.hpp:236:5: note: in expansion of macro ‘DNNL_DISALLOW_COPY_AND_ASSIGN’
236 |     DNNL_DISALLOW_COPY_AND_ASSIGN(jit_uni_x8s8s32x_fwd_kernel<isa>);
|     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tjmaciei/src/oneDNN/src/common/utils.hpp:64:7: error: expected ‘)’ before ‘const’
64 |     T(const T &) = delete; \
|      ~^~~~~ …
```
> src: cpu: x64: remove templated param from constructor resulting in GCC 11.2.1 build error

- src/common/verbose.cpp
- src/cpu/x64/rnn/jit_uni_lstm_cell_postgemm_bwd.hpp
With GCC, that causes the emission of a global-static to initialize `std::cin`, `cout`, `cerr`.
> common, cpu: remove unnecessary #include <iostream>

- src/common/bit_cast.hpp
The static_assert message is talking about the types being trivially
copyable. We should use std::is_trivially_copyable, but that didn't
exist in GCC 4.8 (first in 5.0), so we use a superset of that: trivial
types are both trivially copyable and trivially destructible.
> common: fix annoying warning that std::is_pod is deprecated

- src/common/broadcast_strategy.hpp
- src/cpu/gemm_inner_product_utils.hpp
- src/cpu/x64/injectors/jit_uni_postops_injector.hpp
- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
If all we need is a set of default values in a non-trivial type, just make it a function.
> cpu, common: replace dynamically-initialized variables with functions

- src/cpu/x64/jit_avx512_core_amx_1x1_conv_kernel.cpp
- src/cpu/x64/jit_avx512_core_amx_1x1_conv_kernel.hpp
- src/cpu/x64/jit_avx512_core_amx_conv_kernel.hpp
- src/cpu/x64/jit_gemm_inner_product_utils.cpp
- src/cpu/x64/jit_generator.hpp
- src/cpu/x64/jit_uni_binary_kernel.hpp
- src/cpu/x64/jit_uni_layer_normalization_kernels.cpp
- src/cpu/x64/jit_uni_reduction_kernel.hpp
- src/cpu/x64/jit_uni_reorder.cpp
- src/cpu/x64/jit_uni_resampling_kernel.hpp
- src/cpu/x64/jit_uni_tbb_batch_normalization.cpp
- src/cpu/x64/jit_uni_x8s8s32x_deconvolution.cpp
- src/cpu/x64/jit_uni_x8s8s32x_deconvolution.hpp
Removing the macros left as an exercise for the reader.
This wouldn't be necessary if we could depend on C++14, because then `Xbyak::util::rax` and family are also `constexpr`.
> cpu: hacky solution to remove the global variables per .cpp

- .github/automation/.drone.yml
This PR removes the Ubuntu 16 stages from the DroneCI setup used to perform CI for AArch64 targets.
As discussed in #1256, the Compute Library build is currently failing for Ubuntu16 due to the GCC version.
While these failures can be overcome with changes to the Compute Library source, there are currently no plans to do so for the upcoming release.
Given this, the limited value of the Ubuntu16 stage, and constrained CI resources, it is proposed that the Ubuntu16 stage be removed and replaced with an Ubuntu20 build, using GCC 10.
Please include a summary of the change. Please also include relevant motivation and context. See [contribution guidelines](https://github.com/oneapi-src/oneDNN/blob/master/CONTRIBUTING.md) for more details. If the change fixes an issue not documented in the …
> ci: replace Ubuntu16+GCC7 stage in AArch64 CI with Ubuntu20+GCC10

- src/cpu/aarch64/jit_generator.hpp
- src/cpu/aarch64/jit_uni_softmax.cpp
- src/cpu/aarch64/jit_uni_softmax.hpp
This PR fixes build error on AArch64 [# 1256](https://github.com/oneapi-src/oneDNN/issues/1256) and introduce jit-based v2 compatible softmax for SVE512.
> cpu: aarch64: softmax: fix build error and introduce v2 primitive

- src/cpu/aarch64/acl_softmax.cpp
- src/cpu/aarch64/acl_softmax.hpp
- src/cpu/cpu_softmax_list.cpp
- tests/benchdnn/inputs/softmax/test_softmax_acl
Updates the Compute Library (ACL) based softmax primitive to be compatible with the new softmax_v2 API.
Addresses an issue where the ACL implementation wasn't being called anymore
since softmax_v2 was introduced.
Also adds ACL-specific benchdnn testing harness.
- [N/A]
> cpu: aarch64: acl: update softmax to be compatible to softmax_v2

- src/cpu/aarch64/jit_generator.hpp
- src/cpu/aarch64/jit_sve_512_1x1_conv_kernel.cpp
- src/cpu/aarch64/jit_sve_512_1x1_conv_kernel.hpp
- src/cpu/aarch64/jit_sve_512_conv_kernel.cpp
- src/cpu/aarch64/jit_sve_512_conv_kernel.hpp
- src/cpu/aarch64/jit_uni_batch_normalization.cpp
- src/cpu/aarch64/jit_uni_batch_normalization_s8.cpp
- src/cpu/aarch64/jit_uni_dw_conv_kernel_f32.cpp
- src/cpu/aarch64/jit_uni_dw_conv_kernel_f32.hpp
- src/cpu/aarch64/jit_uni_eltwise.cpp
- src/cpu/aarch64/jit_uni_i8i8_pooling.cpp
- src/cpu/aarch64/jit_uni_pool_kernel.cpp
- src/cpu/aarch64/jit_uni_pool_kernel.hpp
- src/cpu/aarch64/jit_uni_softmax.cpp
This PR cleans up the usage of P registers. Most SVE instructions require a P register as an operand. In many cases, a P register with all valid bits is used as the operand, so it is convenient to prepare a P register whose all bits enabled. "p0" is assigned for this purpose.
Please merge this PR before https://github.com/oneapi-src/oneDNN/pull/1279.
Thank you.
> cpu: aarch64: clean up p registers

- examples/CMakeLists.txt
- src/gpu/nvidia/README.md
- src/gpu/nvidia/cudnn_batch_normalization_executor.hpp
- src/gpu/nvidia/cudnn_binary.cpp
- src/gpu/nvidia/cudnn_convolution.cpp
- src/gpu/nvidia/cudnn_deconvolution.cpp
- src/gpu/nvidia/cudnn_eltwise.cpp
- src/gpu/nvidia/cudnn_inner_product.cpp
- src/gpu/nvidia/cudnn_lrn.cpp
- src/gpu/nvidia/cudnn_matmul.cpp
- src/gpu/nvidia/cudnn_matmul.hpp
- src/gpu/nvidia/cudnn_matmul_executor.hpp
- src/gpu/nvidia/cudnn_pooling.cpp
- src/gpu/nvidia/cudnn_reorder.cpp
- src/gpu/nvidia/cudnn_resampling.cpp
- src/gpu/nvidia/cudnn_softmax.cpp
- src/gpu/nvidia/sycl_cuda_memory_storage_helper.hpp
- src/gpu/nvidia/sycl_cuda_stream.cpp
- tests/benchdnn/conv/deconv.cpp
- tests/benchdnn/dnnl_memory.cpp
- tests/benchdnn/matmul/matmul.cpp
- tests/gtests/CMakeLists.txt
- tests/gtests/api/CMakeLists.txt
- tests/gtests/sycl/api/test_memory_usm.cpp
- tests/gtests/test_matmul.cpp
This PR collects multiple patches that add support for USM for the cudnn backend. In addition it adds USM support to cudnn_matmul. Currently all tests pass with the exception of 10 of the example cases, which fail due to the primitive not being implemented by cudnn, or the primitive is being used in a way that is unsupported.
Already reviewed changes that are included in this PR:
#1258, #1259, #1262, #1263, #1264, #1265, #1266, #1267
> gpu: cuda: Add USM support for CUDNN

- src/cpu/aarch64/jit_primitive_conf.hpp
- src/cpu/aarch64/shuffle/jit_uni_shuffle.cpp
- src/cpu/aarch64/shuffle/jit_uni_shuffle.hpp
- src/cpu/aarch64/shuffle/jit_uni_shuffle_kernel.cpp
- src/cpu/aarch64/shuffle/jit_uni_shuffle_kernel.hpp
- src/cpu/cpu_shuffle_list.cpp
This PR adds jit implementation of shuffle for SVE 512.
Please merge this PR after https://github.com/oneapi-src/oneDNN/pull/1280
> cpu: aarch64: shuffle: add jit impl. for sve_512

- rfcs/20220218-level_zero-headers/README.md
This rfc proposes to include the Level Zero headers to oneDNN repository, to simplify oneDNN build and deployment (especially on Windows)
> rfcs: add proposal to include ZE headers to oneDNN

- .github/automation/.drone.yml
- .github/automation/build_acl.sh
- README.md
- cmake/ACL.cmake
- doc/build/build_options.md
Updates minimum Compute Library version for builds on AArch64 with the Compute Library backend. Updates from 21.11 to 22.02
- DroneCI build updated
- Docs updated
- CMake updated
_Note: gtests currently timing out in DroneCI pipeline due to #1295._
- [N/A] Does RFC document follow the [template](https://github.com/oneapi-src/oneDNN/blob/rfcs/rfcs/template.md#onednn-desi …
> cpu: aarch64: build: update Compute Library min. version to 22.02

- src/gpu/nvidia/cudnn_convolution_impl.hpp
This patch introduces the Floating-point Math Mode for the CUDNN convolutions.
The [oneDNN math modes](https://oneapi-src.github.io/oneDNN/enum_dnnl_fpmath_mode_t.html) are mapped to different [cuDNN math types](https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnMathType_t) which allow or not datatype conversions in order to use the tensor cores. For further details refer to https://github.com/oneapi-src/oneDNN/issues/1268.
Fixes # (https://github.com/oneapi-src/oneDNN/issues/1268)
> gpu: convolution: add fpmath mode for controlling TC usage

- rfcs/20220128-f64-data_type/Readme.md
This RFC PR proposes to add f64 data type support to oneDNN. 
As the first step, GPU reference implementation for convolutions will be extended to support f64. 
Other primitives or engines will not be affected for now.
> RFC: add f64 conv GPU support

- src/cpu/aarch64/CMakeLists.txt
- src/cpu/aarch64/acl_binary.hpp
- src/cpu/aarch64/acl_eltwise.hpp
- src/cpu/aarch64/acl_gemm_convolution.hpp
- src/cpu/aarch64/acl_indirect_gemm_convolution.hpp
- src/cpu/aarch64/acl_inner_product.hpp
- src/cpu/aarch64/acl_softmax.hpp
- src/cpu/aarch64/acl_thread.cpp
- src/cpu/aarch64/acl_thread.hpp
- src/cpu/aarch64/acl_threadpool_scheduler.cpp
- src/cpu/aarch64/acl_threadpool_scheduler.hpp
- src/cpu/aarch64/acl_utils.cpp
- src/cpu/aarch64/acl_utils.hpp
- src/cpu/aarch64/acl_winograd_convolution.hpp
- src/cpu/aarch64/matmul/acl_matmul.hpp
- src/cpu/cpu_engine.hpp
- src/cpu/gemm/gemm.hpp
- src/cpu/platform.cpp
This PR enables `DNNL_RUNTIME_THREADPOOL` support in oneDNN built with Compute Library for Arm® Architecture (ACL).
The implementation follows the approach detailed in the RFC https://github.com/oneapi-src/oneDNN/pull/1293  and the proof-of-concept implementation https://github.com/oneapi-src/oneDNN/compare/master...cfRod:poc-threadpool.
- [ N/A] Have you submitted performance data that demonstrates performance improvements?
- [N/A] Have you added a link …
> src: cpu: aarch64 Add threadpool runtime support for AArch64

- src/common/memory_desc_wrapper.hpp
- src/cpu/reorder/simple_reorder.hpp
- tests/benchdnn/reorder/reorder.cpp
Simple reorder contains a few issues that are not reproducible on x64, because they are disabled. The issues can be reproduced when aarch64 emulation is used:
- Zero padding optimizations bb0f475615097915a17cb0a5cd4a7980d1e84691 introduced an issue by not padding properly in some cases.
- In benchdnn mask is created separately so it doesn't have information about `ndims`. Due to this for `per_tensor` policy the mask is `(1 << DNNL_MAX_NDIMS) - 1` and if implementation relies on the mask this results in an issue. The workaround is to truncate it on the implementation side. An alternative is to forbid to pass such masks and return `invalid_arguments` when `primitive_desc` is being created. Benchdnn should be updated as well to truncate mask on its side.
- Memory descriptor defines size for …
> Fix simple reorder

- rfcs/20220303-Introducing-Threadpool-support-for-Arm-Compute-Library/README.md
This RFC proposes to introduce threadpool runtime for Arm Compute Library.
[Link to rendered document](https://github.com/cfRod/oneDNN/tree/rfc-threadpool-aarch64/rfcs/20220303-Introducing-Threadpool-support-for-Arm-Compute-Library)
Adding a diff link for the proof-of-concept implementation [here](https://github.com/oneapi-src/oneDNN/compare/master...cfRod:poc-threadpool).
> rfc: introducing threadpool support for Arm Compute Library

- CMakeLists.txt
If the CMAKE_{C,CXX}_STANDARD is set to any value, it's likely set to a
more recent standard than C99 or C++11 (otherwise, the build will break
and someone will notice). But the important part is not to
force-downgrade to C++11, since Xbyak has some content that is
C++14-only (notably XBYAK_CONSTEXPR macro).
> CMake: don't downgrade the build to C++11 or C99

- src/cpu/ref_fused_convolution.hpp
A problem had been identified with resource creation for nested primitives in
ref_fused_convolution, see https://github.com/oneapi-src/oneDNN/issues/1333
This PR adds the missing step for creating the primitive resource for _all_ nested primitives.
The new functionality is ifdef-guarded and only available on AARCH64 builds with ComputeLibrary enabled.
> cpu: aarch64: acl: add missing create_resource step in ref_fused_conv

- src/gpu/nvidia/cudnn_convolution_impl.hpp
This patch fix an issue that prevents the compilation of oneDNN with cuDNN versions lower than 8, since for these versions the ``CUDNN_FMA_MATH`` math mode is not defined.
Fortunately, in case of cuDNN 7.6.x , the same behavior of ``CUDNN_FMA_MATH`` (i.e., excluding the utilization of the tensor cores) is provided by ``CUDNN_DEFAULT_MATH``, e.g., see [here](https://docs.nvidia.com/deeplearning/cudnn/archives/cudnn_760/cudnn-developer-guide/index.html#cudnnMathType_t).
> gpu: convolution: fix CUDNN_FMA_MATH for cuDNN 7.6.x

- src/gpu/nvidia/cudnn_matmul.hpp
- src/gpu/nvidia/cudnn_matmul_impl.hpp
This patch allows the gpu matrix multiplication implementation to store results in permuted tensors, i.e., this makes `benchdnn` tests pass when `--dtag` is equal to `ba` or `acb`.
This solves *Transposed destination* in https://github.com/oneapi-src/oneDNN/issues/1292.
Fixes #1292
> gpu: matmul: support --dtag=ba/acb

- .github/automation/.azure-pipeline.yml
Accordind to [Azure documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#timeouts) default timeout limit is 60, while it can be extended to 360 minutes for public repositories using Microsoft-hosted instanses. This PR extends timeout to 2h to keep CI time reasonable and avoid timeouts.
> github: automation: azure: increase ci timeout

- src/cpu/x64/jit_gemm_x8s8s32x_conv_zp_src_pad_comp.hpp
Include cpu_isa_traits.hpp instead, which includes xbyak.h
after defining several XBYAK_* flags. This way we make sure that
all files are compiled using the same Xbyak configuration.
> cpu/x64/jit_gemm_x8s8s32x_conv_zp_src_pad_comp.hpp: do not include xbyak explicitly

- src/common/utils.hpp
- src/cpu/x64/gemm/f32/jit_avx512_common_gemm_f32.cpp
- src/cpu/x64/gemm/f32/jit_avx512_core_gemm_smalln_tn_f32_kern.cpp
- src/cpu/x64/gemm/f32/jit_avx_gemm_f32.cpp
- src/cpu/x64/gemm/gemm_info.cpp
"5572b2eb6 cpu: x64: gemm: fix memory leak" changed some static pointers
to objects with non-trivial destructors to use unique_ptr's. This
avoided memory leaks when unloading/loading the (shared) library.
However, some environments might prefer not running these destructors
(e.g. tests that never unload the library nor merge all threads before
exiting).
This commit makes the use of unique_ptr vs. raw pointers optional for
these object pointers via a compile-time flag.
> utils: define maybe_unique_ptr and wrap static unique_ptr's with it

- src/backend/graph_compiler/core/src/compiler/ir/graph/lowering.cpp
Hi,
This PR fix a typo `make_gloabl_string` -> `make_global_string`.
> [Typo] fix typo in lowering.cpp

- src/cpu/aarch64/injectors/jit_uni_eltwise_injector.cpp
- src/cpu/aarch64/injectors/jit_uni_eltwise_injector.hpp
- src/cpu/aarch64/jit_sve_512_1x1_conv_kernel.cpp
- src/cpu/aarch64/jit_sve_512_conv_kernel.cpp
- src/cpu/aarch64/jit_uni_dw_conv_kernel_utils.hpp
- src/cpu/aarch64/jit_uni_softmax.hpp
This patch fixes three bugs for AArch64 JITed eltwise.  
- Correctly disabled eltwise algorithms that are currently not supported by JIT for aarch64.
- Fixed a bug in eltwise:log. Inf was not correctly output when Inf was input.
- Fixed invalidation for non-supported data type.
```
./benchdnn --eltwise --skip-impl=ref --tag=axb --alg=log --alpha=0 --beta=0 --inplace=true 5x16x3
./benchdnn --softmax --sdt=bf16 --ddt=bf16 --inplace=true 96x1000
./test_convolution_eltwise_forward_f32 --gtest_filter="Convolution_SimpleSmall_Blocked16_eltwise/convolution_test.TestConvolutionEltwise/41"
```
- [Not needed] Have you added relevant regression tests?
> aarch64: eltwise: fix invalidation of unsupported alg. and Log Inf check

- src/cpu/aarch64/jit_primitive_conf.hpp
- src/cpu/aarch64/jit_sve_512_core_x8s8s32x_deconvolution.cpp
- src/cpu/aarch64/jit_sve_512_core_x8s8s32x_deconvolution.hpp
- src/cpu/aarch64/jit_uni_deconv_zp_pad_str_kernel.cpp
- src/cpu/aarch64/jit_uni_deconv_zp_pad_str_kernel.hpp
- src/cpu/cpu_deconvolution_list.cpp
This patch adds jit implementation of deconvolution for AARch64 SVE512.
https://github.com/oneapi-src/oneDNN/pull/1382 and https://github.com/oneapi-src/oneDNN/pull/1383 are required before merge this patch.
> aarch64: deconv: add jit impl. of deconvolution for sve_512

- src/cpu/aarch64/acl_prelu.cpp
- src/cpu/aarch64/acl_prelu.hpp
- src/cpu/cpu_prelu_list.cpp
This PR adds a PReLU primitive which makes use of Compute Library for the Arm® architecture (ACL), optimised for AArch64 targets. The datatype support is just for f32 and can only be used in forward mode.
Implementation follows a similar approach to #1281, including measures to avoid the parallelisation of small workloads. It builds upon the approach originally introduced in the PR #820 and RFC #795. The primitive offers a minimum of ~ x10 speedup
for large tensors (~1million f32s) and is comparable for very small tensors.
Co-authored-by: Louis Kaplan <louis.kaplan@arm.com>
> cpu: aarch64: add ACL PReLU primitive

- src/cpu/aarch64/matmul/acl_matmul.hpp
- src/cpu/aarch64/matmul/acl_matmul_utils.cpp
- src/cpu/aarch64/matmul/acl_matmul_utils.hpp
- src/cpu/matmul/matmul_utils.hpp
- tests/benchdnn/inputs/matmul/test_matmul_all
This PR provides a fix for matmul broadcast test cases on AArch64. Test failures were observed at the TensorFlow level associated with oneDNN matmul implementation using ACL. TensorFlow unit test failure list:
```
//tensorflow/python/ops/parallel_for:math_test_cpu
//tensorflow/python/kernel_tests/linalg:linear_operator_householder_test_cpu
//tensorflow/python/kernel_tests/linalg:linear_operator_inversion_test_cpu
//tensorflow/python/kernel_tests/linalg:linear_operator_block_diag_test_cpu
//tensorflow/python/kernel_tests/linalg:linear_operator_block_lower_triangular_test_cpu
//tensorflow/python/kernel_tests/linalg:linear_operator_kronecker_test_cpu
//tensorflow/python/kernel_tests/math_ops:batch_matmul_op_test_cpu
//tensorflow/python/eager:forwardprop_test_cpu
```
It also improves test …
> src: cpu: aarch64 Fixes matmul broadcast on AArch64

- src/gpu/amd/miopen_eltwise.cpp
- src/gpu/amd/miopen_eltwise.hpp
- src/gpu/amd/miopen_eltwise_impl.hpp
- src/gpu/amd/sycl_hip_engine.cpp
- tests/gtests/api/test_engine.cpp
- tests/gtests/sycl/api/test_memory_buffer.cpp
- tests/gtests/test_eltwise.cpp
- tests/gtests/test_iface_pd_iter.cpp
Introducing AMD backend for the oneDNN Eltwise primitive.
Limitations: 
MIOpen only supports NCHW layout format. MIOpen has limited support for only subset of oneDNN Eltwise algorithms as mentioned below.
We are also attaching output log files for gtests and benchdnn.
[test_internals.log](https://github.com/oneapi-src/oneDNN/files/9006972/test_internals.log)
[test_regression.log](https://github.com/oneapi-src/oneDNN/files/9006973/test_regression.log)
[test_api_buffer.log](https://github.com/oneapi-src/oneDNN/files/9006967/test_api_buffer.log)
[test_api_sycl.log](https://github.com/oneapi-src/oneDNN/files/9006968/test_api_sycl.log)
[test_eltwise.log](https://github.com/oneapi-src/oneDNN/files/9006969/test_eltwise.log)
[test_eltwise_buffer.log](https://github.com/oneapi-src/oneDNN/files/9006 …
> Adding support for Eltwise primitive for AMD backend

- rfcs/20220523-depthwise-post-op-extension/README.md
[Link to rendered document](https://github.com/dzarukin/oneDNN/tree/dzarukin/rfcs/depthwise_post_op_generalization/rfcs/20220523-depthwise-post-op-extension).
> rfc: extend depthwise post-op API

- src/gpu/amd/miopen_softmax.cpp
- src/gpu/amd/miopen_softmax.hpp
- src/gpu/amd/miopen_softmax_impl.hpp
- src/gpu/amd/sycl_hip_engine.cpp
- src/gpu/amd/sycl_hip_utils.hpp
- tests/gtests/test_logsoftmax.cpp
- tests/gtests/test_softmax.cpp
- tests/gtests/test_softmax_v2.cpp
Introducing AMD backend for the oneDNN Softmax primitive.
Limitations:
MIOpen only supports NCHW layout format.
We are also attaching output log files for gtests and benchdnn.
[test_softmax.log](https://github.com/oneapi-src/oneDNN/files/9039909/test_softmax.log)
[test_softmax_v2.log](https://github.com/oneapi-src/oneDNN/files/9039910/test_softmax_v2.log)
[test_softmax_buffer.log](https://github.com/oneapi-src/oneDNN/files/9039911/test_softmax_buffer.log)
[test_regression.log](https://github.com/oneapi-src/oneDNN/files/9039912/test_regression.log)
[test_logsoftmax.log](https://github.com/oneapi-src/oneDNN/files/9039913/test_logsoftmax.log)
[test_logsoftmax_buffer.log](https://github.com/oneapi-src/oneDNN/files/9039914/test_logsoftmax_buffer.log) …
> Adding support for Softmax primitive for AMD backend

- src/cpu/x64/jit_avx512_core_x8s8s32x_1x1_conv_kernel.cpp
- src/cpu/x64/jit_avx512_core_x8s8s32x_1x1_conv_kernel.hpp
- src/cpu/x64/jit_uni_x8s8s32x_1x1_conv_kernel.cpp
- src/cpu/x64/jit_uni_x8s8s32x_1x1_conv_kernel.hpp
When I read the code of conv1x1 int8 implements, I find that the `substep` param in the `reduce_loop` function is not used in the function body. So this PR is trying to remove it.
This PR has run all unit tests, but not benchdnn tests.
> src: cpu: x64: int8: 1x1_conv: remove unused param in reduce_loop call

- .github/automation/.drone.yml
- .github/automation/build_acl.sh
- README.md
- cmake/ACL.cmake
- doc/build/build_options.md
Updates the expected Compute Library for the Arm® Architecture (ACL) version for builds on AArch64 with the Compute Library backend.
The ACL version is updated from 22.02 to 22.05 in:
- DroneCI builds
- Docs
- ACL.cmake
> cpu: aarch64: build: update Compute Library version to 22.05

- src/cpu/aarch64/acl_binary.hpp
- src/cpu/aarch64/acl_prelu.hpp
- src/cpu/aarch64/acl_utils.cpp
- src/cpu/aarch64/acl_utils.hpp
Changes the way we pass dimensions into the Compute Library for the Arm® Architecture (ACL) binary/PReLU operators. Instead of just making the innermost dimension dense, we attempt to order the dimensions of all 3 tensors (`src0`, `src1`, `dst`) by stride so that the memory accesses are as contiguous as possible. This speeds up single threaded performance for NHWC (and other non-naturally ordered tensors) by ~2x, with the speed up decreasing gradually as we use more cores, to around ~0.1x speedup for >16 cores. There is no functional or performance change for NCHW.
This, along with #1404, fixes the regressions identified in #1330.
> cpu: aarch64: Reorder dims by stride in ACL binary

- src/cpu/aarch64/cpu_isa_traits.hpp
- src/cpu/aarch64/injectors/injector_utils.cpp
- src/cpu/aarch64/injectors/injector_utils.hpp
- src/cpu/aarch64/injectors/jit_uni_binary_injector.cpp
- src/cpu/aarch64/injectors/jit_uni_binary_injector.hpp
- src/cpu/aarch64/injectors/jit_uni_eltwise_injector.cpp
- src/cpu/aarch64/injectors/jit_uni_eltwise_injector.hpp
- src/cpu/aarch64/injectors/jit_uni_postops_injector.cpp
- src/cpu/aarch64/injectors/jit_uni_postops_injector.hpp
- src/cpu/aarch64/jit_generator.hpp
- src/cpu/aarch64/jit_primitive_conf.hpp
- src/cpu/aarch64/jit_sve_512_1x1_conv_kernel.cpp
- src/cpu/aarch64/jit_sve_512_conv_kernel.cpp
- src/cpu/aarch64/jit_uni_binary.cpp
- src/cpu/aarch64/jit_uni_binary.hpp
- src/cpu/aarch64/jit_uni_binary_kernel.cpp
- src/cpu/aarch64/jit_uni_binary_kernel.hpp
- src/cpu/aarch64/jit_uni_dw_conv_kernel_utils.hpp
- src/cpu/aarch64/jit_uni_softmax.hpp
- src/cpu/aarch64/utils/jit_io_helper.cpp
- src/cpu/aarch64/utils/jit_io_helper.hpp
- src/cpu/cpu_binary_list.cpp
This patch adds jit implementation of binary for AArch64 SVE512.
> aarch64: binary: add jit impl. for sve_512

- src/cpu/aarch64/acl_convolution_utils.cpp
- src/cpu/aarch64/acl_eltwise.hpp
- src/cpu/aarch64/acl_utils.cpp
- src/cpu/aarch64/acl_utils.hpp
This fixes a bug where all ACL-based primitives were assuming int8 types as being quantised types.
> Remove assumption of int8 quantisation in ACL-based implementations

- src/gpu/amd/miopen_lrn.cpp
- src/gpu/amd/miopen_lrn.hpp
- src/gpu/amd/miopen_lrn_impl.hpp
- src/gpu/amd/sycl_hip_engine.cpp
- tests/benchdnn/lrn/lrn.cpp
- tests/gtests/test_lrn_backward.cpp
- tests/gtests/test_lrn_forward.cpp
Introducing AMD backend for the oneDNN Local Response Normalization(LRN) primitive.
Limitations:
MIOpen only supports NCHW layout format.
We are also attaching output log files for gtests and benchdnn.
[benchdnn_test_lrn_all.log](https://github.com/oneapi-src/oneDNN/files/9253810/benchdnn_test_lrn_all.log)
[test_api_buffer.log](https://github.com/oneapi-src/oneDNN/files/9253811/test_api_buffer.log)
[test_api_sycl.log](https://github.com/oneapi-src/oneDNN/files/9253812/test_api_sycl.log)
[test_internals.log](https://github.com/oneapi-src/oneDNN/files/9253813/test_internals.log)
[test_lrn_backward.log](https://github.com/oneapi-src/oneDNN/files/9253814/test_lrn_backward.log)
[test_lrn_backward_buffer.log](https://github.com/oneapi-src/oneDNN/files/9253815/test_lrn_backward_buffer.log) …
> Adding support for Local Response Normalization(LRN) primitive for AMD backend

- src/cpu/aarch64/acl_pooling.cpp
- src/cpu/aarch64/acl_pooling.hpp
- src/cpu/cpu_pooling_list.cpp
- tests/benchdnn/pool/pool.cpp
- tests/gtests/test_pooling_backward.cpp
- tests/gtests/test_pooling_forward.cpp
src: cpu: aarch64: add ACL pooling primitive
This patch adds a pooling primitive which makes use of Compute Library for the Arm® architecture (ACL), optimised for AArch64.
This primitive is faster for larger problem sizes and smaller thread counts, up to 64x faster for 1 thread and very large (~2^21) problem sizes (defined as the product of mb, ic, oh, ow, kh, kw). An empirically derived heuristic has been implemented to avoid the cases where this primitive is slower (which is the case below a certain problem size. The particular problem size depends on thread count and pooling algorithm, but for 8 threads and max pooling for example, this primitive is slower for problems sizes less than 2^15)
In order to accommodate a difference in the representation of -inf between ACL and the reference …
> src: cpu: aarch64: Add acl pooling

- cmake/blas.cmake
- src/cpu/gemm/gemm.cpp
- src/cpu/platform.cpp
Access the accelerated bfloat16 matrix multiplication code within OpenBLAS when running on PPC64 machines.
- [ yes ] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [ yes ] Have you formatted the code using clang-format?
> Enable sbgemm on PPC64

- src/cpu/aarch64/matmul/acl_matmul.hpp
Fixes `test_matmul` failing for ACL builds (for example https://cloud.drone.io/oneapi-src/oneDNN/1532/4/2) by returning unimplemented if any tensor has a zero dimension.
> src: aarch64: add check for zero dims in ACL matmul

- src/cpu/aarch64/acl_binary.cpp
- src/cpu/aarch64/acl_binary.hpp
- src/cpu/aarch64/acl_convolution_utils.cpp
- src/cpu/aarch64/acl_convolution_utils.hpp
- src/cpu/aarch64/acl_eltwise.cpp
- src/cpu/aarch64/acl_eltwise.hpp
- src/cpu/aarch64/acl_gemm_convolution.cpp
- src/cpu/aarch64/acl_gemm_convolution.hpp
- src/cpu/aarch64/acl_indirect_gemm_convolution.cpp
- src/cpu/aarch64/acl_indirect_gemm_convolution.hpp
- src/cpu/aarch64/acl_inner_product.cpp
- src/cpu/aarch64/acl_inner_product.hpp
- src/cpu/aarch64/acl_post_ops.cpp
- src/cpu/aarch64/acl_post_ops.hpp
- src/cpu/aarch64/acl_utils.cpp
- src/cpu/aarch64/acl_utils.hpp
- src/cpu/aarch64/acl_winograd_convolution.cpp
- src/cpu/aarch64/acl_winograd_convolution.hpp
- src/cpu/aarch64/matmul/acl_matmul.cpp
- src/cpu/aarch64/matmul/acl_matmul.hpp
- src/cpu/aarch64/matmul/acl_matmul_utils.cpp
- src/cpu/aarch64/matmul/acl_matmul_utils.hpp
Adds class `acl_post_ops_t` which enables Compute Library for the Arm® Architecture (ACL) based primitives to have an arbitrary number and type of post ops by composing `acl_binary_t` and `acl_eltwise_fwd_t`.
This class has been added to:
- `acl_inner_product_fwd_t`
- `acl_matmul_t`
- Convolution: `acl_gemm_convolution_fwd_t`, `acl_wino_convolution_fwd_t` and `acl_indirect_gemm_convolution_fwd_t`
This replaces functionality in these classes which previously supported up to sum+eltwise with a more generalised approach. The primitives still fuse eltwise operations where possible, as before.
This patch also modifies the `acl_eltwise_fwd_t` primitive to support any number of dimensions of input/output tensor.
These changes are covered by existing tests for eltwise and the base primitives …
> cpu: aarch64: add arbitrary ACL post ops

- src/cpu/aarch64/acl_batch_normalization.cpp
- src/cpu/aarch64/acl_batch_normalization.hpp
- src/cpu/aarch64/matmul/acl_matmul_utils.cpp
This PR adds eltwise post ops to the Compute Library for the Arm® architecture (ACL) batch normalization primitive.
ReLU (including leaky and bounded) are fused into the bnorm operator. Other eltwise ops are handled using `acl_post_ops_t` and so supports any that `acl_eltwise_fwd_t` supports.
Adding this functionality just means that the ACL impl now covers more cases. In the newly supported case where ReLU is passed in as a post op (rather than a flag) batchnorm performance improvements over `nspc:bnorm` will be the same as in #1378. The other eltwise post ops which are now incidentally covered are unimplemented in `nspc:bnorm` and `ref`, so there are no performance considerations there.
This PR requires and includes f6dbe1efdd08c88924d9f0f4368abd435473ffe5 cherry picked from #1330, so …
> cpu: aarch64: add eltwise post ops to ACL bnorm

- src/gpu/amd/miopen_pooling.cpp
- src/gpu/amd/miopen_pooling.hpp
- src/gpu/amd/miopen_pooling_impl.hpp
- src/gpu/amd/sycl_hip_engine.cpp
- tests/gtests/test_pooling_backward.cpp
- tests/gtests/test_pooling_forward.cpp
Introducing AMD backend for the oneDNN Pooling primitive.
Limitations:
MIOpen only supports NCHW layout format.
MIOpen does not support dilation for Pooling primitive.
We are also attaching output log files for benchdnn and gtests .
[benchdnn_test_pool_all.log](https://github.com/oneapi-src/oneDNN/files/9435303/benchdnn_test_pool_all.log)
[benchdnn_test_pool_ci.log](https://github.com/oneapi-src/oneDNN/files/9435304/benchdnn_test_pool_ci.log)
[test_api_buffer.log](https://github.com/oneapi-src/oneDNN/files/9435305/test_api_buffer.log)
[test_api_sycl.log](https://github.com/oneapi-src/oneDNN/files/9435306/test_api_sycl.log)
[test_internals.log](https://github.com/oneapi-src/oneDNN/files/9435307/test_internals.log)
[test_pooling_backward.log](https://github.com/oneapi-src/oneDNN/files/943530 …
> Adding support for Pooling primitive for AMD backend

- src/cpu/aarch64/acl_binary.hpp
When built with Compute Library for Arm (ACL) version 22.08, binary addition fails when there is no broadcasting and the strides don't match. This causes `test_binary_all` to fail. This patch adds a guard to return unimplemented in this case.
A patch is also underway for ACL which will fix the next release, and allow us to remove this guard.
> src: aarch64: fix ACL add with non-matching strides

- .github/automation/.azure-pipeline.yml
macOS 10.15 support ended in Azure CI, updated test matrix to cover macOS 11 and macOS 12.
> Updated macOS from 10.15 to 12 in Azure CI

- src/cpu/x64/jit_uni_pool_kernel.cpp
A lot of avx-sse transitions are observed in jit_uni_pook kernel and avx-sse transition slows down the CPU for about tens of cycles.
This patch cleaned the avx-sse transitions that observed. And got a remarkable performance speedup (~10%) with my workload.
This could be observed by emon with the following command:
```shell
:~/openvino/build# emon -C 'ASSISTS.SSE_AVX_MIX' -t1 -l 10000
Version Info: V11.33  (Mar 15 2022 at 22:11:59) Intel(R) microarchitecture code named Alderlake-S M:151 S:2
ASSISTS.SSE_AVX_MIX     2,112,264,872   0       2,162,328       0       0       0       0       0       0       0       0       0       0       0       0       0       0       N/A     N/A     N/A     N/A
==========
ASSISTS.SSE_AVX_MIX     2,112,316,661   0       2,138,112       0       0       0       0 …
```
> fixup: avoid avx-sse transition penalty for jit_uni_pool

- examples/CMakeLists.txt
- src/gpu/nvidia/cudnn_reduction.cpp
- src/gpu/nvidia/cudnn_reduction.hpp
- src/gpu/nvidia/cudnn_reduction_impl.hpp
- src/gpu/nvidia/sycl_cuda_engine.cpp
- tests/gtests/test_reduction.cpp
Introducing CUDA backend for the oneDNN Reduction primitive.
Limitations:
cudnnReduceTensor supports only five modes of reduction operations via enumerators which are as follows.  
- `CUDNN_REDUCE_TENSOR_MAX` 
- `CUDNN_REDUCE_TENSOR_MIN` 
- `CUDNN_REDUCE_TENSOR_MUL`
- `CUDNN_REDUCE_TENSOR_ADD` 
- `CUDNN_REDUCE_TENSOR_AVG` 
We are also attaching output log files for benchdnn and gtests .
[test_regression.log](https://github.com/oneapi-src/oneDNN/files/9572342/test_regression.log)
[test_reduction_buffer.log](https://github.com/oneapi-src/oneDNN/files/9572343/test_reduction_buffer.log)
[test_internals.log](https://github.com/oneapi-src/oneDNN/files/9572344/test_internals.log)
[test_api_buffer.log](https://github.com/oneapi-src/oneDNN/files/9572345/test_api_buffer.log) …
> Adding support for Reduction Primitive for CUDA backend

- examples/CMakeLists.txt
- src/gpu/amd/miopen_reduction.cpp
- src/gpu/amd/miopen_reduction.hpp
- src/gpu/amd/miopen_reduction_impl.hpp
- src/gpu/amd/sycl_hip_engine.cpp
- tests/benchdnn/reduction/reduction.cpp
Introducing AMD backend for the oneDNN Reduction primitive.
Limitations:
MIOpen only supports NCHW layout format.
Supported scope:
Supported Data Types: f32, f16
This backend only supports the following algorithms:
- reduction_max
- reduction_min
- reduction_sum
- reduction_mul
- reduction_mean
- reduction_norm_lp_sum
- reduction_norm_lp_power_p_sum
> Adding Support for Reduction-HIP Backend

- src/cpu/aarch64/jit_uni_dw_conv_kernel_utils.hpp
This patch fixes the JIT-ed implementation of convolution for AArch64 SVE environment.
For example, the following `benchdnn` test patterns, which are included `tests/benchdnn/inputs/conv/test_conv_all`, will be passed correctly.
```
--conv --skip-impl=ref --dir=BWD_D g32ic32ih14iw14oc32oh7ow7kh3kw3sh2sw2ph1pw1dh1dw0ndilated_conv:41/dw
--conv --skip-impl=ref --dir=BWD_D g64ic64ih112iw112oc64oh56ow56kh3kw3sh2sw2ph1pw1dh1dw2ndilated_conv:42/dw
--conv --skip-impl=ref,x64:gemm --dir=BWD_D g32ic32ih14iw14oc32oh7ow7kh3kw3sh2sw2ph1pw1dh1dw0ndilated_conv:41/dw
--conv --skip-impl=ref,x64:gemm --dir=BWD_D g64ic64ih112iw112oc64oh56ow56kh3kw3sh2sw2ph1pw1dh1dw2ndilated_conv:42/dw
```
> cpu: aarch64: conv: fix skip condition for dilated conf

- rfcs/20220929-threadpool_max_concurrency/README.md
[Link to rendered document](https://github.com/mgouicem/oneDNN/tree/rfcs/rfcs/20220929-threadpool_max_concurrency)
This RFC proposes to expose functions to set the maximum concurrency with the threadpool backend.
This is a stop gap solution until our CPU optimizations shift their threading heuristics from OMP model to task base model.
> rfcs: threadpool max concurrency setting

- rfcs/20220815-v3.0-API-cleanup/README.md
- rfcs/20220815-v3.0-API-cleanup/dnnl.h
- rfcs/20220815-v3.0-API-cleanup/dnnl.hpp
- rfcs/20220815-v3.0-API-cleanup/dnnl_types.h
[Link to a rendered document](https://github.com/dzarukin/oneDNN/tree/dzarukin/rfcs/v3_cleanup/rfcs/20220815-v3.0-API-cleanup).
This document mentions all (or at least most) changes coming in v3.0 when it comes to names changed or removed.
P.S. Though RFC shows 20k new lines, all of them are copy-pasted public headers to keep nice links inside the document actual.
> rfc: v3 API cleanup

- src/cpu/ppc64/ppc64_gemm_s8x8s32.hpp
After some review, I realized that the eight packing routines in my code for Power-optimized 8-bit matrix multiplication were slow (and also fairly hard to read and understand).  
I've replaced them with new routines.
The four 8-bit packing routines now run 4x faster than before.
The four 16-bit "fallback" packing routines run 2x faster than previously.
The code size for these eight routines is roughly half of what it was before.
- [ YES] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [ YES] Have you formatted the code using clang-format?
- [ See answer] Have you submitted performance data that demonstrates performance improvements?
I will attach a spreadsheet in a comment below that summarizes the …
> Faster packing

- src/cpu/aarch64/acl_eltwise.hpp
- src/cpu/aarch64/jit_uni_eltwise.cpp
- src/cpu/aarch64/matmul/acl_matmul_utils.cpp
This PR covers minor changes to fix issues that were encountered when running unit tests:
(1) Set default value for alpha scaling in matmul
(2) Use method is_alg_supported() from eltwise_injector when initialising primitive to decide whether algorithm is supported or not
Run tests cpp-tutotirals-matmul-matmul-quantization-cpp and test_benchdnn_eltwise_ci_cpu to see failures
- [N/A] Have you …
> fixup: api: aarch64: matmul and eltwise inits

- src/cpu/aarch64/jit_generator.hpp
- src/cpu/aarch64/jit_uni_batch_normalization.cpp
- src/cpu/aarch64/jit_uni_batch_normalization.hpp
This PR adds support of [the batch normalization flags](https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/doc/driver_bnorm.md) for SVE 512 jit-ed.
> cpu: aarch64: bnorm: support flags for SVE 512 jit-ed

- src/cpu/aarch64/jit_generator.hpp
- src/cpu/aarch64/jit_uni_reorder.cpp
- src/cpu/aarch64/jit_uni_reorder.hpp
- src/cpu/aarch64/jit_uni_reorder_utils.cpp
- src/cpu/reorder/cpu_reorder_regular_f32_f32.cpp
- src/cpu/reorder/cpu_reorder_regular_f32_s32.cpp
- src/cpu/reorder/cpu_reorder_regular_f32_s8.cpp
- src/cpu/reorder/cpu_reorder_regular_f32_u8.cpp
- src/cpu/reorder/cpu_reorder_regular_s32.cpp
- src/cpu/reorder/cpu_reorder_regular_s8.cpp
- src/cpu/reorder/cpu_reorder_regular_u8.cpp
This PR adds jit-ed blk_reorder for AArch64.
> cpu: aarch64: reorder: support jit-ed blk_reorder

- src/cpu/aarch64/acl_batch_normalization.hpp
Adds a guard to return unimplemented when src and dst layouts don't match in `acl_batch_normalization_fwd_t`. The underlying class, `arm_compute::NEBatchNormalizationLayer` does not support different src and dst layouts, and neither does the oneDNN ref implementation. This has only recently become necessary due to changes for v3.0 (#1440).
This is tested in `Test_BatchNormalization_EF`, but it doesn't currently fail on AArch64 because the test bails early (because ACL bnorm only supports global stats and the test throws an error before it gets there). There is no sensible and easy way to modify this test to fail, and I assume at some point benchdnn will be able to specify differing src and dst tags for bnorm. I think it makes sense to try to get this in as is for v3.0, but I'm open to …
> cpu: aarch64: Handle src!=dst in ACL bnorm

- src/cpu/aarch64/jit_uni_dw_conv_kernel_utils.hpp
- src/cpu/aarch64/xbyak_aarch64/src/xbyak_aarch64_impl.h
This PR fixes invalid nb_ch calculation and binary code of CBZ instruction of jit-ed `dwconv` for SVE.
```
build/tests/benchdnn/benchdnn --conv --stag=aBcd16b --wtag=Abcde16a --dtag=aBcd16b \
g47mb1_ic47oc47_ih20oh20kh3sh1dh0ph1_iw20ow20kw3sw1dw0pw1
```
```
build/tests/benchdnn/ --deconv --mode=C --dir=FWD_I --cfg=u8s8f32 \
g1ic16ih5oc3oh5kh3ph1n"2d_conv:1st"
```
- [Not needed] Have you added relevant regression tests?
> cpu: aarch64: deconv: fix invalid nb_ch and CBZ instruction

- src/cpu/aarch64/injectors/jit_uni_eltwise_injector.cpp
- src/cpu/aarch64/injectors/jit_uni_eltwise_injector.hpp
This PR fixes invalid preserved Z register size and indices of jit-ed `eltwise` for SVE.
```
tests/gtests/test_convolution_eltwise_forward_f32 \
--gtest_filter="Convolution_SimpleSmall_Blocked16_Tail_eltwise_CPU/\
convolution_test.TestConvolutionEltwise/0"
```
```
tests/benchdnn/benchdnn --conv --dir=FWD_I --stag=axb --dtag=axb \
--attr-post-ops=relu+dw_k3s2p1+tanh --attr-scratchpad=user \
ic32ih112oc64oh112kh1ph0n"MobileNet_v1_fused_stride_2"
```
> cpu: aarch64: eltwise: fix invalid preserved Z register size and indices

- src/cpu/aarch64/injectors/injector_utils.cpp
- src/cpu/aarch64/injectors/jit_uni_binary_injector.cpp
- src/cpu/aarch64/injectors/jit_uni_postops_injector.cpp
- src/cpu/aarch64/jit_primitive_conf.hpp
- src/cpu/aarch64/jit_uni_binary.cpp
- src/cpu/aarch64/jit_uni_binary_kernel.cpp
- src/cpu/aarch64/utils/jit_io_helper.cpp
This PR adds support of plane_layout and blk_size = 8, 4 to jit-ed `binary` for SVE 512/256/128.
https://github.com/oneapi-src/oneDNN/pull/1489 and https://github.com/oneapi-src/oneDNN/pull/1490 are required before this patch.
> cpu: aarch64: binary: support blk_size = 8, 4

- src/cpu/ref_deconvolution.hpp
Resource allocation for ACL object is missing in ref_deconvolution_bwd_data_t struct.
This causes benchdnn tests to crash. This patch adds a method for resource allocation
to fix this issue.
oneDNN 2.7 and git hash f4cc312
- CPU: aarch64
- OS version: Ubuntu 20.04
- Compiler version: GCC 10.3.0
- CMake version: 3.16.3
```
./tests/benchdnn/benchdnn --deconv --dir=BWD_D ic384ih13oc256oh13kh3ph1n"alexnet:deconv3"
terminate called after throwing an instance of 'std::out_of_range'
what():  _Map_base::at
Aborted (core dumped)
```
> cpu: aarch64: deconv: fix ACL resource allocation

- src/cpu/aarch64/acl_deconvolution.cpp
- src/cpu/aarch64/acl_deconvolution.hpp
- src/cpu/cpu_deconvolution_list.cpp
This PR adds a deconvolution primitive which makes use of the Compute Library for the Arm® architecture (ACL),
optimised for AArch64 targets. The datatype support is f32 and f16 and can only be used in forward mode.
This primitive is up to ~27x faster than the reference deconvolution implementation on AArch64.
> cpu: aarch64: deconv: add ACL deconvolution

- src/cpu/aarch64/acl_post_ops.hpp
The oneDNN API specifies that post ops need to (always) be executed in fp32, but ACL executes them in f16 (when running in fp16 mode) which caused a lot of conv+relu benchdnn tests to fail.
Fixes # (#1499)
- [ YES ] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [ YES ] Have you formatted the code using clang-format?
- [ N/A] Have you submitted performance data that demonstrates performance improvements?
- [ N/A] Have you published an RFC for the new feature?
- [ N/A] Was the RFC approved?
- [ N/A] Have you added relevant tests?
- [ YES] Have you included information on how to reproduce the issue (either in a github issue or in this PR)?
- [ N/A] Have you added relevant regression tests?
> cpu: aarch64: fp16 postops: disable ACL post ops for fp16

- src/cpu/aarch64/acl_convolution_utils.cpp
- src/cpu/aarch64/acl_inner_product.hpp
- src/cpu/aarch64/matmul/acl_matmul_utils.cpp
Previously, running benchdnn with `--attr-fpmath` flags set would not have any effect for primitives calling ACL kernels. Only the environment flag would change the behaviour. This patch fixes this to use the correct interface, via `attr`, which takes into account both settings.
Given that it is a bug fix, would it be possible to get this cherry picked onto the release branch please?
> cpu: aarch64: get fpmath mode from attr instead of just env

- src/cpu/aarch64/acl_utils.cpp
This PR adds support for oneDNN's clip algorithm using the Bounded Relu from Compute Library for the Arm® architecture (ACL).
Benchmarks show that performance improvements compared to ref are similar to other algs.
- [N/A] Have you added a link to the rendered document?
> cpu: aarch64: add clip using ACL bounded relu

- examples/CMakeLists.txt
- src/gpu/amd/miopen_matmul.cpp
- src/gpu/amd/miopen_matmul.hpp
- src/gpu/amd/miopen_matmul_executor.hpp
- src/gpu/amd/miopen_matmul_impl.hpp
- src/gpu/amd/sycl_hip_engine.cpp
- src/gpu/amd/sycl_hip_engine.hpp
- src/gpu/amd/sycl_hip_stream.cpp
- src/gpu/amd/sycl_hip_stream.hpp
- src/gpu/amd/sycl_hip_utils.hpp
- tests/gtests/test_matmul.cpp
**Introducing AMD backend for the oneDNN Matmul primitive.**
Supported Data Types: f32, f16, s8/s32, bf16
gtest: API tests passed, Matmul tests passed
Log files for benchdnn:
[test_matmul_all.log](https://github.com/oneapi-src/oneDNN/files/10193081/test_matmul_all.log)
[test_matmul_ci.log](https://github.com/oneapi-src/oneDNN/files/10193086/test_matmul_ci.log)
Log files for gtests:
[test_api_buffer.log](https://github.com/oneapi-src/oneDNN/files/10193075/test_api_buffer.log)
[test_api_sycl.log](https://github.com/oneapi-src/oneDNN/files/10193076/test_api_sycl.log)
[test_internals.log](https://github.com/oneapi-src/oneDNN/files/10193078/test_internals.log)
[test_regression.log](https://github.com/oneapi-src/oneDNN/files/10193087/test_ …
> Adding Support for Matmul Primitive - HIP Backend

- src/cpu/aarch64/jit_uni_binary.cpp
Test test_iface_attr_quantization.TestBinary fails on Neoverse-V1 machines.
When running on Neoverse-V1, `src/cpu/aarch64/jit_uni_binary.cpp` is targeted during the test. The test checks to ensure DST cannot have a scale attribute, which fails on aarch64.
This is due to function `jit_uni_binary_t::pd_t::check_scales_mask()` missing a check on aarch64 to ensure only DNNL_ARG_SRC_0 and DNNL_ARG_SRC_1 are the allowed arguments.
This patch adds a similar check existing for x64 in `src/cpu/x64/jit_uni_binary.cpp` to the aarch64 version. …
> cpu: aarch64: fix test test_iface_attr_quantization

- rfcs/20230104-add-hardsigmoid-graph-op/README.md
This RFC is to add a new HardSigmoid operation to oneDNN graph API opset.
The rendered version: [link](https://github.com/TaoLv/mkl-dnn/tree/lvtao/rfcs/graph-hard-sigmoid/rfcs/20230104-add-hardsigmoid-graph-op)
> rfc: propose hardsigmoid op for graph api

- src/cpu/aarch64/acl_threadpool_scheduler.cpp
This PR fixes the threadpool scheduler implementation in oneDNN-AArch64 to make each thread maintain a local pointer to the threadpool.
Fixes the segmentation fault in https://github.com/tensorflow/tensorflow/pull/58071.
- [ N/A] Have you submitted performance data that demonstrates performance improvements?
- [N/A] Have you added a link to the rendered document?
> src: cpu: aarch64: Fix ACL threadpool scheduler

- src/cpu/aarch64/acl_layer_normalization.cpp
- src/cpu/aarch64/acl_layer_normalization.hpp
- src/cpu/cpu_layer_normalization_list.cpp
This patch adds an lnorm primitive which makes use of Compute Library for the Arm® architecture (ACL), optimised for AArch64.
This primitive is faster for larger channel sizes, larger problem sizes, and smaller thread counts. eg. approximately 40x faster than ref:any, and 5x faster than simple:any for 1 thread and problem size ~10^6.
An empirically derived heuristic has been implemented to avoid the cases where this primitive is slower (Which is the case below a certain channel size, and below a certain problem size per thread). For example, for 1 thread, if no stats are provided (flags=none), acl is slower than simple:any for C<64, and for 64<C<1024, acl is slower when problem size<1024.
> src:cpu:aarc64: add ACL lnorm primitive

- src/cpu/aarch64/acl_inner_product.hpp
- src/cpu/aarch64/matmul/acl_matmul.hpp
- src/cpu/aarch64/matmul/acl_matmul_utils.cpp
Three loosely related small fixes for `acl_matmul` and `acl_inner_product`
For example, running
```
./benchdnn --matmul -v5 3x5:5x7
```
now uses ACL
ACL IP does not support transposed src, but if src was square, it wasn't being detected by validation and would silently fail. This has now been removed
```
./benchdnn --ip --dir=FWD_I --stag=ba --wtag=ba --dtag=ba mb100ic100oc100
```
This is not supported and produces incorrect results so it has been removed
```
./benchdnn --matmul -v5 --dtag=acb 1x3x5:1x5x7 1x3x5:11x5x7 11x3x5:1x5x7
```
> Some small memory layout fixes for ACL matmul and inner product

- src/gpu/nvidia/sycl_cuda_engine.cpp
This change optimizes the computation in `underlying_context_type()`  by reducing the expensive calls to `cuDevicePrimaryCtxRetain` and  `cuDevicePrimaryCtxRelease`. It will be helpful in the case where a system has multiple devices.
[N/A] Have you published an RFC for the new feature?
[N/A] Was the RFC approved?
[N/A] Have you added relevant tests?
[N/A] Have you included information on how to reproduce the issue (either in a github issue or in this PR)?
[N/A] Have you added relevant regression tests?
[N/A] Does RFC document follow the [template](https://github.com/oneapi-src/oneDNN/blob/rfcs/rfcs/template.md#onednn-design-document-rfc)?
[N/A] Have you added a link to the rendered document?
> gpu: sycl: optimize computing underlying context type

- src/cpu/aarch64/jit_uni_binary.cpp
Test test_iface_attr_quantization.TestBinary fails on Neoverse-V1 machines.
When running on Neoverse-V1, `src/cpu/aarch64/jit_uni_binary.cpp` is targeted during the test. The test checks to ensure DST cannot have a scale attribute, which fails on aarch64.
This is due to function `jit_uni_binary_t::pd_t::check_scales_mask()` missing a check on aarch64 to ensure only DNNL_ARG_SRC_0 and DNNL_ARG_SRC_1 are the allowed arguments.
This patch adds a similar check existing for x64 in `src/cpu/x64/jit_uni_binary.cpp` to the aarch64 version. …
> cpu: aarch64: fix test test_iface_attr_quantization rls-v3.0

- src/cpu/aarch64/acl_post_ops.hpp
Remove check when copying ACL post ops, following the recent change which removes status_t return
in primitive attributes (commit a89321f).
- [N/A] Have you added a link to the rendered document?
> cpu: aarch64: fix acl post ops compilation

- src/gpu/nvidia/cudnn_reorder.hpp
- src/gpu/nvidia/sycl_cuda_utils.cpp
- src/gpu/nvidia/sycl_cuda_utils.hpp
**Supported Data Types:** bf16
sdt=bf16 and ddt=bf16, f32, s8
sdt=bf16, f32, s8 and ddt=bf16
**Non Supported Data Types:** 
sdt=bf16 and ddt=f16
sdt=f16 and ddt=bf16
**Supported GPU for bf16:**
NVIDIA A100
**Test output file:**
[test_reorder_all_result.txt](https://github.com/oneapi-src/oneDNN/files/10868643/test_reorder_all_result.txt)
[test_reorder_ci_result.txt](https://github.com/oneapi-src/oneDNN/files/10868645/test_reorder_ci_result.txt)
GPU: NVIDIA A100
**General**
> added bf16 support for cuDNN reorder

- src/gpu/nvidia/README.md
- src/gpu/nvidia/cudnn_eltwise.hpp
- src/gpu/nvidia/cudnn_pooling.cpp
- src/gpu/nvidia/cudnn_pooling.hpp
**Supported scope:
Supported Data Types:**
Forward : bf16
Backward : bf16
**Supported GPU for bf16**
NVIDIA A100
**Test output file:**
[test_eltwise_all.txt](https://github.com/oneapi-src/oneDNN/files/10857487/test_eltwise_all.txt)
GPU: NVIDIA A100
> cuDNN bf16 support for Eltwise

- src/gpu/nvidia/cudnn_batch_normalization.hpp
- src/gpu/nvidia/cudnn_batch_normalization_impl.hpp
- tests/benchdnn/bnorm/bnorm.cpp
Added bf16 datatype support for Batch Normalization
- Forward
- Backward
- ## General 
benchdnn: Passed 
benchdnn: Failed(Known issues)
NVIDIA A100, NVIDIA H100, 
GPU : NVIDIA A100
Please refer below.
[Test_outputs_bnorm.zip](https://github.com/oneapi-src/oneDNN/files/10884811/Test_outputs_bnorm.zip)
> Nvidia Backend:Bf16 datatype support added for Batch Normalization

- src/gpu/nvidia/cudnn_conv_inner_product.hpp
- src/gpu/nvidia/cudnn_gemm_inner_product.hpp
- src/gpu/nvidia/cudnn_gemm_inner_product_impl.hpp
**Supported scope:
Supported Data Types:**
Forward : bf16 
FWD_D : bf16bf16f32 , s8s8bf16
Backward : bf16
BWD_D : f32bf16bf16 ,  bf16bf16bf16
**Non Supported Data Type:**
FWD_D : bf16bf16bf16
BWD_D : s8s8bf16
**Supported GPU for bf16**
NVIDIA A100, Testla T4 
GPU : NVIDIA A100
Failed Testcase are tested on GPU : Nvidia Testla T4
**Test output file on A100 GPU:**
[test_ip_all_result.txt](https://github.com/oneapi-src/oneDNN/files/10870120/test_ip_all_result.txt)
[test_ip_bfloat16_result.txt](https://github.com/oneapi-src/oneDNN/files/10870121/test_ip_bfloat16_result.txt)
[test_ip_ci_result.txt](https://github.com/oneapi-src/oneDNN/files/10870122/test_ip_ci_result.txt)
**Few Case which failed on A100 are tested on Testla T4 gpu , …
> Added bf16 support for cuDNN inner product

- src/gpu/nvidia/cudnn_matmul.hpp
- src/gpu/nvidia/cudnn_matmul_impl.hpp
Supported Data Types: bf16
**Supported GPU for bf16:**
NVIDIA A100
**Test output file:**
[test_matmul_ci_result.txt](https://github.com/oneapi-src/oneDNN/files/10881427/test_matmul_ci_result.txt)
[test_matmul_bfloat16_result.txt](https://github.com/oneapi-src/oneDNN/files/10881429/test_matmul_bfloat16_result.txt)
GPU: NVIDIA A100
GPU: NVIDIA A100
**Comment:**
In the existing code few cases was failing for other data type. Similarly, for bf16 as well same cases do failed.
> Added bf16 support for matmul in cuDNN

- examples/CMakeLists.txt
- src/gpu/amd/miopen_gemm_inner_product.hpp
- src/gpu/amd/miopen_gemm_inner_product_impl.hpp
- src/gpu/amd/miopen_inner_product.cpp
- src/gpu/amd/miopen_inner_product.hpp
- src/gpu/amd/miopen_inner_product_impl.hpp
- src/gpu/amd/sycl_hip_engine.cpp
- src/gpu/amd/sycl_hip_engine.hpp
- src/gpu/amd/sycl_hip_utils.hpp
Introducing AMD backend for the oneDNN Innerproduct primitive.
Supported Data Types: 
Forward : f32, f16, s8/s32, bf16
Backward data : f32, bf16
Backward weight : f32, bf16
gtest: API tests passed, Innerproduct tests passed
**Log files for benchdnn:**
[test_ip_all.log](https://github.com/oneapi-src/oneDNN/files/10471606/test_ip_all.log)
[test_ip_ci.log](https://github.com/oneapi-src/oneDNN/files/10471607/test_ip_ci.log)
**Log files for gtests:**
[test_inner_product_forward.log](https://github.com/oneapi-src/oneDNN/files/10471610/test_inner_product_forward.log)
[test_inner_product_forward_buffer.log](https://github.com/oneapi-src/oneDNN/files/10471611/test_inner_product_forward_buffer.log) …
> Adding Support for Innerproduct Primitive - HIP Backend

- rfcs/20230204-make-graph-api-default/README.md
The RFC is proposing to build graph API by default and make it a general available feature in the next release.
Rendered document: [link](https://github.com/TaoLv/mkl-dnn/blob/lvtao/rfcs/make-graph-default/rfcs/20230204-make-graph-api-default/README.md)
> rfc: build graph api by default

- src/gpu/nvidia/README.md
- src/gpu/nvidia/cudnn_softmax.cpp
- src/gpu/nvidia/cudnn_softmax.hpp
- src/gpu/nvidia/cudnn_softmax_impl.hpp
**Supported Data Types:**
Forward : bf16, s8
Backward : bf16
**Added Output scale support for forward**
**Supported GPU for bf16**
NVIDIA A100
**Test output file:**
[test_softmax_all.txt](https://github.com/oneapi-src/oneDNN/files/10908792/test_softmax_all.txt)
GPU: NVIDIA A100
> Nvidia Backend:Bf16, S8 datatype & output scale added  support for Softmax

- src/cpu/aarch64/jit_generator.hpp
- src/cpu/aarch64/jit_uni_pooling.cpp
- src/cpu/aarch64/jit_uni_reorder.cpp
- src/cpu/aarch64/jit_uni_reorder.hpp
- src/cpu/aarch64/jit_uni_reorder_utils.cpp
- src/cpu/reorder/cpu_reorder_comp_f32_s8.cpp
- src/cpu/reorder/cpu_reorder_comp_s8_s8.cpp
> aarch64: reorder: add f32_s8, s8_s8 compensation and move oscale to scales

- examples/CMakeLists.txt
- src/common/memory_tracking.hpp
- src/gpu/amd/miopen_conv_filter_adjustment_base.hpp
- src/gpu/amd/miopen_convolution.cpp
- src/gpu/amd/miopen_convolution.hpp
- src/gpu/amd/miopen_convolution_impl.hpp
- src/gpu/amd/miopen_convolution_pd.hpp
- src/gpu/amd/sycl_hip_engine.cpp
Introducing AMD backend for the oneDNN Convolution primitive.
Supported scope:
Forward : f32, f16, s8
Backward data : f32, f16
Backward weight : f32, f16
Supported Tags : stag= abx wtag=abx datg=abx, stag=axb wtag=axb dtag=axb
NOTE: MIOpen supports Uniform Data Types and Uniform Layouts Representation
Limitations:
Unsupported Data Types : f16f16f32, f32f32f16, s8s8u8, u8u8s8, s8s8f32 
[https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1961](url)
Unsupported Tags : stag=axb wtag=abx dtag=abx, stag=abx wtag=abx dtag=axb, stag=NDHWC wtag=CDHNW dtag=NDHWC
[https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1959](url)
Testing scope:
gtest: API tests passed, Convolution tests passed
------- **GTest Logs** ---------- …
> Adding Support for Convolution Primitive - HIP Backend

- examples/CMakeLists.txt
- src/gpu/nvidia/README.md
- src/gpu/nvidia/sycl_cuda_engine.cpp
- src/gpu/sycl/prelu_kernels.hpp
- src/gpu/sycl/ref_prelu.cpp
- src/gpu/sycl/ref_prelu.hpp
- src/gpu/sycl/sycl_primitive_conf.hpp
- src/gpu/sycl/sycl_types.hpp
Introducing SYCL backend for the oneDNN PReLU primitive. This contains support for PReLU functionality in both forward and backward propagations.
Forward/ Backward : f32, s32, bf16, f16, s8, u8
`benchdnn: Passed`
Please refer the attached test output files.
[test_prelu_outputs.zip](https://github.com/oneapi-src/oneDNN/files/10912774/test_prelu_outputs.zip)
> SYCL kernel Support for PReLU

- src/gpu/nvidia/README.md
- src/gpu/nvidia/sycl_cuda_engine.cpp
- src/gpu/sycl/ref_shuffle.cpp
- src/gpu/sycl/ref_shuffle.hpp
- src/gpu/sycl/shuffle_kernels.hpp
- src/gpu/sycl/sycl_primitive_conf.hpp
Introducing SYCL backend for oneDNN Shuffle primitive. This contains support for Shuffle functionality.
Supported Data Types: f32, bf16, f16
Please refer the attached test output files.
[test_shuffle.zip](https://github.com/oneapi-src/oneDNN/files/10879962/test_shuffle.zip)
> Sycl Kernel Support for Shuffle Primitive

- src/gpu/nvidia/sycl_cuda_engine.cpp
- src/gpu/sycl/ref_resampling.cpp
- src/gpu/sycl/ref_resampling.hpp
- src/gpu/sycl/resampling_kernels.hpp
- src/gpu/sycl/resampling_utils.hpp
- src/gpu/sycl/sycl_math_utils.hpp
- src/gpu/sycl/sycl_post_ops.hpp
- src/gpu/sycl/sycl_primitive_conf.hpp
- tests/benchdnn/resampling/resampling.cpp
Introducing SYCL backend for oneDNN Resampling primitive. This contains support for Resampling functionality. 
Forward/ Backward : s8, u8, f32, bf16, f16, s32 
Post-Ops:
sum, eltwise, binary
[test_resampling.txt](https://github.com/oneapi-src/oneDNN/files/10979958/test_resampling.txt)
> Sycl support for oneDNN resampling primitive

- src/gpu/nvidia/sycl_cuda_engine.cpp
- src/gpu/sycl/batch_normalizations_kernels.hpp
- src/gpu/sycl/ref_batch_normalization.cpp
- src/gpu/sycl/ref_batch_normalization.hpp
- src/gpu/sycl/sycl_primitive_conf.hpp
Introducing SYCL backend for the oneDNN Batch Normalization primitive. This contains support for Batch normalization functionality in both forward and backward propagations.
Forward : f32, bf16, f16, s8
Backward : f32, bf16, f16
`benchdnn :passed`
##Test Outputs
Please refer the test output files below.
[Batchnorm_test_outputs.zip](https://github.com/oneapi-src/oneDNN/files/10976836/Batchnorm_test_outputs.zip)
> SYCL Kernel support for Batch Normalization

- src/cpu/aarch64/acl_utils.hpp
Building oneDNN with ACL currently fails at compile time with below error in many files:
```
In file included from /oneDNN/src/cpu/aarch64/acl_post_ops.hpp:20:
/oneDNN/src/cpu/aarch64/acl_binary.hpp:196:13: error: use of undeclared identifier 'verbose_has_dispatch'
ACL_CHECK_VALID(validate(asp_));
^
/oneDNN/src/cpu/aarch64/acl_utils.hpp:89:13: note: expanded from macro 'ACL_CHECK_VALID'
LOG_ACL_UNSUPPORTED(s.error_description().c_str()); \
^
/oneDNN/src/cpu/aarch64/acl_utils.hpp:80:13: note: expanded from macro 'LOG_ACL_UNSUPPORTED'
if (verbose_has_dispatch()) \
^
```
To reproduce build ACL:
```
scons -j56 Werror=0 debug=0 neon=1 opencl=0  examples=0 embed_kernels=0 os=linux arch=arm64-v8.2-a build=native
```
oneDNN built with ACL:
```
ACL_ROOT_DIR=/PATH/TO/ACL cmake .. …
```
> cpu: aarch64: fix verbose_has_dispatch

- src/cpu/aarch64/injectors/jit_uni_binary_injector.cpp
- src/cpu/aarch64/injectors/jit_uni_binary_injector.hpp
- src/cpu/aarch64/injectors/jit_uni_eltwise_injector.cpp
- src/cpu/aarch64/injectors/jit_uni_eltwise_injector.hpp
- src/cpu/aarch64/injectors/jit_uni_postops_injector.cpp
- src/cpu/aarch64/injectors/jit_uni_postops_injector.hpp
- src/cpu/aarch64/jit_sve_512_1x1_conv_kernel.cpp
- src/cpu/aarch64/jit_sve_512_1x1_conv_kernel.hpp
- src/cpu/aarch64/jit_sve_512_1x1_convolution.cpp
- src/cpu/aarch64/jit_sve_512_1x1_convolution.hpp
- src/cpu/aarch64/jit_uni_1x1_conv_utils.hpp
- src/cpu/aarch64/jit_uni_binary_kernel.cpp
- src/cpu/aarch64/jit_uni_eltwise.cpp
- src/cpu/aarch64/jit_uni_pool_kernel.cpp
- src/cpu/aarch64/jit_uni_softmax.cpp
This PR supports injectors for 1x1 convolution. 
The following PRs may be required before merge this PR.
- https://github.com/oneapi-src/oneDNN/pull/1556 
- https://github.com/oneapi-src/oneDNN/pull/1557 
- https://github.com/oneapi-src/oneDNN/pull/1558 
- https://github.com/oneapi-src/oneDNN/pull/1559
Thank you.
> aarch64: conv: injector for 1x1 conv

- src/cpu/aarch64/xbyak_aarch64/src/util_impl.cpp
- src/cpu/aarch64/xbyak_aarch64/src/util_impl_linux.h
- src/cpu/aarch64/xbyak_aarch64/src/xbyak_aarch64_impl.h
- src/cpu/aarch64/xbyak_aarch64/src/xbyak_aarch64_mnemonic.h
- src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64/xbyak_aarch64_gen.h
- src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64/xbyak_aarch64_mnemonic_def.h
- src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64/xbyak_aarch64_util.h
This PR updates Xbyak_aarch64 into the latest version, which supports BFCVT/BFCVTN/BFCVTN2 instructions for ASIMD and BF16-feature detection. This PR helps https://github.com/oneapi-src/oneDNN/pull/1594
> aarch64: xbyak_aarch64: BFCVT/BFCVTN[2] for ASIMD and BF16-feature detection

- src/gpu/nvidia/sycl_cuda_engine.cpp
- src/gpu/sycl/batch_normalizations_kernels.hpp
- src/gpu/sycl/prelu_kernels.hpp
- src/gpu/sycl/ref_softmax.cpp
- src/gpu/sycl/ref_softmax.hpp
- src/gpu/sycl/resampling_kernels.hpp
- src/gpu/sycl/softmax_kernels.hpp
- src/gpu/sycl/sycl_primitive_conf.hpp
Introducing SYCL backend for the oneDNN Softmax primitive. This contains support for Softmax functionality in both forward and backward propagations.
**Supported scope**
Forward : f32, bf16, f16, u8, s8
Backward : f32, bf16, f16
**Attribute**
Forward : Scales
**Tested Hardware**
Nvidia Tesla T4
**General**
**Testing Scope**
benchdnn : passed
**Test Output Files**
[file_ci.txt](https://github.com/oneapi-src/oneDNN/files/10942893/file_ci.txt)
[file_gpu.txt](https://github.com/oneapi-src/oneDNN/files/10942894/file_gpu.txt)
[file_all.txt](https://github.com/oneapi-src/oneDNN/files/10942895/file_all.txt)
> oneDNN SYCL support for Softmax primitive

- src/gpu/nvidia/sycl_cuda_engine.cpp
- src/gpu/sycl/layer_normalizations_kernels.hpp
- src/gpu/sycl/ref_layer_normalizations.cpp
- src/gpu/sycl/ref_layer_normalizations.hpp
- src/gpu/sycl/sycl_primitive_conf.hpp
Introducing SYCL backend for the oneDNN Layer Normalization primitive. This contains support for Layernormalization functionality in both forward and backward propagations.
Forward : f32, bf16, f16, s32, s8, u8
Backward : f32, bf16, f16
Attributes: Scales
Please refer the attached test output files.
[test_outputs.zip](https://github.com/oneapi-src/oneDNN/files/10859429/test_outputs.zip)
> SYCL Kernel Support for Layer Normalization in oneDNN

- src/gpu/nvidia/cudnn_lrn.hpp
- src/gpu/nvidia/sycl_cuda_engine.cpp
- src/gpu/sycl/lrn_kernels.hpp
- src/gpu/sycl/ref_lrn.cpp
- src/gpu/sycl/ref_lrn.hpp
- src/gpu/sycl/sycl_primitive_conf.hpp
Introducing SYCL backend for the oneDNN LRN (Local Response Normalization) primitive. This contains support for LRN functionality in both forward and backward propagations.
Forward/ Backward : f32, bf16, f16
Nvidia Tesla T4
`benchdnn : passed`
[test_lrn_gpu_output.txt](https://github.com/oneapi-src/oneDNN/files/11059393/test_lrn_gpu_output.txt)
[test_lrn_ci_output.txt](https://github.com/oneapi-src/oneDNN/files/11059394/test_lrn_ci_output.txt)
[test_lrn_all_output.txt](https://github.com/oneapi-src/oneDNN/files/11059395/test_lrn_all_output.txt)
> SYCL kernel support added for LRN

- src/gpu/sycl/ref_softmax.cpp
- src/gpu/sycl/softmax_kernels.hpp
- src/gpu/sycl/sycl_primitive_conf.hpp
This PR extends softmax SYCL kernel support for the scale part . 
[test_softmax_all.txt](https://github.com/oneapi-src/oneDNN/files/11061162/test_softmax_all.txt)
[test_softmax_gpu.txt](https://github.com/oneapi-src/oneDNN/files/11061159/test_softmax_gpu.txt)
[test_softmax_ci.txt](https://github.com/oneapi-src/oneDNN/files/11061160/test_softmax_ci.txt)
> Updated the scale for softmax sycl

- src/gpu/nvidia/README.md
- src/gpu/nvidia/sycl_cuda_engine.cpp
- src/gpu/sycl/pooling_kernels.hpp
- src/gpu/sycl/ref_pooling.cpp
- src/gpu/sycl/ref_pooling.hpp
- src/gpu/sycl/sycl_math_utils.hpp
- src/gpu/sycl/sycl_post_ops.hpp
- src/gpu/sycl/sycl_primitive_conf.hpp
Introducing SYCL backend for the oneDNN Pooling primitive. This contains support for Pooling functionality in both forward and backward propagations.
- Forward : f32, s32, f16, bf16, s8, u8
- Backward: f32, f16, bf16
Nvidia Tesla T4
`benchdnn : passed`
Please refer the test output files
[Pooling_benchdnn_output.zip](https://github.com/oneapi-src/oneDNN/files/10948726/Pooling_benchdnn_output.zip)
> SYCL kernel support for Pooling

- src/gpu/amd/miopen_batch_normalization.cpp
- src/gpu/amd/miopen_batch_normalization.hpp
- src/gpu/amd/miopen_batch_normalization_executor.hpp
- src/gpu/amd/miopen_batch_normalization_impl.hpp
- src/gpu/amd/sycl_hip_engine.cpp
- tests/benchdnn/bnorm/bnorm.cpp
- tests/gtests/test_batch_normalization.cpp
Introducing AMD backend for the oneDNN Batch Normalization Primitive.
**Supported Data Types:**
Forward Training  : f32
Forward Inference : f32, f16
Backward : f32
gtest: API tests passed, Batch normalization tests passed
**Benchdnn log files:**
[test_bnorm_all_plain.log](https://github.com/oneapi-src/oneDNN/files/11061934/test_bnorm_all_plain.log)
[test_bnorm_ci.log](https://github.com/oneapi-src/oneDNN/files/11061936/test_bnorm_ci.log)
[test_bnorm_all_blocked.log](https://github.com/oneapi-src/oneDNN/files/11061937/test_bnorm_all_blocked.log)
**Gtest log files:**
[test_batch_normalization.log](https://github.com/oneapi-src/oneDNN/files/11061946/test_batch_normalization.log)
[test_batch_normalization_buffer.log](https://github.com/oneapi-src/oneDNN/file …
> Adding Support for Batch Normalization Primitive - HIP Backend

- src/gpu/amd/miopen_convolution.hpp
- src/gpu/amd/miopen_convolution_impl.hpp
- src/gpu/amd/miopen_deconvolution.cpp
- src/gpu/amd/miopen_deconvolution.hpp
- src/gpu/amd/miopen_deconvolution_impl.hpp
- src/gpu/amd/sycl_hip_engine.cpp
- tests/gtests/test_deconvolution.cpp
Introducing AMD backend for the oneDNN Deconvolution primitive.
Forward : f32, f16, s8
Backward data : f32, f16
Backward weight : f32, f16
Supported Tags : stag= abx wtag=abx datg=abx, stag=axb wtag=axb dtag=axb
NOTE: MIOpen supports Uniform Data Types and Uniform Layouts Representation
**Limitations:**
Non-uniform tags and Non-uniform datatypes are not supported.
https://github.com/ROCmSoftwarePlatform/MIOpen/issues/2007
Benchdnn: Passed
Gtests: API tests passed
---------**Benchdnn Logs**----------
[test_deconv_ci.log](https://github.com/oneapi-src/oneDNN/files/11061718/test_deconv_ci.log)
[test_deconv_all.log](https://github.com/oneapi-src/oneDNN/files/11061719/test_deconv_all.log)
---------**Gtests Logs**---------- …
> Adding support for Deconvolution Primitive

- src/gpu/amd/miopen_convolution.hpp
- tests/gtests/test_convolution_backward_data_common.hpp
- tests/gtests/test_convolution_backward_weights_common.hpp
- tests/gtests/test_convolution_eltwise_forward_common.hpp
- tests/gtests/test_convolution_format_any.cpp
- tests/gtests/test_convolution_forward_common.hpp
- tests/gtests/test_iface_wino_convolution.cpp
Fixed Gtest failures for Convolution - HIP Backend
Testing scope:
gtest: API tests passed, Convolution tests passed
[gtest_test_convolution_backward_data_f32.log](https://github.com/oneapi-src/oneDNN/files/11062503/gtest_test_convolution_backward_data_f32.log)
[gtest_test_convolution_backward_data_f32_buffer.log](https://github.com/oneapi-src/oneDNN/files/11062504/gtest_test_convolution_backward_data_f32_buffer.log)
[gtest_test_convolution_backward_weights_f32.log](https://github.com/oneapi-src/oneDNN/files/11062505/gtest_test_convolution_backward_weights_f32.log)
[gtest_test_convolution_backward_weights_f32_buffer.log](https://github.com/oneapi-src/oneDNN/files/11062506/gtest_test_convolution_backward_weights_f32_buffer.log)
[gtest_test_convolution_eltwise_forward_f32.log](https://github. …
> Fixed Gtest Failures for Convolution - HIP Backend

- src/gpu/sycl/binary_kernels.hpp
- src/gpu/sycl/ref_binary.cpp
- src/gpu/sycl/sycl_io_helper.hpp
- src/gpu/sycl/sycl_math_utils.hpp
- src/gpu/sycl/sycl_primitive_conf.hpp
- src/gpu/sycl/sycl_q10n.hpp
This PR extends binary SYCL kernel support for non-uniform group sizes. This includes a new logic for work-item config in kernel launch and handling the trailing portions of workspace. 
In addition, the PR adds support for common scales and handles saturation and rounding for vectors.
[test_binary_all_log.txt](https://github.com/oneapi-src/oneDNN/files/11068148/test_binary_all_log.txt)
> SYCL kernel support for Binary Primitive

- src/gpu/amd/README.md
- src/gpu/amd/miopen_reorder.cpp
- src/gpu/amd/miopen_reorder.hpp
- src/gpu/amd/miopen_reorder_impl.cpp
- src/gpu/amd/miopen_reorder_impl.hpp
- src/gpu/amd/sycl_hip_engine.hpp
- src/gpu/amd/sycl_hip_utils.hpp
- tests/benchdnn/reorder/reorder.cpp
- tests/gtests/test_reorder_common.hpp
Introducing AMD backend for the oneDNN Reorder Primitive.
f32
Benchdnn:Passed
gtest: API tests passed, reorder tests passed except 2 tests cases
[test_reorder_all.txt](https://github.com/oneapi-src/oneDNN/files/11102858/test_reorder_all.txt)
[test_reorder_ci.txt](https://github.com/oneapi-src/oneDNN/files/11102860/test_reorder_ci.txt)
[gtests_reorder_buffer.txt](https://github.com/oneapi-src/oneDNN/files/11102867/gtests_reorder_buffer.txt)
[gtests_reorder.txt](https://github.com/oneapi-src/oneDNN/files/11102868/gtests_reorder.txt)
[gtest_api_test.txt](https://github.com/oneapi-src/oneDNN/files/11102917/gtest_api_test.txt)
[gtest_api_buffer.txt](https://github.com/oneapi-src/oneDNN/files/11102918/gtest_api_buffer.txt)
[gtests_internals.txt](https://github.com/oneapi-src/oneDNN/files/1110291 …
> Adding support for Reorder Primitive HIP Backend

- include/oneapi/dnnl/dnnl_common.hpp
- include/oneapi/dnnl/dnnl_common_types.h
**Description**
Adds "f32->tf32" which was missing in the description for dnnl_fpmath_mode_any
Fixes #1542
> Add f32->tf32 in the description for dnnl_fpmath_mode_any

- src/cpu/x64/jit_brgemm_conv.cpp
The bug was found by Svace static analysis tool:
1. null pointer can be assigned to inp_buffer
2. then it is dereferenced via inp_buffer[i]
> cpu: x64: brgconv: Fix null pointer dereference in dnnl::impl::cpu::x64::brgemm_convolution_fwd_t()

- src/graph/backend/dnnl/constant_cache.cpp
- src/graph/interface/allocator.hpp
- src/graph/interface/backend.cpp
- src/graph/interface/partition_cache.cpp
`std::memory_order` is an enum in pre-C++20, and is an enum class in C++20.
In pre-C++20, its members are intended to be referred as `std::memory_order_relaxed` or so, but in oneDNN, it's referred as `std::memory_order::memory_order_relaxed`.
That style is not valid after C++20, as the member is renamed to `std::memory_order::relaxed`.
This PR drops unneeded `memory_order::`, so that the source is compatible to C++20.
> graph: interface: backend: Fix memory_order enum name for C++20

- src/cpu/aarch64/acl_post_ops.cpp
- src/cpu/aarch64/acl_post_ops.hpp
Perform the eltwise post-ops in fp32 instead of fp16 by casting up (to fp32) before executing the eltwise op and then casting back down (to fp16) after the operation completes. With this change, all fp16 benchdnn tests pass on aarch64.
The oneDNN API specifies that post-ops need to (always) be executed in fp32, but the Arm Compute Library (ACL) executes them in f16 (when running in fp16 mode) which caused a lot of conv+relu benchdnn tests to fail.
To mitigate this, we submitted this RP (#1506) which disables ACL post-ops in fp16. As a result, all primitives which are followed by a post-op in fp16 started falling to the reference kernels.
Hence, a dramatic drop in performance for fp16.
This PR fixes the inaccuracies resulting from ACL executing the eltwise post-ops in fp16 by:
- Not fusing …
> src: cpu: aarch64: re-enable fp16 post-ops for aarch64

- src/common/verbose.cpp
- src/common/verbose.hpp
- src/common/verbose_msg.hpp
- src/cpu/aarch64/acl_benchmark_scheduler.cpp
- src/cpu/aarch64/acl_benchmark_scheduler.hpp
- src/cpu/aarch64/acl_thread.cpp
- src/cpu/aarch64/acl_thread.hpp
- src/cpu/cpu_engine.hpp
This PR covers the implementation for enabling ACL verbose functionality that can capture low-level kernel information from [Compute Library for the Arm® Architecture (ACL)](https://github.com/ARM-software/ComputeLibrary) and kernel timing measurements and present the results in a oneDNN-style verbose output. RFC is available here: https://github.com/oneapi-src/oneDNN/pull/1581
- [ N/A] Have you submitted performance data that demonstrates performance improvements?
- [N/A] Does RFC document follow the [template](https://github.com/oneapi-src/oneDNN/blob/rfcs/rfcs/template.md#onednn-design-docum …
> src:cpu:aarch64 Add benchmark scheduler for acl verbose

- rfcs/20230309-Introducing-ACL-verbose/README.md
RFC to add verbose functionality in oneDNN built with ACL. 
Link to rendered document: https://github.com/cfRod/oneDNN/tree/rfc_acl_benchmark_scheduler/rfcs/20230309-Introducing-ACL-verbose
- [x ] Have you added a link to the rendered document?
> RFC Introducing ACL verbose

- src/cpu/aarch64/jit_generator.hpp
- src/cpu/aarch64/jit_sve_512_1x1_conv_kernel.hpp
- src/cpu/aarch64/jit_sve_512_conv_kernel.cpp
- src/cpu/aarch64/jit_sve_512_conv_kernel.hpp
- src/cpu/aarch64/jit_sve_512_x8s8s32x_conv_kernel.cpp
- src/cpu/aarch64/jit_sve_512_x8s8s32x_conv_kernel.hpp
- src/cpu/aarch64/jit_uni_deconv_zp_pad_str_kernel.cpp
- src/cpu/aarch64/jit_uni_dw_conv_kernel_f32.hpp
- src/cpu/aarch64/jit_uni_reorder.cpp
- src/cpu/aarch64/xbyak_aarch64/src/util_impl_linux.h
- src/cpu/aarch64/xbyak_aarch64/src/util_impl_windows.h
This patch contains the following updates. 
- Fix random print of Xbyak_aarch64 https://github.com/oneapi-src/oneDNN/issues/1633
- Fix clobbering x16-x18 registers in JIT-ed code. It prevented `ctest` to work on Windows/MacOS on Arm.
- Add H/W-capability detection for Windows on Arm.
https://github.com/oneapi-src/oneDNN/files/10745455/arm64-msvc-onednn.patch is also required for building oneDNN on Windows on Arm.
I expect it will be pull-requested by Linaro developers.
> aarch64: fix random print and obstacles to run on Windows/MacOS on Arm

- src/cpu/aarch64/injectors/jit_uni_postops_injector.cpp
- src/cpu/aarch64/injectors/jit_uni_postops_injector.hpp
- src/cpu/aarch64/jit_sve_512_1x1_conv_kernel.cpp
- src/cpu/aarch64/jit_uni_binary.cpp
- src/cpu/aarch64/jit_uni_binary.hpp
This patch fixes 
`benchdnn --binary --attr-post-ops=sum+relu+sum:2 8x8x3x5:8x8x3x5_n"multisum"` on AArch64 SVE environment.
- OS: CentOS 8
- CPU: Fujitsu A64FX (Armv8.2-a + SVE)
- oneDNN: commit 6d1a18ce22c29edc012a5637f198b6b146536c65
- build command: `.github/automation/build.sh --threading omp --mode Release --source-dir $(pwd) --build-dir $(pwd)/build --cmake-opt -DONEDNN_BUILD_GRAPH=OFF`
Some test patterns for `ip` and `resampling` of `benchdnn` failed, but I confirmed that these are not a side effect of this patch.
```
benchdnn --engine=cpu --ip --batch=test_ip_all | tail -n 2 | head -n 1
tests:12781 passed:4150 skipped:8346 mistrusted:31 unimplemented:0 invalid_arguments:0 failed:254 listed:0
benchdnn --engine=cpu --resampling --batch=test_resampling_all | tail -n 2 | head -n 1 …
```
> cpu: aarch64: binary: add check for repeated sum postop

- src/cpu/aarch64/acl_convolution_utils.cpp
- src/cpu/aarch64/acl_convolution_utils.hpp
- src/cpu/aarch64/acl_depthwise_convolution.cpp
- src/cpu/aarch64/acl_depthwise_convolution.hpp
- src/cpu/cpu_convolution_list.cpp
cpu: aarch64: depthwise_convolution: add ACL depthwise convolution
This PR adds a deptwhise convolution primitive which makes use of the Compute Library for the Arm® architecture (ACL),
optimised for AArch64 targets. The datatype support is f32 and f16 and can only be used in forward mode.
> On AArch64 use ACL NEDepthwiseConvolutionLayer for depthwise convolution

- rfcs/20230503-profiling-api/README.md
This is a proposal on introducing an experimental profiling API for GPU engine, OpenCL and SYCL runtimes.
[Link to document](https://github.com/densamoilov/oneDNN/tree/dsamoylo/rfcs/profiling-api/rfcs/20230503-profiling-api).
> rfcs: add proposal on profiling api

- src/graph/backend/dnnl/constant_cache.hpp
- tests/gtests/graph/unit/backend/dnnl/test_constant_cache.cpp
Fixes a build issue in public CI:
https://dev.azure.com/mkldnn/dnnl/_build/results?buildId=1786&view=logs&jobId=705ebb6b-fa1b-5089-a898-faca77d81977&j=705ebb6b-fa1b-5089-a898-faca77d81977&t=5f4b06fe-391a-53f0-1333-5e740e9afb0e
> graph: backend: dnnl: private constant cache constructor

- src/cpu/aarch64/acl_convolution_utils.cpp
Fixes `test_conv_all` failing for ACL builds by returning unimplemented for ACL depthwise convolution cases
when padding dimensions are greater then kernel size and when layout format is NCHW.
The tests that were failing were:
(1) for padding dimension greater then kernel size were from input file shapes_regression_dw in conv directory,
where example shape was g128mb1ic128ih56oh32oc128kh4sh2ph0
(2) for where layout format is NCHW is from input file harness_conv_tags when destination tag was beeing set to
be abx on shapes_basic
> Disable ACL depthwise convolution for cases that are not supported

- src/cpu/x64/brgemm/brgemm.cpp
Fixes -  Simple typo caught while using. gaurentee --> guarantee
No other changes made.
> Update brgemm.cpp fix typo

- src/cpu/rv64/rvv_nchw_pooling.cpp
The implementation of RVV max pooling compares inputs with __FLT_MIN__(near 0), if all inputs are negative, it should return the max of negative number, but now it returns 0(__FLT_MIN__).
To fix, change the MIN from __FLT_MIN__ to min negative float.
> cpu: rv:64 fix rvv pooling wrong results on negative inputs

- src/cpu/aarch64/acl_convolution_utils.cpp
- src/cpu/aarch64/acl_depthwise_convolution.hpp
add tensor dilation parameter configuration for acl depthwise convolution kernels.
The issue is, if we run any convolution shape with dilation, oneDNN was picking the reference kernels instead of ACL and hence the performance was poor. This PR fixes the oneDNN ACL convolution kernel wrapper to pass the dilation parameters to the ACL kernel configuration and run. With the PR, I've observed around 3.75x performance improvement for the dilation …
> [aarch64] add tensor dilation parameter configuration for acl depthwise conv

- src/cpu/aarch64/acl_pooling.cpp
- src/cpu/aarch64/acl_pooling.hpp
- tests/benchdnn/pool/pool.cpp
- tests/gtests/test_pooling_backward.cpp
- tests/gtests/test_pooling_forward.cpp
This patch extends the current Compute Library for the Arm® architecture (ACL) implementation of the pooling primitive to also include forward training cases for max pooling, and to include previously rejected cases where padding >= kernel size.
When benchmarking on a Neoverse-N1 cpu, The additional cases are up to 40x faster than oneDNN reference kernels. The results are similar on Neoverse-V1. The included performance heuristic has been updated to cover new cases, and avoid selecting ACL when reference kernels are faster. For instance, for thread count > 1, in the max pooling forward training cases, and with memory format NHWC, ACL is faster than reference when the per thread problem size is larger than 2048. (here problem size is defined as MB x IC x OH x OW x KH x KW).
> src:cpu:aarc64: extend ACL max pooling primitive

- rfcs/20220404-troubleshooting-helpers/README.md
This RFC aims to setting the foundation to improve our verbose feature, and incrementally add messages to verbose output to help user troubleshoot their issues with API usage and performance.
> rfcs: proposal to improve message printing in oneDNN

- rfcs/20230524-vtune-pdinfo-task/README.md
This is a proposal to introduce a new ITT_TASK level, in order for users to get benchdnn reproducers from Vtune trace.
This allows for:
- better correlation of oneDNN execution calls with the rest of the application, as vtune generates call stack and nested tasks
- better usability, as the users will no more need to separately generate the ONEDNN_VERBOSE output to get benchdnn reproducers.
[rendered document](https://github.com/oneapi-src/oneDNN/blob/09c09d05a6b47efd90c851f7b7e32578a046f437/rfcs/20230524-vtune-pdinfo-task/README.md)
> rfcs: extend vtune integration with pd_info

- src/cpu/aarch64/cpu_isa_traits.hpp
- src/cpu/aarch64/jit_uni_reorder.cpp
- src/cpu/aarch64/xbyak_aarch64/src/util_impl_linux.h
- src/cpu/reorder/cpu_reorder_regular_f32_bf16.cpp
This code adds JIT support for reorder primitive when converting from FP32 to BF16. Running reorder for 768x768 shape from FP32 memory format ba to BF16 memory format BA4b4a on Neoverse-V1 hardware (which supports BF16) improves performance by ~40x with 8 threads.
See above for one example
- [N/A] Have you added a link to the rendered document?
> Add jit support for reorder from FP32 to BF16

- src/cpu/aarch64/cpu_isa_traits.hpp
Adds a missing closing bracket to mayiuse_bf16() based off of [this PR](https://github.com/oneapi-src/oneDNN/pull/1594).
To reproduce, simply build for aarch on master which produces errors such as...
```
/code/oneDNN/src/cpu/aarch64/cpu_isa_traits.hpp:38:16: note: to match this '{'
38 | namespace dnnl {
|                ^
make[1]: *** [CMakeFiles/Makefile2:540: src/common/CMakeFiles/dnnl_common.dir/all] Error 2
[ 32%] Built target dnnl_cpu_aarch64_xbyak_aarch64
make[1]: *** [CMakeFiles/Makefile2:566: src/cpu/CMakeFiles/dnnl_cpu.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```
> src:cpu:aarch64 add closing bracket to mayiuse_bf16

- rfcs/20230911-sparse-support/README.md
Proposal on adding support for sparse memory and the matmul primitive.
[Link to rendered version](https://github.com/densamoilov/oneDNN/tree/dsamoylo/rfcs/sparse-support/rfcs/20230911-sparse-support)
> rfcs: add proposal on sparse memory and matmul

- src/common/deconvolution_pd.hpp
- src/cpu/aarch64/acl_deconvolution.hpp
This PR provides a fix for deconv test failures related to the f64 data type. This failure was exposed by the recent changes to how groups are handled in BenchDNN, which has seen previously skipped cases being dispatched to ACL (including these f64 ones). The test failures were observed when calling deconv functions from Compute Library for the Arm(r) architecture (ACL). Benchdnn's failure test is:
ctest -R test_benchdnn_deconv_ci_cpu
The test failed due to an issue with the ACL not having deconv operation for f64 data type. This resulted in an invalid data type error and caused the failure. To mitigate this problem, this PR checks the validity of the data type before it reaches the ACL, and skips the test when necessary to prevent further issues.
- [N/A] Have you submitted performance …
> tests:cpu:aarch64 Fix failing deconv tests related to f64 data type.

- rfcs/20230807-unify-primitive-and-graph-verbose/README.md
This is to propose unifying primitive and graph api verbose.
The rendered document can be found at [link](https://github.com/xinyu-intel/mkl-dnn/tree/xinyu/rfc/graph-verbose/rfcs/20230807-unify-primitive-and-graph-verbose).
> rfc: unify primitive and graph api verbose

- src/cpu/aarch64/acl_post_ops.hpp
A recent commit removed the use of `copy_from` from dnnl_post_ops.
https://github.com/oneapi-src/oneDNN/commit/b77a0cc7e11494f81a4d24f474d2d6f893789c5d
However, one instance, in `src/cpu/aarch64/acl_post_ops.hpp` was not updated, leading to a build failure on AArch64 platforms.
This PR removes the `copy_from` call from `src/cpu/aarch64/acl_post_ops.hpp`.
Note: to reproduce the error, build oneDNN on AArch64 with `-DDNNL_AARCH64_USE_ACL=ON` set and the location of a Compute Library build specified through the `ACL_ROOT_DIR` environment variable
```
ACL_ROOT_DIR=<path_to_acl> cmake -DDNNL_CPU_RUNTIME=OMP -DDNNL_BUILD_FOR_CI=ON -DDNNL_AARCH64_USE_ACL=ON ../. && make -j
```
> src:cpu:aarch64: Removes unnecessary copy_from

- cmake/platform.cmake
this change is required to support binary compatibility across all armv8 platforms.
This fixes issue on PyTorch  repo: 
https://github.com/pytorch/pytorch/issues/109312
- [ x] Have you formatted the code using clang-format?
- [ x] Have you included information on how to reproduce the issue (either in a github issue or in this PR)?
> [aarch64] set the build flag to "-mcpu=generic"

- src/cpu/aarch64/acl_reorder.cpp
- src/cpu/aarch64/acl_reorder.hpp
- src/cpu/reorder/cpu_reorder.hpp
- src/cpu/reorder/cpu_reorder_regular_f32_f32.cpp
- tests/gtests/test_reorder.cpp
This PR adds a reorder primitive which makes use of the Compute Library for the Arm® architecture (ACL),
optimised for AArch64 targets. The datatype supported is f32 and can only be used in forward mode.
The reorders supported at the moment are:
* ba->Ab4a
* ba->Ab8a
* cdba->Acdb4a
* cdba->Acdb8a
The primitive is up to 3.5x faster than the jitted reorder implementation for AArch64.
> cpu:aarch64:reorder add reorder primitive

- doc/primitives/convolution.md
- src/cpu/aarch64/acl_convolution_utils.cpp
- src/cpu/aarch64/acl_convolution_utils.hpp
- src/cpu/aarch64/acl_threadpool_scheduler.cpp
- src/cpu/aarch64/acl_winograd_convolution.cpp
- src/cpu/aarch64/acl_winograd_convolution.hpp
- src/cpu/aarch64/matmul/acl_matmul.cpp
- src/cpu/aarch64/matmul/acl_matmul.hpp
- src/cpu/aarch64/matmul/acl_matmul_utils.cpp
- src/cpu/aarch64/matmul/acl_matmul_utils.hpp
- src/cpu/cpu_convolution_list.cpp
- tests/gtests/test_iface_wino_convolution.cpp
This is to fix a matmul performance degradation from oneDNN 3.1 to oneDNN 3.2, as reported by
https://github.com/oneapi-src/oneDNN/issues/1691. The regression is a side effect of the implementation
of support for fixed format kernels from Compute Library for the Arm(r) architecture (ACL). As a result,
oneDNN falls back to the ref. impl. when memory::format_tag::any for the weights input is not selected.
This change re-enables support for other memory formats by passing the work to non fixed-format kernels
in these cases.
This update, in addition, restores the ACL Winograd convolution implementation that was previously
removed.
In general, the performance improvement brought by this fix is:
* matmul: >500x improvement for Neoverse-V1.
* winograd: >3x for Neoverse-V1.
At the present, we …
> Fix performance degradation from oneDNN 3.1 to oneDNN 3.2

- src/gpu/sycl/sycl_math_utils.hpp
The math functions in SYCL are not templated, e.g.
```c++
inline double acosh(double a0) __NOEXC {
return __sycl_std::__invoke_acosh<double>(a0);
}
...
inline float tanh(float a0) __NOEXC {
return __sycl_std::__invoke_tanh<float>(a0);
}
inline double tanh(double a0) __NOEXC {
return __sycl_std::__invoke_tanh<double>(a0);
}
```
The templated versions work on `sycl::vec`s, which is what was causing the issue. Fixes #1750 .
> gpu: sycl: fix broken build

- src/gpu/nvidia/cudnn_batch_normalization_executor.hpp
- src/gpu/nvidia/cudnn_binary.cpp
All of the host_tasks used in `amd` and `nvidia` capture by value, except for these ones. They were segfaulting occasionally because oneDNN classes don't do any ref counting (at least for Nvidia/AMD). This fixes that
> gpu: nvidia: Fix race condition in host task

- rfcs/20230331-smooth-quantization/README.md
Here is the [link](https://github.com/igorsafo/oneDNN/tree/rfcs-smooth-quantization/rfcs/20230331-smooth-quantization)
The RFC is already implemented:
- Softmax was exnteded with binary_mul post op support
- Layer normalization was not extended, because frameworks were able to put quantization into `scale` parameter of the Layer Normalization on integration side.
> rfc: smooth quantization

- rfcs/20231107-norm-scale-shift-data-type/README.md
[Rendered doc](https://github.com/densamoilov/oneDNN/tree/dsamoylo/rfcs/norm-scale-shift-dt/rfcs/20231107-norm-scale-shift-data-type)
> rfcs: add proposal on introducing API for specifying data type of scale and shift tensors

- src/cpu/jit_utils/linux_perf/linux_perf.cpp
The value in `marker_addr_` is updated even if it is invalid, i.e. `(void*) -1` This could then be passed to `munmap` which is clearly wrong as that expects a valid pointer.
Make sure to store only a valid pointer in `marker_addr_` ~and `nullptr` on failure as `marker_size` has also been updated so the `munmap` call using the old pointer would be wrong~. Additionally reset it after the `munmap` call to avoid unmapping it again similar to how the file descriptors are reset
Motivation: I observe a double free in PyTorch 2.1 using oneDNN 3.1.1 and found https://github.com/oneapi-src/oneDNN/commit/3480b0c0fa0eb6eacfeafc4527eb3cc981636673 fixing a potential double free wondering how that could even happen. Point is `close_file()` is save to call multiple times as it resets the fd but …
> Avoid invalid `munmap`

- .github/automation/.drone.yml
- .github/automation/build_acl.sh
- README.md
- cmake/ACL.cmake
- doc/build/build_options.md
- src/cpu/aarch64/acl_convolution_utils.cpp
- src/cpu/aarch64/acl_indirect_gemm_convolution.hpp
ACL 23.11 cleanedup some of the legacy post-ops from conv2dinfo. this commit is to update the oneDNN ACL wrapper functions to work with the newer ACL version
> [aarch64] update acl conv2dinfo constructor and bump ACL min version to 23.11

- rfcs/20230720-graph-python-api/README.md
- rfcs/20230720-graph-python-api/src/binding.cpp
This is to propose adding python binding for onDNN graph API.
The rendered document can be found at [link](https://github.com/TaoLv/mkl-dnn/blob/lvtao/rfc/python-api/rfcs/20230720-graph-python-api/README.md).
> rfcs: graph api: add python binding

- tests/benchdnn/utils/dims.hpp
In Musl environment build of oneDNN-3.3.3 (up to current main branch) with tests fails with:
```
In file included from /var/tmp/portage/dev-libs/oneDNN-3.3.3/work/oneDNN-3.3.3/tests/benchdnn/utils/dims.cpp:19:
/var/tmp/portage/dev-libs/oneDNN-3.3.3/work/oneDNN-3.3.3/tests/benchdnn/utils/dims.hpp:25:28: error: 'int64_t' was not declared in this scope
25 | using dims_t = std::vector<int64_t>;
|                            ^~~~~~~
/var/tmp/portage/dev-libs/oneDNN-3.3.3/work/oneDNN-3.3.3/tests/benchdnn/utils/dims.hpp:24:1: note: 'int64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
23 | #include <vector>
+++ |+#include <cstdint>
24 | 
```
This PR adds `#include <cstdint>` and fixes the build.
See also: https://bugs.gentoo.org/922778
> Add missing include <cstdint> for int64_t

- src/cpu/aarch64/jit_uni_softmax.cpp
- src/cpu/aarch64/jit_uni_softmax.hpp
- src/cpu/cpu_softmax_list.cpp
Enhancement: Expand ARM SVE support in **jit_uni_softmax**
This commit enhances the existing ARM SVE support in jit_uni_softmax to include additional vector length compatibility. The changes made are for implementation of different ARM SVE vector length.
Major Code changes:
• Introduce a new struct to accommodate the extended ARM SVE vector length, similar to the sve_512 struct.
• Modify the **get_horizontal_op** function accordingly for enhanced vector length.
- [✓] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit? Yes
1. make test output:
99% tests passed, 2 tests failed out of 160
Total Test time (real) =  50.68 sec
144 - test_graph_unit_dnnl_conv_usm_cpu …
> cpu: aarch64: Expand ARM SVE support in jit_uni_softmax

- src/cpu/aarch64/acl_inner_product.hpp
- src/cpu/cpu_inner_product_list.cpp
- tests/benchdnn/inputs/ip/test_ip_acl
Added sbgemm inner product op to enable PyTorch torch.compile() and bf16 fastmath kernels to work together on aarch64.
- [x ] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
same pass rate as in main branch.
1. torch.compile() with fp32 inner product kernel showed up to 5.8x perf improvement on AWS c7g instance
2. torch.compile() with bf16 inner product kernel showed another 1.25x perf improvement on AWS c7g instance
> [aarch64] add sbgemm inner product op

- cmake/ACL.cmake
Add Maximum version supported to ACL.make,
improve warnings and fatal_errors format and
replace ENV{ACL_ROOT_DIR} with {ACL_INCLUDE_DIR}.
Add cmake maximum Arm Compute Library supported version to solve build issue #1783.
ENV variable can be inconsistent with the cached variable, therefore use the cached path to Arm Compute Library.
Fixes #1783
> build:cmake:aarch64 add ACL maximum version and a few minor changes

- cmake/FindBLAS.cmake
I am building oneDNN using the Intel oneAPI compiler and MKL version 2024.0.0. I get this error at configuration time:
```
MKLROOT=/opt/intel/oneapi cmake \
-DCMAKE_INSTALL_PREFIX=/opt/onednn \
-DCMAKE_INSTALL_LIBDIR=lib \
-DDNNL_LIBRARY_TYPE=STATIC \
-DDNNL_BLAS_VENDOR=MKL \
/home/src/oneDNN
-- CMAKE_BUILD_TYPE is unset, defaulting to Release
-- The C compiler identification is IntelLLVM 2024.0.0
-- The CXX compiler identification is IntelLLVM 2024.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/intel/oneapi/compiler/2024.0/bin/icx - skipped
-- Detecting C compile features
[...]
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenMP_C: -fiopenmp  
-- Found OpenMP_CXX: -fiopenmp  
-- …
```
> Fix FindBLAS.cmake compatibility with MKL 2024.0

- cmake/ACL.cmake
Refine alerts and replace ENV{ACL_ROOT_DIR}.
Improve warnings and fatal_errors format and
replace ENV{ACL_ROOT_DIR} with {ACL_INCLUDE_DIR}.
ENV variable can be inconsistent with the cached variable, therefore use the cached path to Arm Compute Library.
> build:cmake:aarch64 refine alerts and replace ENV{ACL_ROOT_DIR}

- src/cpu/aarch64/jit_uni_softmax.cpp
- src/cpu/aarch64/jit_uni_softmax.hpp
- src/cpu/cpu_softmax_list.cpp
- tests/benchdnn/inputs/softmax/test_softmax_all
This PR includes the following three improvement for Softmax on AArch64.
- SIGSEGV for blk_size = 8 on SVE512 is fixed.
- Performance has been improved.
- blk_size = 4 is enabled. 
SIGSEGV can be reproduce by the following command on AArch64 SVE 512 environment with 51a92cc549e088d1f21852ca5f976c64e9fa0948
```
./benchdnn --softmax --stag=aBx8b 256x10x1x1
```
`stag=aBx4b` is added to `tests/benchdnn/inputs/softmax/test_softmax_all` for testing blk_size =4 cases.
> cpu: aarch64: softmax: fix segv, improve performance, enable blk_size = 4

- tests/benchdnn/softmax/softmax.cpp
ACL softmax accumulates in F16, but oneDNN now expects accumulation in F32, so the tests fail. This commit partially reverts 6727bbe8.
Fixes #1819
> tests: benchdnn: softmax: relax threshold for ACL #1819

- src/cpu/aarch64/acl_softmax.hpp
`acl_softmax` would return incorrect answer if stag did not match dtag, for example
```sh
./benchdnn -v5 --softmax --stag=axb --dtag=abx 2x19x16x64
```
This patch fixes that by falling back to ref if stag != dtag.
> cpu: aarch64: softmax: fall back to ref if stag != dtag

- src/gpu/amd/miopen_pooling_impl.hpp
Currently, when performing 1D pooling in the AMD backend, the src/dst tensor strides are set as `[c*w, w, 1, 0]` which is incorrect because the dimensions are set to be `[n, c, 1, w]`. Thus, this MR updates the strides to the correct format of `[c*w, w, w, 1]`.
> gpu: miopen: pooling: Fixes strides in 1D pooling

- src/cpu/aarch64/acl_inner_product.hpp
- src/cpu/cpu_inner_product_list.cpp
- tests/benchdnn/inputs/ip/test_ip_acl
Added sbgemm inner product op and blocked weights support to enable PyTorch torch.compile() and bf16 fastmath kernels to work together on aarch64.
tested make test and the inner product primitive tests (make test_bench_ip_ci).
- [ x] Have you formatted the code using clang-format?
> [aarch64] add sbgemm inner product op - cherrypick of pr#1768

- src/cpu/aarch64/acl_reorder.hpp
1. It fixes the test_reorder test by checking whether the target supports SVE instructions before executing a reorder that uses SVE intrinsics.
2. It also adds `Acdb8a` and `Acdb4a` formats to the possible target reorder memory formats.
> aarch64: reorder: add Acdb8a/Acdb4a and check for SVE availability when necessary

- src/cpu/aarch64/xbyak_aarch64/src/util_impl_linux.h
- src/cpu/aarch64/xbyak_aarch64/src/util_impl_mac.h
There are platforms with /sys not mounted. skip handling HW caps for such platforms.
Fixes # https://github.com/pytorch/pytorch/issues/115482
I ran subset of benchdnn tests on aarch64 Linux (AWS Graviton3) platform, but didn't test on Mac.
> cpu: aarch64: fix xbyak functions for /sys access failures cherrypick#1773

- src/cpu/aarch64/matmul/acl_matmul.hpp
- src/cpu/platform.cpp
Add access to ACL implementation of `bf16` to `bf16` `matmul` kernels, with the goal of enabling operations through PyTorch® `autocast()`.
> src: cpu: aarch64: Add ACL bf16 to bf16 matmul kernels.

- tests/gtests/test_concat.cpp
- tests/gtests/test_eltwise.cpp
- tests/gtests/test_group_normalization.cpp
- tests/gtests/test_iface_attr_quantization.cpp
- tests/gtests/test_iface_pd_iter.cpp
- tests/gtests/test_layer_normalization.cpp
- tests/gtests/test_matmul.cpp
- tests/gtests/test_prelu.cpp
- tests/gtests/test_primitive_cache_mt.cpp
- tests/gtests/test_reorder_common.hpp
- tests/gtests/test_resampling.cpp
- tests/gtests/test_shuffle.cpp
- tests/gtests/test_sum.cpp
While running the Google test suite using MIOpen we get several errors that need to be addressed. This PR solves:
* test_concat
* test_eltwise
* test_group_normalization.cpp
* test_iface_attr_quantization.cpp
* test_iface_pd_iter.cpp
* test_layer_normalization.cpp
* test_matmul.cpp
* test_prelu.cpp
* test_primitive_cache_mt.cpp
* test_reorder_common.hpp
* test_resampling.cpp
* test_shuffle.cpp
* test_sum.cpp
Latest Main
Mi210 AMD GPU
```bash
cmake .. -DCMAKE_BUILD_TYPE=Debug -DDNNL_CPU_RUNTIME=DPCPP -DDNNL_GPU_RUNTIME=DPCPP -DDNNL_GPU_VENDOR=AMD -DONEDNN_BUILD_GRAPH=OFF
```
```bash
ctest --output-on-failure -E benchdnn --timeout 800
```
Check the [gtests.txt](https://github.com/oneapi-src/oneDNN/files/14837250/gtests.txt) file for additional information.
```bash
83% tests passed, 38 tests …
```
> gtests: gpu: amd: Fix to a subset of gtests failures

- cmake/FindACL.cmake
- src/cpu/platform.cpp
Instead of requiring users to download and build Arm Compute Library themselves, use the version installed on the system. Additionally, only use public header files.
Fixes #1599
> Use installed Arm Compute Library

- src/cpu/aarch64/acl_eltwise.hpp
- src/cpu/aarch64/acl_utils.cpp
Add ACL implementation of GELU erf. On CPUs with SVE, we will continue to use the jit eltwise impl, but this will accelerate GELU on CPUs with Arm® Neon™ by replacing ref. It will also allow impls making use of the `acl_post_ops_t` to work with GELU erf post ops. E.g. matmul+GELU erf will now use ACL rather than ref.
> src: cpu: aarch64: Add ACL GELU erf

- src/gpu/amd/miopen_softmax_impl.hpp
- tests/benchdnn/softmax/softmax.cpp
Fixes failures of benchdnn tests of softmax with MIOpen (`./benchdnn --mode=C -v1 --engine=gpu --softmax --batch=test_softmax_gpu`). Two issues are fixed:
- MIOpen only supports 4-dimensional tensors for softmax. This now throws if higher number of dimensions is provided.
- Threshold for comparison of half precision floating point results was set wrong.
> gpu: miopen: softmax: fix benchdnn failures

- tests/benchdnn/eltwise/eltwise.cpp
There are some precision issues when the algorithm for **eltwise** is **logistic**, **elu**, or **srelu**. MiOpen fails in those cases when the **f16** datatype is used. This PR solves that problem by adjusting the comparison with the computed reference.
Latest Master
Mi210 AMD GPU
ROCm Version 5.6.1
Intel(R) oneAPI DPC++/C++ Compiler 2024.0.2 (2024.0.2.20231213)
```bash
cmake .. -DCMAKE_BUILD_TYPE=Debug -DDNNL_CPU_RUNTIME=DPCPP -DDNNL_GPU_RUNTIME=DPCPP -DDNNL_GPU_VENDOR=AMD -DONEDNN_BUILD_GRAPH=OFF
```
```bash
./benchdnn --mode=C -v1 --engine=gpu --eltwise --batch=test_eltwise_gpu
```
Several errors like this:
```bash
create: --eltwise --engine=gpu --dir=FWD_I --dt=f16 --tag=axb --alg=logistic --alpha=0 --beta=0 --inplace=true 5x16x3
run: --eltwise --engine=gpu --dir=FWD_I --dt=f16 …
```
> benchdnn: gpu: miopen: eltwise: Fixes some comparison issues when f16 is used

- src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64/xbyak_aarch64.h
- src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64/xbyak_aarch64_code_array.h
- src/cpu/aarch64/xbyak_aarch64/xbyak_aarch64/xbyak_aarch64_inner.h
- tests/benchdnn/common.cpp
- tests/benchdnn/dnnl_common.cpp
Handle code paths that are assuming Linux just because `__GNUC__` is defined.
Fixes #1803
> Handle code paths that are assuming Linux just because __GNUC__ is defined

- src/cpu/aarch64/jit_uni_pool_kernel.cpp
- src/cpu/aarch64/jit_uni_pool_kernel.hpp
- src/cpu/aarch64/jit_uni_pooling.cpp
- src/cpu/aarch64/jit_uni_pooling.hpp
- src/cpu/cpu_pooling_list.cpp
Enhancement: Expand ARM SVE support in jit_uni_pool_kernel
This commit enhances the existing ARM SVE support in jit_uni_pooling to include additional vector length compatibility. The changes made are for implementation of different ARM SVE vector length.
Major Code changes:
• Updated the block size definition to accommodate other SVE vector length.
• Added 'OR' condition to extend support for other SVE vector while assigning value of 'ncsp_fmt_tag'.
• Predicate registers are set according to isa vector length.
• ldr is replaced by ld1w instruction for average pooling
- [✓] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit? Yes
1. make test 
```
98% tests passed, 4 tests failed out of 162 …
```
> cpu: aarch64: Expand ARM SVE support in jit_uni_pool_kernel

- src/gpu/amd/sycl_hip_scoped_context.cpp
- src/gpu/amd/sycl_hip_stream.cpp
- src/gpu/nvidia/sycl_cuda_scoped_context.cpp
- src/gpu/nvidia/sycl_cuda_stream.cpp
A recent change broke the build for cuda and miopen backends. This PR adds the header includes that are missing and are breaking the build.
> gpu: cuda/miopen: bugfix missing headers

- src/cpu/aarch64/jit_generator.hpp
- src/cpu/aarch64/matmul/brgemm_matmul_copy_utils.cpp
- src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp
This PR is raised in order to remove build warnings after merging the PR : https://github.com/oneapi-src/oneDNN/pull/1818.
We have just added the third parameter as an empty string for the functions VCONDCHECK_BG, and VCHECK_BG in the file src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp.
> fixup: cpu: aarch64: Expand ARM SVE support for matrix multiplication

- src/gpu/sycl/binary_kernels.hpp
- src/gpu/sycl/ref_binary.hpp
Adds support for broadcasting of second argument to SYCL implementation of binary primitive.
Also removes the restriction that only allows running said kernel on GPUs with subgroup size of 32, which enables it for many AMD GPUs.
> gpu: sycl: binary: add support for broadcasting

- src/cpu/aarch64/acl_convolution_utils.cpp
Remove fall through to oneDNN reference implementation for depthwise convolution when padding greater then kernel as it offers significant performance increase.
Fixes https://github.com/oneapi-src/oneDNN/issues/1807
> cpu: aarch64: conv: Removing fall through to oneDNN reference implementation for depthwise convolution when padding greater then kernel

- src/gpu/nvidia/cudnn_convolution.cpp
- src/gpu/nvidia/cudnn_convolution.hpp
- src/gpu/nvidia/cudnn_convolution_impl.hpp
When destination scaling is applied to int8 data types some benchmarks fails. This happened because the scaling was applied over the int8 result causing saturation issues.
Fixes #1749
We create a temporal vector to save the values in `f32` and keep the computation as expected by oneDNN. The `scratchpad_size` is modified because of this change. We launch `cudnnConvolutionForward` to obtain its result as `f32`. We apply the scaling parameters for `src/wei` at this stage. After the post-operations, we apply the scaling for `dst` over the `f32` result to avoid saturation issues. Finally, the result is converted to `s8`.
> gpu: nvidia: conv: Fix int8 convolution primitive fails

- src/cpu/aarch64/matmul/acl_matmul.cpp
- src/cpu/aarch64/matmul/acl_matmul.hpp
- src/cpu/aarch64/matmul/acl_matmul_utils.cpp
- src/cpu/aarch64/matmul/acl_matmul_utils.hpp
This PR computes (B*A)^T instead of (A^T)*(B^T) when the cost of transposing (B*A) is cheaper. This improves performance by ~1.25x for square matrices and even higher for
tall-skinny/fat-short matrices.
It also reduces code duplication and moves allocation of dst accumulator from ACL to scratchpad memory in oneDNN.
> cpu: aarch64: matmul: Optimize (A^T)*(B^T) in acl_matmul

- .github/workflows/slack-pr.yaml
Add support for posting notifications in UXL slack channel when a PR is labelled with RFC. 
To test this workflow, you need to merge it to main and then open a PR, and label it RFC. GitHub will execute the
workflow file from the `main` branch. Since the workflow is coming from main, it will have access to the secret `SLACK_BOT_TOKEN` Vadim has confirmed that he added the secret to the repo.
- [ n/a] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [ n/a] Have you formatted the code using clang-format?
- [ n/a] Have you submitted performance data that demonstrates performance improvements?
- [ no] Have you published an RFC for the new feature?
- [n/a ] Have you included information on how to reproduce the issue (either in a github …
> add slack notification for RFCs

- cmake/ACL.cmake
- src/cpu/aarch64/matmul/acl_lowp_matmul.hpp
- src/cpu/matmul/cpu_matmul_list.cpp
This PR adds an s8:s8:f32 matmul implementation using `arm_compute::NEGEMMLowpMatrixMultiplyCore`. For moderate sized problems the new implementation is
- several orders of magnitude faster than `gemm:jit`
- ~3-4x faster than the pure `f32` `gemm:acl`
We also bump the minimum ACL version to 24.04 because this is first version which supports runtime `arm_compute:QuantizationInfo` and contains the necessary s8:s8:f32 kernels. This isn't released yet, but will be in the coming days.
> src: cpu: aarch64: add ACL s8:s8:f32 matmul

- src/cpu/aarch64/acl_post_ops.cpp
- src/cpu/aarch64/acl_post_ops.hpp
- src/cpu/aarch64/matmul/acl_matmul.cpp
- src/cpu/aarch64/matmul/acl_matmul.hpp
- src/cpu/aarch64/matmul/acl_matmul_utils.cpp
- src/cpu/aarch64/matmul/acl_matmul_utils.hpp
Fuse the sum post op in acl matmul by setting the accumulate flag to true in arm_compute::GEMMInfo. This speeds up the post op and saves allocating a temporary dst sized tensor.
For example
```
OMP_NUM_THREADS=16 ./benchdnn --mode=p --matmul --attr-post-ops=sum,sum+relu:0 1024x256:256x2048
```
is ~12% faster and uses 1.2kB less peak memory.
We also added `_for_sum` to `use_dst_acc` flag to stop it being confused with the `dst_acc` used for transposing.
Change the way we deal with fused eltwise (as well as the new sum) to fix segfaults when binary ops followed fused ops.
This PR includes the commit from #1889 because it builds on top of it.
> Fuse sum post op acl matmul

- doc/primitives/rnn.md
- examples/primitives/lbr_gru.cpp
- examples/primitives/vanilla_rnn.cpp
Add examples for Vanilla RNN and Linear-before-reset GRU RNN by referring to the [RNN descriptions in oneDNN documentation](https://oneapi-src.github.io/oneDNN/dev_guide_rnn.html).
For lbr_gru, the gates order is update, reset and output gate, and there is an extra bias for u' gate.
> examples: add RNN examples

- src/gpu/sycl/binary_kernels.hpp
- src/gpu/sycl/ref_binary.cpp
- src/gpu/sycl/ref_binary.hpp
- src/gpu/sycl/sycl_primitive_conf.hpp
Add support for the post ops on binary primitive that were previously unsupported (binary, prelu, remaining eltwise ones).
Also fixes a bug in three-way type equality comparison that prevented binary running with bf16 type.
> gpu: sycl: binary: add support for remaining post ops

- src/sycl/sycl_engine_base.hpp
- src/xpu/sycl/utils.cpp
Fixes two bugs that were recently introduced to main and prevent running benchdnn tests on Nvidia and AMD backends. Both bugs cause creation of CPU SYCL engine to fail. They are:
- The `kind` of `sycl_engine_base_t` is hardcoded to `engine_kind::gpu` making it impossible to create a CPU SYCL engine. This was introduced in commit 6e248387e6de095dd7c6945be71220359b0f7378
- The OpenCL path of `are_equal` function for devices is not enabled when SYCL is selected for CPU backend, but it should be. This was introduced in commit ae1dbfe605be02a65049538ca6d884fd1c6e906b
> cpu: sycl: bugfix engine creation

- src/cpu/aarch64/jit_uni_reorder.cpp
- src/cpu/reorder/cpu_reorder_regular_bf16.cpp
use jit uni reorder for aarch64 src=bf16 and dst=bf16
add restriction for bf16 use when beta == 0.f as it is unsupported
CLIP model inference was 2x faster on PyTorch with this patch
> cpu: reorder: use jit uni reorder for bf16

- src/cpu/aarch64/shuffle/jit_uni_shuffle.cpp
- src/cpu/aarch64/shuffle/jit_uni_shuffle_kernel.cpp
This PR fixes https://github.com/oneapi-src/oneDNN/issues/1806
> aarch64: shuffle: fix segv for bf16 cases

- src/common/memory_tracking.hpp
- src/cpu/aarch64/acl_convolution_utils.hpp
- src/cpu/aarch64/acl_deconvolution.cpp
- src/cpu/aarch64/acl_deconvolution.hpp
- src/cpu/aarch64/acl_depthwise_convolution.hpp
- src/cpu/aarch64/acl_gemm_convolution.hpp
- src/cpu/aarch64/acl_indirect_gemm_convolution.hpp
- src/cpu/aarch64/acl_inner_product.cpp
- src/cpu/aarch64/acl_inner_product.hpp
- src/cpu/aarch64/acl_winograd_convolution.hpp
> cpu: aarch64: Move allocation of accumulator from ACL to oneDNN scratchpad

- src/gpu/gpu_reorder_list.cpp
- src/gpu/sycl/ref_reorder.cpp
- src/gpu/sycl/ref_reorder.hpp
- src/gpu/sycl/reorder_kernels.hpp
- src/gpu/sycl/sycl_primitive_conf.hpp
Adds SYCL implementation of reorder primitive.
> gpu: sycl: add reorder primitive

- src/gpu/sycl/batch_normalizations_kernels.hpp
- src/gpu/sycl/layer_normalizations_kernels.hpp
- src/gpu/sycl/ref_batch_normalization.cpp
- src/gpu/sycl/ref_layer_normalizations.cpp
- src/gpu/sycl/sycl_primitive_conf.hpp
This MR adds the following changes:
- Conditionally set sycl_md_t members that are not use if a specific flag is not set to avoid hitting assert in https://github.com/oneapi-src/oneDNN/blob/main/src/xpu/sycl/types.hpp#L116 in Debug mode
- Fix an issue where batch norm's `diff_src1` was loaded as an input parameter, instead of an output parameter resulting in another assertion failure
- sycl_md_ts wrapping workspace memory descriptor were failing the `format_kind::blocked` assertion too, so they were replaced with just the data type, rather than the full md (only the datatype of the workspace is used in the kernel). This also results in a significant reduction of the conf's size.
> gpu: sycl: bnorm: lnorm: Fix debug mode asserts

- src/gpu/sycl/ref_resampling.cpp
- src/gpu/sycl/resampling_kernels.hpp
- src/gpu/sycl/sycl_primitive_conf.hpp
This PR reduces the size of arguments passed to the resampling SYCL kernel to be below 2048 bytes by making the following changes:
- Reduce the size of the `src_md1` array. In the kernel only the first 5 elements of the array (https://github.com/oneapi-src/oneDNN/blob/main/src/gpu/sycl/resampling_kernels.hpp#L131) are accessed.
- The tensor dimensions (MB, IC, IH, IW, etc.) don't need to be passed explicitly as the memory descriptors passed to the kernel contain this information.
- Remove some unused variables from the conf struct.
> gpu: sycl: resampling: Reduce argument size

- rfcs/20231213-determinism/README.md
Link to [rendered document](https://github.com/mgouicem/oneDNN/blob/mgouicem/determinism/rfcs/20231213-determinism/README.md)
> rfc: proposal to support deterministic primitive execution

- rfcs/20230118-f16-accumulation/README.md
This RFC covers accumulation datatype in oneDNN. [Link to rendered document](https://github.com/mgouicem/oneDNN/blob/mgouicem/rfcs/f16-accumulation/rfcs/20230118-f16-accumulation/README.md)
This is mostly to:
- prevent using f16 accumulation during f16 training
- allow using f16 accumulation during inference.
> rfcs: accumulation datatype

- rfcs/20240228-graph-api-ocl-runtime/README.md
This is to propose adding OpenCL GPU runtime support in oneDNN Graph API.
It addresses the API limitations mentioned RFC https://github.com/oneapi-src/oneDNN/pull/1745 and also paves the way for OpenVINO integration.
> rfcs: graph api: propose ocl runtime support

- src/gpu/nvidia/stream.cpp
The `!` seems to have been dropped by mistake during refactoring.
> gpu: nvidia: fix stream init

- src/cpu/aarch64/acl_convolution_utils.cpp
- src/cpu/aarch64/acl_indirect_gemm_convolution.hpp
- src/cpu/cpu_convolution_list.cpp
Backport of https://github.com/oneapi-src/oneDNN/pull/1933 to unreleased rls-v3.5
> Backport: src: cpu: aarch64: conv: Use acl_indirect_gemm for bf16 convolutions

- src/cpu/aarch64/jit_uni_reorder.cpp
- src/cpu/reorder/cpu_reorder_regular_bf16.cpp
Backport of https://github.com/oneapi-src/oneDNN/pull/1915 to unreleased rls-v3.5
> Backport: src: cpu: aarch64: reorder: use jit uni reorder for bf16

- src/cpu/aarch64/acl_post_ops.cpp
- src/cpu/aarch64/acl_post_ops.hpp
- src/cpu/aarch64/matmul/acl_matmul.cpp
- src/cpu/aarch64/matmul/acl_matmul.hpp
- src/cpu/aarch64/matmul/acl_matmul_utils.cpp
- src/cpu/aarch64/matmul/acl_matmul_utils.hpp
This is a backport of #1889 and #1892 
**Backport cpu: aarch64: matmul: Optimize (A^T)*(B^T) in acl_matmul**
Computes (B*A)^T instead of (A^T)*(B^T) when the cost of transposing (B*A) is cheaper. This improves performance by ~1.25x for square matrices and even higher for
tall-skinny/fat-short matrices.
It also reduces code duplication and moves allocation of dst accumulator from ACL to scratchpad memory in oneDNN
**Backport cpu: aarch64: matmul: fuse sum post op in acl matmul**
Fuse the sum post op in acl matmul by setting the accumulate flag to
true in arm_compute::GEMMInfo. This speeds up the post op and saves
allocating a temporary dst sized tensor.
We also added `_for_sum` to `use_dst_acc` flag to stop it being confused
with the `dst_acc` used for transposing.
Change the way we deal …
> Backport cpu: aarch64: matmul: Optimize (A^T)*(B^T) and fuse sum post-op in acl_matmul

- src/cpu/aarch64/acl_convolution_utils.cpp
- src/cpu/aarch64/acl_indirect_gemm_convolution.hpp
- src/cpu/cpu_convolution_list.cpp
Use acl_indirect_gemm for bf16 convolutions
performance improvements:
Total benchdnn tests: 57
Min: 15x
Average: 131x
Max: 320x
> src: cpu: conv: Use acl_indirect_gemm for bf16 convolutions

- src/cpu/aarch64/acl_convolution_utils.cpp
Update direct vs indirect conv heuristics
- Remove fall through to direct conv for low thread counts: the previous heuristic is outdated and no longer optimal
- Do not fall though to direct conv for small convolutions when the datatype is BF16: indirect conv is faster when source, weight, destination are of type BF16
- [ YES ] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [ YES ] Have you formatted the code using clang-format?
> cpu: aarch64: conv: Update direct vs indirect conv heuristics

- src/cpu/aarch64/jit_uni_softmax.cpp
- src/cpu/aarch64/jit_uni_softmax.hpp
- tests/benchdnn/softmax/softmax.cpp
This pull request includes the following changes:
**1. Add bf16 Datatype Support:**
- Added a switch case to support the bf16 datatype in the loading and storing functions within jit_uni_softmax.cpp.
**2. Update BenchDNN Threshold for AArch64:**
- Updated the condition to relax the threshold for AArch64 in the SoftMax BenchDNN tests.
These changes aim to enhance the compatibility and accuracy of SoftMax operations on AArch64 with bf16 datatype support.
- [✓] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit? Yes
**make test**
```
98% tests passed, 3 tests failed out of 194
Total Test time (real) = 513.11 sec
148 - test_graph_unit_dnnl_conv_usm_cpu (Failed)
153 - test_graph_unit_dnnl_large_partition_usm_cpu …
```
> cpu: aarch64: Add bf16 Datatype Support and Relax BenchDNN Threshold for AArch64 SoftMax

- src/common/memory_tracking.hpp
- src/cpu/aarch64/acl_post_ops.cpp
- src/cpu/aarch64/acl_post_ops.hpp
- src/cpu/aarch64/matmul/acl_lowp_matmul.cpp
- src/cpu/aarch64/matmul/acl_lowp_matmul.hpp
Performance results:
matrix scale  |  speed-up
-------------------------
128x128   |  x0.82
256x256   |  x2.63
512x512   |  x33.3
1024x1024  |  x60.7
2048x2048  |  x60.3
To select the correct s8->s8 ACL kernel, we need to send
all quantization info at configuration but oneDNN does
not make these available until execution. This change
goes around this issue by first performing s8->f32 matmul
and then requantizing back to s8.
> src: cpu: aarch64: add support for s8:s8:s8 in ACL lowp matmul

- src/common/memory_tracking.hpp
- src/cpu/aarch64/matmul/acl_matmul.cpp
- src/cpu/aarch64/matmul/acl_matmul.hpp
- src/cpu/aarch64/matmul/acl_matmul_utils.cpp
- src/cpu/aarch64/matmul/acl_matmul_utils.hpp
Introduce 3 new scrathpad memory key names.
> cpu: aarch64: matmul: Move allocation of temporary tensors to scratchpad in acl_matmul

- README.md
This pull request updates the README.md with some specific build and test information for aarch64
- Added Arm Neoverse N1/V1 to list of CPU this library is optimized for.
- Added Arm section to the Validated Configurations for CPU Engine with the configuration that is currently being tested by Arm.
- Bumped version of ACL ( Arm Compute Library ) that is recommended for use with oneDNN to 24.04.
> doc: add aarch64 build and test info to README

- src/cpu/aarch64/brgemm/brgemm_containers.hpp
- src/cpu/aarch64/cpu_isa_traits.hpp
- src/cpu/aarch64/jit_brgemm_1x1_conv.cpp
- src/cpu/aarch64/jit_brgemm_1x1_conv.hpp
- src/cpu/aarch64/jit_brgemm_conv.cpp
- src/cpu/aarch64/jit_brgemm_conv.hpp
- src/cpu/aarch64/jit_brgemm_conv_comp_pad_kernel.cpp
- src/cpu/aarch64/jit_brgemm_conv_comp_pad_kernel.hpp
- src/cpu/aarch64/jit_brgemm_conv_trans_kernel.cpp
- src/cpu/aarch64/jit_brgemm_conv_trans_kernel.hpp
- src/cpu/aarch64/jit_brgemm_conv_utils.cpp
- src/cpu/aarch64/jit_brgemm_conv_utils.hpp
- src/cpu/aarch64/jit_brgemm_post_ops.hpp
- src/cpu/aarch64/jit_brgemm_primitive_conf.hpp
- src/cpu/aarch64/jit_brgemm_transpose_utils.cpp
- src/cpu/aarch64/jit_brgemm_transpose_utils.hpp
- src/cpu/aarch64/jit_primitive_conf.hpp
- src/cpu/cpu_convolution_list.cpp
This commit enables BRGEMM general and 1x1 forward convolution for the ARM SVE ISA.
**Major code changes:**
Added BRGEMM convolution files in src/aarch64 to support general and 1x1 forward convolution.
Added support for brgemm convolution in src/cpu/aarch64/brgemm/brgemm_containers.hpp, src/aarch64/cpu_isa_traits.hpp and src/cpu/aarch64/jit_primitive_conf.hpp.
1. make test output : 
```
98% tests passed, 3 tests failed out of 194
Total Test time (real) = 535.50 sec
148 - test_graph_unit_dnnl_conv_usm_cpu (Failed)
153 - test_graph_unit_dnnl_large_partition_usm_cpu (Failed)
175 - test_benchdnn_modeC_graph_ci_cpu (Failed)
Output from these tests are in: …
```
> cpu: aarch64: Extend ARM SVE Support for BRGEMM General and 1x1 Forward Convolution.

- rfcs/20240325-reorganize-gpu/README.md
[Rendered doc](https://github.com/densamoilov/oneDNN/tree/dsamoylo/rfcs/reorganize-gpu/rfcs/20240325-reorganize-gpu)
>  rfcs: add proposal on refactoring the GPU Architecture

- src/gpu/generic/sycl/ref_eltwise.cpp
- src/gpu/generic/sycl/sycl_primitive_conf.hpp
This MR slightly refactors the eltwise SYCL kernel to remove some unused data that was stored in the conf struct passed to the kernel. As a result, the size of the struct is reduced, allowing the kernel to run on some specific devices with a lower kernel argument size limit.
> gpu: sycl: eltwise: Reduce size of kernel arguments

- src/gpu/generic/sycl/ref_shuffle.cpp
- src/gpu/generic/sycl/ref_shuffle.hpp
The sycl shuffle implementation is not supporting u8 datatype for the forward pass as suggested in [shuffle doc](https://oneapi-src.github.io/oneDNN/dev_guide_shuffle.html#data-types). This PR enables this feature.
> gpu: sycl: shuffle: Enabling u8 datatype support

- src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp
There was an issue raised on the brgemm matmul PR stating there was an assertion error when running this test : ctest -R cpu-tutorials-matmul-matmul-quantization-cpp in OneDNN debug mode. (https://github.com/oneapi-src/oneDNN/issues/1920)
We had intentionally added this statement but on discussion in the community it was decided that it had to be removed. This PR contains the required changes for the same.
```
make test
98% tests passed, 3 tests failed out of 195
Total Test time (real) = 918.81 sec
149 - test_graph_unit_dnnl_conv_usm_cpu (Failed)
154 - test_graph_unit_dnnl_large_partition_usm_cpu (Failed)
176 - test_benchdnn_modeC_graph_ci_cpu (Failed) …
```
> brgemm_assertion_fix

- src/cpu/aarch64/jit_uni_reorder.cpp
This PR implements 32x32 and 64x64 jit:blk transpose kernel, and optimises the existing 8x8 jit:blk kernel.
**Major changes:**
Addition of 32x32 transpose kernel to jit:blk reorder.
Addition of 64x64 transpose kernel to jit:blk reorder.
Adding heuristics as to when to switch to jit:uni from jit:blk(for large shapes jit:uni is better.)
Optimisation of 8x8 jit:blk kernel
- [y] Do all unit and benchdnn tests (`make test`) pass locally for each commit?
```
make test
98% tests passed, 3 tests failed out of 195
Total Test time (real) = 918.81 sec
149 - test_graph_unit_dnnl_conv_usm_cpu (Failed)
154 - test_graph_unit_dnnl_large_partition_usm_cpu (Failed)
176 - test_benchdnn_modeC_graph_ci_cpu (Failed)
Output from these tests are in: …
```
> Addition of 32x32 and 64x64 kernel to jit:blk reorders

- src/gpu/generic/sycl/binary_kernels.hpp
- src/gpu/generic/sycl/ref_binary.hpp
The binary primitive SYCL kernel implementation skipped some tests that must be computed. This PR solves that problem.
As an example, the following test needs to be passed:
```bash
./tests/benchdnn/benchdnn --binary --engine=gpu --skip-impl=cuda --sdt=bf16:bf16 --ddt=u8 --stag=abx:axb 3x5x6x9:3x5x6x9
```
> gpu: sycl: binary: Enabling some skipped tests

- src/gpu/intel/jit/gemm/gen_gemm_kernel_generator.cpp
Fixes missing std::runtime_error to stub translations missing in 11d0481ae.
> gpu: jit: intel: gemm: add missing stub exceptions

- src/common/layer_normalization_pd.hpp
MSVC 19.40.33812.0 has a bug that results in incorrect optimizations and breaks all layer normalization tests.
> build: workaround for MS STL breaking change

- rfcs/20231122-add-group-norm-graph-op/README.md
support group normalization in graph api
[A Link to the rendered document](https://github.com/rongzha1/oneDNN/blob/rfcs_gnorm/rfcs/20231122-add-group-norm-graph-op/README.md)
> rfcs: support group normalization in graph api

- src/gpu/generic/sycl/layer_normalizations_kernels.hpp
- src/gpu/generic/sycl/ref_layer_normalizations.cpp
- src/gpu/generic/sycl/sycl_primitive_conf.hpp
Fixes a bug in SYCL implementation of layer normalization, where source and destination scales could have wrong or even uninitialized types.
> gpu: sycl: lnorm: bugfix scales datatypes

- src/gpu/generic/sycl/ref_reorder.hpp
Fixes a bug in SYCL reorder. Adds checks against using it for cross-engine reorders and cases with runtime dimensions.
> gpu: sycl: reorder: bugfix - more checks

- src/gpu/generic/sycl/ref_batch_normalization.hpp
- src/gpu/generic/sycl/ref_binary.hpp
- src/gpu/generic/sycl/ref_eltwise.hpp
- src/gpu/generic/sycl/ref_layer_normalizations.hpp
- src/gpu/generic/sycl/ref_lrn.hpp
- src/gpu/generic/sycl/ref_pooling.hpp
- src/gpu/generic/sycl/ref_prelu.hpp
- src/gpu/generic/sycl/ref_reorder.hpp
- src/gpu/generic/sycl/ref_resampling.hpp
- src/gpu/generic/sycl/ref_shuffle.hpp
- src/gpu/generic/sycl/ref_softmax.hpp
- src/gpu/generic/sycl/sycl_utils.hpp
Currently dimensions in `xpu::sycl::md_t` are stored as 32-bit integers and the constructor has an assertion that the size of each dimension is <= `INT32_MAX`. This PR adds a check to all SYCL primitives to ensure they return unimplemented if they are created with inputs with dimensions > `INT32_MAX`. Some primitives (e.g. eltwise) have tests with very large tensors, which was triggering this assert in Debug mode.
> gpu: sycl: Ensure dimensions are <= INT32_MAX

- src/cpu/x64/jit_avx512_common_conv_kernel.hpp
The code changes in this PR were generated automatically by the Permanence AI Coder and reviewed by myself. This PR updates memory allocation in `jit_avx512_common_conv_fwd_kernel` and `jit_avx512_common_conv_bwd_data_kernel_f32` by using `utils::make_unique` for object management of the private member `kernel_` instead of raw pointers. 
> cpu: x64: jit_avx512_common_conv_kernel.hpp: improve memory management safety

- src/gpu/generic/sycl/ref_pooling.hpp
- tests/benchdnn/pool/ref_pool.cpp
This pull request facilitates the utilization of distinct source (src) and destination (dst) datatypes during the forward inference pass within the SYCL pooling operator implementation.
> Add support for different src and dst datatypes in the SYCL implementation for pooling

- src/gpu/generic/sycl/ref_binary.hpp
Current sycl binary implementation can support `s32` datatypes, however it does not expect them.
This PR simply adds the `s32` datatype to enable the binary operation to run in this datatype.
> gpu: sycl: binary: Adding datatype support with int32

- src/gpu/generic/sycl/prelu_kernels.hpp
- src/gpu/generic/sycl/ref_prelu.cpp
- src/gpu/generic/sycl/ref_prelu.hpp
- src/gpu/generic/sycl/sycl_primitive_conf.hpp
This PR fixes the backward pass of the SYCL PRELU implementation for scalar broadcast cases. The changes made are:
- Allocate scratchpad in `init()`
- Use the reduction primitive to reduce diff_weights. Since the scratchpad is stored in global memory and the PRELU kernel first stores data in it which is later reduced in the same kernel, there was a race condition as there is no way to guarantee that all threads have finished writing to it before it is being read from. Launching a separate kernel (reduction) guarantees correct synchronisation.
> gpu: sycl: prelu: Fix backward pass

- src/cpu/x64/brgemm/capi/brgemm_api.cpp
The code changes in this PR were generated automatically by the Permanence AI Coder and reviewed by myself. This PR updates memory allocation in `dnnl_brgemm_create` to use `std::unique_ptr`, improving memory safety by reducing opportunities for memory leaks (such as the one previously fixed [here](https://github.com/oneapi-src/oneDNN/commit/014544626fdafca2b6cae76e82a1b88b9a9b0384).
> cpu: x64: brgemm: improve memory safety of dnnl_brgemm_create

- src/gpu/generic/sycl/convolution_kernels.hpp
- src/gpu/generic/sycl/ref_convolution.cpp
- src/gpu/generic/sycl/ref_convolution.hpp
- src/gpu/generic/sycl/sycl_post_ops.hpp
- src/gpu/generic/sycl/sycl_primitive_conf.hpp
- src/gpu/gpu_convolution_list.cpp
Implemented SYCL convolution, including FWD, BWD_DATA and BWD_WEIGHTS. 
Also adds support for hardswish and sum zeropoints to post ops, as these are used in convolution tests.
> gpu: sycl: convolution: implemented

- src/gpu/generic/sycl/sycl_primitive_conf.hpp
The binary SYCL kernel currently only supports up to 5 postops, but the conf struct for binary had an array of 8 postops.
> gpu: sycl: binary: Reduce number of binary postops

- src/gpu/generic/sycl/batch_normalizations_kernels.hpp
- src/gpu/generic/sycl/binary_kernels.hpp
- src/gpu/generic/sycl/convolution_kernels.hpp
- src/gpu/generic/sycl/eltwise_kernels.hpp
- src/gpu/generic/sycl/layer_normalizations_kernels.hpp
- src/gpu/generic/sycl/lrn_kernels.hpp
- src/gpu/generic/sycl/pooling_kernels.hpp
- src/gpu/generic/sycl/prelu_kernels.hpp
- src/gpu/generic/sycl/reorder_kernels.hpp
- src/gpu/generic/sycl/resampling_kernels.hpp
- src/gpu/generic/sycl/shuffle_kernels.hpp
- src/gpu/generic/sycl/softmax_kernels.hpp
- src/gpu/generic/sycl/sum_kernels.hpp
Fixes includes in headers containing sycl kernels, so that they include what they use and nothing else. This has been a bit of a mess, making header include order matter.
Fixes a bug introduced in https://github.com/oneapi-src/oneDNN/pull/2004 where clang-format reordering includes caused a build failure.
> gpu: sycl: bugfix kernel includes

- src/cpu/aarch64/acl_eltwise.cpp
- src/cpu/aarch64/acl_eltwise.hpp
Switch out NEActivationLayer for the stateless CpuActivation interface from ACL. acl_eltwise_obj_t does not store any tensors now; instead we pass a ITensorPack to CpuActivation::run().
The acl_eltwise_obj_t struct has also been replaced with a unique_ptr to CpuActivation.
Follows the pattern of #2022
> cpu: aarch64: use stateless ACL CpuActivation interface for eltwise

- tests/benchdnn/pool/ref_pool.cpp
When enabling src/dst datatypes for nVidia a bug was introduced that makes the different datatypes unsuccessful on AMD. This PR fixes that situation.
> generic: sycl: pooling: Enabling different src/dst dt for AMD

- src/cpu/reorder/cpu_reorder_regular_f16.cpp
This patch enables fp16 direct copy reorder implementation. Aarch64 implementation of jit_reorder lacks fp16 support, so direct copy instance provides better performance
This change is upstreamed from [oneDNN fork repo](https://github.com/openvinotoolkit/oneDNN) maintained by [OpenVINO organization](https://github.com/openvinotoolkit).
```
100% tests passed, 0 tests failed out of 197
Total Test time (real) = 1701.15 sec
```
> [ARM] Enable fp16 direct copy reorder implementation

- src/gpu/generic/sycl/convolution_kernels.hpp
- src/gpu/generic/sycl/ref_batch_normalization.cpp
- src/gpu/generic/sycl/ref_convolution.cpp
- src/gpu/generic/sycl/ref_convolution.hpp
- src/gpu/generic/sycl/ref_deconvolution.cpp
- src/gpu/generic/sycl/ref_deconvolution.hpp
- src/gpu/generic/sycl/sycl_primitive_conf.hpp
- src/gpu/gpu_deconvolution_list.cpp
Implemented SYCL deconvolution. For fwd and bwd data it uses existing implementations. For bwd_weights it uses existing convolution kernel, which is modified a bit.
> generic: sycl: deconvolution: implemented

- src/cpu/aarch64/brgemm/brgemm.cpp
- src/cpu/aarch64/brgemm/brgemm_utils.cpp
- src/cpu/aarch64/jit_brdgmm_dw_conv.cpp
- src/cpu/aarch64/jit_brdgmm_dw_conv.hpp
- src/cpu/aarch64/jit_primitive_conf.hpp
- src/cpu/cpu_convolution_list.cpp
This commit enables BRGEMM depthwise forward convolution for the ARM SVE ISA.
Major code changes:
- Added BRGEMM depthwise convolution files in src/aarch64 to support BRGEMM depthwise forward convolution.
- Updated brgemm_utils.cpp and brgemm.cpp to support multiple ISAs by incorporating relevant changes.
1. make test output: 
```
99% tests passed, 2 tests failed out of 196
Total Test time (real) = 1461.70 sec
155 - test_graph_unit_dnnl_large_partition_usm_cpu (Failed)
177 - test_benchdnn_modeC_graph_ci_cpu (Failed)
Output from these tests are in: /home/deekshak/xybak/oss_pr/latest_brgemm/oneDNN_Fork/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
make: *** …
```
> cpu: aarch64: Enable BRGEMM Depthwise Forward Convolution.

- src/cpu/aarch64/matmul/acl_matmul.cpp
- src/cpu/aarch64/matmul/acl_matmul.hpp
- src/cpu/aarch64/matmul/acl_matmul_utils.cpp
- src/cpu/aarch64/matmul/acl_matmul_utils.hpp
Following on from #2027, #2032, #2043 et al, this patch upgrades matmul to use the new stateless ACL API.
However, this patch needs to go in after #2043 is merged, as it needs the minimum version of ACL to be bumped up. Please take care to merge in order.
> cpu: aarch64: Upgrade matmul to use ACL stateless API

- src/gpu/generic/sycl/ref_sum.cpp
- src/gpu/generic/sycl/ref_sum_many_inputs.hpp
- src/gpu/generic/sycl/sum_kernels.hpp
- src/gpu/generic/sycl/sycl_primitive_conf.hpp
We were having some issues on Intel when running the benchdnn tests on Intel PVC:
```bash
create: --sum --engine=gpu --dtag=abx --scales=0.25 --inplace=true 3x3x16x4
terminate called after throwing an instance of 'sycl::_V1::compile_program_error'
what():  The program was built for 1 devices
Build program log for 'Intel(R) Data Center GPU Max 1100':
-11 (PI_ERROR_BUILD_PROGRAM_FAILURE)
```
The previous issue is solved by reducing the size of the conf_ struct.
Additionally, we were having issues because the scaling factor was not being applied to the first tensor in the sum SYCL kernel. This was also fixed in the current PR.
> generic: sycl: sum: Issues with scales and conf_ struct on Intel

- src/cpu/rv64/rvv_nchw_pooling.hpp
The patch fixes build on riscv64 platforms: adds missing include `common/primitive.hpp` where the base class `primitive_t` of `riscv_nchw_pooling_fwd_t` is defined.
This change is upstreamed from [oneDNN fork repo](https://github.com/openvinotoolkit/oneDNN) maintained by [OpenVINO organization](https://github.com/openvinotoolkit).
> [RV64] Add missing include `common/primitive.hpp` required for riscv64 platforms

- .github/dependabot.yml
- .github/labels.yml
- .github/workflows/labeler.yml
This PR adds [Pull Request Labeler](https://github.com/actions/labeler?tab=readme-ov-file#pull-request-labeler) workflow that automatically adds labels to PRs based on changed files and target branch. Currently the following labels are enabled:
* `platform:x` using rules similar to CODEOWNERS
* `documentation`
* `governance` for CODEOWNERS and MAINTAINERS.md
* `devops` for .github
* `backport` for PRs targeting release branches
You can see it in action in [my fork](https://github.com/vpirogov/oneDNN/pulls)
> Workflow for automatic labeling

- .github/CODEOWNERS
- .github/labels.yml
- .github/workflows/labeler.yml
Follow up to #2055.
This PR introduces Labeler and CODEOWNERS to an orphan branch `rfcs`.
> Workflow for automatic RFC labeling

- src/cpu/aarch64/acl_convolution_utils.cpp
- src/cpu/aarch64/acl_convolution_utils.hpp
- src/cpu/aarch64/acl_depthwise_convolution.cpp
- src/cpu/aarch64/acl_depthwise_convolution.hpp
- All common conv code is now stateless, so we can delete all legacy code.
- Coincidentally fixes #2033 by making the weights constant.
> cpu: aarch64: Enable stateless ACL depthwise convolution

- MAINTAINERS.md
I would like to nominate Sunita Nadampalli @snadampal for the role of code owner of AArch64 component. Sunita has [history of contributions](https://github.com/oneapi-src/oneDNN/pulls?q=is%3Apr+author%3Asnadampal) to oneDNN and vested interest in quality of oneDNN support for AWS Graviton processors in Pytorch.
> @snadampal as codeowner for AArch64

- README.md
- cmake/ACL.cmake
- src/cpu/aarch64/acl_binary.cpp
- src/cpu/aarch64/acl_binary.hpp
make binary ops use stateless ACL interface
> [!NOTE]
> This patch depends on ACL v23.08.1. Please add it to the 3.6 milestone but kindly wait for the ACL v23.08.1 release before merging.
Will allow all post-ops to be made stateless, as pointed out by @dzarukin in [this comment](https://github.com/oneapi-src/oneDNN/pull/2043#discussion_r1723733268).
> cpu: aarch64 make binary ops use stateless ACL interface

- rfcs/20240819-generic-vendor/README.md
[Link to rendered document](https://github.com/densamoilov/oneDNN/tree/dsamoylo/rfcs/generic-vendor/rfcs/20240819-generic-vendor)
> Proposal on enabling generic GPU vendor

- src/cpu/x64/jit_avx512_core_bf16_conv_kernel.hpp
- src/cpu/x64/jit_avx512_core_x8s8s32x_1x1_conv_kernel.hpp
- src/cpu/x64/jit_avx512_core_x8s8s32x_conv_kernel.hpp
- src/cpu/x64/jit_avx512_core_x8s8s32x_deconvolution.hpp
- src/cpu/x64/jit_uni_x8s8s32x_1x1_conv_kernel.hpp
- src/cpu/x64/jit_uni_x8s8s32x_conv_kernel.hpp
The code changes in this PR were generated automatically by the Permanence AI Coder and reviewed by @fwph & @jweese. This PR updates memory allocation for `jit_generator` objects across several structs. Note that in the case of `jit_avx512_core_x8s8s32x_fwd_kernel` the macro `DNNL_DISALLOW_COPY_AND_ASSIGN` was missing; and was added. This PR is effectively applying the update from https://github.com/oneapi-src/oneDNN/pull/2017 to additional files.
> cpu: x64: improve memory management safety for additional kernels

- src/cpu/aarch64/jit_sve_512_core_x8s8s32x_deconvolution.hpp
- src/cpu/aarch64/jit_sve_conv_kernel.hpp
- src/cpu/aarch64/jit_uni_dw_conv_kernel_f32.hpp
- src/cpu/aarch64/jit_uni_dw_conv_kernel_utils.hpp
The code changes in this PR were generated automatically by the Permanence AI Coder and reviewed by @fwph & @jweese. This PR updates memory allocation across several objects in the aarch64 implementation. Note that the bot is configured to add the `DNNL_DISALLOW_COPY_AND_ASSIGN` where it is missing; while this is redundant with the use of unique_ptr, it provides more consistency with existing code.
* note that on our build system (AWS graviton instance) the test `172 - test_benchdnn_modeC_brgemm_ci_cpu (Subprocess aborted)` is failing both on this branch AND on the main branch.
> cpu: aarch64: improve memory management safety for aarch64 kernels

- src/cpu/x64/jit_avx512_core_bf16cvt.hpp
- src/cpu/x64/jit_uni_dw_conv_kernel_utils.hpp
- src/cpu/x64/jit_uni_xf16_sum.hpp
The code changes in this PR were generated automatically by the Permanence AI Coder and reviewed by @fwph & @jweese. This PR updates memory allocation for additional JIT-related objects for cpu/x64. Note that in the case of `jit_avx512_core_add_cvt_ps_to_bf16_t` the macro `DNNL_DISALLOW_COPY_AND_ASSIGN` was missing and was added. This PR is effectively applying the update from https://github.com/oneapi-src/oneDNN/pull/2017 to additional files.
> cpu: x64: improve memory safety for additional x64 JIT objects

- src/gpu/generic/sycl/matmul_kernels.hpp
- src/gpu/generic/sycl/ref_matmul.cpp
- src/gpu/generic/sycl/ref_matmul.hpp
- src/gpu/generic/sycl/sycl_io_helper.hpp
- src/gpu/generic/sycl/sycl_post_ops.hpp
- src/gpu/generic/sycl/sycl_primitive_conf.hpp
- src/gpu/generic/sycl/sycl_utils.hpp
- src/gpu/gpu_matmul_list.cpp
- src/xpu/sycl/types.hpp
Implemented SYCL matmul. Rruntime dimensions and prelu post op are not yet supported - will be added in future. 
As they are used in the benchdnn tests a number of post ops options have also been added.
> generic: sycl: matmul: implemented

- src/gpu/generic/sycl/binary_kernels.hpp
- src/gpu/generic/sycl/convolution_kernels.hpp
- src/gpu/generic/sycl/eltwise_kernels.hpp
- src/gpu/generic/sycl/pooling_kernels.hpp
- src/gpu/generic/sycl/ref_binary.cpp
- src/gpu/generic/sycl/ref_convolution.cpp
- src/gpu/generic/sycl/ref_eltwise.cpp
- src/gpu/generic/sycl/ref_pooling.cpp
- src/gpu/generic/sycl/ref_resampling.cpp
- src/gpu/generic/sycl/ref_softmax.cpp
- src/gpu/generic/sycl/reorder_kernels.hpp
- src/gpu/generic/sycl/resampling_kernels.hpp
- src/gpu/generic/sycl/softmax_kernels.hpp
- src/gpu/generic/sycl/sycl_io_helper.hpp
- src/gpu/generic/sycl/sycl_post_ops.hpp
- src/gpu/generic/sycl/sycl_primitive_conf.hpp
Refactor where data for post ops is loaded. Instead of the kernel that supports post ops now post ops load any data they need. This has two benefits:
- data is only loaded if actually used by post ops
- code is simplified.
> generic: sycl: refactor how post op arguments are loaded

- src/cpu/aarch64/acl_batch_normalization.hpp
- src/cpu/aarch64/acl_deconvolution.hpp
- src/cpu/aarch64/acl_depthwise_convolution.cpp
- src/cpu/aarch64/acl_depthwise_convolution.hpp
- src/cpu/aarch64/acl_gemm_convolution.cpp
- src/cpu/aarch64/acl_gemm_convolution.hpp
- src/cpu/aarch64/acl_indirect_gemm_convolution.cpp
- src/cpu/aarch64/acl_indirect_gemm_convolution.hpp
- src/cpu/aarch64/acl_inner_product.hpp
- src/cpu/aarch64/acl_post_ops.hpp
- src/cpu/aarch64/acl_winograd_convolution.cpp
- src/cpu/aarch64/acl_winograd_convolution.hpp
- src/cpu/aarch64/matmul/acl_lowp_matmul.cpp
- src/cpu/aarch64/matmul/acl_matmul.cpp
- src/cpu/aarch64/matmul/acl_matmul.hpp
Elementwise and binary post-ops have been made stateless by previous patches to oneDNN and ACL. This patch removes the now redundant calls to create_resource for these operators.
Fixes: [this comment](https://github.com/oneapi-src/oneDNN/pull/2043#discussion_r1723733268) by @dzarukin
> cpu: aarch64: remove calls to acl_post_ops_t::create_resource

- MAINTAINERS.md
I would like to nominate Hamza Butt @theComputeKid for the role of code owner of AArch64 component. Hamza is a member of oneDNN team at Arm and has a [history of contributions](https://github.com/oneapi-src/oneDNN/pulls?q=is%3Apr+author%3AtheComputeKid) to oneDNN.
> @theComputeKid as codeowner for AArch64

- src/cpu/aarch64/acl_threadpool_scheduler.cpp
- src/cpu/aarch64/matmul/acl_matmul.cpp
Test cpu-tutorials-matmul-matmul-quantization-cpp is failing due to Threadpool not being initialised. This patch fixes the issue by executing the task on a single thread when Threadpool is unavailable. It is a response to the comment made by @mgouicem [here](https://github.com/oneapi-src/oneDNN/pull/2047#discussion_r1724733775).
The error can be reproduced executing:
`DNNL_VERBOSE=1 ./examples/cpu-tutorials-matmul-matmul-quantization-cpp`
> cpu: aarch64: Fix Threadpool not initializing issue causing test to fail.

- src/gpu/generic/sycl/ref_binary.hpp
- src/gpu/generic/sycl/ref_convolution.hpp
- src/gpu/generic/sycl/ref_eltwise.hpp
- src/gpu/generic/sycl/ref_reorder.hpp
- src/gpu/generic/sycl/ref_softmax.hpp
- src/gpu/generic/sycl/ref_sum.hpp
- src/gpu/generic/sycl/sycl_post_ops.hpp
Move check on whether post ops are supported from each individual operation to a common location. The check itself is also improved to more accurately check what is actually supported.
Also fixes a bug introduced in https://github.com/oneapi-src/oneDNN/pull/2005 that `sum_dt_` was not set.
> generic: sycl: move check on post ops to a single location

- tests/gtests/test_convolution_format_any.cpp
Prevents a spurious Success result when GPU support is not available.
---
I'm not terribly familiar with gtest, if there's a more idiomatic way to run the test on both engine types I'm happy to do that instead. One way to reproduce the issue is to set `OCL_ICD_VENDORS=/dev/null` and verify that `clinfo -l` shows no platforms or devices before running the test.
> tests: Run convolution_format_any on GPU

- src/gpu/generic/sycl/pooling_kernels.hpp
- tests/benchdnn/pool/ref_pool.cpp
There were some cases causing issues like the following when running on Intel PVC devices:
```bash
[3214][SRC][1:2:0:3] exp_f32:          64 exp:          64 got:          76 diff:      12 rdiff:  0.1875
[COMPARE_STATS][SRC]: trh=0.078125 err_max_diff:      12 err_max_rdiff:  0.1875 all_max_diff:      28 all_max_rdiff:  0.1875
3627:FAILED (errors:1 total:5746) __REPRO: --pool --engine=gpu --dir=BWD_D --dt=bf16:bf16 ic17ih13oh37kh17ph20
```
And also some unimplemented ones that were not caught in the implementation:
```bash
create: --pool --engine=gpu --tag=aBx16b ic64iw32ow16kw3sw2pw0
Error: Function 'check_dnnl_status' at (/home/svet/oneDNN-intel/tests/benchdnn/dnnl_common.hpp:324) returned 'unimplemented'
Error: Function 'create_primitive' at …
```
> generic: sycl: pooling: bug fixes when running on Intel GPU

- cmake/SDL.cmake
Adds a CMAKE code check for GNU on Windows systems, which should mean mingw, and then does not apply the non-existent /DEPENDENTLOADFLAG:0x2000 flag that fails on mingw
Added as part of the fix for  #2092
> cmake: skip DEPENDENTLOADFLAG for mingw

- src/gpu/generic/sycl/ref_reorder.cpp
Some benchdnn cases were failing.
```bash
onednn_verbose,v1,primitive,exec,cpu,reorder,jit_direct_copy:uni,undef,src:f32::blocked:abcd::f0 dst:f32::blocked:abcd::f0,,,2x16x3x4,0.158936
onednn_verbose,v1,primitive,exec,cpu,reorder,jit_direct_copy:uni,undef,src:f32::blocked:abcd::f0 dst:f32::blocked:abcd::f0,,,2x16x3x4,0.166992
onednn_verbose,v1,primitive,exec,gpu,reorder,dpcpp:ref:any,undef,src:f32::blocked:abcd::f0 dst:f32::blocked:abcd::f0,attr-scales:src0:2:f32 attr-post-ops:sum:0.5,,2x16x3x4,0.233887
onednn_verbose,v1,primitive,exec,cpu,reorder,jit_direct_copy:uni,undef,src:f32::blocked:abcd::f0 dst:f32::blocked:abcd::f0,,,2x16x3x4,0.216064
[   0][DST][0:0:0:0] exp_f32: 1.25829e+07 exp: 1.25829e+07 got:         nan diff:     nan rdiff:     nan
[   1][DST][0:0:0:1] exp_f32:-1.25829e+07 …
```
> gpu: generic: sycl: reorder: sum post-ops issues

- .github/automation/get_acl.sh
- .github/workflows/ci-aarch64.yml
- src/cpu/aarch64/acl_winograd_convolution.cpp
This change enables a basic ci pipeline for macos using github actions. At this moment, it only performs a build, and uses the provided free macos runners, which are sufficient for the use case.
The logic is:
- When compiling with clang, we just pull ACL from its github releases and link oneDNN with it. This is because macos ACL releases are built with clang. The script to do this is added.
- When compiling with gcc, we build ACL and link with it.
I had to make a trivial code change in one file to get the code to compile with gcc.
For now, the yaml file is quite crude (for example, the fact that I have to specify the ACL_VERSION twice is not elegant), but I would like to submit it so that we can start ci. There are plans to improve on it later and then also at some point I would like to …
> Enable macos build in ci

- src/gpu/generic/sycl/binary_kernels.hpp
- src/gpu/generic/sycl/convolution_kernels.hpp
- src/gpu/generic/sycl/eltwise_kernels.hpp
- src/gpu/generic/sycl/layer_normalizations_kernels.hpp
- src/gpu/generic/sycl/lrn_kernels.hpp
- src/gpu/generic/sycl/pooling_kernels.hpp
- src/gpu/generic/sycl/prelu_kernels.hpp
- src/gpu/generic/sycl/ref_binary.cpp
- src/gpu/generic/sycl/ref_convolution.cpp
- src/gpu/generic/sycl/ref_deconvolution.cpp
- src/gpu/generic/sycl/ref_eltwise.cpp
- src/gpu/generic/sycl/ref_eltwise.hpp
- src/gpu/generic/sycl/ref_layer_normalizations.cpp
- src/gpu/generic/sycl/ref_lrn.cpp
- src/gpu/generic/sycl/ref_reorder.cpp
- src/gpu/generic/sycl/ref_softmax.cpp
- src/gpu/generic/sycl/ref_sum.cpp
- src/gpu/generic/sycl/reorder_kernels.hpp
- src/gpu/generic/sycl/resampling_kernels.hpp
- src/gpu/generic/sycl/shuffle_kernels.hpp
- src/gpu/generic/sycl/softmax_kernels.hpp
- src/gpu/generic/sycl/sum_kernels.hpp
- src/gpu/generic/sycl/sycl_primitive_conf.hpp
- src/gpu/generic/sycl/sycl_utils.hpp
Refactors mainloops in many sycl kernels so that consecutive workitems work on consecutive calculations. This should improve performace on Nvidia and AMD GPUs, as coalesced memory transfers can be used in more cases. The amount of duplicated code is also reduced.
This PR should be easier to review with hiding of whitespace changes, as in many places there is difference only in indentation levels.
> generic sycl: refactor kernel mainloops

- src/gpu/generic/sycl/ref_matmul.cpp
- src/gpu/generic/sycl/ref_resampling.cpp
We found that the issue solved in #2096 was also happening for **matmul** and **resampling** operators. The data type initialization in the sycl_post_ops_t is needed.
> gpu: generic: sycl: resampling and matmul sycl-post-ops issues

- MAINTAINERS.md
I would like to nominate Hamza Butt @theComputeKid for the role of code owner of devops component. Hamza contributed initial CI support for Arm processors and working on extending this functionality with Arm Hosted GHA Runners.
> @theComputeKid as codeowner for devops

- .github/workflows/ci-aarch64.yml
Adding smoke tests for macos-14, for clang.
Unfortunately, we have test failures (per config) and warnings (per compiler), so we cannot turn on Werror and we also need to attach test failures to specific configurations.
We want to remove all test failures and warnings. This is a work in progress to at least remove some warnings (#2116). If we can get ci in as fast as possible for at least one OS, even in a primitive, messy state, we can stop more test failures and warnings from being added.
I also applied formatting to the YAML file.
There are some problems with GCC testing that needs some investigation from myself but I didn't want GCC to stop me from starting testing in ci for clang.
> github: workflows: Add macos smoke tests

- src/cpu/aarch64/brgemm/jit_brgemm_kernel.cpp
- src/cpu/aarch64/jit_brgemm_conv_comp_pad_kernel.hpp
- src/cpu/aarch64/jit_brgemm_post_ops.hpp
- src/cpu/cpu_deconvolution_list.cpp
this change is to fix aarch64 compile warning so that we can enable Werror for aarch64 in the ci.
So far, we've fix t warnings inside oneDNN/src/cpu/aarch64/ folder and the following out-of-bound warning
```
In file included from /Users/runner/work/oneDNN/oneDNN/oneDNN/src/common/memory_desc_wrapper.hpp:27,
from /Users/runner/work/oneDNN/oneDNN/oneDNN/src/common/memory.hpp:26,
from /Users/runner/work/oneDNN/oneDNN/oneDNN/src/common/engine.hpp:26,
from /Users/runner/work/oneDNN/oneDNN/oneDNN/src/cpu/cpu_engine.hpp:26,
from /Users/runner/work/oneDNN/oneDNN/oneDNN/src/cpu/cpu_deconvolution_list.cpp:19:
In function 'void dnnl::impl::copy_c_op_desc(op_desc_t*, const op_desc_t*)',
inlined from 'dnnl::impl::primitive_desc_iterator_t::primitive_desc_iterator_t(dnnl::impl::engine_t*, const …
```
> cpu: aarch64: fix jit_brgemm warnings

- .github/workflows/ci-aarch64.yml
having fix all existing warnings for aarch64 in https://github.com/oneapi-src/oneDNN/pull/2118, we'd like to turn on DONEDNN_WERROR option in ci.
> cpu: aarch64: ci turn on DONEDNN_WERROR

- src/gpu/generic/sycl/ref_sum_many_inputs.cpp
This PR fixes an issue in the generic SYCL sum where the `base_prims_` vector was accessed out of bounds because the index variable `i` was incremented before the access.
> generic: sycl: fix sum with many inputs

- src/gpu/nvidia/cudnn_matmul_executor.hpp
When compiling oneDNN with C++20, the current matmul executor causes errors due to the lambda capturing `this`.
In C++20 implicit capture of `this` is an error, while in C++17 explicit capture will flag as a warning.
PR adds use of the already existing compiler workaround for the lambda capture `WA_THIS_COPY_CAPTURE`
Example error:
```
src/gpu/nvidia/cudnn_matmul_executor.hpp:89:13: error: implicit capture of 'this' with a capture default of '=' is deprecated [-Werror,-Wdeprecated-this-capture]   89 |             free_runtime_scratch(matmul_impl_->has_runtime_params(),      |             ^/export/users/mkltest/ec/oneDNN-auto-ef77e8c0-f90d-f1f3-8666-a4bf010d0e2d/sources/src/gpu/nvidia/cudnn_matmul_executor.hpp:63:33: note: add an explicit capture of 'this' to capture '*this' by reference …
```
> gpu: nvidia: Updated matmul labda capture

- MAINTAINERS.md
I would like to nominate Radu Salavat @Radu2k and Siddhartha Menon @Sqvid for the roles of code owner of AArch64 component. Radu and Siddhartha are members of oneDNN team at Arm and have a history of contributions to oneDNN.
> @Radu2k and @Sqvid as codeowners for AArch64

- src/gpu/nvidia/cudnn_matmul.cpp
- src/gpu/nvidia/cudnn_reorder_lt.cpp
Commit 28ec30dd80dea203949ec175996122b81b9d825e introduces changes to `memory_t`. Adding the required changes to enable building nvidia backend, as it currently does not compile.
> gpu: nvidia: Updating pointers to memory_t

- src/cpu/aarch64/acl_deconvolution.hpp
- src/cpu/aarch64/brgemm/brgemm.cpp
- src/cpu/aarch64/brgemm/brgemm_utils.cpp
- src/cpu/aarch64/brgemm/brgemm_utils.hpp
- src/cpu/aarch64/jit_brgemm_conv_utils.cpp
- src/cpu/aarch64/matmul/brgemm_matmul.cpp
- src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp
- tests/benchdnn/graph/ref_primitive.cpp
Remove the asserts that cause segfaults in the test and handle unsupported cases based on oneDNN status type. As well remove the forgotten asserts in brgemm_matmul.cpp and modify acl_deconvolution.hpp to make op/f32/deconv_bwd_d test pass.
This replaces the asserts in brgemm that make `test_benchdnn_modeC_graph_ci_cpu` segfault on AArch64 by replacing the asserts with `status_t` type in oneDNN. As well, the segfault of `--graph --skip-impl=ref --case=op/f32/deconv.json` test when built with gcc-10 and g++-10, which is part of the graph test batch.
> cpu: aarch64: Expand brgemm aarch64 unsupported cases handling mechanism

- src/cpu/aarch64/jit_uni_reorder.cpp
- src/cpu/aarch64/jit_uni_reorder.hpp
- src/cpu/aarch64/jit_uni_reorder_utils.cpp
- src/cpu/x64/jit_uni_reorder.cpp
- src/cpu/x64/jit_uni_reorder.hpp
- src/cpu/x64/jit_uni_reorder_utils.cpp
Overuse of `verbose_printf` has led to verbose output like
```
onednn_verbose,v1,init : onednn_verbose,v1,@@@ type:f32:f32 ndims:3 onednn_verbose,v1,[1:0:0:-1:false:1:1:0:0]onednn_verbose,v1,xonednn_verbose,v1,[1:0:1:-1:false:1:1:0:0]onednn_verbose,v1,xonednn_verbose,v1,[1:0:2:-1:false:1:1:0:0]onednn_verbose,v1, off:0:0
onednn_verbose,v1,norm : onednn_verbose,v1,@@@ type:f32:f32 ndims:3 onednn_verbose,v1,[1:0:0:-1:false:1:1:0:0]onednn_verbose,v1,xonednn_verbose,v1,[1:0:1:-1:false:1:1:0:0]onednn_verbose,v1,xonednn_verbose,v1,[1:0:2:-1:false:1:1:0:0]onednn_verbose,v1, off:0:0
onednn_verbose,v1,smpl : onednn_verbose,v1,@@@ type:f32:f32 ndims:1 onednn_verbose,v1,[1:0:-1:-1:false:1:1:0:0]onednn_verbose,v1, off:0:0
onednn_verbose,v1,tile : onednn_verbose,v1,@@@ type:f32:f32 ndims:1 …
```
> cpu: {x64,aarch64}: fix debug verbose output

- .gitignore
- src/cpu/aarch64/jit_uni_reorder.cpp
The PR: https://github.com/oneapi-src/oneDNN/pull/1986 changed a particular condition for bf_16(This was not intended in the PR). So after this was merged some testcases which were going to jin:uni before, started going to simple:any(reference). Therefore, this PR contains the fix for that by just reverting the un-intended change to the original.
```
make test
99% tests passed, 2 tests failed out of 200
Total Test time (real) = 2142.22 sec
159 - test_graph_unit_dnnl_large_partition_usm_cpu (Failed)
181 - test_benchdnn_modeC_graph_ci_cpu (Failed)
Output from these tests are in: …
```
> Re-enablement of bf16 jit:uni reorders for aarch64

- src/gpu/nvidia/cudnn_batch_normalization_executor.hpp
- src/gpu/nvidia/sycl_cuda_compat.hpp
- src/gpu/nvidia/sycl_cuda_utils.hpp
Adding support for the extension `ext_codeplay_enqueue_native_command` [LINK](https://github.com/intel/llvm/blob/2f0abc61d551b773e0497276c61fbcc576475a23/sycl/doc/extensions/experimental/sycl_ext_codeplay_enqueue_native_command.asciidoc#L2) to documentation.
Apart from improved dependencies for native commands, the native command provides less execution overhead, improving performance.
Example:
```
total perf: min(ms):38.256 avg(ms):97.7698
total perf: min(ms):33.4952 avg(ms):33.7441
```
Results generated running on A100 with command
`--eltwise --engine=gpu --mode=P --skip-impl=dpcpp:ref:any --batch=tests/benchdnn/inputs/eltwise/test_eltwise_gpu`
- [ x ] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [ x ] Have you formatted the …
> gpu: nvidia: Added support for native host task extension

- tests/gtests/test_iface_wino_convolution.cpp
The benchDNN wino_conv_test_t.TestSmallPadding test now fails on AArch64 due to the absence of an FP16 Winograd convolution kernel implementation in ACL. This PR modifies the test suite to skip FP16 test cases when compiled with the DNNL_AARCH64_USE_ACL option.
Fixes #2109
> cpu: aarch64: fix wino conv test failure

- src/gpu/generic/sycl/binary_kernels.hpp
Adding support for blocked format in https://github.com/oneapi-src/oneDNN/pull/1972 partially broke post op sum. This PR fixes the bug.
> generic: sycl: binary: bugfix post ops with blocked formats

- src/cpu/aarch64/jit_uni_dw_conv_kernel_f32.cpp
Change the condtion `(simd_w_ != 16 || simd_w_ != 8)`, which is logically always-true, to `(simd_w_ != 16 && simd_w_ != 8)`, which is the intention of the assert message.
run `benchdnn --conv --dir=BWD_W g16ic16ih5oc16oh5kh3ph1n"conv_basic_2d:depthwise"` before and after the patch.
Introduced by https://github.com/oneapi-src/oneDNN/pull/2062
@nishith-fujitsu @abhijain1204fujitsu Could you confirm that my change was the original intention?
> cpu: aarch64: Fix always-true assert guard

- src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp
Remove asserts in brgemm_matmul_utils.cpp to make
test_benchdnn_modeC_graph_fusions_cpu fail or pass. The datatype support should be checked in
check_datatype. This has been renamed as well from check_isa_with_datatype to check_datatype.
By enabling all graph API tests on AArch64 as a follow-up of this change (https://github.com/oneapi-src/oneDNN/pull/2099#issuecomment-2379967176) unveiled that `ctest -R "test_benchdnn_modeC_graph_fusions_cpu"` failed due to the assets on lines 323, 324 and 325 in `src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp`.  
The test segfaulted because `pick_blocked_B_layout` is called before the init, when the object is constructed. These datatypes are checked in the init and return status unimplemented. 
This behaviour should be changed to calling …
> cpu: aarch64: Fix C_graph_fusions_cpu test

- src/cpu/aarch64/jit_uni_softmax.cpp
- src/cpu/aarch64/jit_uni_softmax.hpp
The code changes in this PR were generated automatically by the Permanence AI Coder and reviewed by @fwph & @jweese. This PR updates memory allocation for `softmax_driver_ ` objects in two structs. Note that in the macro `DNNL_DISALLOW_COPY_AND_ASSIGN` was missing; it has been added to be consistent with other objects. 
> cpu: aarch64: improve memory management safety for jit_uni_softmax

- src/common/primitive_hashing.cpp
The code changes in this PR were generated automatically by the Permanence AI Coder and reviewed by @eelenberg and @jweese. This PR replaces a loop-based check for equality of `hint_mds_` and `rhs.hint_mds_` with a call to `std::equal`. The 2 vectors are guaranteed to be the same size after the condition on line 60. This change removes an unnecessary indexing variable, improves readability, and reduces potential off-by-one errors.
> common: replace loop with algorithm for primitive_hashing.cpp

- .github/automation/build_aarch64.sh
- .github/automation/build_acl.sh
- .github/automation/common_aarch64.sh
- .github/automation/test_aarch64.sh
- .github/workflows/ci-aarch64.yml
The oneDNN repo has now been enabled with Arm hosted GitHub runners. They have been activated for PRs opened against the repo.
This is an initial version of AArch64 CI for Linux, on c6g and c7g. We build for gcc-13 and clang-17, in debug and release, for openmp builds. For now, we enable smoke tests for most, but not all, configurations (in order to preserve runner resources). We have logic in the test scripts to skip tests on certain configs. As per suggestions from @vpirogov (and I agree), CI logic has been moved into cross-platform scripts.
The CI is dependent on MacOS pipelines passing. Total run time seems to be in line with x86:
- MacOS: 45 minutes
- Linux: 20-30 minutes
Overall time for a run: 1:15 (reasonable).
A few notes:
1. I have renamed the GitHub jobs generically so that …
> github: workflows: Enable Arm Hosted GitHub Runners

- src/cpu/x64/brgemm/jit_brdgmm_kernel.cpp
The code changes in this PR were generated automatically by the Permanence AI Coder and reviewed by @eelenberg and @jweese. This PR replaces an iteration-based for loop over `jmp_table_labels` with a range-based for loop, which removes an unnecessary indexing variable, improves readability, and reduces potential off-by-one errors.
> cpu: x64: brgemm: use range-based loop

- .github/automation/build_aarch64.sh
- .github/automation/build_acl.sh
- .github/automation/common_aarch64.sh
- .github/automation/test_aarch64.sh
- .github/workflows/ci-aarch64.yml
- src/cpu/aarch64/acl_winograd_convolution.cpp
- Backport for v3.6 for #2130
- Plus backporting a small change to successfully compile with gcc.
> github: workflows: Enable aarch64 CI

- src/cpu/x64/gemm/bf16/jit_avx512_core_gemm_bf16bf16f32_kern.cpp
- src/cpu/x64/gemm/bf16/jit_avx512_core_gemm_bf16bf16f32_kern.hpp
- src/cpu/x64/jit_avx512_core_bf16_dw_conv_kernel.hpp
The code changes in this PR were generated automatically by the Permanence AI Coder and reviewed by @fwph & @jweese. This PR updates memory allocation for `bf16_emu_` objects across multiple structs. Note that in the macro DNNL_DISALLOW_COPY_AND_ASSIGN was missing; it has been added to be consistent with other objects.
> cpu: x64 improve memory management safety for multiple objects

- src/cpu/aarch64/injectors/jit_uni_eltwise_injector.cpp
- src/cpu/aarch64/injectors/jit_uni_eltwise_injector.hpp
Improvement: gelu performance for block size 16 in jit_uni_eltwise_injector
This commit improves the performance of gelu function jit_uni_eltwise_injector for block size 16:
• Added a new function gelu_erf_minimax_approx_compute_vector_fwd(const TRegS &vmm_src) for
computing gelu_erf for block size 16.
• Added new gelu_minimax constants and polynomial constants table.
[✓] Do all unit and benchdnn tests (make test and make test_benchdnn_*) pass locally for each commit? Yes
make test summary :
95% tests passed, 11 tests failed out of 200
Total Test time (real) = 3750.50 sec
55 - test_convolution_backward_data_f32 (Subprocess aborted)
123 - test_graph_c_api_compile_parametrized_usm_cpu (Failed)
153 - …
> src: cpu: aarch64: injectors: eltwise_injector - improve gelu performance for block size 16

- .github/automation/pr-title-check.py
- .github/workflows/pr-check.yml
- Enforce that the length of the commit title is at most 72.
- Enforce comma/colon separated scopes as per contribution guidelines.
I promised @vpirogov that I would do this [here](https://github.com/oneapi-src/oneDNN/pull/2103#issuecomment-2371657992).
For code reviewers, in order to test this on your local machine:
```
python3 .github/automation/pr-title-check.py "test: Should Pass"
python3 .github/automation/pr-title-check.py "Should Not Pass"
python3 .github/automation/pr-title-check.py "Really Loooooooooooooooooooooooooooooooooooooooooooooooooooooooooong commit"
python3 .github/automation/pr-title-check.py "Should, Not: Pass, and Error:  XYZ"
python3 .github/automation/pr-title-check.py "Should, Pass: All, good:  XYZ"
```
The free ubuntu github runners are sufficient for this purpose …
> github: workflows: Enable PR checks

- src/cpu/x64/brgemm/jit_brgemm_amx_uker.cpp
The code changes in this PR were generated automatically by the Permanence AI Coder and reviewed by @eelenberg and @jweese. This PR replaces iteration-based for loops over members of `tloop` with range-based for loops, which removes unnecessary indexing variables, improves readability, and reduces potential off-by-one errors. This PR is effectively applying the update from https://github.com/oneapi-src/oneDNN/pull/2086 to an additional file.
> cpu: x64: brgemm: use range-based loop for jit_brgemm_amx_uker.cpp

- RELEASE_NOTES.md
With growing amount of contributions to oneDNN capturing all the user-visible changes in human readable form became challenging. This PR includes a release notes draft based on the information from the PRs for the contributors to review. Your additions and corrections are highly appreciated.
> oneDNN v3.6 release notes

- src/gpu/generic/sycl/binary_kernels.hpp
- src/gpu/generic/sycl/eltwise_kernels.hpp
- src/gpu/generic/sycl/matmul_kernels.hpp
- src/gpu/generic/sycl/pooling_kernels.hpp
- src/gpu/generic/sycl/ref_binary.cpp
- src/gpu/generic/sycl/ref_convolution.cpp
- src/gpu/generic/sycl/ref_eltwise.cpp
- src/gpu/generic/sycl/ref_matmul.cpp
- src/gpu/generic/sycl/ref_matmul.hpp
- src/gpu/generic/sycl/ref_pooling.cpp
- src/gpu/generic/sycl/ref_reorder.cpp
- src/gpu/generic/sycl/ref_resampling.cpp
- src/gpu/generic/sycl/ref_softmax.cpp
- src/gpu/generic/sycl/resampling_kernels.hpp
- src/gpu/generic/sycl/softmax_kernels.hpp
- src/gpu/generic/sycl/sycl_post_ops.hpp
- src/gpu/generic/sycl/sycl_primitive_conf.hpp
Implements PReLu as a post op, which can be used in any SYCL kernels that use post-ops.
This PR also includes some post-ops related cleanup (removing of now redundant members from conf structs) from previous refactors.
> generic: sycl: implement prelu post-op

- src/cpu/aarch64/injectors/jit_uni_eltwise_injector.cpp
- src/cpu/aarch64/injectors/jit_uni_eltwise_injector.hpp
Performance Improvement:  Eltwise Tanh performance improvement for block size 16
Major Code changes:
• Added a new function tanh_polynomial_approx_compute_vector_fwd(const TRegS &vmm_src) for
computing tanh.
• Added new tanh constants and polynomial constants table.
All the tests are carried on A64FX machine which has block size 16:
- [✓] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit? 
1. `make test`
```
95% tests passed, 11 tests failed out of 200
Total Test time (real) = 3790.05 sec
55 - test_convolution_backward_data_f32 (Subprocess aborted)
123 - test_graph_c_api_compile_parametrized_usm_cpu (Failed)
153 - test_graph_unit_dnnl_conv_usm_cpu (Failed)
157 - test_graph_unit_dnnl_group_norm_usm_cpu (Failed) …
```
> cpu: aarch64: injectors: Improve performance of tanh for block size 16

- src/cpu/aarch64/brgemm/jit_brgemm_kernel.cpp
- src/cpu/aarch64/matmul/brgemm_matmul_reorders.cpp
- src/cpu/aarch64/matmul/brgemm_matmul_utils.cpp
- src/cpu/aarch64/matmul/brgemm_matmul_utils.hpp
This PR brings some optimizations to brgemm matmul operator by improving memory utilization and multithreading capabilities.
This PR contains the following changes:
- Modification of blocking parameters for M,K,N based on some heuristics obtained by testing matmul on shapes of majority of language models.
- Assembly level optimization which removes the necessity of the `fadd() `instruction before storing the accumulator results in destination matrix.
```
make test
99% tests passed, 2 tests failed out of 200
Total Test time (real) = 2142.22 sec
159 - test_graph_unit_dnnl_large_partition_usm_cpu (Failed)
181 - test_benchdnn_modeC_graph_ci_cpu (Failed) …
```
> cpu: aarch64: optimising memory/thread utilization in BRGEMM Matmul

- src/cpu/aarch64/brgemm/brgemm_utils.cpp
[Removing asserts in brgemm](https://github.com/oneapi-src/oneDNN/pull/2099#issuecomment-2393169719) accidentally flipped the validation conditions for brgemm, causing brgemm to go to the gemm:jit implementation instead of brg:sve_256 implementation. This is a fix for that issue.
The issue can be reproduced by running the `./tests/benchdnn/benchdnn --matmul 2048x479:479x1024`. The observed behaviour is gemm:jit being used whereas this fix should cause brg:sve_256 to be run.
> cpu: aarch64: brgemm: Fix unimplemented conditions for brgemm

- src/gpu/generic/sycl/README.md
This PR updates the documentation about SYCL primitives.
> sycl: update documentation

- src/gpu/generic/sycl/ref_binary.hpp
- src/gpu/generic/sycl/ref_convolution.hpp
- src/gpu/generic/sycl/ref_layer_normalizations.hpp
- src/gpu/generic/sycl/ref_matmul.hpp
- src/gpu/generic/sycl/ref_prelu.hpp
- src/gpu/generic/sycl/ref_reorder.hpp
- src/gpu/generic/sycl/ref_resampling.hpp
- src/gpu/generic/sycl/ref_sum.hpp
- src/gpu/generic/sycl/sycl_io_helper.hpp
Adds type checks on scales and refactors out a function for checking if a type is supported by SYCL kernels (they all support the same types).
> generic: sycl: add missing type checks on scales

- src/cpu/ppc64/ppc64_gemm_s8x8s32.cpp
This PR resolves the build failure on Power 10 by using qualified names `cpu::q10n::out_round` and `cpu::q10n::saturate`
Fixes [Build failure on Power10](https://github.com/oneapi-src/oneDNN/issues/2145). 
```
100% tests passed, 0 tests failed out of 200
Total Test time (real) = 1439.56 sec
```
> build: Fix the build failure on Power 10

- .github/automation/commit-msg-check.py
- .github/workflows/commit-msg-check.yml
Current code checks the PR title and not the commit messages.
This PR:
- renames the check from PR_check to commit_msg_check for more clarity
- checks all commit messages in the PR instead of the PR title.
> github: apply commit msg check to all commits

- src/cpu/aarch64/acl_gemm_convolution.cpp
- src/cpu/aarch64/acl_gemm_convolution.hpp
- src/cpu/aarch64/acl_winograd_convolution.cpp
- src/cpu/aarch64/acl_winograd_convolution.hpp
This is a hot fix patch for aarch64 wino grad conv. The problem happens when same wino conv is taken from primitive cache due to wrong memory management behavior.
> cpu: aarch64: hot fix for segfault in cached Winograd

- .github/automation/build_acl.sh
- .github/workflows/ci-aarch64.yml
We keep on wasting resources while rebuilding ACL on every ci run. This is an attempt to test out caching ACL for aarch64. I will continue to make the CI more efficient but for now, this is a large enough step to submit on its own.
I temporarily removed stale job cancellations until I can figure out the correct way to cancel stale jobs.
@mgouicem - this also solves the GCC warnings issue we have been facing by downgrading the version of GCC to 13 from 14.
> github: workflows: Enable ACL caching for aarch64 ci

- src/gpu/generic/sycl/ref_convolution.hpp
- src/gpu/generic/sycl/ref_deconvolution.hpp
- src/gpu/generic/sycl/ref_softmax.hpp
Adds some previously missing checks on the SYCL implementations of convolution, deconvolution and softmax.
> generic: SYCL: convolution/deconvolution/softmax: add missing checks

- tests/benchdnn/softmax/softmax.cpp
Softmax benchdnn was missing a precision threshold for bf16, this PR adds it for the nvidia backend, as it caused some failing tests there.
> gpu: nvidia: Added missing bf16 threshold for softmax

- src/gpu/generic/sycl/binary_kernels.hpp
- src/gpu/generic/sycl/convolution_kernels.hpp
- src/gpu/generic/sycl/eltwise_kernels.hpp
- src/gpu/generic/sycl/matmul_kernels.hpp
- src/gpu/generic/sycl/ref_pooling.hpp
- src/gpu/generic/sycl/ref_resampling.hpp
- src/gpu/generic/sycl/reorder_kernels.hpp
- src/gpu/generic/sycl/resampling_kernels.hpp
- src/gpu/generic/sycl/softmax_kernels.hpp
- src/gpu/generic/sycl/sycl_post_ops.hpp
- src/xpu/sycl/types.hpp
Kernels supporting sum post-op can also read the output buffer. This PR fixes them to use appropriate read-write accessor types to access them.
I believe this is not changing any behavior, but it is making use correct according to SYCL spec.
Also fixes resampling and pooling missing post-op checks.
> generic: sycl: fix accessor types

- .github/automation/build_aarch64.sh
- .github/automation/test_aarch64.sh
- src/graph/backend/dnnl/kernels/sdp_primitive_config.cpp
Enabling graph builds in the CI so we can monitor breakages for aarch64. To do this, I had to deal with solving some aarch64 compiler warnings, same as those that appeared in #2118. So I adopted the same resolution as [suggested](https://github.com/oneapi-src/oneDNN/pull/2118#issuecomment-2372124064) for that PR.
For MacOS we only test graph for release mode with clang as the smoke tests take too long in debug mode (1 hour+).
Fixes #2137.
> github: workflows: Enable graph builds for aarch64 CI

- src/gpu/generic/sycl/resampling_kernels.hpp
Fixes wrong offset passed to post-ops in the resampling kernel when the number of dimensions is less than max 6.
> generic: sycl: resampling: fix a bug with post ops and non-max dimensions

- src/gpu/generic/sycl/ref_softmax.hpp
Fixes swapped format checks between fwd and bwd softmax introduced in https://github.com/oneapi-src/oneDNN/pull/2146.
> generic: sycl: softmax: bugfix checks

- src/gpu/generic/sycl/ref_resampling.hpp
Fixes checks on bwd implementation being done on wrong `md`s.
> generic: sycl: resampling: fix checks

- src/gpu/generic/sycl/ref_convolution.cpp
- src/gpu/generic/sycl/ref_convolution.hpp
Fixes a bug with deconvolution post ops not being supported and with sum post op outputting nan.
> generic: sycl: deconvolution: bugfix post-ops

- .github/automation/test_aarch64.sh
temporary skip unit test `test_graph_unit_dnnl_sdp_decomp_usm_cpu` on aarch64 ci. This's a known bug which causes segfault. aarch64 doesn't support graph until this one is fixed.
> github: workflows: disable testcase for graph on macos aarch64 CI

- src/cpu/aarch64/acl_softmax.cpp
A patch to fix bug in recently merged PR https://github.com/oneapi-src/oneDNN/pull/2136.
> cpu: aarch64: fix bug in make softmax ops use stateless ACL interface

- .github/automation/.azure-pipeline.yml
macOS 12 runners [were deprecated](https://github.com/actions/runner-images/issues/10721) in Azure and CI jobs on this platform are now failing.
> github: automation: azure: updated macOS 12 to 14

- src/gpu/generic/sycl/convolution_kernels.hpp
- src/gpu/generic/sycl/ref_convolution.cpp
- src/gpu/generic/sycl/ref_convolution.hpp
- src/gpu/generic/sycl/ref_deconvolution.cpp
- src/gpu/generic/sycl/ref_deconvolution.hpp
- src/gpu/generic/sycl/sycl_primitive_conf.hpp
This PR splits the conf struct for Convolution primitives into 3 separate structs, reducing the argument size passed to the kernel and enabling them to run on intel devices.
> generic: conv: deconv: reduce kernel argument size

- include/oneapi/dnnl/dnnl_ukernel.hpp
Add a missing `#ifdef DNNL_EXPERIMENTAL_UKERNEL` around `dnnl_api_utils` group.  The templates inside that group reference `dnnl_brgemm_t` and `dnnl_brgemm_pack_B_t` types that are guarded using the same condition, and therefore attempting to include the file without the define results in errors:
```
/home/mgorny/miniforge3/envs/pytorch/include/oneapi/dnnl/dnnl_ukernel.hpp:38:22: error: ‘dnnl_brgemm_t’ was not declared in this scope; did you mean ‘dnnl_stream_t’?
38 | struct handle_traits<dnnl_brgemm_t> {
|                      ^~~~~~~~~~~~~
|                      dnnl_stream_t
/home/mgorny/miniforge3/envs/pytorch/include/oneapi/dnnl/dnnl_ukernel.hpp:38:35: error: template argument 1 is invalid
38 | struct handle_traits<dnnl_brgemm_t> {
|                                   ^ …
```
> include: Add missing DNNL_EXPERIMENTAL_UKERNEL ifdef

- cmake/platform.cmake
OneDNN build with https://github.com/riscv-collab/riscv-gnu-toolchain fails with the following error:
The [GNU toolchain for RISC-V](https://github.com/riscv-collab/riscv-gnu-toolchain) now supports RVV by default - ratified RVV1.0. All intrinsics have prefix __riscv64. Some compilers (clang, llvm) can compile a code contained intrinsics without this prefix (have overloaded functions). But GCC from riscv-gnu-toolchain doesn't have them - so cannot compile max pooling primitive from oneDNN.
The fix adds cmake configuration time check that corresponding intrinsics are really supported by the compiler.
This change is upstreamed from [oneDNN fork repo](https://github.com/openvinotoolkit/oneDNN) maintained by [OpenVINO organization](https://github.com/openvinotoolkit).
> [risc-v] cmake: added rvv intrinsics compilation check

- src/cpu/aarch64/matmul/acl_matmul.cpp
This enables matmul config `sdt: bf16 wei: bf16 ddt: f32` to pick ACL kernel. 
> benchdnn: `ONEDNN_VERBOSE=all ./benchdnn --matmul --dt=bf16:bf16:f32 32x128:128x32` 
> Before:
onednn_verbose,v1,primitive,create:dispatch,matmul,cpu,matmul,gemm:acl,undef,src:bf16:a:any:any::f0 wei:bf16:a:any:any::f0 dst:f32:a:any:any::f0,,,32x128:128x32,unsupported datatype combination,src/cpu/aarch64/matmul/acl_matmul.cpp:89
> After: (picks up ACL kernel)
onednn_verbose,v1,primitive,exec:external,CpuGemmAssemblyWrapperKernel/sve_ffhybrid_bf16fp32_mmla_6x4VL,0.242188
onednn_verbose,v1,primitive,exec,cpu,matmul,gemm:acl,undef,src:bf16:a:blocked:ab::f0 wei:bf16:a:blocked:BA8b4a::f0 dst:f32:a:blocked:ab::f0,,,32x128:128x32,0.267822
> cpu: aarch64: enable bf16f32 matmul

- src/cpu/platform.cpp
When running with --cpu-isa-hints=prefer_ymm, tests fail on aarch64 due to an unimplmented error. This change will instead allow the code to run the reference implementations.
Reproducible:
```
./tests/benchdnn/benchdnn --conv --cpu-isa-hints=prefer_ymm --dt=bf16:bf16:bf16 --stag=axb --dtag=axb --attr-post-ops=sum+tanh:1:1 g1ic64ih1000oc64oh1000kh3ph128dh127
```
> test: aarch64: Fix unimplemented error when --cpu-isa-hints=prefer_ymm

- src/cpu/aarch64/jit_uni_reorder.cpp
- tests/benchdnn/inputs/reorder/test_reorder_bfloat16
This enables `jit:uni` reorder for dtype-> ` bf16 -> f32` 
Adding a small testcase logs to demonstrate perf numbers before and after. 
TC: `ONEDNN_VERBOSE=all ./benchdnn --reorder --sdt=bf16 --ddt=f32 --mode=p   1x4096x4096` 
(new) jit:any : 
> onednn_verbose,v1,primitive,exec,cpu,reorder,jit:uni,undef,src:bf16::blocked:abc::f0 dst:f32::blocked:abc::f0,,,1x4096x4096,**0.493896**
(old) simple:any : 
> onednn_verbose,v1,primitive,exec,cpu,reorder,simple:any,undef,src:bf16::blocked:abc::f0 dst:f32::blocked:abc::f0,,,1x4096x4096,**11.9778**
> src: cpu: aarch64: Enable jit bf16 -> f32 reorder

- doc/primitives/matmul.md
- doc/programming_model/data_types.md
Matmul supported data types requested by https://github.com/oneapi-src/oneDNN/issues/2196
> doc: matmul: updated supported data types and minor edits

- src/cpu/aarch64/acl_indirect_gemm_convolution.cpp
cpu: aarch64: Re-enable ACL indirect conv for BF16
Fixes change caused by c547c7770f7eaf2330f410e481c3618ff75c3152
- [ Y ] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [ Y ] Have you formatted the code using clang-format?
> cpu: aarch64: Re-enable ACL indirect conv for BF16

- .github/automation/commit-msg-check.py
- .github/workflows/commit-msg-check.yml
Three main things:
* Makes the action to actually fail when commit messages do not meet requirements.
* Script output now clearly indicates which commit message are are bad and what specific checks failed.
* Extends limit to commit message from 72 to 100 character, as Github and terminals handle this length without line breaks just fine.
Sample output:
```
47f9fbd58700f56cf3732b946b40a1e6cbc5a7db governance: extended commit message length limit to 100
Message length: OK
Message scope:  OK
6de15ad81ed6bb86c1d92c689ac0a796afbbb449 TMP: commit with veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery long message
Message length: FAILED: Commit message summary must not exceed 100 characters.
Message scope:  OK
2370ea1c1ae4e2b112be8bdfa73fa3bc62dcd400 TMP cpu: …
```
> Improvements for commit message checker

- rfcs/20241008-graph-api-swish/README.md
The RFC proposes adding support for Swish operation in Graph API.
Rendered version: [link](https://github.com/TaoLv/mkl-dnn/blob/lvtao/rfcs/swish/rfcs/20241008-graph-api-swish/README.md) .
> rfcs: graph api: support swish operation

- examples/CMakeLists.txt
- tests/gtests/sycl/api/CMakeLists.txt
- tests/gtests/test_deconvolution.cpp
- tests/gtests/test_group_normalization.cpp
- tests/gtests/test_iface_attr_quantization.cpp
- tests/gtests/test_matmul.cpp
- tests/gtests/test_softmax.cpp
This PR adds skips in gtests for unimplemented primitives on nvidia.
> gpu: nvidia: skip unsupported gtests

- src/cpu/aarch64/jit_uni_reorder.cpp
- tests/benchdnn/inputs/reorder/test_reorder_ci
This PR is the fix for the issue : https://github.com/oneapi-src/oneDNN/issues/2213 raised on github.
There was a missing condition that had to be added when zero-points are involved in the reorder.
```
make test
99% tests passed, 2 tests failed out of 218
Total Test time (real) = 1695.47 sec
167 - test_graph_unit_dnnl_large_partition_cpu (Failed)
199 - test_benchdnn_modeC_graph_ci_cpu (Failed)
Output from these tests are in: /home/shreyas/G/shr-fuj/oneDNN_open_source/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
make: *** [Makefile:71: test] Error 8
```
- [y] …
> cpu : aarch64 : reorder : zp correction for 4d shapes

- .github/workflows/ci-aarch64.yml
MacOS github runners are taking too much time. Reduced the configs as well as added more robust stale job kill policies.
> github: workflows: Reduce MacOS CI configs

- .github/automation/build_acl.sh
- README.md
- cmake/ACL.cmake
- src/cpu/aarch64/matmul/acl_matmul.cpp
- src/cpu/aarch64/matmul/acl_matmul.hpp
Some of the underlying kernels used by ACL still require some state and are not safe to be called in parallel with different execution contexts. Eventually when all kernels are truly stateless, this guard can be removed. This feature depends on ACL >= 24.11.1 so the build system and docs have been updated to reflect that.
> fix, build, docs: aarch64: mutex lock if the ACL kernel is not stateless

- .github/automation/test_aarch64.sh
- src/cpu/aarch64/acl_layer_normalization.hpp
- tests/benchdnn/lnorm/lnorm.cpp
* Change acl_layer_normalization to support non-global stats only
* Remove mean and variance check for ACL lnorm from benchdnn
> cpu: aarch64: non-global stats mode for ACL lnorm

- src/gpu/intel/jit/ngen/ngen_elf.hpp
- src/gpu/intel/jit/ngen/ngen_interface.hpp
Note for use: gdb-oneapi only supports the L0 backend.
Sample session:
```
$ cat env/gdb-oneapi_env.sh
source ~/intel/gdb-oneapi/setvars.sh --force
export ZET_ENABLE_PROGRAM_DEBUGGING=1
for f in /sys/class/drm/card*/prelim_enable_eu_debug; do
val=$(cat $f)
if [ $val == 0 ]; then
sudo sh -c "echo 1 > $f"
fi
done
$ source env/gdb-oneapi_env.sh
:: initializing oneAPI environment ...
-bash: BASH_VERSION = 5.1.16(1)-release
args: Using "$@" for setvars.sh arguments:
:: debugger -- latest
:: oneAPI environment initialized ::
$ gdb-oneapi --args ~/dnnl/build/tests/benchdnn/benchdnn --matmul --engine=gpu --impl=jit 16x16:16x16
GNU gdb (Intel(R) Distribution for GDB* 2025.0.0) 15.1
...
(gdb) break gen_gemm_t::execute
Function "gen_gemm_t::execute" not defined.
Make breakpoint pending on future …
```
> xe: jit: ngen: add symbol table

- src/cpu/aarch64/acl_thread.cpp
Makes setting of ThreadpoolScheduler in ACL thread_local to enable use of multiple (thread_local) Schedulers in ACL.
> cpu: aarch64: thread_local ThreadpoolScheduler setting

- src/gpu/intel/jit/gemm/generator/pieces/k_loop.cxx
Backport of 9265b7086f7a76a28caf87735c7b92bcac651573.
> [rls-v3.7-pc] xe: jit: gemm: set lateScale lookahead to match load size

- src/gpu/intel/jit/codegen/codegen.cpp
PR fixes MFDNN-12763.
The original regression is introduced by https://github.com/oneapi-src/oneDNN/commit/ee32525d4f.
> xe: jit: use F pipe for zero initialization

- src/graph/backend/dnnl/kernels/sdp_primitive.cpp
Currently in oneDNN Graph, the MHA cases that passed the initial check of sdpa primitive on GPU will go through the passes and try to create a sdpa primitive. If the creation fails, it will fall back to the reference computation.
With the introduction of int4 sdpa, we added some quantization passes to sdpa primitive kernel, but missed fusion for dst scale and dst, leading to the result that some case with subsequent reorders might fail during layout propagation. The PR has fixed the problem.
```
./tests/benchdnn/benchdnn --graph --engine=gpu --case=tests/benchdnn/inputs/graph/complex_fusion/mha/MHA-bert_large-inf-int8-bs1.json
0:PASSED __REPRO: --graph --engine=gpu --case=tests/benchdnn/inputs/graph/complex_fusion/mha/MHA-bert_large-inf-int8-bs1.json
tests:1 passed:1 skipped:0 …
```
> graph: backend: dnnl: fuse dst scale/zps for layout propagation in sdpa primitive kernel

- .github/labels.yml
We have `platform:XXX` labels for platform specific code, but no way to identify PRs touching on common code. This PR adds `component:XXX` labels:
* build (for CMake files)
* examples
* tests
* api
* graph-api
> github: workflows: added labels for common code changes

- src/common/memory_tracking.hpp
- src/cpu/aarch64/acl_convolution_utils.cpp
- src/cpu/aarch64/acl_convolution_utils.hpp
- src/cpu/aarch64/acl_depthwise_convolution.cpp
- src/cpu/aarch64/acl_gemm_convolution.cpp
- src/cpu/aarch64/acl_gemm_convolution.hpp
- src/cpu/aarch64/acl_indirect_gemm_convolution.cpp
- src/cpu/aarch64/acl_winograd_convolution.cpp
- src/cpu/aarch64/matmul/acl_lowp_matmul_sq.cpp
- src/cpu/aarch64/matmul/acl_lowp_matmul_sq.hpp
- src/cpu/cpu_convolution_list.cpp
- src/cpu/matmul/cpu_matmul_list.cpp
This is to enable `matmul` and `conv` static quantization operations through ACL. Currently, the supported data type combinations are `s8:s8:s8` and `u8:s8:u8`.
> src: cpu: aarch64: Enable matmul and convolution static quantisation through ACL.

- src/gpu/intel/ocl/micro_sdpa.cl
- src/gpu/intel/ocl/micro_sdpa.cpp
This PR changes the way the kernel accepts the KQ scalar values in the SDPA kernel. This is normally the way scale values are layed out in memory as there is no way to specify the format tag of the scalar tensor.
> xe: sdpa: Allow non-transposed scalars for the KQ matmul

- src/gpu/generic/sycl/simple_reduction.cpp
- src/gpu/generic/sycl/simple_reduction.hpp
- src/gpu/generic/sycl/simple_reduction_kernels.hpp
- src/gpu/generic/sycl/sycl_primitive_conf.hpp
- src/gpu/gpu_reduction_list.cpp
This PR adds a fallback simple reduction implementations for cases not covered by #2243.
> gpu: generic: add simple SYCL reduction implementation

- cmake/platform.cmake
Adding flags that build oneDNN with frame pointers, which can be used to walk CPU stack frames by profilers. First step for #1232
> build: cmake: enabling frame pointers

- doc/primitives/softmax.md
- src/cpu/ref_softmax.cpp
- src/cpu/ref_softmax.hpp
- src/cpu/x64/jit_uni_softmax.cpp
- src/cpu/x64/jit_uni_softmax.hpp
- tests/benchdnn/inputs/softmax/test_softmax_ci
- tests/benchdnn/softmax/softmax.cpp
Fixes MFDNN-12822
Fixes #2237
Numbers are obtained not from the perf machine but the trend is visible:
```
perf,cpu,jit:avx10_1_512,,--mode=P --softmax --dir=FWD_I --sdt=bf16 --ddt=bf16 --stag=abcd --dtag=abcd --axis=3 --attr-acc-mode=relaxed 64x16x100x100,0,0.270752,0.192383,0,0.20202,0
perf,cpu,jit:avx10_1_512,,--mode=P --softmax --dir=FWD_I --sdt=bf16 --ddt=bf16 --stag=abcd --dtag=abcd --axis=3 64x16x100x100,0,0.208252,1.38135,0,1.44547,0
```
> cpu: softmax: enable relaxed acc_mode (fixes MFDNN-12822)

- .github/automation/.azure-pipeline.yml
- .github/automation/clang-format.sh
- .github/workflows/pr-linter.yml
This PR updates Azure Pipelines configuration to only trigger x64 CI for changes that can break it, specifically:
* .github to catch CI related changes
* cmake, examples, include, tests
* src/common, src/cpu/common, src/cpu/x64
Also clang-format check moved from Azure Pipelines to Github Actions, as Azure does not seem to allow jobs with different triggers.
> Restricted x64 CI to relevant changes

- src/cpu/x64/brgemm/brgemm_utils.cpp
- src/cpu/x64/matmul/brgemm_matmul.cpp
- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
- tests/benchdnn/inputs/matmul/test_matmul_ci
- tests/benchdnn/inputs/matmul/test_matmul_int8
backport for https://github.com/oneapi-src/oneDNN/pull/2253
> [rls-v3.6 backport] cpu: x64: matmul/brgemm: enable f16 dst dt for int8 matmul 

- .github/workflows/ci-aarch64.yml
There's no need to run AArch64 CI on changes that are unlikely to affect this platform.
> Restricted AArch64 CI to relevant changes

- src/gpu/generic/sycl/ref_sum.hpp
- src/gpu/generic/sycl/ref_sum_many_inputs.hpp
This fixes the generic GPU SyCL build failing due to typos in VDISPATCH_SUM macro calls.
> gpu: generic: sycl: fix typos in VDISPATCH_SUM calls

- src/gpu/intel/ocl/gemm/gemm_with_post_ops.cl
Fixes the following error observed on XeLP.
```
$ ~/dnnl/build_clang/tests/benchdnn/benchdnn  --mode-modifier=P --matmul --engine=gpu --dt=s8:u8:f16 --attr-scales=src:common:0.25 2048x13:13x512
[   0][DST][0:0] exp_f32:         9.5 exp:         9.5 got:           9 diff:     0.5 rdiff:0.0526316
[   1][DST][0:1] exp_f32:         1.5 exp:         1.5 got:           1 diff:     0.5 rdiff:0.333333
[   2][DST][0:2] exp_f32:         5.5 exp:         5.5 got:           5 diff:     0.5 rdiff:0.0909091
[   3][DST][0:3] exp_f32:         9.5 exp:         9.5 got:           9 diff:     0.5 rdiff:0.0526316
[   4][DST][0:4] exp_f32:        4.25 exp:        4.25 got:           4 diff:    0.25 rdiff:0.0588235
[   5][DST][0:5] exp_f32:        14.5 exp:        14.5 got:          14 diff:     0.5 …
```
> xe: ocl: gemm: fix gemm_with_post_ops accumulator type

- src/gpu/intel/ocl/micro_sdpa.cl
- src/gpu/intel/ocl/micro_sdpa.cpp
This PR fixes an issue with the alignment on the KQ matrix multiplication. This fixes several accuracy issues for smaller tensor sizes.
> xe: sdpa: Fix KQ gemm alignment for the K tensor

- src/gpu/generic/sycl/README.md
- src/gpu/generic/sycl/ref_inner_product.cpp
- src/gpu/generic/sycl/ref_inner_product.hpp
- src/gpu/gpu_inner_product_list.cpp
- src/gpu/nvidia/cudnn_matmul_executor.hpp
- src/gpu/nvidia/cudnn_matmul_lt_impl.hpp
- tests/gtests/test_inner_product_forward.cpp
> generic:sycl: Inner Product FWD

- .github/automation/commit-msg-check.py
This PR updates commit checker to avoid false positives in #2279 ([job link](https://github.com/oneapi-src/oneDNN/actions/runs/12393533080/job/34594975133)), #2276, and #2272.
As `:` can be used in commit message itself there's no good way to reliably identify cases with multi-level scope.
> github: automation: fixed rules for commit scope check

- src/graph/utils/pm/nested_matcher.cpp
- src/graph/utils/pm/nested_matcher.hpp
- tests/gtests/graph/unit/utils/test_pattern_matcher_cpu.cpp
Relax the single consumer support in pattern matcher to (limited) multi consumers support.
Add check for shared inputs for cases like gated MLP.
- If a pattern is defined to have shared inputs, then the corresponding input of the graph should have multiple consumers, check if the number of shared inputs aligns with the pattern.
> graph: utils: pm: verify multi-consumers number

- src/graph/backend/dnnl/kernels/sdp.hpp
- src/graph/backend/dnnl/kernels/sdp_decomp_config.cpp
- src/graph/backend/dnnl/kernels/sdp_primitive.cpp
- src/graph/backend/dnnl/kernels/sdp_primitive_config.cpp
[Graph API] Code quality improvement: enhancement for SDP
> graph: backend: kernels: sdp verbose enhancement

- src/gpu/intel/ocl/reusable_simple_concat.cpp
This PR adresses performance regressions discovered as part of regular monitoring by increasing the lws[0] as much as possible. The new get_optimal_lws() logic is biased towards a more n-dimensional lws. Removing the requested vectorization axis (-1) will create a lws[0] as large as possible. If maximizing lws[0] will cause new slowdowns an updated reverted get_optimal_lws() will be used instead.
> xe: increase concat lws[0] size w/new optimal calculation

- src/gpu/intel/ocl/micro_sdpa.cpp
If attention mask is not given, the attn_mask_md will contain undef data type. Querying data type size for it will hit assertion in debug build.
> xe: sdpa: check attn mask presence

- src/graph/backend/dnnl/patterns/sdp.cpp
SDPA K only and V only patterns required the mask/scale nodes in order to find the pattern in the graph. This PR makes the mask and scale nodes as optional.
> graph: sdpa: Fix k/v only pattern to allow for optional mask/scale

- src/common/primitive_hashing.cpp
- src/common/serialization.cpp
- src/common/type_helpers.hpp
The sdpa descriptor has hadn't been updated with the new scales and zero points parameters so the primitive caching mechanism was reusing primitives with invalid configurations. This PR updates the sdpa primitive hash functions to take those parameters into account.
> Fix sdpa descriptor hashing function

- CMakeLists.txt
- cmake/utils.cmake
- src/CMakeLists.txt
This PR is a follow up to #2225 including two changes:
* Restored `target_link_libraries_install` function to strip paths from libraries that end up in CMake config.
* Removes CMake policy settings [redundant for version 3.13](https://cmake.org/cmake/help/latest/manual/cmake-policies.7.html#policies-introduced-by-cmake-3-13).
Fixes MFDNN-12931.
> Fix for issue with generated CMake config file

- examples/CMakeLists.txt.in
- tests/CMakeLists.txt
Remove redundant policies setting in examples and tests CMakeLists.txt after moving to CMake 3.13.
> build: cmake: remove old cmake policies for examples and tests

- CMakeLists.txt
- cmake/Sphinx.cmake
FindPythonInterp was deprecated in CMake 3.12 and removed in CMake 3.27.
With this PR oneDNN build system does not have any policy warnings with CMake 3.31, the latest version available.
> build: switched from FindPythonInterp to FindPython2

- .github/automation/build_aarch64.sh
- .github/automation/build_acl.sh
- .github/automation/common_aarch64.sh
- .github/automation/test_aarch64.sh
- .github/workflows/nightly-aarch64.yml
Confirmed to work when made to trigger [manually](https://github.com/oneapi-src/oneDNN/actions/runs/12555027236) so one can assume it will also work with a cron job. Though we will only know for sure when we submit to main and either:
1. wait for the nightly to trigger at the set time (`on: cron`)
2. manually trigger the workflow (`on: workflow_dispatch`)
More info on how to manually trigger a workflow is [here](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow).
> github: workflows: add AArch64 nightly runs

- tests/benchdnn/doc/driver_graph.md
- tests/benchdnn/graph/graph.cpp
- tests/benchdnn/graph/graph.hpp
- tests/benchdnn/inputs/graph/complex_fusion/harness_mha_all
- tests/benchdnn/inputs/graph/complex_fusion/harness_mha_ci
- tests/benchdnn/inputs/graph/pattern/harness_bf16_all
- tests/benchdnn/inputs/graph/pattern/harness_f16_all
- tests/benchdnn/inputs/graph/pattern/harness_f32_all
- tests/benchdnn/inputs/graph/pattern/harness_f8_all
- tests/benchdnn/inputs/graph/pattern/harness_f8_ci
- tests/benchdnn/inputs/graph/pattern/harness_int8_all
Currently on main branch, `--expected-n-partitions` is 0 by default (if not provided in benchdnn command line), which means to skip checking the partition number returned from an input graph.
This PR changes the default value of `--expected-n-partitions` to 1 which means the input graph should be fused into one partition.
Most of the cases we have in CI/Nightly should fused into one partition. With this check enabled by default, we can detect that if a PR breaks a fusion into multiple partitions. Before this change, those multiple partitions will silently pass the correctness check of benchdnn.
Apparently, we still have a few cases which cannot fuse into one partition due to:
- the cases previously were added for graph compiler backend.
- the cases can fuse on cpu but not on gpu, or vice …
> benchdnn: graph: check partition number by default

- src/cpu/aarch64/jit_sve_conv_kernel.cpp
Inclusion of ldr_imm_check at more parts of the code to improve the readability. This reduces the complex nature of a expression into a simpler form.
make test:
Start   1: cpu-bnorm-u8-via-binary-postops-cpp
1/218 Test   #1: cpu-bnorm-u8-via-binary-postops-cpp .....................   Passed    0.09 sec
Start   2: cpu-cnn-inference-f32-c
2/218 Test   #2: cpu-cnn-inference-f32-c .................................   Passed    0.07 sec
Start   3: cpu-cnn-inference-f32-cpp
......
190/218 Test #190: test_benchdnn_modeC_binary_ci_cpu .......................   Passed    1.60 sec
Start 191: test_benchdnn_modeC_binary_different_dt_ci_cpu
191/218 Test #191: test_benchdnn_modeC_binary_different_dt_ci_cpu ..........   Passed    3.30 sec
Start 192: test_benchdnn_modeC_bnorm_ci_cpu
192/218 Test #192: …
> src : cpu : aarch64 : jit_sve_conv_kernel    Inclusion of ldr_imm_check to improve the readability

- src/cpu/x64/matmul/brgemm_matmul_copy_utils.cpp
Slightly modified cherry-pick of [this commit](https://github.com/oneapi-src/oneDNN/commit/15f3f6f1224296b36ae2e5e21062621e8d93d7ff)
There was no clear association of isa with data type, which is why the wrong copy kernel was selected.
It is required to fix issues caused by [this PR](https://github.com/oneapi-src/oneDNN/pull/2282).
> [rls-v3.6 backport]  cpu: x64: matmul: copy_routines: associate fp16 support with dt, not only isa

- cmake/platform.cmake
MSVC does not define __cplusplus macro by default. This results in oneDNN failing to build with C++ 17 and C++ 20 flags.
Reference: https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170
Fixes MFDNN-12942.
> build: enabled __cplusplus preprocessor macro for MSVC compiler

- src/gpu/intel/jit/binary_format.cpp
- src/gpu/intel/jit/codegen/kernel.hpp
- src/gpu/intel/jit/conv/conv_kernel.hpp
- src/gpu/intel/jit/conv/zero_out.hpp
- src/gpu/intel/jit/emulated_generator.hpp
- src/gpu/intel/jit/gemm/include/generator.hpp
- src/gpu/intel/jit/gen9_simple_sum_kernel_f32.hpp
- src/gpu/intel/jit/jit_generator.hpp
- src/gpu/intel/jit/jit_reduction_generator.hpp
- src/gpu/intel/jit/ngen/ngen.hpp
- src/gpu/intel/jit/ngen/ngen_auto_swsb.hpp
- src/gpu/intel/jit/ngen/ngen_config.hpp
- src/gpu/intel/jit/ngen/ngen_core.hpp
- src/gpu/intel/jit/ngen/ngen_debuginfo.hpp
- src/gpu/intel/jit/ngen/ngen_elf.hpp
- src/gpu/intel/jit/ngen/ngen_gen12.hpp
- src/gpu/intel/jit/ngen/ngen_interface.hpp
- src/gpu/intel/jit/ngen/ngen_level_zero.hpp
- src/gpu/intel/jit/ngen/ngen_opencl.hpp
- src/gpu/intel/jit/ngen/ngen_pseudo.hpp
- src/gpu/intel/jit/ngen/ngen_register_allocator.hpp
- src/gpu/intel/jit/ngen/ngen_utils.hpp
- src/gpu/intel/jit/pooling/pooling_kernel.hpp
- src/gpu/intel/jit/reorder/reorder_kernel.hpp
- src/gpu/intel/jit/v2/conv/kernel.hpp
Downstreams new nGEN code. In particular downstreams support for DWARF debug information. The basic debug information was originally implemented in #2227, and was further extended to include a line table. The line table is only enabled in DNNL_DEV_MODE to avoid overhead in release builds (potentially this condition should be removed to improve the information collected by profiling tools) and under C++20 builds (due to a dependency on `std::source_location`.) This line table works with `gdb-onapi` as can be seen with the following picture:
Sample usage (requires using SYCL gpu runtime for gdb to work):
```
$ cat env/gdb-oneapi_env.sh
source ~/intel/gdb-oneapi/setvars.sh --force
export ZET_ENABLE_PROGRAM_DEBUGGING=1
for f in /sys/class/drm/card*/prelim_enable_eu_debug; do
val=$(cat $f)
if …
```
> xe: jit: enable kernel debug information

- src/cpu/matmul/ref_matmul.hpp
- src/cpu/x64/brgemm/brgemm_types.hpp
- src/cpu/x64/brgemm/brgemm_utils.cpp
- src/cpu/x64/brgemm/jit_brgemm_kernel.cpp
- src/cpu/x64/cpu_isa_traits.hpp
- src/cpu/x64/jit_generator.hpp
- src/cpu/x64/matmul/brgemm_matmul.cpp
- src/cpu/x64/matmul/brgemm_matmul_copy_utils.cpp
- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
- src/cpu/x64/matmul/brgemm_matmul_utils.hpp
- tests/benchdnn/inputs/brgemm/test_brgemm_bf16
- tests/benchdnn/inputs/matmul/test_matmul_bfloat16
- tests/benchdnn/inputs/matmul/test_matmul_float16
MFDNN-11992
The change adds f32:f16:f32 support on AVX512_CORE and AVX2 through a up-conversion path.
Extended a brgemm kernel (thanks @dmitry-gorokhov) and brgemm matmul copy routines to support the conversion.
> cpu: x64: brgemm, matmul: add f32:f16 configuration support on AVX2 and AVX512_CORE (fixes MFDNN-11992)

- tests/benchdnn/dnnl_memory.cpp
- tests/benchdnn/graph/input_displacer.cpp
Since the backend does not support int4->int4 reorder currently, we use direct if-else condition to check the unsupported case during input displacement currently. We'd better try with reorder first and use plain copy-and-paste instead if the attempt fails.
> benchdnn: graph: use plain copy and paste for reorder if fail to create pd

- .github/labels.yml
I wanted to review the changes of graph document, but Github refused me to label #2301  with `component:graph-api` .
> github: codeowners: add graph team to review graph doc

- src/gpu/intel/jit/conv/zero_out.cpp
- src/gpu/intel/jit/conv/zero_out.hpp
- src/gpu/intel/jit/ir/kernel_desc.hpp
- src/gpu/intel/jit/ir/primitive_plan.cpp
- src/gpu/intel/jit/ir/primitive_plan.hpp
- src/gpu/intel/jit/v2/conv/builder.cpp
- src/gpu/intel/jit/v2/conv/kernel_desc.cpp
- src/gpu/intel/jit/v2/conv/kernel_desc.hpp
- src/gpu/intel/jit/v2/conv/plan.cpp
PR introduces initial Stream-K support in convolution. It's disabled by default, enabling will be done in a future PR. In the meantime Stream-K support can be enabled manually:
```
$ export desc="--hw xehpc --prop bwd_w --src axb:bf16 --wei axcb:f32 --dst axb:bf16 --fma dpas --simd 16 --regs 256 --iter ic32oc64mb16 --tg ic8oc2 --loop_desc mb,ow,oh,od --2d 1 --prefetch x3 --reqs dd0id1kd1od1pd0sd1"
$ ./build/tests/benchdnn/benchdnn --engine=gpu --conv --mode=f --dt=bf16:bf16:bf16 --dir=BWD_W --impl=v2 --stag=axb --wtag=xba --dtag=axb mb128ic512ih28oc128oh28kh3
perf,gpu,jit:ir_v2,,--mode=F --conv --engine=gpu --dir=BWD_W --dt=bf16:bf16:bf16 --stag=axb --wtag=xba --dtag=axb --attr-scratchpad=library --impl=v2 mb128ic512ih28oc128oh28kh3ph1,112.81,87.6985,2.99376,37681.7,3.00074,37594.1
export …
```
> xe: conv_v2: introduce Stream-K support

- src/graph/backend/dnnl/patterns/matmul_post_ops.cpp
- src/graph/backend/dnnl/patterns/utils.hpp
- tests/benchdnn/inputs/graph/op/f32/dynamicq_s4.json
- tests/benchdnn/inputs/graph/pattern/f8/f8_bf16_matmul_add_fusion.json
- tests/benchdnn/inputs/graph/pattern/f8/f8_bf16_matmul_sum_add_mul_relu.json
- tests/benchdnn/inputs/graph/pattern/f8/f8_f32_matmul_mul_add_fusion.json
- tests/benchdnn/inputs/graph/pattern/f8/f8_matmul_sum_add_mul_relu.json
- tests/benchdnn/inputs/graph/pattern/harness_f8_all
- tests/gtests/graph/unit/backend/dnnl/test_matmul.cpp
- tests/gtests/graph/unit/backend/dnnl/test_pass.cpp
Enhance support for fp8 MatMul patterns in oneDNN Graph.
- Support more fp8 MatMul patterns.
- Add more test cases in benchdnn graph.
> graph: backend: dnnl: enhance fp8 matmul patterns

- examples/CMakeLists.txt
- examples/graph/gated_mlp_int4.cpp
- src/graph/backend/dnnl/patterns/mlp.cpp
- tests/benchdnn/inputs/graph/complex_fusion/harness_mlp_all
- tests/benchdnn/inputs/graph/complex_fusion/harness_mlp_ci
- tests/benchdnn/inputs/graph/complex_fusion/mlp/gated-mlp-int4.json
- tests/benchdnn/inputs/graph/test_graph_all
1. Define Gated MLP patterns with int4 compressed weights.
2. Add the example and benchdnn test file accordingly.
> graph, example, benchdnn: add int4 gated mlp

- src/cpu/aarch64/brgemm/brgemm.cpp
- src/cpu/aarch64/brgemm/brgemm_types.hpp
- src/cpu/aarch64/brgemm/jit_brgemm_kernel.cpp
- src/cpu/aarch64/jit_brgemm_conv.cpp
- src/cpu/x64/brgemm/brgemm.cpp
- src/cpu/x64/brgemm/brgemm_types.hpp
- src/cpu/x64/brgemm/brgemm_utils.cpp
- src/cpu/x64/brgemm/jit_brdgmm_kernel.cpp
- src/cpu/x64/brgemm/jit_brdgmm_kernel.hpp
- src/cpu/x64/brgemm/jit_brgemm_amx_uker.cpp
- src/cpu/x64/brgemm/jit_brgemm_kernel.cpp
- src/cpu/x64/jit_brgemm_1x1_conv.cpp
- src/cpu/x64/jit_brgemm_1x1_conv.hpp
- src/cpu/x64/jit_brgemm_conv.cpp
- src/cpu/x64/jit_brgemm_conv_bwd_strided.cpp
- src/cpu/x64/jit_brgemm_conv_bwd_w.cpp
- src/cpu/x64/jit_brgemm_conv_utils.cpp
- src/cpu/x64/jit_brgemm_inner_product.hpp
- src/cpu/x64/jit_primitive_conf.hpp
- src/cpu/x64/matmul/brgemm_matmul.cpp
- src/cpu/x64/matmul/brgemm_matmul_copy_utils.cpp
- src/cpu/x64/matmul/brgemm_matmul_copy_utils.hpp
- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
- src/cpu/x64/matmul/brgemm_matmul_utils.hpp
- tests/benchdnn/brgemm/brgemm.cpp
There are two problems regarding brgemm K value on AMX:
brgemm doesn't support K not divisible by vnni granularity
for K not divisible by tile width (32 or 64) the blocking by K dimension may be not optimal.
To get around this limitation brgemm primitives are forced to either transform the matrix A or call many small brgemm kernels with different tile configurations. Both ways leads to performance lost.
This PR implements support of arbitrary K in brgemm on AMX and implements corresponding updates in 1x1 convolutions and in matmul to use this new ability.
Performance update for convolutions:
Performance update for matmul
> brgemm: support arbitrary K on AMX

- tests/benchdnn/binary/binary.cpp
MFDNN-12857
Make src1 input integer only to avoid potential cancellation in sdpa patterns.
> benchdnn: binary: update filling (maybe fixed MFDNN-12857)

- src/common/verbose.cpp
- src/cpu/x64/brgemm/capi/brgemm_api.cpp
- src/gpu/intel/ocl/ocl_gpu_engine.cpp
- src/graph/utils/verbose.cpp
Fixes MFDNN-12862
Disabled verbose shouldn't print data even if requested. The change is complied with this requirement with a marginal price of the library size for disabled verbose build, but easier way to support this mode.
> src: handle DNNL_VERBOSE=OFF support through an early exit (fixes MFDNN-12862)

- MAINTAINERS.md
Changes summary:
* Removed maintainers who changed assignments and no longer contribute to oneDNN.
* Added @ranukund as code owner for the documentation. Ranu is a technical writer [supporting](https://github.com/oneapi-src/oneDNN/pulls?q=is%3Apr+involves%3Aranukund) oneDNN documentation.
* Added @spalicki as code owner for the core. Stefan is established contributor to oneDNN who [switched focus to common parts](https://github.com/oneapi-src/oneDNN/pulls?q=is%3Apr+author%3Aspalicki) of the library.
* Added @amakarev as code owner for x64 CPU implementation. Alexey is focused on x64 CPU optimizations and has [history of contributions](https://github.com/oneapi-src/oneDNN/pulls?q=is%3Apr+author%3Aamakarev) to the component.
* Added @TaoLv as code owner for the documentation. Tao is an …
> Maintainers: year end cleanup and new nominations

- src/common/memory_tracking.hpp
- src/cpu/aarch64/acl_convolution_utils.cpp
- src/cpu/aarch64/acl_convolution_utils.hpp
- src/cpu/aarch64/acl_gemm_convolution.cpp
- src/cpu/aarch64/acl_gemm_convolution.hpp
- src/cpu/aarch64/acl_winograd_convolution.cpp
- src/cpu/aarch64/acl_winograd_convolution.hpp
partially reverts 16d6dd4f: "cpu: aarch64: Enable stateless ACL depthwise convolution"
reverts commit 03db3e4a: "cpu: aarch64: Call stateless ACL API from winograd convolution"
reverts commit 513f882d: "cpu: aarch64: hot fix for aux tensor management of stateless gemm-conv and winograd conv without lock."
Fixes #2324 
Fixes #2303
On a Neoverse V1 machine:
Current:
```
$ ./build-upstream/tests/benchdnn/benchdnn --max-ms-per-prb=3e3 --mode=P --conv --reset --allow-enum-tags-only=0 --engine=cpu --dir=FWD_I --alg=WINO --dt=f32:f32:f32 --stag=acdb --wtag=any --dtag=acdb --attr-scratchpad=user mb1_ic512oc512_ih7oh7kh3sh1dh0ph1_iw6ow6kw3sw1dw0pw1
Output template: perf,%engine%,%impl%,%name%,%prb%,%Gops%,%+ctime%,%-time%,%-Gflops%,%0time%,%0Gflops%
perf,cpu,wino:acl,,--mode=P --conv …
```
> fix: revert acl_winograd_convolution to stateful

- src/graph/backend/dnnl/dnnl_op_def.hpp
- src/graph/backend/dnnl/dnnl_shape_infer.cpp
- src/graph/backend/dnnl/dnnl_shape_infer.hpp
- src/graph/backend/dnnl/kernels/large_partition.cpp
- src/graph/backend/dnnl/kernels/matmul.cpp
- src/graph/backend/dnnl/kernels/sdp_decomp.cpp
- src/graph/backend/dnnl/kernels/sdp_decomp_config.cpp
- src/graph/backend/dnnl/kernels/select.cpp
- src/graph/backend/dnnl/op_executable.cpp
- src/graph/backend/dnnl/passes/lower.cpp
- src/graph/backend/dnnl/passes/transform.cpp
- src/graph/backend/dnnl/passes/transform.hpp
- src/graph/backend/dnnl/passes/utils.cpp
- src/graph/backend/dnnl/passes/utils.hpp
- src/graph/interface/shape_infer.cpp
- src/graph/interface/shape_infer.hpp
- tests/benchdnn/inputs/graph/complex_fusion/harness_mha_all
- tests/benchdnn/inputs/graph/op/harness_bf16_all
- tests/benchdnn/inputs/graph/op/harness_f16_all
- tests/benchdnn/inputs/graph/op/harness_f32_all
1. `cond` input is defined for dnnl binary op
2. For now, as primitive doesn't support broadcast for `cond` input, we use binary select primitive for non-broadcast case only, the lowering logic is: always lower select to binary primitive and then decide which impl path to use in pass `decompose_select_to_multiple_binary_ops` and decompose it to multiple binary ops if necessary.
3. It's unsupported on GPU as binary primitive doesn't support either.
relative perf:
platform: Intel(R) Xeon(R) Platinum 8490H
case | speedup
-- | --
./tests/benchdnn/benchdnn --graph --mode=P --reset --in-shapes=1:1x12x128x128+2:1x12x128x128 --case=complex_fusion/mha/MHA-distill_bert-inf-fp32-bs1.json | 98.24%
./tests/benchdnn/benchdnn --graph --mode=P --reset --dt=bf16 --in-shapes=1:1x12x128x128+2:1x12x128x128 …
> graph: backend: dnnl: support select with binary primitive

- src/graph/backend/dnnl/passes/compile_ops.cpp
- src/graph/backend/dnnl/passes/insert_ops.cpp
- src/graph/backend/dnnl/passes/layout_propagation.cpp
- src/graph/backend/dnnl/passes/lower.cpp
- src/graph/backend/dnnl/passes/memory_planning.cpp
- src/graph/backend/dnnl/passes/transform.cpp
- src/graph/backend/dnnl/passes/utils.cpp
- src/graph/backend/dnnl/passes/utils.hpp
verbose log enhancement for compile passes
> graph: backend: passes: verbose log enhancement

- src/gpu/intel/ocl/micro_sdpa.cl
- src/gpu/intel/ocl/micro_sdpa.cpp
- src/gpu/intel/ocl/tile_ops.h
This PR improves the performance of the micro SDPA kernel by using prefetching and setting better alignment when generating the microkernels. This change has a significant impact on certain sizes ranging from (0.89x-1.26x) over the original version.
> xe: sdpa: Improve performance of quantization with better alignment and prefetching

- src/gpu/intel/jit/conv/zp_plan.cpp
1) Fix data type for conv zp mask; set to `s16` instead of `s32`. This is to avoid invalid data type combination for the mad instruction,`mad dst:d src0:d src1:d src2:d`.
Failing case  
> --mode-modifier=P --conv --engine=gpu --skip-impl=ref --allow-enum-tags-only=false --check-ref-impl=true -- dt=u8:s8:u8 --attr-scales=wei:per_oc --attr-zero-points=src:per_dim_1 --attr-post-ops=hardswish:0.271:0.314+linear:0.271:0.314    g240mb32ic240ih28oc240oh14kh3sh2ph0n"f191c263e53dbb3ce0c02a13f311a72a*1"
2) Fix gemm hang for the following case on Xe2: -Fixed in https://github.com/oneapi-src/oneDNN/pull/2358#issuecomment-2580750925
> --matmul --engine=gpu --dt=f16:s4:f16 --wtag=acb --attr-scales=wei:per_ocic:f16:128x1 --attr-zero-points=wei:per_ocic:u4:128x1 --attr-fpmath=f16:true --skip-impl=ref …
> [GPU] Conv and Gemm fix

- src/gpu/intel/ocl/micro_sdpa.cpp
- src/gpu/intel/ocl/micro_sdpa.hpp
- src/gpu/intel/ocl/tile_ops.h
- tests/benchdnn/inputs/graph/complex_fusion/harness_mha_all
This pull request adds the ability to support quantization with head size that is not a power of two. This was a limitation on the vs ugemm and was required by the phi3-mini-4k-instruct model.
The shape that was failing was  Q [1x32xSEQ_LENx96] KV [1x32xSEQ_LENx96] which now passes with this change.
Additionally this PR addresses a failure to build when the vs work group was configured with an 16x16 work group tile.
> Add support for non-power of 2 head size with quantization

- src/gpu/intel/ocl/gemm/gemm_with_post_ops.cpp
- src/gpu/intel/ocl/gemm_matmul.hpp
Fixes [MFDNN-12752](https://jira.devtools.intel.com/browse/MFDNN-12752), and a miscellaneous error that needed a fixup.
Fixup: https://github.com/oneapi-src/oneDNN/commit/3bab3477800cda65732763152b3a18174da7bd49 introduced a bug when running `gemm_with_postops` without bias, resulting in an assertion error. This fix uses the dst tensor to create bias macros when not using a bias, which removes the error and does not affect results.
MFDNN-12752: The following layer was reported to fail:
> $ ./oneDNN/build/tests/benchdnn/benchdnn --matmul --engine=gpu --allow-enum-tags-only=false --dt=u8:s8:bf16 --stag=abcd --wtag=abdc --attr-scales=src:common:0.5+wei:common:0.5 --attr-zero-points=src:common:1+wei:common:1 --attr-post-ops=mul:f32:8:abx+add:bf16:8:abx+div:bf16:0:abx+add:bf16:9:abcd …
> xe: gemm: fixup postop formats and correctness failure

- src/gpu/intel/jit/gemm/generator/microkernel_provider.cpp
- src/gpu/intel/ocl/micro_sdpa.cpp
DG2/LNL quantized SDPA tuned configs for head sizes 64/128.
DG2, int8 K/V, first token performance vs. main (d = head size). For some cases (marked `*`), micro_sdpa was previously unimplemented (kernel/ukernel did not build).
sequence length | d = 32 | d = 64 | d = 128 
-- | -- | -- | --
32 | 100% | 104% | 100%
64 | 100% | 108% | 120%
128 | 190% | 178% | 120%
256 | 217% | 101% | 177%
512 | * | 101% | 222%
1024 | * | 101% | 153%
DG2, second token:
sequence length | d = 32 | d = 64 | d = 128 
-- | -- | -- | --
32 | 100% | 110% | 117%
64 | 100% | 109% | 105%
128 | 123% | 153% | 122%
256 | 180% | 214% | 188%
512 | 188% | 225% | 174%
1024 | 193% | 229% | 179%
LNL, first token:
sequence length | d = 64 | d = 128 
-- | -- | --
32 | 99% | 159%
64 | 104% | 112%
128 | 103% | 93%
256 | 113% | 116% …
> xe: ocl: sdpa: integer SDPA strategy tweaks

- src/cpu/x64/brgemm/brgemm.cpp
- src/cpu/x64/brgemm/brgemm_utils.cpp
- src/cpu/x64/brgemm/brgemm_utils.hpp
- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
This PR is a fix for [MFDNN-12970](https://jira.devtools.intel.com/browse/MFDNN-12970) and [MFDNN-12971](https://jira.devtools.intel.com/browse/MFDNN-12971)
> update brgemm and matmul initialization for some cases

- src/graph/backend/dnnl/kernels/sdp_primitive_config.cpp
- src/graph/backend/dnnl/passes/insert_ops.cpp
- src/graph/backend/dnnl/passes/lower.cpp
- src/graph/backend/dnnl/subgraph.cpp
- src/graph/interface/op_def_constraint.cpp
- tests/benchdnn/inputs/graph/complex_fusion/harness_mha_all
We recently supported the compressed SDPA patterns which incorporate scales and zero points as inputs. Also, we aim to support the problem with a Key shape of ( N, H, S, D ) with `transpose_b`=true for the QK MatMul. For such case with transposed MatMul, the graph library adds `permute` ops prior to the pattern input, including the scale and zp tensors. To be more specific, for the following woq MatMul with tranpose_b=true:
After the graph compilation, we will have the graph as follows. The permute ops will not touch the physical memories but only change the mds.
However, we faced a issue that DNNL backend always regards scale and zp tensors as `abx` format, leading to failing results, hence we need to set the tag explicitly as `abx` and execute extra reorders. After the change, the graph …
> graph: backend: dnnl: support permute for scale and zps inputs

- src/gpu/intel/ocl/micro_sdpa.cl
- src/gpu/intel/ocl/micro_sdpa.cpp
- src/gpu/intel/ocl/micro_sdpa.hpp
- src/gpu/intel/ocl/tile_ops.h
This PR focuses on enabling blfoat16 for micro_sdpa. It aims to make modification in the tile operations along with the micro sdpa kernel to enable this new data format.
Right now, this doesn't include quantization - this will be my next PR. 
Large test cases have slight precision issues for some of the data points in the tensor - likely related to cumulative chain effect in accumulation. Talking to @dzarukin about it.
Test cases of smaller sizes pass - for example:
```
> ./tests/benchdnn/benchdnn --engine=gpu --graph --dt=bf16 --in-shapes=0:1x1x16x64+1:1x1x16x64+8:1x1x16x64+5:1x1x1x16 -v7 --case=complex_fusion/mha/sdpa-plain-simplified-f16.json                  [INFO] Graph dump:
> {(0) MatMul}
>     In: { (0):bf16:1x1x16x64, (1):bf16:1x1x16x64 }
>     Out: { (2):bf16:1x1x16x16 }
> {(1) …
```
> Enable bfloat16 for micro sdpa kernel

- src/cpu/cpu_inner_product_list.cpp
- src/cpu/x64/jit_brgemm_inner_product.hpp
- src/cpu/x64/matmul_inner_product.cpp
- src/cpu/x64/matmul_inner_product.hpp
This PR introduces a matmul-based inner product implementation for inference that will be used instead of the current brgemm-based one. The latter will be disabled for inference.
This PR is targeting oneDNN v3.8 and will be merged after the oneDNN v3.7 code freeze date.
The implementation allows using blocked weights layouts directly or via the special tag `any`.
The Inner Product weights must meet **ONE** of the following requirements to enable using the blocked layouts:
* Weights don't have spatial.
* Weights have unit spatial.
* Weights have non-unit spatial but the number of input channels is a multiple of K block.
If none of the above requirements are met then a plain layout will be used.
The new matmul-based implementation is able to leverage blocked weights layouts for all cases …
> cpu: x64: enable matmul-based IP for forward inference

- examples/tutorials/matmul/cpu_matmul_quantization.cpp
- src/common/sdpa_utils.hpp
- tests/gtests/dnnl_test_common.hpp
- tests/gtests/test_sum.cpp
MFDNN-12954
Engine is peculiar, Coverity understands it's global object and that it has some singletons and that their initialization order od destruction is uncertain and may lead to issues.
Rest cases are less interesting.
> Arch: coverity fixes (fixed MFDNN-12954)

- src/gpu/intel/jit/emulation.hpp
- src/gpu/intel/ocl/gemm/gemm_with_post_ops.cl
- src/gpu/intel/ocl/gemm/gemm_with_post_ops.cpp
- src/gpu/intel/ocl/ocl_conversion.h
- src/gpu/intel/ocl/ocl_io.h
Fixes an emulate gap uncovered by #2276 ,  a support gap uncovered by #2289, and fixes a type conversion issue uncovered by #2289.
> xe: fix various GEMM issues on XeLP

- src/gpu/intel/jit/codegen/reorder.hpp
This resolves [MFDNN-12989](https://jira.devtools.intel.com/browse/MFDNN-12989).
> (v3.7 backport) src: gpu: intel: jit: fix div-by-0 when aligning hs=0 grf regions

- src/cpu/x64/matmul/brgemm_matmul_copy_utils.cpp
This is a fix for brgemm matmul failures on Windows ( [MFDNN-12969](https://jira.devtools.intel.com/browse/MFDNN-12969) )
> x64: brgemm matmul copy routines: fix parameters reading

- src/cpu/gemm_convolution_utils.cpp
- src/cpu/x64/jit_avx512_core_amx_conv_kernel.cpp
- src/cpu/x64/jit_avx512_core_bf16_conv_kernel.cpp
This is a fix for [MFDNN-12771](https://jira.devtools.intel.com/browse/MFDNN-12771) and [MFDNN-12746](https://jira.devtools.intel.com/browse/MFDNN-12746)
> x64: conv: limitations for huge spatial sizes

- src/graph/backend/dnnl/op_executable.cpp
- src/graph/utils/pm/nested_matcher.cpp
- tests/benchdnn/graph/setting_handler.cpp
Fixes the coverity issues in graph component.
Will need to backport them to rls-v3.7 branch.
> graph: fix coverity issues

- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
This is a quick fix to prevent failures for some brgemm matmul on GNR
> x64: brgemm matmul: update condition for extendable_k

- src/cpu/gemm_convolution_utils.cpp
- src/cpu/x64/jit_avx512_core_amx_conv_kernel.cpp
- src/cpu/x64/jit_avx512_core_bf16_conv_kernel.cpp
- src/cpu/x64/matmul/brgemm_matmul_copy_utils.cpp
- src/cpu/x64/matmul/brgemm_matmul_utils.cpp
This is a cumulative backport of:
#2379 :  x64: brgemm matmul copy routines: fix parameters reading
#2387 :  x64: conv: limitations for huge spatial sizes
#2392 :  x64: brgemm matmul: update condition for extendable_k
> x64: cumulative backport: fixes in brgemm matmul and convolution 

- cmake/gen_gpu_kernel.cmake
- cmake/gen_gpu_kernel_list.cmake
- src/gpu/intel/compute/compute_engine.hpp
- src/gpu/intel/compute/kernel.hpp
- src/gpu/intel/ocl/ocl_gpu_engine.cpp
- src/gpu/intel/ocl/ocl_gpu_engine.hpp
- src/gpu/intel/ocl/ocl_gpu_kernel.cpp
- src/gpu/intel/ocl/ocl_gpu_kernel.hpp
- src/gpu/intel/sycl/engine.hpp
- src/gpu/intel/sycl/sycl_interop_gpu_kernel.hpp
As the difficult case for handling nGEN was already handled in #2297, it seems only fitting to enable debug information in the simpler case where we use OpenCL C kernels. This PR limits the scope of support for this to Linux due to the nuances required for handling temporary files. It should be fairly easy to extend with Windows support when it becomes useful.
> xe: enable source code information for OpenCL kernels

- src/common/memory_tracking.hpp
- src/cpu/aarch64/matmul/acl_lowp_matmul_sq.cpp
- src/cpu/aarch64/matmul/acl_lowp_matmul_sq.hpp
- src/cpu/matmul/cpu_matmul_list.cpp
This is to re-enable `matmul` static quantization operations through ACL. Currently, the supported data type combinations are `s8:s8:s8` and `u8:s8:u8`. Neoverse-N1 is skipped until failing tests are fixed.
Previous PR: #2198
> src: cpu: aarch64: Re-enable matmul static quantisation through ACL.

- src/gpu/intel/compute/device_info.cpp
This PR addresses a gen9_concat failure in nightly testing where the allowable subgroup_size in device_info was insufficiently strict for xe3.
> xe: correct allowable sg sizes

- src/graph/backend/dnnl/kernels/sdp_decomp_config.cpp
- src/graph/backend/dnnl/passes/transform.cpp
1. SDPA decomp kernel doesn't support select case with non-broadcast `cond` input now, as we haven't supported single binary select impl path in SDPA decomp kernel yet, dnnl backend should dispatch these cases to large partition kernel, this PR aims at fixing this.
2. Fix the out-of-bounds issue
> graph: backend: fix select binary related issues

- src/cpu/aarch64/jit_sve_1x1_conv_kernel.cpp
- src/cpu/cpu_convolution_list.cpp
In benchdnn testing, jit_sve conv performs about x1.3 better than acl conv on average and jit_sve_1x1 conv performs x1.3-x3 better on average depending on the number of threads. In testing with CNNs, we got a 10-15% speed-up by using jit_sve and jit_sve_1x1 conv. So, they should be the preferred implementations whenever possible.
> src: cpu: aarch64: move jit_sve conv above acl conv in convolution_list

- src/gpu/intel/sycl/l0/utils.cpp
- third_party/ngen/ngen_level_zero.hpp
Example of warnings this PR fixes:
```
src/gpu/intel/sycl/l0/utils.cpp: In function ‘dnnl::impl::status_t dnnl::impl::gpu::intel::sycl::get_device_ip(ze_device_handle_t, uint32_t&)’:
src/gpu/intel/sycl/l0/utils.cpp:296:78: error: missing initializer for member ‘_ze_device_properties_t::pNext’ [-Werror=missing-field-initializers]
ze_device_properties_t deviceProps = {ZE_STRUCTURE_TYPE_DEVICE_PROPERTIES};
^
src/gpu/intel/sycl/l0/utils.cpp:296:78: error: missing initializer for member ‘_ze_device_properties_t::type’ [-Werror=missing-field-initializers]
src/gpu/intel/sycl/l0/utils.cpp:296:78: error: missing initializer for member ‘_ze_device_properties_t::vendorId’ [-Werror=missing-field-initializers]
src/gpu/intel/sycl/l0/utils.cpp:296:78: error: missing initializer for member …
```
> Fix some warnings emmited by gcc 8.5

- src/gpu/intel/jit/gemm/gen_gemm.cpp
- src/gpu/intel/jit/gemm/gen_gemm_kernel.cpp
- src/gpu/intel/jit/gemm/include/type.hpp
- src/gpu/intel/jit/gemm/xe_hp_systolic_gemm.cpp
Fixes the following failure observed on PVC:
```
$./benchdnn --engine=gpu --matmul --stag=any --wtag=any --dtag=any --dt=bf16:u8:bf16 --attr-fpmath=bf16:true 1x2:2x1789201856
[   0][DST][0:0] exp_f32:          26 exp:          26 got:          18 diff:       8 rdiff:0.307692
[   1][DST][0:1] exp_f32:          14 exp:          14 got:          30 diff:      16 rdiff: 1.14286
[   2][DST][0:2] exp_f32:           7 exp:           7 got:          35 diff:      28 rdiff:       4
[   3][DST][0:3] exp_f32:          20 exp:          20 got:           8 diff:      12 rdiff:     0.6
[   4][DST][0:4] exp_f32:          27 exp:          27 got:          23 diff:       4 rdiff:0.148148
[   5][DST][0:5] exp_f32:          26 exp:          26 got:           6 diff:      20 rdiff:0.769231
[   7][DST][0:7] …
```
> xe: jit: gemm: fix invalid use of 2d messages

- .github/workflows/pr-linter.yml
Formatting job uses ubuntu-latest version which is ubuntu 24.04. This version doesn't have clang-format 11 in default packages. Changed os version to 22.04.
> ci: linters: OS fix for clang-format 

- include/oneapi/dnnl/dnnl.hpp
- include/oneapi/dnnl/dnnl_common.hpp
- include/oneapi/dnnl/dnnl_graph.hpp
- include/oneapi/dnnl/dnnl_graph_ocl.hpp
- include/oneapi/dnnl/dnnl_graph_sycl.hpp
- include/oneapi/dnnl/dnnl_ocl.hpp
- include/oneapi/dnnl/dnnl_sycl.hpp
- include/oneapi/dnnl/dnnl_threadpool.hpp
- include/oneapi/dnnl/dnnl_ukernel.hpp
- tests/benchdnn/graph/deserialize.cpp
Fixes [MFDNN-12814](https://jira.devtools.intel.com/browse/MFDNN-12814). 
Implementation handles regression by removing string-based error message construction for exception messages. The PR removes the message construction mechanism introduced in commit [e9d8e12](https://github.com/oneapi-src/oneDNN/commit/e9d8e126c8969513f1825ed23913ae210cc0b469). 
```
KMP_AFFINITY=compact,1,0,granularity=fine OMP_NUM_THREADS=4 OMP_PLACES=threads OMP_PROC_BIND=close numactl --membind=0 --physcpubind=0-3 ./tests/benchdnn/benchdnn --mode=P --graph --in-shapes=0:1x16x12x64+1:1x16x12x64+2:1x16x64x12+6:1x1x1x12 --case=$WORKDIR/projects/mfdnn12814/graph-mha-v2-head_16-dt_f32.json
```
Error Commits:  [e9d8e12](https://github.com/oneapi-src/oneDNN/commit/e9d8e126c8969513f1825ed23913ae210cc0b469), …
> [MHA][CPU] common: fix for mha cpu regression

- src/gpu/intel/jit/emulation.hpp
Fixes [MFDNN-12978](https://jira.devtools.intel.com/browse/MFDNN-12978). The following layer (among others) is failing:
> ./benchdnn --mode=F --matmul --engine=gpu --allow-enum-tags-only=false --memory-kind=usm_device --cold-cache=all --dt=f16:f16:f16 --stag=abc --wtag=abc --dtag=abc 192x663x64:192x64x663
onednn_verbose,v1,info,oneDNN v3.7.0 (commit 5890fc624e0d45ac585b35fd1e1d460456319f3a)
onednn_verbose,v1,info,cpu,runtime:OpenMP,nthr:64
onednn_verbose,v1,info,cpu,isa:Intel AVX-512 with Intel DL Boost
onednn_verbose,v1,info,gpu,runtime:OpenCL
onednn_verbose,v1,info,gpu,engine,opencl device count:2
onednn_verbose,v1,info,gpu,engine,0,name:Intel(R) Data Center GPU Max 1550,driver_version:24.39.31294,binary_kernels:enabled
onednn_verbose,v1,info,gpu,engine,1,name:Intel(R) Data Center GPU …
> xe: jit: gemm: implement qqw mul instructions

- cmake/testing.cmake
- tests/benchdnn/CMakeLists.txt
- tests/benchdnn/benchdnn.cpp
- tests/benchdnn/dnn_types.cpp
- tests/benchdnn/dnnl_common.cpp
- tests/benchdnn/dnnl_common.hpp
- tests/benchdnn/doc/knobs_common.md
- tests/benchdnn/utils/parser.cpp
Adds ability to run benchdnn tests using graph execution by adding `--execution-mode=[direct(default)|graph]` option. It is currently limited to SyCL GPU engine executing on L0 backend.
> tests: benchdnn: add experimental support for sycl graph

- src/gpu/intel/jit/gemm/generator/pieces/matrix_access.cxx
- src/gpu/intel/jit/pooling/ir_builder.cpp
- third_party/ngen/ngen_pseudo.hpp
Fixes a mistake in #2365/addresses the final Coverity hit from [MFDNN-12963](https://jira.devtools.intel.com/browse/MFDNN-12963). Addresses [MFDNN-12986](https://jira.devtools.intel.com/browse/MFDNN-12986).
> [GPU] Coverity fixups

- src/cpu/x64/jit_brgemm_conv.cpp
- src/cpu/x64/jit_brgemm_conv.hpp
- src/cpu/x64/jit_brgemm_conv_utils.cpp
- src/cpu/x64/jit_brgemm_conv_utils.hpp
MFDNN-12916
The reason for slowdown is executing a really long cycle where a full brgemm descriptor as going to be created. In the reality, only a short set of M values must be check.
The reason why this loop is called is dilated convolution can fail the condition for exec_vpad type (left a TODO comment there). This type would only call verification for two M values and that's it.
The solution was to adopt the approach for exec_base type from the actual initialization step.
Measured on sdpdal774583
Timing before (cpdtime is a primitive descriptor creation time):
```
run: --mode=P --conv --dir=FWD_I --dt=u8:s8:u8 --stag=acb --dtag=acb --attr-scales=wei:per_oc --attr-post-ops=relu:0.1+linear:350.855:35 mb1ic32iw129024oc32ow129024kw3pw5dw4
Output template: %impl%,%+cpdtime% …
```
> brgconv: fix long pd time for problems with dilation (fixed MFDNN-12916)

- src/graph/backend/graph_compiler/core/src/compiler/jit/xbyak/debug/vtune/vtune.cpp
- src/graph/backend/graph_compiler/core/src/runtime/microkernel/cpu/brgemm_onednn.cpp
- tests/gtests/graph/unit/backend/graph_compiler/CMakeLists.txt
- Fix the include paths of itt and gtest after they are moved into `third_party`.
- Fix a variable name change in brgemm.
> graph: backend: graph compiler: fix build
